scikit-hep/pyhf

docs/bib/media.bib

Add links in the "In the Media" section to the [May/June 2021 Issue](https://cds.cern.ch/record/2765233) of the CERN Courier that feature `pyhf` in the the article "LHC reinterpreters think long-term" (page 23) written by @sabinekraml (:raised_hands:).
```
* Add May/June 2021 Issue of the CERN Courier that features pyhf's role in open likelihood publishing and summary of the 6th LHC Reinterpretation Workshop to 'In the Media' section
- c.f. https://cds.cern.ch/record/2765233
- "LHC reinterpreters think long-term" article on page 23 written by Sabine Kraml
```

docs: Add CERN Courier article to media listing

---

.pre-commit-config.yaml
docs/examples/notebooks/binderexample/StatisticalAnalysis.ipynb

Resolves #1431
Add custom pre-commit.ci autoupdate commit message that is in semantic PR style by prepending "chore:" to the default. Update the additional dependencies to match their top level pre-commit hook versions.
```
* Add custom pre-commit.ci autoupdate commit message that is in semantic PR style
- c.f. https://pre-commit.ci/#configuration
* Update black pre-commit hook
- github.com/psf/black: 21.4b2 → 21.5b0
* Update black and pyupgrade additional_dependencies to current versions
- github.com/psf/black: 21.4b1 → 21.5b0
- github.com/asottile/pyupgrade: v2.11.0 → v2.14.0
- Apply Black to notebooks
```

ci: Add custom commit message for pre-commit.ci autoupdate

---

src/pyhf/readxml.py
tests/test_import.py

Resolves #1389 
resolves  space issue  https://github.com/scikit-hep/pyhf/issues/1389 
```
* Strip trailing spaces from parameter names
- Normalizes parameter name string and makes robust to space differences
* Add test for trailing spaces functioning properly 
```

fix: Remove trailing spaces in parameter names

---

.github/workflows/docker.yml

Fix for PR #1441 in which `load` and `push` can not be used simultaneously for the `docker/build-push-action@v2` action. So remove `load` as the image isn't needed locally.
> ### <a name="push"></a> Push the build result to a registry (--push)
> 
> Shorthand for [`--output=type=registry`](https://github.com/docker/buildx/blob/master/docs/reference/buildx_build.md#registry). Will automatically push the
> build result to registry.
> 
> ### <a name="load"></a> Load the single-platform build result to `docker images` (--load)
> 
> Shorthand for [`--output=type=docker`](https://github.com/docker/buildx/blob/master/docs/reference/buildx_build.md#docker). Will automatically load the
> single-platform build result to `docker images`.
```
* Remove load from …
```

fix: Remove load option from Docker workflow publish steps

---

docs/conf.py
setup.py

Sphinx v4.0 is out now and it appears that it requires [`mathjax3_config`](https://www.sphinx-doc.org/en/master/usage/extensions/math.html#confval-mathjax3_config) to be able to work as at the moment it is spitting out lots of 
```
WARNING: mathjax_config/mathjax2_config does not work for the current MathJax version, use mathjax3_config instead
```
in the docs builds.
```
* Update Sphinx config to use mathjax3_config
- Used in Sphinx v4.x+
- c.f. https://www.sphinx-doc.org/en/master/usage/extensions/math.html#confval-mathjax3_config
* Set lower bound of supported Sphinx to v4.0.0
```

fix: Update to mathjax3_config to support math rendering in Sphinx v4.x+

---

.github/workflows/ci.yml
.github/workflows/dependencies-head.yml
.github/workflows/docs.yml
.github/workflows/lint.yml
.github/workflows/lower-bound-requirements.yml
.github/workflows/notebooks.yml
.github/workflows/publish-package.yml
CONTRIBUTING.md
docs/development.rst
docs/installation.rst

From the current docs build there is a warning from `pip`
```
DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
```
This PR adds in the `pip` option `--use-feature=in-tree-build` to the docs workflow (only needed to test in one place, not all of our `pip` installs but do need a non `--editable` install to get the warning) to test this feature change in advance as requested.
c.f. https://github.com/pypa/pip/issues/7555 for further details
Also revise …

chore: Trial pip in-tree-build before release in pip 21.3

---

.github/workflows/docker.yml

* Resolves #1462
* Needed for PR #1460 
There's no need to login to a container registry like Docker Hub or GitHub Container Registry unless there is going to be a push to them. As this should only happen on merges in the project, then we can safely not have contributed PRs from forks of the project login to the container registries and still succeed in their builds.
```
* Don't login to Docker Hub or GitHub Container Registry during PRs
- The only need to login to the container registries is to be able to push to them, which is only needed on merges into the project
* Avoids errors from contributed PRs from fork not having access to secrets
```

ci: Don't login to Docker container registries on PRs

---

src/pyhf/contrib/utils.py

Fixes #1455. This is the equivalent of #866, which fixed #865.
`pyhf.contrib.utils` sets up logging, thereby preventing users who import that module from configuring logging themselves after the import. This removes the logging setup, which is only needed for the CLI (and done there).
```
* Remove the logging configuration in contrib.utils as it interferes with custom logging users may want to set up
```

fix: Do not configure logging in contrib.utils

---

.bumpversion.cfg
.github/workflows/ci.yml
.github/workflows/dependencies-head.yml
.github/workflows/docker.yml
.github/workflows/lower-bound-requirements.yml
.gitignore
docs/conf.py
pyproject.toml
setup.cfg
src/pyhf/__init__.py
src/pyhf/cli/cli.py
src/pyhf/version.py
tests/test_public_api.py

This bumps us up to a more modern version of `setuptools_scm` that supports `pyproject.toml` and will inject the right version at build time (via PEP517/8) as well as generate the corresponding `version.py` for us at build time.
```
* Update to a modern version of setuptools_scm to support pyproject-based Python packages
- Use local_scheme = "no-local-version" to continue uploading to TestPyPI
- c.f. https://github.com/pypa/setuptools_scm/blob/v6.0.1/README.rst#version-number-construction
* Remove src/pyhf/version.py in favor of generating at build time
- Remove setup.cfg and src/pyhf/version.py from bump2version control
* Set fetch depth:0 in CI to get full history and tags to generate version number
- c.f. https://github.com/scikit-hep/pyhf/issues/1465
```

chore: Use newer setuptools_scm for versioning

---

docs/bib/use_citations.bib

Add `pyhf` use citation from [Search for B⁺→ K⁺νν̅ decays using an inclusive tagging method at Belle II](https://inspirehep.net/literature/1863052) by the Belle II Collaboration in a contribution to the 2021 EW session of the 55th Rencontres de Moriond.
```
* Add use citation from Belle II in Moriond EW 2021 contribution on B⁺→ K⁺νν̅ search
- Contribution title: 'Search for B⁺→ K⁺νν̅ decays using an inclusive tagging method at Belle II'
- c.f. https://inspirehep.net/literature/1863052
```

docs: Add use citation from Belle II in Moriond EW 2021 contribution

---

docker/Dockerfile
docker/gpu/Dockerfile

Resolves #1478 
```
* Add 'contrib' extra to Docker images so that 'pyhf contrib download' can be used
* Ignore hadolint SC2102 as [xmlio,contrib] is valid for pip
* Move --no-cache-dir flag to indicate it is a top level pip command
```

feat: Add 'contrib' extra to Docker images

---

.gitignore
pyproject.toml
src/pyhf/__init__.py

Following https://github.com/pypa/setuptools_scm/pull/576 change the generated version file (c.f. PR #1450) to be named `_version.py`
```
* Renames generated version file from version.py to _version.py following setuptools_scm recommendations
- c.f. https://github.com/pypa/setuptools_scm/pull/576
- Avoids publishing the contents of "version.py" as externally visible API
* Amends PR #1450
```

chore: Use _version.py to follow setuptools_scm recommendations

---

.github/workflows/lint.yml
docker/Dockerfile

Create a default virtual environment and place it on `PATH` so that it is active and used to install all libraries. Then, just `COPY` the virtual environment from the builder image instead of all of `/usr/local/` reducing the amount of files copied to _only_ the necessary files.
This has the added benefit of symlinking the installed `python3` to the `virtualenv` PATH, so the equivalent of
```
ln -s $(command -v python3) /usr/local/venv/bin/python
```
This approach was recommended by Anthony Sottile in his YouTube video "[how to get pip for deadsnakes / docker pythons (intermediate) anthony explains 293](https://youtu.be/2Hg5-Hrsa6w)". Thanks Anthony!
```
* Add a venv virtual environment to PATH
- Adding venv also symlinks the python doing the installing to the …
```

chore: Add default virtual environment on PATH for Docker image

---

docs/bib/use_citations.bib

Resolves #1482 
Add use citation from [Search for chargino--neutralino pair production in final states with three leptons and missing transverse momentum in s√=13 TeV pp collisions with the ATLAS detector](https://inspirehep.net/literature/1866951) by the ATLAS Collaboration! :rocket: 
This is the third citation from ATLAS following the paper https://doi.org/10.1007/JHEP04(2021)165 and the PUB note.
```
* Add use citation from 'Search for chargino--neutralino pair production in final states with three leptons and missing transverse momentum in s√=13 TeV pp collisions with the ATLAS detector'
- c.f. https://inspirehep.net/literature/1866951
- Third citation from ATLAS
```

docs: Add use citation from ATLAS SUSY 3L+compressed combination paper

---

tests/test_scripts.py

As brought up in Issue #1485, the `test_patchset_download` tests don't actually need to use the `datadir` fixture, so for clarity use the `tmpdir` fixture.
```
* Use tmpdir fixture instead of datadir fixture in test_patchset_download as datadir is not explicitly needed
- The tests are easier to understand when fixtures are used in situations that use their intended features
```

chore: Use tmpdir fixture over datadir in pyhf contrib download tests

---

src/pyhf/schemas/1.0.0/defs.json
tests/test_patchset.py
tests/test_patchset/patchset_bad_wrong_valuetype.json
tests/test_patchset/patchset_good_stringvalues.json

This loosens the PatchSet schema to allow for value types in the "values" of a patch to accept strings (in addition to numbers). Therefore one could do patch tuples of `(decay, m1, m2) = ("Gtt", 1000, 800)` for example.
```
* Allow string types for patch values in patchsets
- Example: "values": [2100, 800, "Gtt"]
- Extends schemas/1.0.0/defs.json   
* Add tests for string types
```

feat: Allow strings in patch values for patchset

---

.pre-commit-config.yaml
src/pyhf/infer/calculators.py
src/pyhf/interpolators/code4.py
src/pyhf/parameters/paramview.py
src/pyhf/workspace.py
tests/test_constraints.py

Update pre-commit hooks and bump pyupgrade in the pre-commit hooks run order. As pre-commit hooks execute sequentially as defined in `.pre-commit-config.yaml`, those that can edit the code base like `pyupgade` should run before others like `black` that will apply formatting.
```
* Update and apply pre-commit hooks:
- github.com/pre-commit/pre-commit-hooks: v3.4.0 → v4.0.1
- github.com/asottile/pyupgrade: v2.15.0 → v2.19.4
- github.com/psf/black: v21.5b1 → v21.6b0
- github.com/nbQA-dev/nbQA: v0.8.0 → v0.12.0
* Move pyupgrade so that it runs sooner
- pre-commit hooks execute in order of definition in .pre-commit-config.yaml, so hooks that can change the codebase should execute before linter hooks
* Remove quotes from time interval on pre-commit.ci autoupdate_schedule …
```

chore: Update pre-commit hooks versions and run order

---

.github/workflows/publish-package.yml

Remove the option `--sdist --wheel` from 
https://github.com/scikit-hep/pyhf/blob/f5dad2981e9c2c480e9d76f3f5c5a611a7843720/.github/workflows/publish-package.yml#L32-L34
to enable the default behavior for `build` in release `v0.5.0` of building a sdist and then building a wheel from the sidst to ensure that the sdist is capable of building a wheel. This was added in https://github.com/pypa/build/pull/304
```console
$ pip list | grep build
build       0.5.0
$ python -m build --help
usage: python -m build [-h] [--version] [--sdist] [--wheel] [--outdir OUTDIR] [--skip-dependency-check] [--no-isolation] [--config-setting CONFIG_SETTING] [srcdir]
A simple, correct PEP 517 package builder.
By default, a source distribution (sdist) is built from {srcdir}
and a binary distribution (wheel) is built …
```

ci: Remove distribution options to enable default build v0.5.0 behavior

---

docs/bib/HEPData_likelihoods.bib
docs/citations.rst

Add HEPData record for published statistical model and observations for [Search for squarks and gluinos in final states with jets and missing transverse momentum using 139 fb−1 of s√ =13 TeV pp collision data with the ATLAS detector](https://www.hepdata.net/record/ins1827025). Revise usages of the term "likelihoods" to more accurate "probability models" in keeping with upcoming white paper on open statistical models and likelihoods.
Needed for https://github.com/scikit-hep/pyhf/issues/1494#issuecomment-865152062
```
* Add ATLAS squarks and gluinos search HEPData record with patchset pallet (stat model and observations)
- c.f. https://www.hepdata.net/record/ins1827025
* Revise usages of 'likelihoods' to more accurate 'statistical models' in keeping with upcoming white …
```

docs: Add squarks and gluinos search statistical model record

---

README.rst

Resolves #1361 
The old Docker deployment badge is now broken, 
[![badge](https://img.shields.io/docker/automated/pyhf/pyhf.svg)](https://hub.docker.com/r/pyhf/pyhf/)
so fix it by using the GitHub Actions stats badge. Also reorder badges for user convince over developer convenience.
**Current layout**
**PR layout**
@phinate we'll merge this before you can probably look at it, but feedback and future revision suggestions are welcome.
```
* Update broken Docker deployment badge with GitHub Actions Docker workflow status badge
* Remove Docker stars and pulls badges
* Add pyhf CUDA enabled Docker images badge
* Revise badge layout to prioritize user needs (docs and distributions) over developer interests (code quality and CI status)
```

docs: Improve badge layout and fix broken Docker badge

---

docs/release-notes.rst
docs/release-notes/v0.6.2.rst

Add `v0.6.2` release notes as part of completing Issue #1494.
```
* Add release notes for pyhf v0.6.2
- c.f. https://github.com/scikit-hep/pyhf/releases/tag/v0.6.2
```

docs: Add v0.6.2 release notes

---

codemeta.json

Needed for part of Issue #1494
Applies the changes from PR #1382 to `codemeta.json` for them to match in `v0.6.2`.
This PR will fail the following test
https://github.com/scikit-hep/pyhf/blob/a244d65f395da74877670cac37317926509c579e/.github/workflows/release_tests.yml#L38-L42
but it will pass in the next release.
```
* Update softwareRequirements in codemeta.json to use required lower bounds on all core dependencies
- Applies lower bounds from PR #1382
* Add CPython implimentation to programmingLanguage codemeta.json metadata
```

chore: Update codemeta softwareRequirements to match setup.cfg

---

tests/test_optim.py

Resolves #1503 
The `32b` `test_optim` tests
https://github.com/scikit-hep/pyhf/blob/a9f4fae5a423e501755e0e4cd710a8f2335dd064/tests/test_optim.py#L49-L103
are too unreliable and provide poor enough precision that we shouldn't have the tests be reliant on them passing. We can support `32b` as runnable, but not as recommended precision. This PR removes the `32b` precision parameterization option from the minimizaiton tests and removes `'precision'` as being a test parameterization argument.
```
* Remove the 32b precision tests from test_minimize
- 32b precision is not good enough to be used reliably for optimization comparison
* Remove precision as parameterization argument
```

test: Remove 32b test_minimize tests from optim tests

---

.bumpversion.cfg
setup.cfg

This PR adds the release notes webpage to the PyPI project URL metadata in `setup.cfg` so that it shows up on PyPI in a similar fashion to how [`click`'s page](https://pypi.org/project/click/) has it.
The name of the `project_urls` keys is based off what [`click` has in their `setup.cfg`](https://github.com/pallets/click/blob/70358c57b20454c262bceaa901ab273b2487d7f3/setup.cfg#L5-L12) and the [template rules for the PyPA warehouse](https://github.com/pypa/warehouse/blob/3a93612489a47e37c68419821061a530064677ed/warehouse/templates/packaging/detail.html#L20-L58) that @duetosymmetry [found](https://twitter.com/duetosymmetry/status/1410687033237028876) (thanks Leo!).
```
* Add release notes webpage to PyPI project metadata
- Follows PyPA warehouse template rules: …
```

docs: Add release notes URL to PyPI project urls metadata

---

docs/bib/use_citations.bib
docs/contributors.rst

Resolves #1401
As summarised in the issue, the citation for the paper has been updated with the [new INSPIRE reference](https://inspirehep.net/literature/1846026).
(I'm not able to select an assignee for the PR)
```
* Update citation for  'Charged Lepton Flavor Violation at the EIC' paper for publication in JHEP
- c.f. https://doi.org/10.1007/JHEP03(2021)256
```

docs: Update citation for 'Charged Lepton Flavor Violation at the EIC' paper

---

.github/workflows/ci.yml
.github/workflows/dependencies-head.yml
.github/workflows/lower-bound-requirements.yml
tests/test_public_api.py
tests/test_simplemodels.py

Resolves #1465
* Removes testing of deprecated `pyhf.simplemodels.hepdata_like` as it was deprecated in `v0.6.2` with the exception of testing that using it properly raises a warning
https://github.com/scikit-hep/pyhf/blob/18a7a08a38676a44048e9a2b88958723e357feee/tests/test_simplemodels.py#L30-L40
* Remove the required full checkouts of the repository history added in PR #1450
```
* Remove pyhf version checks
- Were used only to guard against pyhf.simplemodels.uncorrelated_background not being in the public API until the release of v0.6.2
* Remove full fetch depths in CI where it is not explicitly needed for version information
- Partially reverts PR #1450
```

test: Remove tests of deprecated simplemodels.hepdata_like API

---

setup.py

* Resolves #1501
* Resolves https://github.com/google/jax/issues/7128
* Resolves https://github.com/actions/virtual-environments/issues/3679
Following the resolution of https://github.com/google/jax/issues/7128, unrestrict `jaxlib`'s upper bound, reverting PR #1502, and exclude `jaxlib` `v0.1.68`.
```
* Unrestrict the upper bound on jaxlib in 'jax' extra
- Reverts PR #1502
* Exclude jaxlib v0.1.68 from being installed as part of 'jax' extra
- c.f. https://github.com/google/jax/issues/7128
```

fix: Unrestrict jaxlib upper bound and exclude jaxlib v0.1.68

---

.github/workflows/dependencies-head.yml

As described in Issue #1531, the nightly tests against the `HEAD` of SciPy's source have been failing for so long that they are no longer useful and are generating too many false positives (test failures) for the `HEAD` of dependencies workflow to be a useful test. Until the build issue can be resolved, replace testing from `HEAD` against testing against releases with release candidates as eligible installs.
```
* Temporarily remove installs of SciPy from the HEAD of source to reduce false failures in 'HEAD of dependencies' workflow
- c.f. Issue #1531
* Use pip install --pre to test against release candidates of SciPy
```

test: Temporarily move to testing against SciPy pre-releases

---

.github/workflows/dependencies-head.yml

* Resolves #1531
* Effectively reverts PR #1532
To avoid having to build SciPy from source (slowing things down and [doing redundant work worse](https://twitter.com/ralfgommers/status/1419917265781334025)) take @rgommers advice and install the [nightly SciPy wheels available on Anaconda's PyPI](https://anaconda.org/scipy-wheels-nightly/scipy) with
```console
python -m pip install --upgrade --index-url https://pypi.anaconda.org/scipy-wheels-nightly/simple scipy
```
This works great!
```
* Use nightly wheels of SciPy from Anaconda's PyPI to avoid building SciPy from source for 'HEAD of dependencies' workflow
- Huge thanks to Ralf Gommers (@rgommers) for pointing this out!
- c.f. https://anaconda.org/scipy-wheels-nightly/scipy
* Effectively reverts PR #1532
```

fix: Use nightly SciPy wheels from Anaconda in HEAD of dependencies testing

---

src/pyhf/optimize/mixins.py
src/pyhf/optimize/opt_minuit.py
src/pyhf/optimize/opt_scipy.py
src/pyhf/pdf.py
tests/test_optim.py
tests/test_simplemodels.py

Resolves #1099. This passes through parameter names to the optimizers, both scipy and minuit. This is done by adding `ModelConfig.par_names()` which returns the parameter names in a format that has yet to be agreed upon (for indexing n-binned parameters). This function output is threaded through the optimizer framework via the `Optimizer._get_minimizer()` function call. However, scipy does not make use of this, so not much changes except to support the updated function signature, while Minuit is able to take advantage of this.
A format string is allowed as an optional keyword argument so we're not locked into a specific format.
```
* Propagate model parameter names through to the optimizers (primarily Minuit)
- Additionally allow a customizable format for the …
```

feat: Propagate model parameter names to optimizers

---

docs/bib/use_citations.bib

Resolves #1534
Add citation from [Reinterpreting the ATLAS bounds on heavy neutral leptons in a realistic neutrino oscillation model](https://inspirehep.net/literature/1893584) by @JLTastet, Oleg Ruchayskiy, Inar Timiryasov.
Also update BibTeX for "How to discover QCD Instantons at the LHC" now that the [paper has been published in European Physical Journal C](https://doi.org/10.1140/epjc/s10052-021-09412-1).
```
* Add citation from 'Reinterpreting the ATLAS bounds on heavy neutral leptons in a realistic neutrino oscillation model'
- c.f. https://inspirehep.net/literature/1893584
* Update BibTeX record for 'How to discover QCD Instantons at the LHC' to reference EPJC paper
- c.f. https://doi.org/10.1140/epjc/s10052-021-09412-1
```

docs: Add citation from heavy neutral leptons neutrino oscillation model paper

---

docs/bib/general_citations.bib
docs/bib/use_citations.bib
docs/citations.rst
docs/conf.py

Resolves #1538
Separates out "general" citations in which `pyhf` is recommended or described but not actually used from "use" citations in which the software was used for the publication.
Additionally, update the following citations which now have publications in journals:
- Reinterpretation of LHC Results for New Physics: Status and Recommendations after Run 2
- Higgs boson potential at colliders: Status and perspectives
```
* Separate citation into 'general' and 'use' citations
- Add docs/bib/use_citations.bib for general citations and add it to known Sphinx BibTeX files
* Update BibTeX record for 'Reinterpretation of LHC Results for New Physics'
- c.f. https://doi.org/10.21468/SciPostPhys.9.2.022
* Update BibTeX record for 'Higgs boson potential at colliders'
- …
```

docs: Separate citations into 'use' and 'general'

---

src/pyhf/mixins.py
tests/test_mixins.py

Resolves #1545 
This PR sorts the `_ChannelSummaryMixin.channel_nbins` `dict` by its keys such that its keys are in the same order as the entries of the `_ChannelSummaryMixin.channels` `list`. This is done for aesthetics mostly and for quick checks, as users should rely on `dict` keys not `dict` ordering. It additionally adds a test.
```
* Sort _ChannelSummaryMixin.channel_nbins dict by keys to match the order of _ChannelSummaryMixin.channels
* Add a test for the order of channel_nbins keys matching the order of channels entries
```

feat: Sort `_ChannelSummaryMixin.channel_nbins` by keys to match `channels` order

---

docker/Dockerfile

Update the base image of the Dockerfile from `python:3.8-slim` to `python:3.8-slim-bullseye` to ensure that the OS is set and can only be updated through a manual update process. This provides greater package stability.
c.f. https://gitlab.cern.ch/atlas-amglab/atlstats/-/merge_requests/47
```
* Use python:3.8-slim-bullseye as the base image for the Dockerfile to ensure package stability
- Packages on distributions of OSes are not all released at the same time and updating OS versions without necessary packages being available can break Docker builds
- c.f. https://gitlab.cern.ch/atlas-amglab/atlstats/-/merge_requests/47
```

chore: Define OS in base image tag of Dockerfile

---

src/pyhf/events.py
tests/test_events.py
tests/test_public_api_repr.py

Resolves #1506
```
* Rewrite the events code to handle weakrefs more properly
- This is needed to work with Click v8.0+
* Fix up tests that were incorrectly written due to API changes in unittest.mock
```

fix: Remove WeakList in favor of built-ins

---

src/pyhf/events.py

Fixes #1555 
Promote event examples to docstrings and use Python 3 syntax.
```
* Promote pyhf.event.subscribe and pyhf.event.register examples to docstring examples
* Use Python 3 syntax in examples
```

docs: Promote comments to docstring examples for pyhf.event

---

src/pyhf/pdf.py
tests/test_optim.py
tests/test_pdf.py

Should fully resolve the last remaining parts of #867. There are two issues handled:
- `par_names` did allow for customizable fstring, but this would never get passed through to the underlying optimizers that use it, so it's being dropped as the benefit of configurability is outweighed by the extra work on the user to maintain and bookkeep
- `par_names` now correctly uses the fact that parameter sets which are non-scalar but only have one parameter (e.g. channel of 1 bin) will still be named with the index `{parameter}[0]` rather than just `{parameter}` to clarify that it's a non-scalar parameter explicitly (but also somewhat implicitly).
```
* change par_names API to drop fstring configurability
* modify par_names to handle non-scalar parameters in 1-bin channels …
```

feat: par_names handles non-scalar modifiers with 1 parameter

---

.github/workflows/dependencies-head.yml
lower-bound-requirements.txt
setup.py
src/pyhf/writexml.py
tests/test_export.py

Resolves #1566
Drop all usages of `uproot3` and only use `uproot` `v4.1.1+` for all reading and writing of ROOT files.
```
* Remove all uproot3 dependency and use uproot4 for all reading and writing of ROOT files
* Require uproot>=4.1.1 in 'xmlio' extra
* Require uproot==4.1.1 in lower-bound-requirements.txt
* Remove uproot3 HEAD of dependencies testing workflow
* Add test to ensure pyhf.writexml writes histograms to ROOT files as expected
```

feat: Drop uproot3 for uproot4 for writing ROOT files

---

docs/bib/use_citations.bib
docs/citations.rst

Add citations from vCHEP 2021 papers from [Distributed statistical inference with pyhf enabled through funcX](https://inspirehep.net/literature/1849745) and [Building and steering binned template fits with cabinetry](https://inspirehep.net/literature/1911802). Also note that citations are [automatically updated on INSPIRE](https://inspirehep.net/literature/1845084) but are incomplete.
```
* Add use citation from 'Distributed statistical inference with pyhf enabled through funcX'
- c.f. https://inspirehep.net/literature/1849745
* Add use citation from 'Building and steering binned template fits with cabinetry'
- c.f. https://inspirehep.net/literature/1911802
* Note that citations are automatically updated on INSPIRE but are incomplete
```

docs: Add use citations from vCHEP 2021

---

setup.py
src/pyhf/tensor/tensorflow_backend.py
tests/test_tensor.py

Resolves #997 
~~As TensorFlow Probability `v0.11.0+` is needed for PR #817, and as Issue #997 makes it clear that TF/TFP minor releases can be as breaking as normal major releases, require TensorFlow `v2.3.0+` in the `v2.3.X` range and TensorFlow Probability `v0.11.0+` in the `v0.11.X` range.~~
Ensure compatibility of TensorFlow Poisson's behavior with PyTorch and JAX while Issue #293 is being resolved by using the differentiable TensorFlow operations `tf.logical_or` and `tf.where` to allow for checking if the situation in which `Poisson(n=0 | lam=0)` is being encountered. This provides a working solution for both the TF `v2.2.X` and TFP `V0.10.X` API behavior as well as for the TF `v2.3.+` and TFP `v0.11.0+` API behavior. Also disallow TF `v2.3.0` given …

fix: Ensure TensorFlow backend Poisson compatibility with other backends

---

.github/ISSUE_TEMPLATE/documentation-report.yml
.github/ISSUE_TEMPLATE/feature-request.yml

Fix the links in the Issue forms to point to the same Issue type label as the form. So have the docs Issue templates point to "docs" label, etc. Amends PR #1576 where @matthewfeickert forgot to fix this.
```
* Fix the links in the Issue forms to point to the same Issue type label as the form
* Amends PR #1576
```

docs: Fix links to existing issues for 'docs' and 'feat' labels

---

src/pyhf/tensor/jax_backend.py

Required to get PR #1583 done. JAX [`v0.2.20`](https://pypi.org/project/jax/0.2.20/#history) was released 35 minutes ago  _while_ I was working on PR #1583.
```
* Update jax backend poisson docstring examples to jax v0.2.20+ DeviceArray return of showing `weak_type=True`
```

docs: Update JAX backend poisson docstring to jax v0.2.20 returns

---

README.rst
docs/contributors.rst
docs/release-notes.rst
docs/release-notes/v0.6.3.rst

Add `v0.6.3` release notes as part of completing Issue #1578 .
```
* Add release notes for pyhf v0.6.3
- c.f. https://github.com/scikit-hep/pyhf/releases/tag/v0.6.3
* Update link to uproot in README to point to uproot4 GitHub repo
* Add Sviatoslav Sydorenko as a contributor
```

docs: Add v0.6.3 release notes

---

.github/workflows/lower-bound-requirements.yml

Run pytest explicitly over the tests/ directory only to avoid in the 'Minimum supported dependencies' workflow to avoid running doctest on the docstring examples. The latest version of the JAX docsting examples have some print failures that are incompatible with the older versions of JAX, even thought the API tests pass.
```
* Run pytest explicitly over the tests/ directory only to avoid in the 'Minimum supported dependencies' workflow to avoid running doctest on the docstring examples
- The docstring examples use the latest dependencies which might have different text output than older releases. So focus only on the API tests
```

ci: Skip doctest for 'Minimum supported dependencies' workflow

---

docs/release-notes/v0.6.3.rst

Fixes #1590
Change dict to list for ``channels`` because ``channels`` is a list, not a dict. 
Hi @matthewfeickert, how does this look?
Let me know if this needs any changes.
Thanks 
```
* In pyhf v0.6.3 pyhf.pdf._ModelConfig.channels is a list, but in the release notes it was incorreclty noted as a dict. Correct this.
- Amends PR #1583
```

docs: Correct v0.6.3 release notes to note `pyhf.pdf._ModelConfig.channels` is a list

---

.github/workflows/release_tests.yml

Resolves #1581
Now that `pyhf` `v0.6.3` is out and supports Python 3.9 across all backends (TensorFlow was the missing one, all others have been supported for some time) there is a release on PyPI to test against Python 3.9
```
* Add Python 3.9 to public API tests for the 'Current Release' workflow
- Required a release to be on PyPI that supported _all_ backends on Python 3.9. With pyhf v0.6.3 out this is now possible.
```

ci: Add Python 3.9 to 'Current Release' workflow tests

---

.github/ISSUE_TEMPLATE/~release-checklist.md

Resolves #1578
Update the release checklist for project maintainers with notes taken during the pyhf v0.6.3 release process
```
* Update the release checklist for project maintainers with notes taken during the pyhf v0.6.3 release process
- Add check for copying release notes into GitHub release
- Add check for Zenodo metadata consistency
- Add check for Conda-forge feedstock requirements matching those of the GitHub project
```

docs: Update maintainer release checklist with v0.6.3 notes

---

.pre-commit-config.yaml

Resolves #1594
Wit the addition of the `jupyter-black` hook by @MarcoGorelli (c.f. https://github.com/psf/black/pull/2357) in `black` `v21.8b0` the `nbqa-black` hook has essentially been contributed to Black and now `nbqa-black` is no longer needed. This has the additional advantage of being tied to the Black version directly and doesn't require updating the Black version as an `additional_dependencies` of `nbqa-black` and also that the `black` hook id is now also contained in `black-jupyter`.
```
* Use jupyter-black pre-commit hook id from Black
- black-jupyter will run on Python and pyi files, so it replaces the black hook id as well
* Remove nbqa-black pre-commit hook from nbQA
- Marco Gorelli essentially contributed nbqa-black to Black in the form of …
```

ci: Use `jupyter-black` pre-commit hook over `nbqa-black`

---

docs/bib/use_citations.bib

Add use citation from [Publishing statistical models: Getting the most out of particle physics experiments](https://inspirehep.net/literature/1919763) &mdash; the particle physics broader community white paper. The pyhf dev team were all coauthors on this paper.
```
* Add use citation from 'Publishing statistical models: Getting the most out of particle physics experiments'
- c.f. https://inspirehep.net/literature/1919763
```

docs: Add use citation from publishing statistical models white paper

---

docs/release-notes/v0.6.3.rst

Retroactively make mention of the speedup in workspace conversion from JSON to XML + ROOT with the improvements in `uproot` `v4.1.1`. This was noticed by @alexander-held and is thanks to @jpivarski fixing a bug in https://github.com/scikit-hep/uproot4/pull/426.
```
* Add large speedup of workspace conversion from JSON to XML + ROOT with uproot v4.1.1 to pyhf v0.6.3 release notes
- c.f. https://github.com/scikit-hep/uproot4/pull/426
```

docs: Add `uproot4` writing speedup to v0.6.3 release notes

---

docs/bib/use_citations.bib

Add use citation from [Collider Signatures of Coannihilating Dark Matter in Light of the B-Physics Anomalies](https://inspirehep.net/literature/1924354) by Michael J. Baker, Darius A. Faroughy, and Sokratis Trifinopoulos
```
* Add use citation from 'Collider Signatures of Coannihilating Dark Matter in Light of the B-Physics Anomalies'
- c.f. https://inspirehep.net/literature/1924354
```

docs: Add use citation from collider signatures of coannihilating dark matter paper

---

docs/bib/use_citations.bib

Add use citation from ATLAS PUB note [Implementation of simplified likelihoods in HistFactory for searches for supersymmetry](https://cdsweb.cern.ch/record/2782654) (ATL-PHYS-PUB-2021-038).
(Full disclosure, Giordon and Lukas were on the analysis team.)
```
* Add use citation from 'Implementation of simplified likelihoods in HistFactory for searches for supersymmetry'
- ATLAS PUB note: ATL-PHYS-PUB-2021-038
- c.f. https://cdsweb.cern.ch/record/2782654
```

docs: Add use citation from simplified likelihoods ATLAS PUB note

---

docs/citations.rst
docs/conf.py
docs/outreach.rst

Resolves #969
Set the `sphinxcontrib-bibtex` style to 'unsert` so that citations are sorted in reverse chronological order. Also make them enumerated lists (can they be made reverse order enumerated lists?)
```
* Use sphinxcontrib-bibtex style 'unsrt' to sort bibtex entries in reverse chronological order
* Set the conf.py bibtex_default_style to 'unsrt'
* Use the enumerated lists option for lists of citations
```

docs: Use sphinxcontrib-bibtex style 'unsrt' to sort citations in reverse chronological order

---

docs/conf.py
setup.py

Apply results of https://github.com/executablebooks/sphinx-copybutton/pull/82 (released in [`sphinx-copybutton` `v0.3.0`](https://pypi.org/project/sphinx-copybutton/0.3.0/)) to use the `copybutton_prompt_text` regex support to accept both `>>>` and `...` as valid prompt text (along with the others shown in https://github.com/executablebooks/sphinx-copybutton/pull/82 to safeguard against future prompts) to allow for the "hello world" example from the README
https://github.com/scikit-hep/pyhf/blob/6db5223278bb3b54cb803c41d90e3972870ad1eb/README.rst#L42-L52
to be copied correctly.
This is covered in more depth in the sphinx-copybutton docs on how to [Strip and configure input prompts for code cells](https://sphinx-copybutton.readthedocs.io/en/latest/#strip-and-configure-input-prompts-for-code …

docs: Use sphinx-copybutton prompt regex to fully capture examples

---

src/pyhf/contrib/utils.py

* Resolves #1491
* First step in addressing Issue #1672 
> The HEPData landing page for the resource file can check if the [`Accept`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept) request HTTP header matches the content type of the resource file and return the content directly if so, for example, `curl -LH "Accept: application/x-tar" https://doi.org/10.17182/hepdata.89408.v1/r2`.
```
* Pass requests the `Accept` HTTP header that matches the content type
of the resource file. The HEPData landing page for the resource
requested can check if the header matches and then return the content
directly.
- c.f. https://blog.datacite.org/changes-to-doi-content-negotiation/
Co-authored-by: Graeme Watt <Graeme.Watt@durham.ac.uk>
```

refactor: Pass `Accept` header to requests in `contrib.utils.download`

---

.github/workflows/dependencies-head.yml

Use of the unauthenticated git protocol (`git://`) is no longer supported on GitHub (c.f. the 2021-09-01 GitHub Security blog [Improving Git protocol security on GitHub](https://github.blog/2021-09-01-improving-git-protocol-security-github/)). As a result, the [current HEAD of dependencies workflow](https://github.com/scikit-hep/pyhf/blob/377b85de8c5440c8e09bf2945778a4e0dfc65cca/.github/workflows/dependencies-head.yml) fails with the following error.
```
Collecting git+git://github.com/scikit-hep/uproot4.git
Cloning git://github.com/scikit-hep/uproot4.git to /tmp/pip-req-build-faju_mnt
Running command git clone --filter=blob:none -q git://github.com/scikit-hep/uproot4.git /tmp/pip-req-build-faju_mnt
fatal: remote error:
The unauthenticated git protocol on port 9418 is no longer supported. …
```

fix: Use https protocol as unauthenticated git protocol is no longer supported

---

docs/bib/HEPData_likelihoods.bib
docs/citations.rst

Add HEPData record for published statistical model and observations for the following ATLAS top physics results:
* [Measurement of the tt̅ production cross-section in the lepton+jets channel at s√ =13 TeV with the ATLAS experiment](https://www.hepdata.net/record/ins1802524)
* [Measurements of the inclusive and differential production cross sections of a top-quark-antiquark pair in association with a Z boson at s√ =13 TeV with the ATLAS detector](https://www.hepdata.net/record/ins1853014)
* [Measurement of the tt̅tt̅ production cross section in pp collisions at s√ =13 TeV with the ATLAS detector](https://www.hepdata.net/record/ins1869695)
These models started to be published [in Summer 2020 along with Phys. Lett. B 810 (2020) 135797](https://atlas.web.cern.ch/Atlas/GROUPS/PHYSICS/PAPERS/TOP …

docs: Add ATLAS top group probability model records through June 2021

---

docs/bib/HEPData_likelihoods.bib
docs/citations.rst

Add HEPData record for published statistical model and observations for ATLAS Exotics search [Search for pair production of third-generation scalar leptoquarks decaying into a top quark and a tau-lepton in pp collisions at √s = 13 TeV with the ATLAS detector](https://www.hepdata.net/record/ins1843001) (c.f. [JHEP 06 (2021) 179](https://atlas.web.cern.ch/Atlas/GROUPS/PHYSICS/PAPERS/EXOT-2019-15/)). Also link to the ATLAS public results page for stats model listing.
```
* Add ATLAS third-generation scalar leptoquarks search probability model
HEPDdata record
- c.f. https://www.hepdata.net/record/ins1843001
* Change ATLAS probability models listing to all ATLAS public results
page with clarification on keyword filters
```

docs: Add ATLAS third-generation scalar leptoquarks search statistical model record

---

src/pyhf/tensor/jax_backend.py
src/pyhf/tensor/numpy_backend.py
src/pyhf/tensor/pytorch_backend.py
src/pyhf/tensor/tensorflow_backend.py
tests/test_tensor.py

* ~~Partially addresses Issue #815~~
* Resolves #815
* Resolves #1573
Add a `percentile` function to the tensor backends that adheres to [NumPy's `numpy.percentile`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.percentile.html) API.
~~To get quotation marks to look okay for the interpolation method section of the docstrings I used `\\` to escape them given [this Stack Overflow question](https://stackoverflow.com/questions/17965655/how-to-escape-single-quotes-in-restructuredtext-when-converting-to-html-using-sp). There may be a better way.~~
Docs build at: https://pyhf--817.org.readthedocs.build/en/817/api.html#backends
```
* Add percentile function to the tensor backends
* Add tests for percentile and its interpolation methods
- JAX requires additional …
```

feat: Add percentile function to tensorlib

---

src/pyhf/workspace.py

Resolves #1684.
As confirmed by @kratsg, the pruning API was meant to take lists to specify which modifiers / samples etc. are meant to be pruned, and to not support strings in addition to that. This updates the docstrings in the public and internal API to reflect the implementation: as shown in the example in #1684, only lists are supported.
```
* Correct Workspace.prune docstrings to indicate lists are accepted
```

docs: only lists are accepted when specifying objects to prune

---

src/pyhf/tensor/jax_backend.py
src/pyhf/tensor/numpy_backend.py
src/pyhf/tensor/pytorch_backend.py
src/pyhf/tensor/tensorflow_backend.py
tests/test_tensor.py

As TensorFlow does not support a `.transpose()` or `.T` functionality for `EagerTensors` add a `transpose` function to the tensorlib API.
This is needed for PR #1694.
```
* Add transpose function to tensorlib
* Add test for transpose
* Fix a backend name typo in the JAX backend docstrings
```

feat: Add transpose function to tensorlib

---

src/pyhf/tensor/jax_backend.py

Resolves #1137 
In more recent releases of JAX the `jax.numpy` module is more filled out and it now supports `jax.numpy.tolist`, which was the only thing NumPy was used for previously.
NumPy must still be kept as JAX relies on `numpy` itself to convert from JAX DeviceArray to NumPy
https://github.com/scikit-hep/pyhf/blob/2b2b28181a038b25bd4634808cdfec869b30d834/src/pyhf/tensor/jax_backend.py#L568-L593
```
* Use jax.numpy.tolist to provide the tolist method for the JAX backend
- Note that NumPy dependency can never be removed as JAX depends on
NumPy for JAX to NumPy conversion
```

refactor: Use jax.numpy for JAX backend tensorlib.tolist

---

src/pyhf/infer/calculators.py

Now that PR #817 (and PR #1696), use `tensorlib.percentile` for the calculators.
```
* Use the tensorlib backends percentile functions when calculating
p-values in the calculators
- tensorlib.percentile requires all inputs be tensors so ensure
with tensorlib.astensor
```

refactor: Use tensorlib.percentile in calculators

---

pyproject.toml
tests/test_tensor.py

As covered in Paul Ganssle's blog post [How and why I use pytest's xfail](https://blog.ganssle.io/articles/2021/11/pytest-xfail.html) for tests that could start passing due upstream fixes in the backends it is perferable to catch this through a failing xfail test and start using these fixes then to skip the tests and have to manually track things.
```
* Mark tests that fail for backends due to upstream problems with the
respective @pytest.mark.fail_<backend> decorator. These tests could
start passing due upstream fixes in the backends and it is perferable
to catch this through a failing xfail test and start using these fixes
then to skip the tests and have to manually track things.
- Motivation for this change came from Paul Ganssle's blog post
"How and why I use …
```

test: Use xfail for tests that fail for upstream problems

---

setup.py

Set only lower bounds for all the `pyhf` backend extras. `pyhf` is testing daily the lower bounds, latest releases, and pre-releases, so these are empirically arrived at and tested. Note this is simply just enforcing the lower bounds already tested
```console
$ grep 'tensor\|torch' lower-bound-requirements.txt 
tensorflow==2.3.1  # tensorflow-probability v0.11.0 requires tensorflow>=2.3
tensorflow-probability==0.11.0  # c.f. PR #1657
torch==1.10.0
```
c.f. Henry's upcoming blog post for the deep dive on why this is optimal for libraries
Also add a note for the PR that caused these lower bounds to exist for easy reference for the core devs or the curious contributor.
```
* Set only lower bounds on the requirements for all backend extras.
- This is done to avoid …
```

build: Set only lower bounds on backend dependencies

---

setup.py
src/pyhf/contrib/utils.py
src/pyhf/exceptions/__init__.py
tests/contrib/test_utils.py
tests/test_scripts.py

* Resolves #1672
* Resolves #1111
* Resolves #1519
* Resolves #1486
```
* Refactor the internals of contrib.utils.download to be more robust and
handle uncompressed tarfile targets as well as zipfile targets.
* Mock HEPData responses to avoid load on HEPData API and avoid testing
problems due to HEPData outages. This generally makes the test suite more
robust.
* Add requests-mock as a dependency to the 'test' extra. requests-mock makes
mocking requests calls easy and allows for a pytest fixture.
* Add tests for contrib.utils.download Python API to test outside of script runner
```

refactor: Make contrib.utils.download robust to archive file types

---

src/pyhf/contrib/utils.py

From https://github.com/scikit-hep/pyhf/pull/1697#discussion_r751385432 @GraemeWatt notes:
> The `Accept` headers will be ignored if `archive_url` is a HEPData URL (ending in `?view=true`) that returns the content directly.  The `Accept` headers will only become relevant when `archive_url` is a HEPData DOI for a resource file after we redirect to a landing page.  We're still working on the relevant PR (HEPData/hepdata#412) after it expanded in scope.  The default `Accept` header is `*/*` for Python `requests` (and `curl`), different from the [default `Accept` values of most web browsers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation/List_of_default_Accept_values) where `*/*` has a lower weighting ([quality …

fix: Accept tar and zip headers in contrib.utils.download requests

---

src/pyhf/modifiers/staterror.py
src/pyhf/parameters/paramsets.py
src/pyhf/pdf.py
tests/test_modifiers.py

The `staterror` refactoring in #1639 caused `model.config.suggested_fixed()` to return `numpy.bool_` elements for `staterror` modifiers. Those behave differently from `bool` objects, and for consistency I believe it is useful to have a consistent return type, in line with the documented return type of `List[bool]`:
https://github.com/scikit-hep/pyhf/blob/f25b8ddc6ab34d089954eb4898d54220f7f2defa/src/pyhf/pdf.py#L349-L355
#1701 includes an example to showcase the current status.
There are many places at which a change could be introduced to restore the old behavior. The current implementation applies the change at the first possible point, where the list is initially created. Alternatively, a conversion could probably happen in `paramset` or at the last point in …

fix: Ensure `_ModelConfig.suggested_fixed` list contains only booleans for all modifiers

---

.github/workflows/ci.yml
.github/workflows/dependencies-head.yml
.github/workflows/docs.yml
.github/workflows/lint.yml
.github/workflows/lower-bound-requirements.yml
.github/workflows/notebooks.yml
.github/workflows/publish-package.yml
.github/workflows/release_tests.yml
.github/workflows/tag.yml

As preventative actions, quote the `python-version` numbers in CI as without quotes [YAML will treat `3.10` as a float and interpret it as `3.1`](https://twitter.com/HEPfeickert/status/1445860336565948416) which is certainly not desired. :) This won't affect us until all backends are on Python 3.10, but it will keep us from having the CI fail weirdly in the future.
Also simplify the macos-latest inclusion with `include` keyword.
Please describe the purpose of this pull request in some detail. Reference and link to any relevant issues or pull requests.
```
* Quote all python-version numbers in CI. This is done as a preventive
action to set a YAML string precedence for when Python 3.10 is added
to testing, as without quotes YAML will treat `3.10` as a float and …
```

ci: Quote GitHub Action python-version number as YAML strings

---

src/pyhf/workspace.py
tests/test_workspace.py

When building a model, unexpected kwargs are caught in `_ModelConfig` and an error is raised:
https://github.com/scikit-hep/pyhf/blob/34dd45c84426c5e14a280b7da8742d0d4fd7c83d/src/pyhf/pdf.py#L218-L221
This PR ports the same behavior over to `Workspace` construction as well. I believe this is useful to catch typos. Slightly related to #1699, where I came across this originally.
A test has been added for the new behavior. Since the workspace tests used the same `simplemodels` setup a few times for different purposes, I factored that out into a fixture. Happy to implement any other solution you may prefer for this instead.
```
* Raise an Unsupported exception if unexpected kwargs are passed during
pyhf.Workspace creation.
* Add test for this behavior.
* Refactor …
```

feat: Catch unexpected keyword arguments in workspace construction

---

setup.py
tests/conftest.py
tests/test_paramviewer.py
tests/test_regression.py

With https://github.com/scikit-hep/scikit-hep-testdata/pull/67, the sbottom probability models that are used for regression tests are added to `scikit-hep-testdata`. This provides stability in testing that is independent of HEPData's availability and doesn't abuse HEPData either as we currently ping them _a lot_ with our test suite.
This also simplifies the tests a bit by removing the need for a fixture to provide the tarfile archive.
```
* Add scikit-hep-testdata to the 'test' extra
* Use scikit-hep-testdata to provide the file path to the tar.gz that
contains the sbottom probability models used for regression tests
(pyhf-ins1748602-probability-models.tar.gz)
- File added in release scikit-hep-testdata v0.4.11
* Refactor get_json_from_tarfile pytest fixture to open …
```

test: Use scikit-hep-testdata to provide probability models for regression tests

---

src/pyhf/contrib/utils.py

Resolves #1714
Use the [`doctest` SKIP directive](https://docs.python.org/3/library/doctest.html#doctest.SKIP) to skip evaluation of all `pyhf.contrib.utils.download` related commands in the docstring example to avoid reliance on HEPData for testing. Along with PRs #1697, #1704, and #1711, this should remove all direct usage of HEPData infrastructure for testing.
```
* Use the doctest SKIP directive to skip commands related to
pyhf.contrib.utils.download in its docstring example to remove
reliance on HEPData infrastructure for testing.
- c.f. https://docs.python.org/3/library/doctest.html#doctest.SKIP
```

fix: Skip doctest of `pyhf.contrib.utils.download`

---

docs/examples/notebooks/ImpactPlot.ipynb
tests/test_notebooks.py

The nightly notebook tests are failing due to the ImpactPlot notebook because of changes in HEPData. Adopting the new DOIs for the probability models and using `pyhf contrib download` to properly deal with HEPData headers fixes this.
```
* Use stable DOI https://doi.org/10.17182/hepdata.89408.v3/r2 to download
probability models archive from HEPData.
- This version of the 1Lbb probability models uses a pyhf PatchSet, so
update the impact plot notebook accordingly.
* Use `pyhf contrib download` as it can properly accept HEPData headers.
* Change directories for the impact plot notebook test so that the paths used
in the notebook do not have to be changed to accommodate testing paths.
```

docs: Fix download method of probability models archive in impact plot notebook

---

docs/examples/notebooks/pullplot.ipynb
tests/test_notebooks.py

The nightly notebook tests are failing due to the `pullplot`  notebook because of changes in HEPData. Adopting the new DOIs for the probability models and using `pyhf contrib download` to properly deal with HEPData headers fixes this.
This is a similar PR to PR #1721.
```
* Use stable DOI https://doi.org/10.17182/hepdata.89408.v3/r2 to download
probability models archive from HEPData.
* Use `pyhf contrib download` as it can properly accept HEPData headers.
* Change directories for the impact plot notebook test so that the paths used
in the notebook do not have to be changed to accommodate testing paths.
* This PR is complimentary to PR #1721
```

docs: Fix download method of probability models archive in pull plot notebook

---

pyproject.toml
src/pyhf/tensor/jax_backend.py
tests/conftest.py
tests/test_tensor.py

Resolves #1729
To get `xfail_strict = true` to work properly in `pyproject.toml` it needs to be located under `[tool.pytest.ini_options]` as is [noted in the `pytest` docs](https://docs.pytest.org/en/6.2.x/customize.html#pyproject-toml):
> One might wonder why `[tool.pytest.ini_options]` instead of `[tool.pytest]` as is the case with other tools.
> 
> The reason is that the pytest team intends to fully utilize the rich TOML data format for configuration in the future, reserving the `[tool.pytest]` table for that. The `ini_options` table is being used, for now, as a bridge between the existing `.ini` configuration system and the future configuration format.
Once that has been moved then to deal with the issue of `pytest.xfail` skipping tests instead of running them and checking results …

test: Make fail_backend markers add pytest.mark.xfail and remove fail_jax marker on percentile tests

---

.github/workflows/publish-package.yml
docs/development.rst

There is a build up of releases on TestPyPI that will eventually need to get deleted into the future. This is a manual process (which will be done by me) and is very slow. To avoid this, only publish to TestPyPI on tags (that start with `v`) or if a workflow dispatch event is run with the user selecting the `true` option from the drop down menu in response to the question 'Publish to TestPyPI?'
Using workflow dispatch will still allow for using TestPyPI to check images before release.
https://github.blog/changelog/2021-11-10-github-actions-input-types-for-manual-workflows/
I've tested this setup of the CI config on my fork.
```
* Publish to TestPyPI on push events where a tag is pushed that starts with
a 'v' (release tags of form vX.Y.Z) or on workflow dispatch …
```

ci: Publish to TestPyPI on tag or by workflow dispatch trigger

---

.github/ISSUE_TEMPLATE/~release-checklist.md

Add step of reporting release to [GitHub Release Radar](https://github.com/github/release-radar) and add making release to TestPyPI following PR #1727.
```
* Add step of manually releasing to TestPyPI in advance of release
- Amends PR #1727
* Add step to verify citations are up to date
* Add step of opening GitHub Release Radar issue
- c.f. https://github.com/github/release-radar
```

docs: Add GitHub Release Radar check to release checklist

---

.github/workflows/docs.yml
setup.py

Disallow [`nbsphinx` `v0.8.8`](https://pypi.org/project/nbsphinx/0.8.8/) as it introduces a bug for empty 'raw' directives (c.f. https://github.com/spatialaudio/nbsphinx/issues/620). This is fixed in https://github.com/spatialaudio/nbsphinx/pull/621 and so should work its way into the next `nbsphinx` release. :+1: 
```
* Disallow nbsphinx v0.8.8 as it introduces a bug for empty 'raw' directives.
- c.f. https://github.com/spatialaudio/nbsphinx/issues/620
```

fix: Disallow nbsphinx v0.8.8 to avoid empty "raw" directive bug

---

docs/likelihood.rst

Resolves #1717
Note in warning that for shapesys and staterror modifier data with bins of `0` will result in the modifier being fixed to `1` (changed in PR #1639).
Also move description of example _before_ the example for clarity and simplicity.
```
* Update warning note for shapesys modifier, and add similar warning for
staterror modifier, that bins that have a modifier data value of 0 will
result in a nuisance parameter being allocated resulting in a fixed modifier
of 1.
- These changes occurred in PR #1639
* Move descriptions of modifier examples before example is given for clarity.
```

docs: Note shapesys and staterror modifier set to 1 for modifier data of 0

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/docker.yml
.github/workflows/docs.yml
.github/workflows/lint.yml
.github/workflows/publish-package.yml
.github/workflows/release_tests.yml

Resolves #1631 
Use GitHub Actions `concurrency` key with `cancel-in-progress` option to limit the number of concurrent workflow jobs to one per workflow per ~~`github.head_ref`~~ `github.ref` (so per branch which results in per PR). This should speed up CI by keeping the queue clear by canceling CI jobs when another commit has been pushed that would kick off the same workflow.
Example:
* On a PR a commit is pushed that doesn't pass the `pre-commit` checks.
* `pre-commit.ci` pushes back the changes that allows for `pre-commit` to pass.
* There would now be two jobs running for all the GHA workflows that run per PR, which is wasteful and slows things down.
* With 
```yaml
concurrency:
group: some-identifying-string-${{ github.ref }}
cancel-in-progress: true
```
the offending first workflow …

ci: Limit concurrent workflow jobs to one per workflow per branch

---

.github/workflows/publish-package.yml

* Update gh-action-pypi-publish action to [`v1.5.0`](https://github.com/pypa/gh-action-pypi-publish/releases/tag/v1.5.0) to enable `print_hash` to show digests of files to be uploaded.
```
* Update gh-action-pypi-publish action to v1.5.0 to enable print_hash
to show digests of files to be uploaded.
```

ci: Update gh-action-pypi-publish to use print_hash

---

src/pyhf/tensor/jax_backend.py

In [JAX `v0.2.27`](https://github.com/google/jax/releases/tag/jax-v0.2.27) the error raised for trying to pass a sequence as a list includes a `ValueError`
```python
>>> import jax
>>> import jax.numpy as jnp
>>> jax.__version__
'0.2.27'
>>> jnp.asarray([[1, 2], 3, [4]])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/.../site-packages/jax/_src/numpy/lax_numpy.py", line 3648, in asarray
return array(a, dtype=dtype, copy=False, order=order)
File "/.../site-packages/jax/_src/numpy/lax_numpy.py", line 3606, in array
out = np.array(object, dtype=dtype, ndmin=ndmin, copy=False)
ValueError: setting an array …
```

fix: Accept ValueError for JAX backend `tolist` fallback

---

.github/workflows/ci.yml

If the pytest jobs fail and the ci workflow was triggered as the result of a workflow dispatch, launch a [tmate session](https://github.com/mxschmitt/action-tmate) which allows for sshing into the runner with the environment from the failed job.
This idea comes from Simon Willison's (@simonw) blog post (in his TIL series): [Open a debugging shell in GitHub Actions with tmate](https://til.simonwillison.net/github-actions/debug-tmate). Thanks Simon!
```
* If the pytest jobs fail and the ci workflow was triggered as the result of
a workflow dispatch, launch a tmate session which allows for sshing into the
runner with the environment from the failed job.
- c.f. https://github.com/mxschmitt/action-tmate
This idea comes from Simon Willison's (@simonw) blog post: …
```

ci: Launch tmate session if pytest fails on workflow dispatch run

---

tests/test_tensor.py

Resolves #1759
To avoid the floating point deviations that are seen only on macOS runners with TensorFlow `v1.8.0` use `pytest.approx` for the failing test. Add the corresponding `xfail` test to know if this ever stops being needed.
```
* Use pytest.approx in test_simple_tensor_ops to avoid floating point
difference with tensorflow on macOS (compared to Linux).
* Add a pytest.mark.xfail test for the failing operation to know if future
tensorflow releases cause this to floating point difference to stop happening.
```

test: Avoid tensorflow macOS floating point deviation with pytest.approx

---

.github/workflows/dependencies-head.yml

As seen in Issue #1759, testing release candidates of software only on Linux distributions is not enough to catch bugs before they hit in public releases. To guard against this in the future, add `macos-latest` to tests for release candidates on PyPI.
```
* As seen in Issue #1759, testing pre-releases of software only on Linux
distributions is not enough to catch bugs before they hit in public
releases. To guard against this in the future, add macos-latest to
tests for release candidates on PyPI.
```

ci: Add macos-latest to dependency release candidates testing

---

docs/conf.py
tests/test_optim.py

Resolves #1766 
At the time of opening this PR there are still problems (c.f. https://github.com/scipy/scipy/issues/15545#issuecomment-1031909411), however those should be resolved in time. This PR tries to avoid some problems in the future by updating the `scipy` intersphinx url to use `https://docs.scipy.org/doc/scipy/objects.inv` (new as of `scipy` `v1.8.0`) to avoid getting redirected there from `https://docs.scipy.org/doc/scipy/reference/objects.inv`.
```
* Update scipy scipy intersphinx url to target 'https://docs.scipy.org/doc/scipy/objects.inv'
to avoid redirect from 'https://docs.scipy.org/doc/scipy/reference/'.
- This is the result of SciPy changing the location in scipy v1.8.0.
```

docs: Update scipy intersphinx url to drop 'reference'

---

.github/workflows/ci.yml
pyproject.toml

Add html ~~and annotated source code~~ coverage report option~~s~~ to `pyproject.toml` to get more reports for local testing.
The `html` version is quite nice as you can simply open up the `htmlcov/index.html` file in your browser and scroll through the same report that you'd see on Codecov. :+1: 
Examples:
```
* Add pytest tool options for html coverage reports
```

test: Add html coverage reports from pytest

---

.coveragerc
.github/workflows/ci.yml
.github/workflows/dependencies-head.yml
.github/workflows/lower-bound-requirements.yml
.github/workflows/notebooks.yml
.github/workflows/release_tests.yml
pyproject.toml
tests/test_export.py
tests/test_optim.py
tests/test_tensor.py

Resolves #1685
Remove `.coveragerc` and consolidate pytest options to `pyproject.toml` (this results in `--cov-branch` getting added.) In doing so, also apply the [Configuring pytest recommendations from Scikit-HEP](https://scikit-hep.org/developer/pytest#configuring-pytest) that Henry wrote.
* `-ra` includes a report after pytest runs with a summary on all tests except those that passed. From `pytest --help`:
- > -r chars              show extra test summary info as specified by chars: (f)ailed, (E)rror, (s)kipped, (x)failed, (X)passed, (p)assed, (P)assed with output, (a)ll except passed (p/P), or (A)ll. (w)arnings are enabled by default (see --disable-warnings), 'N' can be used to reset the list. (default: 'fE').
- This allows for removal of `-r sx` in all the CI jobs.
* ~~`-Wd` enables …

test: Consolidate and update pytest options in pyproject.toml

---

pyproject.toml

Resolves #1774
```
* setuptools releases prior to v42.0.0 had stability issues with
pyproject.toml or didn't support PEP 517 and so couldn't support
pyproject.toml.
- c.f. https://www.python.org/dev/peps/pep-0517/
Co-authored-by: Henry Schreiner <henry.fredrick.schreiner@cern.ch>
```

build: Require setuptools v42.0.0+ for stability

---

pyproject.toml

Resolves #1787 
As noted by @henryiii in https://github.com/scikit-hep/pylhe/pull/111, neither `wheel` or `attrs` are needed.
* Remove wheel from build-system requires as it is declared by PEP 517's `get_requires_for_build_sdist` and so already covered.
- c.f. https://www.python.org/dev/peps/pep-0517/
* Remove attrs as not required at build time.
```
* Remove wheel from build-system requires as it is declared by
PEP 517's get_requires_for_build_sdist and so already covered.
- c.f. https://www.python.org/dev/peps/pep-0517/
* Remove attrs as not required at build time.
```

build: Remove wheel and attrs from build-system requires

---

README.rst

Resolves #1782
Add a "User Guide" section as the very first section in the README that link to the [`pyhf` tutorial](https://pyhf.github.io/pyhf-tutorial/). Also add badge to the Jupyter Book tutorial to the top of the README. [![Jupyter Book Badge](https://jupyterbook.org/_images/badge.svg)](https://pyhf.github.io/pyhf-tutorial/)
```
* Add section to README that links to the pyhf tutorial.
- c.f. https://pyhf.github.io/pyhf-tutorial/
* Add badge to the Jupyter Book tutorial to the top of the README.
* Add section to README that explicitly links to the documentation.
- c.f. https://pyhf.readthedocs.io/
```

docs: Add section for tutorial and docs to README

---

docs/bib/general_citations.bib

Add general citation from [Differentiable Matrix Elements with MadJax](https://inspirehep.net/literature/2040678) by @lukasheinrich and @makagan. :rocket: 
The paper was also submitted to the Proceedings of the 20th International Workshop on Advanced Computing and Analysis Techniques in Physics Research (ACAT 2021), but as that doesn't seem to be published yet we'll just treat it as a standalone paper for now.
```
* Add general citation from 'Differentiable Matrix Elements with MadJax'.
- c.f. https://inspirehep.net/literature/2040678
```

docs: Add general citation from MadJAX paper

---

docs/bib/use_citations.bib

Add use citation from ATLAS paper [Search for events with a pair of displaced vertices from long-lived neutral particles decaying into hadronic jets in the ATLAS muon spectrometer in pp collisions at \sqrt{s}=13 TeV](https://inspirehep.net/literature/2040545) ([ANA-EXOT-2019-24](https://atlas.web.cern.ch/Atlas/GROUPS/PHYSICS/PAPERS/EXOT-2019-24/)).
```
* Add use citation from 'Search for events with a pair of displaced vertices
from long-lived neutral particles decaying into hadronic jets in the ATLAS
muon spectrometer in pp collisions at \sqrt{s}=13 TeV'
- ATLAS paper: ANA-EXOT-2019-24
- c.f. https://inspirehep.net/literature/2040545
```

docs: Add use citation from ATLAS UEH MS displaced jet paper

---

CITATION.cff

In PR #1551 we accidentally had @kratsg listed as being at Illinois in the `CITATON.cff` file. whoops.
```
* Fix typo that had Illinois twice instead of SCIPP
- Amend PR #1551
```

docs: Correct Giordon's affiliation to SCIPP in CITATON.cff

---

docs/bib/use_citations.bib

Add use citation from ATLAS paper [Search for neutral long-lived particles in pp collisions at \sqrt{s}=13 TeV that decay into displaced hadronic jets in the ATLAS calorimeter](https://inspirehep.net/literature/2043503) ([ANA-EXOT-2019-23](https://atlas.web.cern.ch/Atlas/GROUPS/PHYSICS/PAPERS/EXOT-2019-23/)).
Congratulations on the nice publication to @masonproffitt and @gordonwatts who were on the analysis team! :rocket:
```
* Add use citation from 'Search for neutral long-lived particles in pp collisions
at \sqrt{s}=13 TeV that decay into displaced hadronic jets in the ATLAS calorimeter'.
- ATLAS paper: ANA-EXOT-2019-23
- c.f. https://inspirehep.net/literature/2043503
```

docs: Add use citation from ATLAS UEH displaced jets CalRatio paper

---

docs/likelihood.rst

No issue related. Change minor typo in docs.
```
* Change phrasing in MC Stat Error docs from "constrained term" to "constraint term"
```

docs: Fix tiny typo in MC Stat Error documentation

---

.github/workflows/ci.yml
.github/workflows/dependencies-head.yml
.github/workflows/docs.yml
.github/workflows/lint.yml
.github/workflows/notebooks.yml
.github/workflows/publish-package.yml
.github/workflows/release_tests.yml
.github/workflows/tag.yml

Resolves #1758 
Now that PyTorch [`v1.11.0`](https://pypi.org/project/torch/1.11.0/) is out with [Python 3.10 support](https://pypi.org/project/torch/1.11.0/#files), we can add CPython 3.10 to the CI. A follow up PR will add Python 3.10 to the metadata.
```
* Add CPython 3.10 to the testing matrix in CI.
* Use CPython 3.10 as the default Python for all CI/CD workflows.
```

ci: Add CPython 3.10 to testing

---

codemeta.json
docker/Dockerfile
setup.cfg

Follow up PR to PR #1808 
* Add support for Python 3.10 to the PyPI metadata and codemeta.json.
* Update Dockerfile base image to `python:3.10-slim-bullseye`.
```
* Add support for Python 3.10 to the PyPI metadata and codemeta.json.
* Update Dockerfile base image to python:3.10-slim-bullseye.
```

build: Add support for Python 3.10 across all backends

---

docs/bib/use_citations.bib

Add use citation from [neos: End-to-End-Optimised Summary Statistics for High Energy Physics](https://inspirehep.net/literature/2050088) by @phinate and @lukasheinrich. :rocket: 
Congrats to them both! :)
[![neos_shot](https://user-images.githubusercontent.com/5142394/158256265-45dc95a2-c15c-4ee5-8d66-7c1885137208.png)](https://arxiv.org/abs/2203.05570)
The paper was also submitted to the Proceedings of the 20th International Workshop on Advanced Computing and Analysis Techniques in Physics Research (ACAT 2021), but as that doesn't seem to be published yet we'll just treat it as a standalone paper for now.
```
* Add use citation from 'neos: End-to-End-Optimised Summary Statistics for High
Energy Physics'.
- c.f. https://inspirehep.net/literature/2050088
```

docs: Add use citation from neos paper

---

src/pyhf/tensor/jax_backend.py

Update `jax` backend `normal` docstring examples to `jax` `v0.3.2+` `DeviceArray` return of showing `weak_type=True`. This is the same sort of thing that was required for PR #1584.
So now after the update
```console
$ python -m pip list | grep jax
jax                               0.3.2
jaxlib                            0.3.2
jupyter-server-mathjax            0.2.3
$ pytest src/pyhf/tensor/jax_backend.py
```
passes the doctest. :+1: 
```
* Update jax backend normal docstring examples to jax v0.3.2+
DeviceArray return of showing `weak_type=True`.
```

docs: Update JAX backend normal docstring to jax v0.3.2 returns

---

src/pyhf/writexml.py
tests/test_export.py
tests/test_export/workspace_no_parameter_bounds.json
tests/test_export/workspace_no_parameter_inits.json

Fixes #1814.
```
* In situations in writexml where the normfactor parameter config is missing
inits or bounds, fall back to using default values instead.
* Add tests that use workspaces with no parameter inits and no parameter bounds
to cover this behavior.
```

fix: writexml handles missing parameter configs for normfactor

---

docs/conf.py
src/pyhf/schema/__init__.py
tests/test_public_api.py
tests/test_schema.py

Resolves #1815, originally asked on #1753.
```
* Add contextlib support to the pyhf.schema API.
- Follow up to PR #1753.
* Add tests for use of the schema contextlib to tests/test_schema.py.
* Add tests for use of the schema contextlib to the public API tests.
```

feat: Add contextlib support to pyhf.schema API

---

src/pyhf/writexml.py
tests/test_export.py

Resolves #1770.
```
* Add comment to writexml.py to clarify the role of staterror's name when
exporting to HistFactory XML.
* Add modifier type to test_export_modifier and assert that the modifier for
StatError has no name attribute.
```

test: Assert exported StatError has no name attribute

---

setup.py

Stopgap measure to deal with Issue #1823 for the time being until there is a fix. As `nbsphinx` `v0.8.7` is reliant on `Jinja2` `v3.0.X` APIs and so `Jinja2` `v3.1.0` breaks it.
This is a stopgap measure and this should be removed as soon as there is a resolution and new `nbsphinx` release.
c.f. https://github.com/spatialaudio/nbsphinx/issues/641 for more details.
```
* Disallow Jinja2 v3.1.0 to avoid nbsphinx triggering attribute error:
AttributeError: module 'jinja2.utils' has no attribute 'escape'
This is a stopgap measure and this line should be removed as soon as there
is a resolution and new nbsphinx release.
- c.f. https://github.com/spatialaudio/nbsphinx/issues/641
```

fix: Disallow Jinja2 v3.1.0 to avoid nbsphinx triggering attribute error

---

pyproject.toml

Add a ignore to pytest `filterwarnings` to avoid `Pillow` `DeprecationWarning`
> DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
> DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
> DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
> DeprecationWarning: HAMMING is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.HAMMING instead.
> DeprecationWarning: BOX is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BOX instead.
> DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use …

fix: Add filterwarnings ignore for Pillow DeprecationWarning

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/dependencies-head.yml
.github/workflows/docker.yml
.github/workflows/docs.yml
.github/workflows/lint.yml
.github/workflows/lower-bound-requirements.yml
.github/workflows/merged.yml
.github/workflows/notebooks.yml
.github/workflows/publish-package.yml
.github/workflows/release_tests.yml
.github/workflows/tag.yml

* Update GitHub Action workflows:
- Use [actions/checkout v3](https://github.com/actions/checkout/releases/tag/v3.0.0) for all workflows.
- Use [github/codeql-action/init v2](https://github.com/github/codeql-action).
- Use [github/codeql-action/analyze v2](https://github.com/github/codeql-action).
- Use [hadolint/hadolint-action v2.1.0](https://github.com/hadolint/hadolint-action/releases/tag/v2.1.0).
Don't touch the `tag.yml` workflow though as that's going to be deprecated soon, and it is best not to touch something important and difficult to test like that.
```
* Update GitHub Action workflows:
- Use actions/checkout v3 for all workflows.
https://github.com/actions/checkout/releases/tag/v3.0.0
- Use github/codeql-action/init v2 and github/codeql-action/analyze v2. …
```

ci: Update GitHub Actions to next stable version

---

.github/workflows/dependencies-head.yml

With the addition of `matplotlib` nightly wheels on the [`scipy-wheels-nightly` Anaconda Cloud organization](https://anaconda.org/scipy-wheels-nightly) package index (c.f. https://github.com/matplotlib/matplotlib/pull/22733), wheels that are either at, or very close to, matplotlib's HEAD on GitHub can now be tested.
As the only place that `matplotlib` is used in `pyhf` is in `pyhf.contrib`, only test the `contrib` module instead of all of `pyhf`.
Note for devs: 
* Need to use `--extra-index-url` as dependencies aren't on scipy-wheels-nightly package index.
* Need to use `--pre` as dev releases will need priority over stable releases.
```
* With the addition of matplotlib nightly wheels on the
scipy-wheels-nightly Anaconda Cloud organization package index,
wheels that …
```

ci: Add matplotlib nightly wheels to HEAD of dependencies testing

---

.github/workflows/dependencies-head.yml

Use a [GitHub Actions concurrency group](https://docs.github.com/en/actions/using-jobs/using-concurrency) to limit the HEAD of dependencies workflow to only one run at a time.
Normally this will never get used, but if someone is trying to test something on a dev branch then this will be helpful to avoid wasting a lot of cycles.
```
* Use a concurrency group to limit the HEAD of dependencies workflow
to only one run at a time.
- c.f. https://docs.github.com/en/actions/using-jobs/using-concurrency
```

ci: Add concurrency group to HEAD of dependencies workflow

---

setup.py

Revert PR #1824 given updates in `nbconvert` `v6.4.5` (c.f. https://github.com/spatialaudio/nbsphinx/issues/641#issuecomment-1086944106). The issues described there were resolved upstream of `nbsphinx` in https://github.com/jupyter/nbconvert/pull/1737.
```
* Revert PR #1824 to remove restrictions place on Jinja2 given
https://github.com/spatialaudio/nbsphinx/issues/641. The issues
described there were resolved upstream of nbsphinx in
https://github.com/jupyter/nbconvert/pull/1737.
- Lower bounds of 'nbconvert>=6.4.5' are not added as lower
bound restrictions should be applied upstream of pyhf in
nbsphinx. PR #1824 was applied only because it was
necessary.
```

revert: Remove Jinja2 restrictions given nbconvert v6.4.5

---

.github/workflows/notebooks.yml
pyproject.toml
setup.py
tests/test_notebooks.py

To get the notebook tests to pass given the many warnings that pop up from the Jupyter infrastructure and `papermill`, override the ini option for `filterwarnings` (added in PR #1773) with an empty list to disable error on filterwarnings as the notebook tests are testing for notebooks to run with the latest API, not if Jupyter infrastructure is warning free.
The use of `PYTHONWARNINGS='default'` should be possible, but is causing errors and is now Issue #1840.
Use `scrapbook` as it is the new name of `nteract-scrapbook` and `nteract-scrapbook` is no longer maintained or developed.
Restrict `papermill` and `scrapbook` to compatible releases at the patch level for API stability.
Use the `papermill.execute_notebook` `cwd` optional argument to change the execution directory safely to avoid …

fix: Override error on filterwarnings to pass notebook tests

---

docs/bib/general_citations.bib

Add general citation from ATLAS PUB note [SimpleAnalysis: Truth-level Analysis Framework](https://cds.cern.ch/record/2805991/) (ATL-PHYS-PUB-2022-017). @kratsg and @lukasheinrich were on the analysis team for the note.
All figures including auxiliary figures are available at https://atlas.web.cern.ch/Atlas/GROUPS/PHYSICS/PUBNOTES/ATL-PHYS-PUB-2022-017
```
* Add general citation from ATLAS PUB note 'SimpleAnalysis: Truth-level Analysis Framework'.
- ATL-PHYS-PUB-2022-017
- c.f. https://cds.cern.ch/record/2805991/
```

docs: Add general use citation from SimpleAnalysis ATLAS PUB note

---

docs/bib/general_citations.bib

Add general citation from [Toward the End-to-End Optimization of Particle Physics Instruments with Differentiable Programming: a White Paper](https://inspirehep.net/literature/2059102). @lukasheinrich is an author on the paper.
```
* Add general citation from 'Toward the End-to-End Optimization of Particle
Physics Instruments with Differentiable Programming: a White Paper'.
- c.f. https://inspirehep.net/literature/2059102
```

docs: Add general use citation from End-to-End Optimization paper

---

tests/conftest.py

Resolves #1728
Use `setuptools._distutils` over `distutils` as `distutils` is deprecated in Python 3.10 and scheduled for removal in Python 3.12 as noted in the [`pip` `v21.3` release notes](https://pip.pypa.io/en/stable/news/#v21-3).
Also apply `isort` to `tests/conftest.py` as a small change like this seemed like a good time to sneak it in.
```
* Use setuptools._distutils over distutils as distutils is deprecated in
Python 3.10 and scheduled for removal in Python 3.12 as noted in the pip v21.3
release notes.
- c.f. https://pip.pypa.io/en/stable/news/#v21-3
```

refactor: Deprecate distutils in favor of setuptools._distutils

---

README.rst
src/pyhf/cli/infer.py

[GitHub is killing off the `git.io` URL shortening service this Friday (2022-04-29)](https://github.blog/changelog/2022-04-25-git-io-deprecation/) so all URLs in the docs that use it need to be updated.
```
* Replace all instances of git.io shortened URLs with full URLs as git.io is
being killed off by GitHub on 2022-04-29.
- c.f. https://github.blog/changelog/2022-04-25-git-io-deprecation/
```

docs: Deprecate use of git.io URL shortener

---

docs/development.rst
docs/examples/notebooks/binderexample/StatisticalAnalysis.ipynb
docs/governance/ROADMAP.rst
src/pyhf/optimize/opt_minuit.py

Update all links that `sphinx -b linkcheck` identifies as being broken as part of Issue #1853.
* Use [new URL](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-extra-index-url) for the docs on `pip install --extra-index-url`.
* Fix yadage GitHub organization and also link to @lukasheinrich's [KubeCon 2018 keynote](https://youtu.be/2PRGUOxL36M) instead of yadage on GitHub.
* Remove the 'edit#gid' key from the end of Google Sheets URLs that direct to a specific page on a Google Sheet. While [they are valid links](https://docs.google.com/spreadsheets/d/1VKpHlQWXu_p8AUv5E5H_BzqF_i7hh2Z-Id0XPwNHu8o/edit#gid=1864915304), linkcheck doesn't properly handle them and it is easier to just avoid it.
* Use the CERN CDS entry for the [MINUIT: Function Minimization and Error Analysis Reference …

docs: Fix broken links identified by Sphinx linkcheck

---

.readthedocs.yaml

Update the ReadTheDocs build image to use `ubuntu:22.04`
c.f. https://twitter.com/readthedocs/status/1522266722635436041
```
* Use the Docker image ubuntu:22.04 to run the ReadTheDocs build.
- c.f. https://twitter.com/readthedocs/status/1522266722635436041
```

ci: Update ReadTheDocs build to Ubuntu 22.04

---

docs/bib/use_citations.bib

Add use citation from [Strange quark as a probe for new physics in the Higgs sector](https://inspirehep.net/literature/2052514), by Alexander Albert, Matthew J. Basso, Samuel K. Bright-Thonney, Valentina M. M. Cairo, Chris Damerell, Daniel Egana-Ugrinovic, Ulrich Heintz, @shomiller, Shin-ichi Kawada, Jingyu Luo, Chester Mantel, Patrick Meade, Jose Monroy, Meenakshi Narain, Robert S. Orr, Joseph Reichert, Anders Ryd, Jan Strube, Dong Su, Ariel G. Schwartzman, Tomohiko Tanabe, Junping Tian, Emanuele Usai, Jerry Va'vra, Caterina Vernieri, Charles C. Young, Rui Zou. The paper was part of the Snowmass 2022 submissions.
```
* Add use citation from 'Strange quark as a probe for new physics in the Higgs sector'.
- c.f. https://inspirehep.net/literature/2052514
- Contribution …
```

docs: Add use citation from strange quark probe Snowmass paper

---

docs/bib/use_citations.bib

Add use citation from ATLAS paper [Search for heavy, long-lived, charged particles with large ionisation energy loss in pp collisions at s√=13 TeV using the ATLAS experiment and the full Run 2 dataset](https://inspirehep.net/literature/2080541).
```
* Add use citation from 'Search for heavy, long-lived, charged particles with
large ionisation energy loss in pp collisions at s√=13 TeV using the ATLAS
experiment and the full Run 2 dataset'.
- ATLAS paper: SUSY-2018-42
- c.f. https://inspirehep.net/literature/2080541
```

docs: Add use citation from ATLAS dE/dX long-lived particle paper

---

src/pyhf/cli/rootio.py
src/pyhf/readxml.py
tests/test_import.py

This resolves #1864. Added functionality `pyhf.readxml` to push the exception down to a warning if needed, so conversion still works for invalid XML workspaces, but will still warn that it is invalid. This also adds it to `pyhf xml2json` as well.
```
* Add ability to passing validation_as_error=False to readxml.parse to warn when the workspace
is invalid instead of just raising an exception (default is to raise exception).
* Add --validation-as-error/validation-as-warning flag to xml2json command line interface to
switch between the two (default is to raise exception).
```

feat: Allow readxml to demote validation exception to warning

---

docs/contributors.rst
docs/likelihood.rst

clarify and fix typo for `Staterror` modifier.
The `\delta` parameter is the absolute error in each bin due to MC Stat at +/- 1 sigma. Thus, the `\sigma` of the Gaussian constraint term should have `\delta / nominal` value not the other way around.
And by play around with the `logpdf()` output, I'm convinced that the input in JSON is `\delta` rather than `\delta^2` (https://scikit-hep.org/pyhf/intro.html#id25)
```
* Correct the description of the calculation of the scale of the constraint
to indicate it is calculated from the relative statistical uncertainty from the
channel's event rate.
* Add additional channel subscripts to make the notation be more explicit that
staterror is per-channel.
* Remove typo of additional 'are'.
* Add Jerry Ling to contributor list.
```

docs: Clarify staterror modifier specification

---

docs/Makefile
docs/conf.py
docs/governance/ROADMAP.rst

~* Manually specify Sphinx options of `-W` and remove `--keep-going` to avoid hanging of completed Sphinx `linkcheck` Make target in GitHub Actions CI. I'm not sure why this is happening in CI, as I can't reproduce it locally, but this is perhaps the easiest step forward to get things working.~
* Ignore the DOI URL for [SModelS database update v1.2.3](https://inspirehep.net/literature/1794162)
https://github.com/scikit-hep/pyhf/blob/461d3685b88ad7cec6df684eefae9d44da275d2f/docs/JOSS/paper.bib#L104
during Sphinx's `linkcheck` as it is causing timeout errors in CI like
```
(       citations: line   25) broken    https://doi.org/10.31526/lhep.2020.158 - HTTPConnectionPool(host='journals.andromedapublisher.com', port=80): Max retries exceeded with url: /index.php/LHEP/article/download/158/86/ …
```

test: Ignore LHEP DOI URLs during Sphinx linkcheck

---

docs/conf.py

DOI URLs for EPJ Web of Conferences proceedings will periodically fail to resolve given '500 Server Error' as the result of EPJ backend problems.
Example:
```
(       citations: line   25) broken    https://doi.org/10.1051/epjconf/202024506017 - 500 Server Error: Internal Server Error for url: https://www.epj-conferences.org/10.1051/epjconf/202024506017
(           index: line  309) ok        https://github.com/scikit-hep/pyhf/pull/1000
(   release-notes: line   19) ok        https://github.com/scikit-hep/pyhf/pull/1001
(       citations: line   25) broken    https://doi.org/10.1051/epjconf/20212[510](https://github.com/scikit-hep/pyhf/runs/6603171789?check_suite_focus=true#step:7:511)2070 - 500 Server Error: Internal Server Error for url: …
```

test: Ignore EPJ Web of Conferences DOI URLs during Sphinx linkcheck

---

setup.py
tests/constraints.txt

`protobuf` `v3.20.1` is the last release to support ABI compatibility with `tensorflow` pre `tensorflow` `v2.9.1`. The next release of `protobuf`, [`v4.21.0`](https://pypi.org/project/protobuf/4.21.0/) (released 2022-05-25), breaks ABI compatibility and so requires an upper bound of `protobuf` `v3.20.1` for older `tensorflow` releases to not break.
`tensorflow` released a series of patch releases in response to `protobuf` `v4.21.0`: `v2.6.5`, `v2.7.3`, `v2.8.2`, `v2.9.1`. As the oldest `tensorflow` that `pyhf` supports API compatibility with is `tensorflow` `v2.3.1` add an upper bound of `protobuf<=3.20.1` to `ci/constraints.txt` ~update the lower bound to `tensorflow>=2.6.5`~.
c.f. https://github.com/tensorflow/tensorflow/issues/56077
~**edit**: Motivated by discussions below, this PR is …

test: Restrict tf dependency protobuf to ABI compatible releases

---

setup.py
tests/constraints.txt

Amends PR #1869. Following Discussion #1871, bump tensorflow lower bound to the oldest supported version by the TensorFlow project following https://github.com/tensorflow/tensorflow/issues/56077.
```
* Update lower bound on tensorflow to v2.6.5 as it is the "oldest" SemVer release
that is not broken on install by protobuf v4.21.0 ABI incompatibility.
- c.f. https://github.com/tensorflow/tensorflow/issues/56077
- Amend PR #1869
* Update tests/constraints.txt to use tensorflow==2.6.5.
```

build: Update lower bound on tensorflow to v2.6.5

---

pyproject.toml

Resolves #1872.
Use `(true_)?divide` regex to match to 'true_divide' or 'divide' in `RuntimeWarning` from NumPy.
```
* Add `(true_)?divide` regex in pytest filterwarnings to match to 'true_divide'
or 'divide' in `RuntimeWarning` from NumPy.
Co-authored-by: Angus Hollands <goosey15@gmail.com>
```

fix: Allow for true_divide or divide `RuntimeWarning` from NumPy

---

docs/conf.py

Set 'en' - English as the language for the docs. In [Sphinx v5.0.0+](https://github.com/sphinx-doc/sphinx/releases/tag/v5.0.0) setting a language is required to avoid:
```pytb
WARNING: Invalid configuration value found: 'language = None'
```
```
* Set 'en' - English as the language for the docs. In Sphinx v5.0.0+ setting
a language is required to avoid:
> WARNING: Invalid configuration value found: 'language = None'
```

docs: Set English as language for Sphinx

---

.pre-commit-config.yaml

`name-tests-test` verifies that test files under `tests/` conform to pytest naming conventions.
```
* Add the 'name-tests-test' pre-commit hooks which verifies that test files
under tests/ conform to pytest naming conventions.
- Use the '--django' option to match the 'test*.py' naming convention.
```

ci: Add 'name-tests-test' to pre-commit hooks

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/dependencies-head.yml
.github/workflows/docker.yml
.github/workflows/docs.yml
.github/workflows/lint.yml
.github/workflows/notebooks.yml
.github/workflows/publish-package.yml
.github/workflows/release_tests.yml
.github/workflows/semantic-pr-check.yml

Use `github.workflow` property to ensure that the concurrency group id from `${{ github.workflow }}-${{ github.ref }}` is unique to the workflow.
c.f. [Example: Only cancel in-progress jobs or runs for the current workflow](https://docs.github.com/en/actions/using-jobs/using-concurrency#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow)
This also simplifies maintenance as it is removes unique names that need to be manually searched for.
```
* Use github.workflow property to ensure that the concurrency group id from
`${{ github.workflow }}-${{ github.ref }}` is unique to the workflow.
- c.f. https://docs.github.com/en/actions/using-jobs/using-concurrency
```

ci: Use `github.workflow` property to ensure unique concurrency group

---

setup.cfg

Resolves #1880
Use `find_namespace:` in conjunction with `include_package_data = True` in `setup.cfg` to properly find package data (`pyhf.data` and `pyhf.schemas`) during build of sdist and wheel. The [recommendation from `setuptools`](https://setuptools.pypa.io/en/stable/userguide/datafiles.html#subdirectory-for-data-files) is to treat the `data/` and `schemas/` subdirectories as namespace packages given [PEP 420](https://peps.python.org/pep-0420/).
```
* Use `find_namespace:` in conjunction with `include_package_data = True` in setup.cfg
to properly find package data (pyhf.data and pyhf.schemas) during build of sdist
and wheel.
- The recommendation from setuptools is to treat the data/ and schemas/ subdirectories as
namespace packages given PEP 420 …
```

build: Use `find_namespace:` to ensure discovery of package data

---

src/pyhf/pdf.py
tests/test_pdf.py

Provides functionality for clipping `expected_data` in the `_MainModel` via `pyhf.Model(clip_sample_data=0.0, clip_bin_data=0.0)` keyword arguments. Added to the docstrings.
Backwards functionality is preserved, which is that clipping is not done. There does not seem to be a performance hit in checking for clipping or not. Clipping can be done at two levels:
- the level at which we have the individual samples (perhaps useful if we need the granularity and a specific sample is providing large negative yields)
- the level at which we have the bin-by-bin data (this is primarily the expected use case that makes the most sense? Maybe...)
Note that it seems ROOT primarily goes for the level of the individual samples, so adding both options and leaving it up to the user to decide if they want to …

feat: Allow for clipping negative yields in the main model

---

.pre-commit-config.yaml

Following https://github.com/pre-commit/pre-commit-hooks/pull/779 and [pre-commit-hooks `v4.3.0`](https://github.com/pre-commit/pre-commit-hooks/releases/tag/v4.3.0) use the `--pytest-test-first` option of `name-tests-test` for clarity.
This amends PR #1877.
Related: https://github.com/scikit-hep/scikit-hep.github.io/pull/231
```
* Update github.com/pre-commit/pre-commit-hooks: v4.2.0 → v4.3.0 to get
`--pytest-test-first` option for name-test-tests.
* Use `--pytest-test-first` option for name-test-tests for greater clarity of
convention.
* Amends PR #1877.
```

ci: Use '--pytest-test-first' option for naming clarity

---

setup.py
tests/constraints.txt

This was caught in the [Minimum supported dependencies workflow](https://github.com/scikit-hep/pyhf/blob/2411ed32e4077259a6676bd95f3e381e1b5b3507/.github/workflows/lower-bound-requirements.yml) after PR #1845 was merged.
Update lower bound on `iminuit` to `v2.7.0` as it is the 'oldest' SemVer release that has the behavior (as described in the [`iminiuit` `v2.7.0` changelog](https://iminuit.readthedocs.io/en/stable/changelog.html#july-4-2021)):
> `Minuit.hesse` no longer sets the status of the `FunctionMinimum` unconditionally to valid if it was invalid before.
Without this fix, the situation can arise where `Minuit.hesse()` can cause `Minuit.valid` to be `True` when it should be `False`. Specifically in 
https://github.com/scikit-hep/pyhf/blob/2411ed32e4077259a6676bd95f3e381e1b5b3507/src/p …

build: Update lower bound on iminuit to v2.7.0 

---

docs/bib/use_citations.bib

Add use citation from Audrey Kvam's Ph.D. thesis: [Search for Events with Two Displaced Vertices from Pair-Produced Neutral Long-Lived Particles Decaying to Hadronic Jets in the Muon Spectrometer of the ATLAS Detector with Full Run 2 Data](https://inspirehep.net/literature/2086276). The document exists on CDS at https://cds.cern.ch/record/2812260.
Congratulations Dr. Kvam! :rocket: 
```
* Add use citation from 'Search for Events with Two Displaced Vertices from
Pair-Produced Neutral Long-Lived Particles Decaying to Hadronic Jets in the
Muon Spectrometer of the ATLAS Detector with Full Run 2 Data'.
- c.f. https://inspirehep.net/literature/2086276
- c.f. https://cds.cern.ch/record/2812260
- Ph.D. dissertation of Audrey Kvam
```

docs: Add use citation from Audrey Kvam's Ph.D. thesis

---

docs/bib/use_citations.bib

Update the use citation information for the following papers published in journals in June 2022:
* [Revisiting mono-tau tails at the LHC](https://inspirehep.net/literature/1998227) (published in [European Physical Journal C](https://doi.org/10.1140/epjc/s10052-022-10504-9))
* [Search for neutral long-lived particles in pp collisions at 𝑠√ = 13 TeV that decay into displaced hadronic jets in the ATLAS calorimeter](https://inspirehep.net/literature/2043503) (Published in [Journal of High Energy Physics](https://doi.org/10.1007/JHEP06(2022)005))
```
* Update 'Revisiting mono-tau tails at the LHC' reference for publication in European
Physical Journal C.
- c.f. https://doi.org/10.1140/epjc/s10052-022-10504-9
* Update 'Search for neutral long-lived particles in pp …
```

docs: Update use citations published in journals in June 2022

---

.github/dependabot.yml

This would help keep actions up to date.
c.f. https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
```
* Add GitHub Dependabot config to check for GitHub Action version updates and
to open PRs if available. Set the check and update interval to weekly.
- c.f. https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
```

ci: Enable Dependabot version updates for GitHub Actions

---

.github/workflows/docker.yml

Combines PR #1901, #1902, #1904, #1905 into a single PR for clarity in the future as the Docker actions all work together.
* Closes #1901
* Closes #1902 
* Closes #1904 
* Closes #1905
```
* Apply Dependabot bumps for:
- docker/setup-qemu-action from 1 to 2.
- docker/login-action from 1 to 2.
- docker/setup-buildx-action from 1 to 2.
- docker/build-push-action from 2 to 3.
Signed-off-by: dependabot[bot] <support@github.com>
```

chore: Update Docker GitHub Actions to Dependabot bumped versions

---

setup.py

* Disallow Sphinx `v5.1.0` as it introduces an deque error that can be caused by `sphinx.ext.napoleon`:
```pytb
Extension error (sphinx.ext.napoleon):
Handler <function _process_docstring at 0x7f43e8361a20> for event 'autodoc-process-docstring' threw an exception (exception: pop from an empty deque)
```
- This was fixed rapidly in https://github.com/sphinx-doc/sphinx/pull/10709 and
so will not be a problem in Sphinx v5.1.1+. (Thanks again to the amazing Sphinx team for the super rapid work they do on patch releases!)
```
* Disallow Sphinx v5.1.0 as it introduces an deque error that can be
caused by sphinx.ext.napoleon:
> Extension error (sphinx.ext.napoleon):
> Handler <function _process_docstring at 0x7f43e8361a20> for event 'autodoc-process-docstring'
> threw an …
```

fix: Disallow Sphinx v5.1.0 to avoid 'exception: pop from an empty deque'

---

setup.py

* Update lower bound of `Sphinx` to `v5.1.1` to ensure consistent docs builds. This is simpler than disallowing particular problematic versions like `Sphinx` `v5.1.0` given that the documentation can be viewed as a deployment of an application and does not need to support as wide of a version range as possible.
* Amends PR #1925.
```
* Update lower bound of Sphinx to v5.1.1 to ensure consistent docs
builds. This is simpler than disallowing particular problematic versions
like Sphinx v5.1.0 given that the documentation can be viewed as a
deployment of an application and does not need to support as wide of a
version range as possible.
* Amends PR 1925.
```

docs: Update lower bound on Sphinx to v5.1.1

---

docs/bib/use_citations.bib

* Add use citation from [Signal region combination with full and simplified likelihoods in MadAnalysis 5](https://inspirehep.net/literature/2103971) by @Ga0l, @jackaraz, @BFuks, and @sabinekraml. :tada:
* Add use citation from [Search for a dark leptophilic scalar produced in association with τ+τ− pair in e+e− annihilation at center-of-mass energies near 10.58 GeV](https://inspirehep.net/literature/2115280) by the Belle Collaboration.
* Add use citation from [HighPT: A Tool for high-pT Drell-Yan Tails Beyond the Standard Model](https://inspirehep.net/literature/2121076) by Lukas Allwicher, Darius. A. Faroughy, Florentin Jaffredo, Olcyr Sumensari, and Felix Wilsch.
```
* Add use citation from 'Signal region combination with full and simplified likelihoods
in …
```

docs: Add July 2022 use citations

---

src/pyhf/readxml.py
tests/test_import.py
tests/test_import/xmlimport_noChannelData/config/HistFactorySchema.dtd
tests/test_import/xmlimport_noChannelData/config/example.xml
tests/test_import/xmlimport_noChannelData/config/example_channel.xml

Handle cases where channel is missing data in the XML configuration (associated with Asimov). c.f. Issue #1911
```
* Raise RuntimeError for cases where channel is missing data in the XML configuration
(associated with Asimov).
- c.f. Issue #1911
* Add tests and test XML files.
```

fix: Coverage for importing XML channels with no data

---

src/pyhf/readxml.py
tests/test_import.py
tests/test_import/xmlimport_missingPOI/config/HistFactorySchema.dtd
tests/test_import/xmlimport_missingPOI/config/example.xml
tests/test_import/xmlimport_missingPOI/config/example_channel.xml

See #1909.
Add runtime check for missing POI in XML measurements. XML measurements are not necessarily required to have a POI, but we require it, so need to fix coverage.
```
* Add runtime check for missing POI in XML measurements. XML measurements are not
necessarily required to have a POI, but we require it, so need to fix coverage.
* Add test and test XML files for missing POI in XML configs.
```

fix: Handle importing XML measurements with no POI attribute

---

.github/workflows/ci.yml

Remove check to only report coverage to Codecov for the oldest Python (Python 3.7) and newest (Python 3.10) tested
https://github.com/scikit-hep/pyhf/blob/97664bcfcef3b4a459a7f700b0703b40aec9b842/.github/workflows/ci.yml#L29
and instead report the coverage for all versions. The coverage flag for Codecov is `unittests-${{ matrix.python-version }}` and so the Codecov report will now show coverage for all versions and not just the 'bookend' versions.
https://github.com/scikit-hep/pyhf/blob/97664bcfcef3b4a459a7f700b0703b40aec9b842/.github/workflows/ci.yml#L64-L67
```
* Remove check to only report coverage to Codecov for the oldest Python
(Python 3.7) and newest (Python 3.10) tested and instead report
the coverage for all versions. The coverage flag for Codecov is …
```

ci: Report coverage for all Python versions

---

.pre-commit-config.yaml
pyproject.toml
setup.cfg
src/pyhf/cli/rootio.py
src/pyhf/readxml.py
src/pyhf/schema/validator.py
src/pyhf/typing.py
tests/test_import.py

This will need to be rebased again on top of `master` once #1909 is merged in.
```
* Add mypy to pre-commit.
* Add typehints to readxml.
* Enable typing for the pyhf package.
* Add nearly all other files to mypy.overrides.
```

feat: Enable typehints in pre-commit and add typehints to readxml

---

.coveragerc

As introduced in #1909, we had a drop in coverage due to the `TYPE_CHECKING` blocks. We'll ignore it to fix coverage as those blocks aren't meant to be seen during runtime.
```
* Add .coveragerc file with configuration to ignore TYPE_CHECKING.
- ref: https://coverage.readthedocs.io/en/6.4.3/excluding.html#advanced-exclusion
```

test: Ignore TYPE_CHECKING for coverage

---

setup.cfg
tests/constraints.txt

Add a lower bound of the supported `typing_extensions` version to `v3.7.4` as `TypedDict` was added in `v3.7.4`.
> The typing_extensions module contains both backports of these changes as well as experimental types that will eventually be added to the typing module, such as Protocol or TypedDict.
- c.f. https://pypi.org/project/typing-extensions/3.7.4/
Amends PR #1934.
Example:
```console
(venv) $ python -m pip --quiet install 'typing-extensions==3.7.2' && python -c 'from typing_extensions import Literal, TypedDict' && echo $?
Traceback (most recent call last):
File "<string>", line 1, in <module>
ImportError: cannot import name 'TypedDict' from 'typing_extensions' (/venv/lib/python3.7/site-packages/typing_extensions.py)
(venv) $ python -m pip --quiet install 'typing-extensions==3.7.4' && …
```

build: Set lower bound of typing-extensions to v3.7.4

---

.github/workflows/publish-package.yml

Add `PYTHONWARNINGS=error,default::DeprecationWarning` to the environment to cause Python to treat warnings as errors (but use default for `DeprecationWarning` as probably internal to build tools) during the package build to ensure that the build configuration conforms to the latest standards. Use the ['PYTHONWARNINGS' environment variable](https://docs.python.org/3/library/warnings.html#describing-warning-filters) as `build` runs in a new process and so something like `python -Werror -m build .` won't be able to pass the flags into the new process, but the shell environment will be picked up. c.f. https://github.com/pypa/build/issues/482
Thanks to @agoose77 for their help pointing out that `PYTHONWARNINGS` should be used. :+1: 
```
* Add …
```

ci: Make `build` error on warnings

---

.github/workflows/lint.yml
setup.py

* Remove the 'lint' extra. All linting should be done through pre-commit now and so there is no need to have a specific lint extra.
* Remove the flake8 and black components of the lint workflow, as these are redundant to pre-commit.ci.
```
* Remove the 'lint' extra. All linting should be done through pre-commit now
and so there is no need to have a specific lint extra.
* Remove the flake8 and black components of the lint workflow, as these are
redundant to pre-commit.ci.
```

chore: Remove 'lint' extra from setup.py

---

.coveragerc
src/pyhf/typing.py

Resolves #1941 
* Use [string literal types](https://mypy.readthedocs.io/en/stable/runtime_troubles.html#string-literal-types) of generic builtins for type checking until Python 3.8 support is dropped (so pyhf is Python 3.9+ only) to avoid having to check for `if typing.TYPE_CHECKING`.
- c.f. https://mypy.readthedocs.io/en/stable/runtime_troubles.html#string-literal-types
- c.f. https://mypy.readthedocs.io/en/stable/builtin_types.html#generic-types
- c.f. https://mypy.readthedocs.io/en/stable/runtime_troubles.html#generic-builtins
- c.f. https://peps.python.org/pep-0585/
* Remove `.coveragerc` as no longer needed.
- Reverts PR #1937
Thanks @henryiii for the nudge on this.
```
* Use string literal types of generic builtins for type checking until Python
3.8 support is …
```

refactor: Use string literal types of generic builtins for type checking

---

.git_archival.txt
.gitattributes
pyproject.toml

From the removed sections of https://github.com/scikit-hep/scikit-hep.github.io/pull/250/ I see that we should be updating the `.git_archival.txt` information to allow for Git archives (including the ones generated from GitHub) to also support versioning. c.f. https://github.com/pypa/setuptools_scm/tree/1b18371fc2fa672f39c758a103c4d12956b5964f#git-archives
In there it is additionally pointed out (in the removed section) that 
> If you are missing `setuptools_scm` or possibly the `toml` dependency on old versions of `setuptools_scm`, you will silently get version 0.0.0.
> ...
> This will only work with `setuptools_scm>=7`, which requires Python 3.7+ (though adding the files won't hurt older versions).
So additionally update `build-system` `requires` to have `setuptools_scm>=7.0.1` as …

build: Update git archival options to support auto versioning

---

.github/workflows/publish-package.yml

Use `twine check --strict` to fail on warnings.
```
* Use `twine check --strict` to fail on warnings.
```

ci: Use 'strict' option for twine check

---

src/pyhf/workspace.py
tests/test_workspace.py

The validation of a workspace specification against the schema currently takes place after some aspects of the workspace are already accessed in the constructor of `_ChannelSummaryMixin`. This can lead to unintuitive error messages, which should instead be caught by the schema validation. This PR re-orders the logic such that validation takes place first, ensuring that the relevant information is available for subsequent steps (assuming validation succeeds).
resolves #1952
```
* Validate the workspace specification in Model construction before any spec information
can be accessed in the constructor of _ChannelSummaryMixin.
* Add test that checks for an pyhf.exceptions.InvalidSpecification being raised, indicating
that the invalid model spec has been caught before a …
```

feat: Validate workspace specification before accessing parts of it

---

.github/workflows/docs.yml

Following the blog announcement [GitHub Pages: Custom GitHub Actions Workflows (beta)](https://github.blog/changelog/2022-07-27-github-pages-custom-github-actions-workflows-beta/), publish the GitHub Pages docs directly from the repository using GitHub Actions, without needing to set up a [publishing source](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site) like a branch.
This also restricts deployments to happening in specific environments (c.f. https://github.com/scikit-hep/pyhf/settings/environments).
```
* Use the GitHub Actions:
- actions/configure-pages@v2
- actions/upload-pages-artifact@v1
- actions/deploy-pages@v1
over the peaceiris/actions-gh-pages@v3 to deploy the GitHub Pages docs …
```

ci: Deploy GitHub Pages docs directly using GitHub Actions

---

setup.py
src/pyhf/schema/__init__.py
src/pyhf/schema/loader.py
tests/test_schema.py

Resolves #1916 by re-introducing the pre-population of the schema cache that had been done before the re-write of the schema utilities in #1753. Since  `defs.json` is in the cache under its id, `jsonschema.RefResolver` will not attempt to connect to `"https://scikit-hep.org"` to find it, which can crash code using pyhf in environments where the resource is not reachable.
I also tried to include a test to avoid future regression, but I am not happy with it. 
A better/more robust test would be a dedicated run in a sandboxed (i.e. no internet access / relevant ports blocked) environment, e.g. as part of the CI. But I have no clue how to set that up. 
```
* Load `defs.json` into `schema.variables.SCHEMA_CACHE` from the local file.
- in line with what was done before in …
```

fix: Populate the schema cache with local `defs.json` again

---

.coveragerc
.pre-commit-config.yaml
codecov.yml
pyproject.toml
src/pyhf/readxml.py
src/pyhf/tensor/numpy_backend.py
src/pyhf/typing.py

See #1284.
```
* Add typehints to the NumPy backend.
* Add .coveragerc file with configuration to ignore pyhf/typing.py.
- ref: https://coverage.readthedocs.io/en/6.4.3/excluding.html#advanced-exclusion
- Reverts part of PR #1942.
* Ignore pyhf/typing.py in Codecov.
```

feat: Add typehints to pyhf.tensor

---

setup.cfg
tests/constraints.txt

Resolves #1957 
* Update lower bound of the supported `click` versions to `v8.0.0` as it is required to support behavior in PR #1909. I'm not actually sure what changed, but from empirical testing something in [`v8.0.0`](https://click.palletsprojects.com/en/8.1.x/changes/#version-8-0-0) is needed. :?
**edit**: @kratsg has found in https://github.com/scikit-hep/pyhf/issues/1957#issuecomment-1228782947 that Click v7 has a bug and didn't set the path type correctly.
* Update 
https://github.com/scikit-hep/pyhf/blob/f01dcf59da10ec9313345305efc49cfb7186bf99/tests/constraints.txt#L3
to use `click==8.0.0`.
```
* Update lower bound of the supported click versions to v8.0.0 as it
is required to support behavior in PR #1909 due to click v7.x not
setting the type correctly for …
```

build: Update lower bound of click to v8.0.0

---

setup.cfg
tests/constraints.txt

Update lower bound of the supported typing-extensions versions to `v3.7.4.3` to ensure `SupportsIndex` is available, which is used as of PR #1940.
```
* Update lower bound of the supported typing-extensions versions to v3.7.4.3
to ensure SupportsIndex is available, which is used as of PR #1940.
- Amends PR #1940.
* Update tests/constraints.txt to use typing-extensions==3.7.4.3.
```

build: Update lower bound of typing-extensions to v3.7.4.3

---

setup.cfg
setup.py
tests/constraints.txt

* `tensorflow` `v2.6.5` restricts `numpy` to [`numpy~=1.19.2`](https://github.com/tensorflow/tensorflow/blob/6b54e9fa35d6261adae9565f18cde359003b551b/tensorflow/tools/pip_package/setup.py#L81) but `numpy.typing` was not added until `numpy` `v1.20.0`. For typing of the NumPy backend to work as added in PR #1940, `tensorflow` `v2.7.0+` is required, where `tensorflow` relaxes `numpy` constraints to [`numpy>=1.14.5`](https://github.com/tensorflow/tensorflow/blob/c256c071bb26e1e13b4666d1b3e229e110bc914a/tensorflow/tools/pip_package/setup.py#L81).
* `jaxlib` `v0.1.60` required [`numpy>=1.12,<1.20`](https://github.com/google/jax/blob/7495f71ea42db7b985427a12a1d366ed3cffda64/jaxlib/setup.py#L39) but `jaxlib` `v0.1.61` requires [`numpy>=1.16`](https://github.com/google/jax/blob/8c3371cae133e22c48eb …

build: Update lower bounds to tensorflow v2.7.0, jaxlib v0.1.61

---

.github/workflows/docs.yml

Split the docs workflow into a build and deploy jobs, where the deploy job requires the build job to succeed. This avoids unnecessary deployments by only having the github-pages environment exist in the deploy job.
```
* Split the docs workflow into a build and deploy jobs, where the deploy
job requires the build job to succeed. This avoids unnecessary deployments
by only having the github-pages environment exist in the deploy job.
* Constrain the deployment of environments to PR merges by requiring push
events on master to trigger the deploy job.
Co-authored-by: Giordon Stark <kratsg@gmail.com>
```

ci: Restrict deployments of environments to PR merges

---

docs/citations.rst

Following up on PR #1688, add note in the docs about links to the public-probability-models website that generates a nightly list of all public probability models.
- c.f. https://pyhf.github.io/public-probability-models
```
* Add note that links to the public-probability-models website that
generates a nightly list of all public probability models.
- c.f. https://pyhf.github.io/public-probability-models
```

docs: Add link to public-probability-models website

---

src/pyhf/modifiers/staterror.py
tests/test_modifiers.py
tests/test_modifiers/issue1720_greedy_staterror.json
tests/test_scripts.py

* Resolves #1720 
* Resolves #1945
This PR is supposed to fix the issue w/ staterrors which erroneously affected multiple samples. 
@alexander-held @matthewfeickert @kratsg 
```
* Fix staterror bug introduced after v0.6.3 where staterror erroneously affected
multiple samples.
- Amends PR #1639 which introduced regression.
- c.f. Issue #1720
* Remove staterror_combined.__staterror_uncrt as it is unused by the codebase.
* Add test to verify that staterror does not affect more samples than shapesys equivalently.
Co-authored-by: Giordon Stark <kratsg@gmail.com>
```

fix: Keep staterror from affecting multiple samples

---

.github/workflows/publish-package.yml

Resolves #1907.
```
* Run the publish package workflow on release events when a GitHub release is published.
```

ci: Publish to PyPI on publish of GitHub release

---

docs/conf.py
src/pyhf/tensor/numpy_backend.py

Resolves #1964.
Link to docs render: https://pyhf--1969.org.readthedocs.build/en/1969/_generated/pyhf.tensor.numpy_backend.numpy_backend.html#pyhf.tensor.numpy_backend.numpy_backend
```
* Use Sphinx autodoc typehint aliases to improve readability of documentation.
- c.f. https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_type_aliases
```

docs: Add typehint aliases

---

src/pyhf/schema/validator.py

`jsonschema` has traditionally been not the greatest with resolving references. More recent development has definitely aimed to improve this behavior (thanks to @Julian) and it seems it highlighted an issue with how we defined our `RefResolver`. This PR moves the `version` up to the `baseuri` instead of being part of the document name.
Resolves #1975.
```
* update baseuri to include the version of the HiFa JSON schema to provide forward-compatibility for jsonschema>=4.15.0
```

fix: Base URI for jsonschema.RefResolver has better behavior

---

.github/workflows/semantic-pr-check.yml

The Semantic PR Check is cancelling itself on other PRs because the concurrency is based on target branch only, rather than the PR number as well.
```
* Add PR number to Semantic PR Title Check concurrency to avoid unintended cancellation.
```

fix: Add PR number to Semantic PR Title Check concurrency group

---

docs/contributors.rst
src/pyhf/simplemodels.py

When doing experiments for differentiable models (#882), it's sometimes been easier to just skip validation with `simplemodels`, which I've been writing out specs for. This just reduces a bit of code overhead for me when I do that ;)
Made sure to highlight in the docstring that this should probably never be touched if one doesn't know why.
This is also partially because #1665 isn't fully done yet, which would probably make this redundant in some ways.
```
* Add `validate` kwarg to pyhf.simplemodels.uncorrelated_background and
pyhf.simplemodels.correlated_background API. This allows expert users to avoid
validating their models in specific circumstances.
* Add Nathan Simpson to contributors list.
```

feat: Promote `validate` kwarg to top-level functions in `pyhf.simplemodels`

---

docs/likelihood.rst

Resolves #1718.
```
* Clarify the schema data for histosys is absolute and not relative counts in the
Correlated Shape (histosys) documentation example for likelihood specification.
```

docs: Clarify absolute/relative for histosys

---

docs/api.rst
pyproject.toml
src/pyhf/mixins.py
src/pyhf/pdf.py
tests/test_workspace.py

* Resolves #1747
* Resolves #1982.
```
* Make _ChannelSummaryMixin parameter related attributes properties.
* Add documentation for parameter related properties of _ModelConfig by documenting
the _ChannelSummaryMixin.
* Add typehints to mixins.
* Update tests to mock the properties.
```

docs: Document Channel Summary Mixin

---

src/pyhf/pdf.py
tests/test_public_api.py

Resolves #1984 by allowing `_ModelConfig.set_poi(None)` to be allowed behavior to remove the POI from a model.
```
* Allow for `_ModelConfig.set_poi(None)` as a way to unset the POI from a model.
* Add test of `model.config.set_poi` for value of the poi that are valid strings and None.
```

feat: Add support for `_ModelConfig.set_poi(None)` to unset model POI

---

src/pyhf/modifiers/histosys.py
src/pyhf/modifiers/lumi.py
src/pyhf/modifiers/normfactor.py
src/pyhf/modifiers/normsys.py
src/pyhf/modifiers/shapefactor.py
src/pyhf/modifiers/shapesys.py
src/pyhf/modifiers/staterror.py
src/pyhf/pdf.py
tests/test_custom_mods.py
tests/test_pdf.py

* Resolves #1908
* Resolves #1967 
* Resolves #1973
* Amends PR #1625
```
* Add checks to determine if modifiers should be shared across channels when
the modifier is being built. This guards against accidental correlations across
channels. e.g. shared shapesys paramsets.
- Amends PR #1625
* Add tests for raised pyhf.exceptions.InvalidModel in the event that a shared shapesys
paramset is introduced in the model spec.
```

fix: Add guards against shared shapesys paramsets

---

pyproject.toml
src/pyhf/events.py
src/pyhf/tensor/manager.py
src/pyhf/tensor/numpy_backend.py
src/pyhf/typing.py

See #1284.
This PR adds typing for `src/pyhf/tensor/manager.py` (and also adds some typing for the `src/pyhf/events.py` to make sure the decorators used are [forwarding their signatures](https://mypy.readthedocs.io/en/stable/generics.html#declaring-decorators)).
Additionally provides some minor fix on top of #1940 to get the NumPy backend more properly typed according to the expanded (stricter) `TensorBackend` `Protocol`.
```
* Add type hints to the tensor manager.
* Add type hints to some of the events management code for the decorators used.
* Expand the TensorBackend protocol and fix up the NumPy backend type hints to align properly.
- Amends PR #1940.
```

feat: Add type hints for tensor manager

---

src/pyhf/infer/calculators.py
src/pyhf/infer/test_statistics.py
tests/test_infer.py

* Resolves #1992
* Resolves #529
* Resolves #1994
```
* Guard against nan from division by zero in pyhf.infer.calculators.AsymptoticCalculator.teststatistic.
* Add use of 'less than or equal to' to docs for tests stats to match equations 14
and 16 of https://arxiv.org/abs/1007.1727.
* Add tests to ensure that nan conditions in Issue #529 and Issue #1992 are not possible.
```

fix: Guard against nan in test stat calculation

---

.github/workflows/release_tests.yml
codemeta.json

Resolves #1990 by choosing to pin to `v0.3.5` until a viable solution to https://github.com/proycon/codemetapy/issues/24 is found.
```
* Pin codemetapy to v0.3.5 in the 'current release' test workflow to keep the
`--no-extras` CLI API option.
- c.f. https://github.com/proycon/codemetapy/issues/24
* Update lower bounds for scipy and click in codemeta.json and add lower bounds
for importlib-resources and typing-extensions.
```

fix: Pin codemetapy to v0.3.5 for `--no-extras` functionality

---

.github/workflows/release_tests.yml

Use release candidates that are on PyPI for verifiying that the public API passes tests. This verifies that the release candidates that users are being asked to test reflect the release API.
```
* Use release candidates that are on PyPI for verifiying that the public API
passes tests. This verifies that the release candidates that users are being
asked to test reflect the release API.
* Use the latest version of pytest.
```

ci: Install release candidates for 'current release' test workflow

---

src/pyhf/contrib/utils.py

Use [`urllib.parse.urlsplit`](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlsplit) over [`urllib.parse.urlparse`](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlparse) to avoid having to deal with `urlparse`'s `params` argument which incurs a performance cost.
This isn't strictly needed, but it came up in the "Anthony Explains" video [python: don't use urlparse! (beginner - intermediate) anthony explains 474](https://youtu.be/ABJvdsIANds).
```
* Use urllib.parse.urlsplit over urllib.parse.urlparse to avoid having to deal with
urlparse's 'params' argument which incurs a performance cost.
- c.f. https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlsplit
- c.f. https://youtu.be/ABJvdsIANds
```

refactor: Use urllib.parse.urlsplit over urlparse

---

codemeta.json

Resolves #1999
* jsonschema lower bound is v4.15.0
* importlib-resources lower bound is v1.4.0
Amends PR #1979.
```
* Update jsonschema lower bound to v4.15.0 and importlib-resources lower bound to v1.4.0
to match their versions in setup.cfg.
- Amends PR #1979
```

fix: Update codemeta lower bounds for jsonschema, importlib-resources

---

README.rst

Add milestone to README for 2000 project GitHub issues and pull requests.
For time context, PR #1000 came back in 2020-07-28. :slightly_smiling_face: 
```
* Add milestone to README for 2000 project GitHub issues and pull requests.
```

docs: Add milestone for 2000 project GitHub items

---

.github/workflows/release_tests.yml
codemeta.json

Following the release of [`codemetapy` `v2.2.1`](https://github.com/proycon/codemetapy/releases/tag/v2.2.1) which resolved https://github.com/proycon/codemetapy/issues/24, `codemetapy` `v2.2.2+` releases have the `--no-extras` CLI API option restored. Release `v2.2.2` then made it possible for reproducible runs (c.f. https://github.com/proycon/codemetapy/issues/26). Update the current release check workflow to use this new API.
Amends PR #1995
Many thanks @proycon for being so responsive and helpful on `codemetapy`!
```
* Update codemetapy to v2.2.2+ in 'current release' workflow to have access to
the `--no-extras` CLI API in v2.0+ and reproducible runs.
- c.f. https://github.com/proycon/codemetapy/issues/24
- c.f. https://github.com/proycon/codemetapy/issues/26
- …
```

fix: Use codemetapy v2.2.2+ API

---

pyproject.toml

Add a ignore to filterwarnings to avoid a protobuf DeprecationWarning
> DeprecationWarning: Call to deprecated create function FileDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
from TensorFlow's use of protobuf.
```
* Add a ignore to filterwarnings to avoid a protobuf DeprecationWarning
> DeprecationWarning: Call to deprecated create function FileDescriptor().
> Note: Create unlinked descriptors is going to go away. Please use get/find
> descriptors from generated code or query the descriptor_pool.
from TensorFlow's use of protobuf.
```

fix: Add filterwarnings ignore for protobuf DeprecationWarning

---

docs/faq.rst

Resolves #1513
Add FAQ explaining how reasons why users might have to manually downgrade dependencies.
```
* Add FAQ explaining how reasons why users might have to manually downgrade dependencies.
- c.f. PR #1979 for context
```

docs: Add FAQ on reasons for need to downgrade dependencies

---

tests/test_infer.py

Needed for PR #1274 
* Use the 'function' scope for hypotest_args fixture. Fixing the POI in the model config changes it for the entire fixture if the fixture is 'module' scope, which would cause errors in other tests that later use it and defeats the point of the fixture.
* Remove unnecessary use of tmpdir fixture as no output is written.
```
* Use the 'function' scope for hypotest_args fixture. Fixing the POI in the model config
changes it for the entire fixture if the fixture is 'module' scope, which would cause
errors in other tests that later use it and defeats the point of the fixture.
* Remove unnecessary use of tmpdir fixture as no output is written.
```

fix: Use function scope to avoid altering hypotest_args fixture

---

MANIFEST.in
src/conftest.py

* Resolves #2015
* Needed for PR #1274
Symlink the `tests/conftest.py` under the `src` tree to allow for the autouse pytest fixtures to be discovered and used during doctest. This is needed as the backends are not currently being automatically reset between doctests and the fixtures will not be discovered during doctest runs invoked with `pytest src/` as noted in the [pytest docs](https://docs.pytest.org/en/7.1.x/how-to/doctest.html#doctest-namespace-fixture):
> Note that like the normal `conftest.py`, the fixtures are discovered in the directory tree conftest is in. Meaning that if you put your doctest with your source code, the relevant `conftest.py` needs to be in the same directory tree. Fixtures will not be discovered in a sibling directory tree!
- c.f. …

test: Discover pytest fixtures during doctest

---

.github/dependabot.yml

Ignore all dependencies that are under the domain of pip in Dependabot's package ecosystems to avoid automatic security PRs that target `tests/constraints.txt`, which must remain static for lower bound constraints testing. This is designed to keep things like PR #2008 from ever happening.
```
* Ignore all dependencies that are under the domain of pip in Dependabot's package
ecosystems to avoid automatic security PRs that target tests/constraints.txt,
which must remain static for lower bound constraints testing.
* Add default labels and reviewers to be applied to PRs from GHA updates from Dependabot.
```

ci: Ignore Dependabot PRs to update tests/constraints.txt 

---

docs/generate_jupyterlite_iframe.py
docs/jupyterlite.rst

Given the async nature of the Pyodide kernel https://github.com/scikit-hep/pyhf/issues/1775#issuecomment-1079128954 `requests` isn't something we can usefully use for `pyhf.contrib.utils.download` in Pyodide examples. Given this, to simplify things as much as possible remove the install of `requests` from the setup of the JupyterLite REPL for the docs.
```
* To simplify things, remove the piplite install of requests from the JupyterLite REPL setup.
- Given the async nature of Pyodide, requests isn't currently useful for examples using
pyhf.contrib.utils.download. c.f. Issue #1775 for context.
```

docs: Remove requests install from JupyterLite REPL setup

---

docs/bib/HEPData_likelihoods.bib

Update the list of the published statistical models to include those from 2022 and those from previously published analyses that ATLAS has made public. Following https://pyhf.github.io/public-probability-models
```
* Update the list of published statistical models to include new ones analyses in 2022
and previous analyses that have had their models made public. Information is gathered
from https://github.com/pyhf/public-probability-models which queries
https://twiki.cern.ch/twiki/bin/view/AtlasPublic.
* Reorder the list by analysis publication date as given by ATLAS.
```

docs: Update list of statistical models for 2022

---

.github/ISSUE_TEMPLATE/~release-checklist.md

* Note that Conda-forge has a conda-grayskull bot that can help users update build requirements.
- c.f. https://twitter.com/mdtrevisani/status/1487894867799859201
* Add that it is the dev team's responsibility to ask the CERN LCG view team to put the new release of pyhf in the next LCG release.
```
* Note that Conda-forge has a conda-grayskull bot that can help users update
build requirements.
- c.f. https://twitter.com/mdtrevisani/status/1487894867799859201
* Add that it is the dev team's responsibility to ask the CERN LCG view team
to put the new release of pyhf in the next LCG release.
```

docs: Update release checklist notes for Conda-forge and LCG views

---

docs/bib/general_citations.bib
docs/bib/use_citations.bib

Update the use and general citations to reflect publications of preprints in journals.
- ATLAS publication ['Search for events with a pair of displaced vertices from long-lived neutral particles decaying into hadronic jets in the ATLAS muon spectrometer in pp collisions at \sqrt s =13  TeV'](https://inspirehep.net/literature/2040545) is published as Phys.Rev.D 106 (2022) 3, 032005. https://doi.org/10.1103/PhysRevD.106.032005
- ['Publishing statistical models'](https://inspirehep.net/literature/1919763) is published as SciPost Phys. 12 (2022) 1, 037. https://doi.org/10.21468/SciPostPhys.12.1.037
- ['Reinterpreting the ATLAS bounds on heavy neutral leptons in a realistic neutrino oscillation model'](https://inspirehep.net/literature/1893584) is published as JHEP 12 (2021) 182. …

docs: Update use citations and general citations to latest distribution

---

src/pyhf/optimize/mixins.py
src/pyhf/pdf.py
tests/test_optim.py
tests/test_pdf.py
tests/test_simplemodels.py

Resolves #1700
Make `pyhf.pdf._ModelConfig.par_names()` a property attribute to match the `pyhf.pdf._ModelConfig.par_order` API.
```
* Make pyhf.pdf._ModelConfig.par_names() property attribute pyhf.pdf._ModelConfig.par_names,
like the the pyhf.pdf._ModelConfig.par_order API.
* Update all usage of `.par_names()` to `par_names`.
* Use unittest.mock.PropertyMock to properly mock par_names return.
```

feat: Make `par_names` a _ModelConfig property attribute

---

docs/conf.py
docs/contributors.rst
docs/release-notes.rst
docs/release-notes/v0.7.0.rst
src/pyhf/cli/rootio.py

Add release notes for pyhf v0.7.0.
Relevant RTD build: https://pyhf--1705.org.readthedocs.build/en/1705/release-notes.html#release-v0-7-0
```
* Add release notes for pyhf v0.7.0.
* Add Graeme Watt to contributors list.
```

docs: Add v0.7.0 release notes

---

.readthedocs.yaml
docs/conf.py

Resolves #2029 
* Add 'https://pyhf.readthedocs.io/en/.*' to the linkcheck ignore as tags for a release won't exist until it is made, but ReadTheDocs needs to reference them.
* Remove linkcheck from ReadTheDocs config.
```
* Add 'https://pyhf.readthedocs.io/en/.*' to the linkcheck ignore as tags
for a release won't exist until it is made, but ReadTheDocs needs to reference them.
* Remove linkcheck from ReadTheDocs config.
```

fix: Skip ReadTheDocs verions during Sphinx link check

---

tests/test_backends.py

Resolves #2033
This only affects the tests as `jax.errors.TracerArrayConversionError` works in the JAX `v0.2.10` API, so nothing needs to be altered elsewhere.
```
* Use jax.errors API over jax._src.errors as jax._src is removed from the
jax public namespace in jax v0.3.18.
- c.f. https://github.com/google/jax/releases/tag/jax-v0.3.18
```

fix: Use `jax.errors` API as `jax._src` removed from public namespace

---

src/pyhf/cli/spec.py
src/pyhf/infer/intervals/upper_limits.py
src/pyhf/modifiers/staterror.py
src/pyhf/optimize/mixins.py
src/pyhf/optimize/opt_minuit.py
src/pyhf/optimize/opt_scipy.py
src/pyhf/parameters/utils.py
src/pyhf/pdf.py
src/pyhf/tensor/jax_backend.py
src/pyhf/tensor/numpy_backend.py
src/pyhf/tensor/pytorch_backend.py
src/pyhf/tensor/tensorflow_backend.py
src/pyhf/workspace.py
tests/test_import.py
tests/test_mixins.py
tests/test_scripts.py

Based [on this Tweet by Tim Head](https://twitter.com/betatim/status/1575020386411896832?s=20&t=WvZIENWyUdA7E_9q4AiDvg)
> In Python, is `some_key in d.keys()` as fast as `some_key in d`? Why wouldn't it be?
>
> TIL that the former takes about twice as long as the latter. (On Python 3.10)
Remove calls to `some_dict.keys()` when `some_dict` would work instead.
The remaining instances
```console
$ git grep ".keys()"     
src/pyhf/schema/loader.py:        >>> schema.keys()
tests/test_export.py:    assert sorted(modifier.keys()) == ['High', 'Low', 'Name', 'Val']
```
are needed.
```
* Remove calls of `.keys()` when just using the dict by itself would work as
.keys() incurrs extra overhead that makes it about twice as slow as using
the dict.
- c.f. …
```

perf: Remove instances of `.keys()` that are not needed

---

setup.cfg

Add numpy explicitly as a dependency of pyhf. As the lower bound (and upper bound) of numpy is tightly controlled by scipy a lower bound is not given to avoid potential future confusion for pip's dependency resolver. Explicitly adding numpy as a dependency improves the metadata for packaging. e.g. `pip show` will now list numpy under the 'Requires' output.
Note that no more information is contained with this addition, but it provides additional context to metadata inspection.
**Before**
```console
$ python -m pip show pyhf             
Name: pyhf
Version: 0.7.1.dev5
Summary: pure-Python HistFactory implementation with tensors and autodiff
Home-page: https://github.com/scikit-hep/pyhf
Author: Lukas Heinrich, Matthew Feickert, Giordon Stark
Author-email: lukas.heinrich@cern.ch, …
```

build: Add numpy as a dependency explicitly

---

.github/workflows/ci.yml
.github/workflows/lower-bound-requirements.yml
.github/workflows/release_tests.yml
.pre-commit-config.yaml
codemeta.json
pyproject.toml
setup.cfg
src/pyhf/contrib/utils.py
src/pyhf/typing.py
tests/constraints.txt
tests/test_optim.py

Following Discussion #2042, drop Python 3.7 support to follow NEP 29 development recommendations. As a result, drop the requirement of `typing_extensions` as that is needed for Python 3.7 only and update the lower bound on SciPy to v1.3.2 &mdash; the first release with Python 3.8 wheels.
```
* Drop Python 3.7 support to follow NEP 29 development recommendations.
- c.f. https://github.com/scikit-hep/pyhf/discussions/2042
* Drop typing_extensions as a requirement as that is needed by Python 3.7 only.
* Update lower bound of the supported scipy versions to v1.3.2, the first scipy release
with Python 3.8 wheels.
* Update pre-commit hooks to use Python 3.8.
```

feat: Drop Python 3.7 support

---

.github/workflows/release_tests.yml
codemeta.json
setup.py

* Add `numpy` metadata information to `codemeta.json`.
- Amends PR #2041
* Update lower bound on `scipy` to `v1.3.2` and remove `typing-extensions`.
- Amends PR #2044
* Update `codemetapy` lower bound to `v2.3.0` to ensure consistency of output
```
* Add numpy metadata information to codemeta.json.
- Amends PR #2041
* Update lower bound on scipy to v1.3.2 and remove typing-extensions.
- Amends PR #2044
* Update codemetapy lower bound to v2.3.0 to ensure consistency of output.
```

chore: Update codemeta.json for numpy, scipy, and typing-extensions

---

.coveragerc
.github/workflows/ci.yml
.github/workflows/dependencies-head.yml
.github/workflows/lower-bound-requirements.yml
.github/workflows/release_tests.yml
docs/development.rst
noxfile.py
pyproject.toml
setup.py

Following Anthony Sottile's video [I don't use pytest-cov (intermediate) anthony explains 489](https://youtu.be/sPgvHGkmd0U), this PR drops `pytest-cov` in favor of just managing coverage ourselves with `coverage[toml]`. This implements running the tests with coverage as and **optional** part of the `tests` `nox` session (enabled with adding `coverage` as a positional argument) and adds generating the coverage report as a separate step with `nox -s coverage`:
* Simplifies the reporting of pytest runs to show the information that is most relevant.
* Speeds up running the pytest tests as coverage takes additional time to properly check all branches. For the full test suite the result is a speed up of about a minute.
`pytest` with `coverage`: `03:54`
```console
$ nox -s tests-3.10 -- …
```

test: Use coverage over pytest-cov

---

.github/workflows/dependencies-head.yml

* Update HEAD of dependencies workflow to use uproot5 URL. This is a purely cosmetic change as the uproot4 URL will resolve to the uproot5 URL.
- c.f. https://github.com/scikit-hep/uproot5
Migrated from PR #2054.
```
* Update HEAD of dependencies workflow to use uproot5 URL. This is a purely cosmetic change
as the uproot4 URL will resolve to the uproot5 URL.
- c.f. https://github.com/scikit-hep/uproot5
```

chore: Update uproot URL to uproot5

---

.github/workflows/docker.yml

Add the `platforms` argument to the `docker/build-push-action` GitHub Action and pass the platform names to enable build for both amd64 and arm64 architectures. This will enable Apple M1 and M2 machines to run the `pyhf/pyhf` Docker images without emulation which will significantly improve runtime performance.
While this hasn't been run through the CI, this has been tested locally with
```console
$ docker buildx build --file docker/Dockerfile --platform linux/arm64 --tag pyhf/pyhf:debug-arm64 --load .
$ docker image inspect pyhf/pyhf:debug-arm64 | jq '.[] | with_entries(select(.key == "Architecture"))'
{
"Architecture": "arm64"
}
```
```
* Add the 'platforms' argument to the docker/build-push-action GitHub
Action and pass the platform names to enable build for both …
```

ci: Enable multiplatform builds for amd64 and arm64

---

docs/bib/use_citations.bib

Add use citation from [Search for a dark leptophilic scalar produced in association with taupair in electron-positron annihilation at center-of-mass energies near 10.58 GeV](https://inspirehep.net/literature/2178671), which is the Ph.D. dissertation of @diptaparna. Congratulations Dr. Biswas! :tada: 
```
* Add use citation from 'Search for a dark leptophilic scalar produced in
association with taupair in electron-positron annihilation at center-of-mass
energies near 10.58 GeV'.
- c.f. https://inspirehep.net/literature/2178671
- Ph.D. dissertation of Diptaparna Biswas
```

docs: Add use citation from Diptaparna Biswas's Ph.D. thesis (#2040)

---

docs/bib/use_citations.bib

Add use citation from [The IRIS-HEP Analysis Grand Challenge](https://inspirehep.net/literature/2598292) (by @alexander-held and @oshadura) and [pyhf: a pure-Python statistical fitting library with tensors and automatic differentiation](https://inspirehep.net/literature/2598491) (by the pyhf dev team) which both appear in the ICHEP 2022 proceedings.
```
* Add use citation from 'The IRIS-HEP Analysis Grand Challenge' and
'pyhf: a pure-Python statistical fitting library with tensors and
automatic differentiation' which both appear in the ICHEP 2022
proceedings.
- https://inspirehep.net/literature/2598292
- https://inspirehep.net/literature/2598491
```

docs: Add use citations from ICHEP 2022 proceedings

---

setup.py

Resolves #2067 
Disallow `ipython` `v8.7.0` to avoid Pygments warning
```pytb
WARNING: Pygments lexer name 'ipython3' is not known
```
which arises during the docs build. This is a stopgap measure and this line should be removed as soon as there is a resolution and new `ipython` release.
c.f. https://github.com/ipython/ipython/issues/13845
```
* Disallow ipython v8.7.0 to avoid Pygments warning
> WARNING: Pygments lexer name 'ipython3' is not known
which arises during the docs build. This is a stopgap measure and this
line should be removed as soon as there is a resolution and new ipython
release.
- c.f. https://github.com/ipython/ipython/issues/13845
```

fix: Disallow ipython v8.7.0 to avoid Pygments lexer warning

---

.github/workflows/dependencies-head.yml

List the release candidates, alpha releases, and beta releases that are installed as part of testing against dependencies with the '--pre' pip flag to help make it easier to visually identify them in the CI logs
This comes up when the release candidate workflows fail and we want to try to identify what might be coming down the line easier.
```
* List the release candidates, alpha releases, and beta releases that are
installed as part of testing against dependencies with the '--pre' pip flag
to help make it easier to visually identify them in the CI logs.
```

chore: List release candidates, alpha, and beta releases

---

pyproject.toml

Add a ignore to filterwarnings to avoid a numpy DeprecationWarning
> DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
from TensorFlow's use of numpy. This DeprecationWarning first appeared in numpy v1.24.0rc1, and so this ignore is being added in advance of v1.24.0 as a preventative measure for HEAD of dependencies testing.
```
* Add a ignore to filterwarnings to avoid a numpy DeprecationWarning
> DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
from TensorFlow's use of numpy. This DeprecationWarning first appeared in
numpy v1.24.0rc1, and so this ignore is being added in advance of
v1.24.0 as a preventative measure for HEAD of dependencies testing.
```

fix: Add filterwarnings ignore for np.bool8 DeprecationWarning

---

setup.cfg
setup.py
src/pyhf/tensor/jax_backend.py
tests/constraints.txt

Resolves #2078 
* Update JAX backend `array_type` and `array_subtype` to `jax.Array`, which is a unified array type introduced in jax v0.4.1 that subsumes `DeviceArray`, `ShardedDeviceArray`, and `GlobalDeviceArray` types in JAX.
- c.f. https://github.com/google/jax/releases/tag/jax-v0.4.1
* Update the lower bound of jax and jaxlib to v0.4.1 to ensure support for jax.Array.
* Update lower bound of the supported scipy versions to v1.5.0 as required by jax v0.4.1.
* Update the JAX backend docstring examples to use Array as the array type.
```
* Update JAX backend array_type and array_subtype to jax.Array, which is a unified
array type introduced in jax v0.4.1 that subsumes DeviceArray, ShardedDeviceArray,
and GlobalDeviceArray types in JAX.
- c.f. …
```

feat: Update JAX backend array_type and array_subtype to jax.Array

---

setup.cfg
tests/constraints.txt

Following PR #2079 there were _some_ (but not all!) runs of the minimum supported dependencies workflow that failed with `scipy` `v1.5.0`. However, all runs passed with `v1.5.1` so as this is just a patch release bump (from a release in 2020) this should be an uncontroversial fix.
Amends PR #2079.
```
* Update lower bounds of scipy to v1.5.1 to ensure that the minimum supported dependencies
workflow passes, as it failed nondeterministically for v1.5.0.
* Amends PR #2079.
```

build: Update lower bounds of scipy to v1.5.1

---

docs/bib/use_citations.bib

Add use citation from [Search for an invisible Z' in a final state with two muons and missing energy at Belle II](https://inspirehep.net/literature/2611344). :rocket: 
```
* Add use citation from 'Search for an invisible Z' in a final state with
two muons and missing energy at Belle II'.
- c.f. https://inspirehep.net/literature/2611344
```

docs: Add use citation from Belle II invisible Z' search

---

tests/test_validation.py

Loosen the relative tolerance from ~1e-9 to ~1e-6 to have comparisons with NumPy v1.24.0+ work. A relative tolerance of ~1e-6 is still fine and so this shouldn't be considered a regression.
```
* Loosen the relative tolerance from ~1e-9 to ~1e-6 to have comparisons with
NumPy v1.24.0+ work. A relative tolerance of ~1e-6 is still fine and so this
shouldn't be considered a regression.
```

test: Loosen tolerance for test_validation[1bin_normsys_mu1]

---

noxfile.py
tests/constraints.txt

Set lower bound on numpy to v1.21.0 as this is the lower bound required by JAX v0.4.1 in addition to the lower bound of numpy>=1.14.5 by scipy v1.5.1 (the current lowest supported version). Newer versions of scipy place an upper bound on numpy for compatibility reasons and so this is only required for older scipy releases.
Example: `scipy` `v1.9.3` requires `numpy<1.26.0,>=1.18.5`.
This needs to be bumped again for JAX 
```
jax 0.4.1 depends on numpy>=1.20
The user requested (constraint) numpy==1.14.5
```
Need `numpy` `v1.21.0` for
```python
from numpy.typing import ArrayLike, DTypeLike, NBitBase, NDArray
```
to not give
```pytb
ImportError: cannot import name 'NDArray' from 'numpy.typing'
```
```
Set lower bound on numpy to v1.21.0 as this is the lower bound …
```

test: Add lower bound on supported numpy versions

---

.pre-commit-config.yaml
src/pyhf/tensor/numpy_backend.py

As prompted by pre-commit.ci, remove the `--enable-recursive-aliases` `mypy` option to avoid
> Warning: --enable-recursive-aliases is deprecated; recursive types are enabled by default
and remove `type: ignore[no-any-return]` to avoid
> error: Unused "type: ignore" comment
```
* Remove the `--enable-recursive-aliases` mypy option in pre-commit to avoid
> Warning: --enable-recursive-aliases is deprecated; recursive types are enabled by default
and remove `type: ignore[no-any-return]` to avoid
> error: Unused "type: ignore" comment
These changes are prompted from pre-commit.ci runs.
```

chore: Remove 'enable-recursive-aliases' from mypy checks

---

docs/bib/general_citations.bib

Add general citation from [Application of deep learning techniques in CMS: from matrix element regression to the search for Higgs boson pair production](https://inspirehep.net/literature/2621189), which is @FlorianBury's Ph.D. dissertation. Congratulations Dr. Bury! :rocket:
```
* Add general citation from 'Application of deep learning techniques in
CMS: from matrix element regression to the search for Higgs boson pair
production'.
- c.f. https://inspirehep.net/literature/2621189
- Ph.D. dissertation of Florian Bury
```

docs: Add general citation from Florian Bury's Ph.D. thesis

---

.github/workflows/notebooks.yml
docs/examples/notebooks/learn/InterpolationCodes.ipynb
tests/test_notebooks.py

* To avoid having the notebook tests hang on the `ipywidgets` `interact` sections of `InterpolationCodes.ipynb` set the matplotlib backend to the non-gui Agg which disallows the creation of the gui elements that are causing the problem. This also speeds up runtime as no gui-elements are created for the notebook tests now.
* Remove '%pylab inline' from InterpolationCodes.ipynb as pylab is very deprecated.
* Add --verobse flag to notebook tests to make it easier to track the progress of the notebooks in the CI logs.
```
* Avoid the notebook tests hanging on the ipywidgets interact sections of `InterpolationCodes.ipynb`
by setting the matplotlib backend to the non-gui Agg which disallows the creation of the gui elements
that are causing the problem.
* Remove '%pylab …
```

fix: Use non-gui matplotlib backend for tests to avoid hanging on ipywidgets interact

---

pyproject.toml

Add https://github.com/scikit-hep/pyhf/releases to 'Project links' section on PyPI webpage.
Inspired by [Awkward's use](https://github.com/scikit-hep/awkward/blob/e81128ad63ad5fbf4c8943ec6abacc7ddea9ec08/pyproject.toml#L62), which was added in https://github.com/scikit-hep/awkward/commit/0a80b2a09f8ae81264d1fa214c4b3c7df7fef88c.
```
* Add https://github.com/scikit-hep/pyhf/releases to 'Project links' section
on PyPI webpage.
```

docs: Add GitHub Releases page to project url metadata

---

docs/bib/general_citations.bib

Add general citation from '[ATLAS HL-LHC Computing Conceptual Design Report](https://inspirehep.net/literature/1845103)' (2020).
> The paradigm of Deep Learning is evolving into a more general notion of numeric programs that are end-to-end optimizable through the use of auto-differentiation techniques. Here, projects such as pyhf[49] use ML libraries not for standard neural network training but rather to compute traditional HEP targets such as profile likelihoods leading to significantly higher performances for (e.g.) maximum likelihood fitting or limit calculation. Such differentiable analysis modules will also allow more direct integration of systematic uncertainties into the ML training, leading to more robust classifiers that are well-aligned with the final science objective.
For the …

docs: Add general citation from ATLAS HL-LHC Computing CDR

---

.github/workflows/notebooks.yml

As a temporary fix to Issue #2104 (which is because of https://github.com/nteract/papermill/issues/711), downgrade `jupyter-client` to a version less than `v8.0.0` so that `papermill` is able to run. This is not a sufficient fix and an alternative to using `papermill` should be considered.
```
* As a temporary fix to Issue #2104, downgrade jupyter-client to a
version less than v8.0.0 so that papermill is able to run.
This is not a sufficient fix and an alternative to using papermill
should be considered.
```

fix: Downgrade jupyter-client for papermill to work

---

docs/installation.rst
src/pyhf/cli/complete.py
src/pyhf/cli/rootio.py
src/pyhf/contrib/cli.py
src/pyhf/contrib/utils.py
tests/test_scripts.py

Resolves #2114
* Use `req@url` syntax when using `pip` to install from a remote Git repository over `url#egg=req` to avoid the use of `#egg=` fragments with a non-PEP 508 name. This will be required in `pip` `v25.0+`. c.f. https://github.com/pypa/pip/pull/11617 for more details. This avoids `pip` throwing the following warning:
> DEPRECATION: git+https://github.com/scikit-hep/pyhf.git#egg=pyhf[all] contains an egg fragment with a non-PEP 508 name pip 25.0 will enforce this behaviour change. A possible replacement is to use the req @ url syntax, and remove the egg fragment. Discussion can be found at pypa/pip#11617
* For best practice, quote the use of extras for compatibility across all shells.
```
* Use 'req@url' syntax when using pip to install from a remote git …
```

docs: Use 'req@url' syntax to install from remote VCS

---

CONTRIBUTING.md
binder/postBuild
docs/development.rst

Resolves #2110
* Update all uses of the removed 'complete' extra to 'develop'.
- The 'complete' extra was removed when moving to `hatchling` in PR #2095, but the 'develop' extra retains most of that functionality.
- Update the 'complete' extra to 'all' for the Binder postBuild to reduce the number of dependencies that need to be installed.
* Quote the extra for best practice to ensure compatibility across shells.
```
* Update all uses of the removed 'complete' extra to 'develop'.
- The 'complete' extra was removed when moving to hatchling in
PR #2095, but the 'develop' extra retains most of that functionality.
- Update the 'complete' extra to 'all' for the Binder postBuild to
reduce the number of dependencies that need to be installed.
* Quote the extra for best …
```

docs: Use 'develop' extra over removed 'complete'

---

README.rst

https://prefix.dev provides a significantly nicer and faster browsing experience of packages on conda-forge with a UI that is more user focused. prefix.dev comes from the mamba-org team and so has backing support.
- c.f. https://prefix.dev/channels/conda-forge/packages/pyhf
Big thanks to @agoose77 for sharing https://prefix.dev/ with us!
```
* https://prefix.dev/ provides a significantly nicer and faster browsing
experience of packages on conda-forge with a UI that is more user
focused. prefix.dev comes from the mamba-org team and so has backing support.
- c.f. https://prefix.dev/channels/conda-forge/packages/pyhf
```

docs: Use prefix.dev as conda-forge package page

---

tests/constraints.txt

Constrain `protobuf` to be less than `4.21.0` for `tensorflow` to work in the minimum supported dependencies workflow test. For the version of `tensorflow` used, `protobuf` `v4.21.0+` results in a `protobuf` error of
```pytb
/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/google/protobuf/descriptor.py:560: in __new__
_message.Message._CheckCalledFromGeneratedFile()
E   TypeError: Descriptors cannot not be created directly.
E   If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
E   If you cannot immediately regenerate your protos, some other possible workarounds are:
E    1. Downgrade the protobuf package to 3.20.x or lower.
E    2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use …
```

test: Add constraint to protobuf for lower bound tests

---

pyproject.toml

Add PyPI trove classifiers to the PyPI metadata for `Environment :: WebAssembly :: Emscripten` as pyhf can run on a WASM build of CPython.
- c.f. https://discuss.python.org/t/do-we-want-classifiers-for-webassembly-on-pypi/22712
Thanks to @treyhunner for [sharing this on Twitter](https://twitter.com/treyhunner/status/1616937929276022784?s=43&t=ExhFr34n5b725DwOITxJ6g) and to @brettcannon for adding them in https://github.com/pypa/trove-classifiers/pull/129. :+1: 
```
* Add the PyPI Environment :: WebAssembly :: Emscripten trove classifier
to the PyPI metadata as pyhf can run on a WASM build of CPython.
- c.f. https://discuss.python.org/t/do-we-want-classifiers-for-webassembly-on-pypi/22712
* Update hatchling lower bound to v1.13.0, the first version to support
the …
```

docs: Add Environment :: WebAssembly :: Emscripten PyPI trove classifier

---

pyproject.toml

* Resolves #2111
* Closes #2118
Use [`hatchling`'s environment markers](https://hatch.pypa.io/latest/config/dependency/#environment-markers) system to use platform information to determine when the installing machine is an Apple silicon Mac and install `tensorflow-macos` instead of `tensorflow` in this situation. This works because of the following:
* x86-64 Linux machine:
```python
>>> import platform
>>> platform.machine()
'x86_64'
>>> platform.system()
'Linux'
```
* x86-64 Apple machine:
```python
>>> import platform
>>> platform.machine()
'x86_64'
>>> platform.system()
'Darwin'
```
* AArch64 machine:
```python
>>> import platform
>>> platform.machine()
'aarch64'
>>> platform.system()
'Linux'
```
* Apple silicon machine:
```python
>>> import platform
>>> platform.machine()
'arm64'
>>> …
```

build: Install tensorflow-macos on Apple silicon Macs

---

docs/bib/general_citations.bib
docs/bib/use_citations.bib

Add citations from Ph.D. theses that are on CDS but not yet on INSPIRE:
* Add general citation from [Searching for Beyond the Standard Model Resonances in the HH→bb¯bb¯ Final State Using the ATLAS Detector](https://cds.cern.ch/record/2743178/) by @beojan.
* Add use citation from [Differential Cross Section Measurement of the pp→WH→WWW Process With the ATLAS Experiment](https://cds.cern.ch/record/2799614/) by Moritz Hesping.
(belated) Congratulations Dr. Stanislaus and Dr. Hesping! :rocket:
```
* Add general citation from 'Searching for Beyond the Standard Model Resonances
in the HH→bb¯bb¯ Final State Using the ATLAS Detector'.
- c.f. https://cds.cern.ch/record/2743178/
- Ph.D. dissertation of Beojan Stanislaus
* Add use citation from 'Differential Cross Section …
```

docs: Add citations from Ph.D. theses on CDS

---

docs/bib/use_citations.bib

Add use citation from [Prospects of Searches for Anomalous Hadronic Higgs Boson Decays at the LHeC](https://inspirehep.net/literature/2636748) by Subhasish Behera, Manuel Hageluken, and Matthias Schott.
```
* Add use citation from 'Prospects of Searches for Anomalous Hadronic
Higgs Boson Decays at the LHeC'.
- c.f. https://inspirehep.net/literature/2636748
```

docs: Add use citation from Anomalous Hadronic Higgs at the LHeC paper

---

docs/bib/use_citations.bib

Add use citation from ATLAS paper [Search for long-lived, massive particles in events with displaced vertices and multiple jets in pp collisions at s√=13 TeV with the ATLAS detector](https://inspirehep.net/literature/2628398) ([SUSY-2018-13](http://atlas.web.cern.ch/Atlas/GROUPS/PHYSICS/PAPERS/SUSY-2018-13/)).
Congratulations to the analysis team! :tada: 
```
* Add use citation from 'Search for long-lived, massive particles in events
with displaced vertices and multiple jets in pp collisions at s√=13 TeV
with the ATLAS detector'.
- ATLAS paper: SUSY-2018-13
- c.f. https://inspirehep.net/literature/2628398
```

docs: Add use citation from ATLAS displaced vertices and multiple jets paper

---

src/pyhf/tensor/jax_backend.py

Update JAX backend array_type to `jaxlib.xla_extension.ArrayImpl`, which is a unified array type introduced in `jaxlib` `v0.4.6`.
- c.f. https://github.com/google/jax/releases/tag/jaxlib-v0.4.6
- c.f. https://github.com/google/jax/issues/14768
```
* Update JAX backend array_type to jaxlib.xla_extension.ArrayImpl, which is a unified
array type introduced in jaxlib v0.4.6.
- c.f. https://github.com/google/jax/releases/tag/jaxlib-v0.4.6
- c.f. https://github.com/google/jax/issues/14768
```

docs: Update JAX backend array_type to jaxlib.xla_extension.ArrayImpl

---

docs/generate_jupyterlite_iframe.py
docs/jupyterlite.rst

Resolves #2132
To ensure that all the dependencies for examples in the JupyterLite are available add matplotlib to the list of libraries to install with piplite.
```
* To ensure that all the dependencies for examples in the JupyterLite
are available add matplotlib to the list of libraries to install with
piplite.
```

docs: Add matplotlib to piplite installs for JupyterLite example

---

.flake8
.pre-commit-config.yaml
pyproject.toml
src/pyhf/cli/spec.py

This moves the flake8 & pyupgrade checks into a single Ruff check, and moves the config to pyproject.toml. There are a lot of checks that could be added (see https://scikit-hep.org/developer/style#ruff), I've just stuck to replicating the current config. The one loss is flake8-encodings, someone could request this added to Ruff.
I've skipped the failing checks for notebooks, might be worth checking to see if they are valid.
```
* Drop flake8, yesqa, pyupgrade, and nbqa-pyupgrade pre-commit hooks in favor of Ruff.
- Remove .flake8 config file as no longer used.
- Remove nbqa config options for pyupgrade in pyproject.toml and add ruff config options.
```

chore: Move to using Ruff for pre-commit

---

tests/test_tensor.py

Remove the xfail test as for TensorFlow v2.12.0+ the floating point agreement is restored and so the test is no longer needed. c.f. Issue #1759 for details.
```
* Remove the xfail test as for TensorFlow v2.12.0+ the floating point
agreement is restored and so the test is no longer needed.
- c.f. https://github.com/scikit-hep/pyhf/issues/1759 for summary details.
```

test: Remove xfail test for floating point agreement on macOS

---

tests/test_tensor.py

Resolves #2143 
In Python 3.11 mocking of attributes through [`unittest.mock.patch`](https://docs.python.org/3.11/library/unittest.mock.html#patch) will fail with an `AttributeError`. To avoid this, use [`unittest.mock.patch.object`](https://docs.python.org/3.11/library/unittest.mock.html#patch-object) to mock the `_setup` attribute of a `pyhf.tensorlib` object.
c.f. https://docs.python.org/3.11/library/unittest.mock.html#the-mock-class footnote:
> The only exceptions are magic methods and attributes (those that have leading and trailing double underscores). Mock doesn’t create these but instead raises an [AttributeError](https://docs.python.org/3.11/library/exceptions.html#AttributeError). This is because the interpreter will often implicitly request these methods, and gets very confused …

fix: Use unittest.mock.patch.object to mock attributes

---

.github/workflows/bump-version.yml
.github/workflows/ci.yml
.github/workflows/dependencies-head.yml
.github/workflows/docs.yml
.github/workflows/notebooks.yml
.github/workflows/publish-package.yml
.github/workflows/release_tests.yml
.pre-commit-config.yaml
.readthedocs.yaml
binder/runtime.txt
codemeta.json
docker/Dockerfile
docs/development.rst
noxfile.py
pyproject.toml

Now that [TensorFlow `v2.12.0`](https://pypi.org/project/tensorflow/2.12.0/) is out with Python 3.11 support, add Python 3.11 to the testing in CI and then default all the uses of Python 3.10 in the project to Python 3.11.
```
* Add Python 3.11 to testing in CI.
* Default to using Python 3.11 in GitHub Actions where possible.
* Update to using Python 3.11 in linting and validation tools.
* Update Binder runtime Python to Python 3.11.
* Update Dockerfile base image to python:3.11-slim-bullseye.
* Update the docs to advocate using Python 3.11 for development.
* Add ignore of DeprecationWarning of Python's sre_constants from TensorFlow
- c.f. https://docs.python.org/3.11/whatsnew/3.11.html#modules
> Undocumented modules sre_compile, sre_constants and sre_parse
> are now …
```

feat: Add Python 3.11 to testing and default to using it

---

.github/workflows/ci.yml
.github/workflows/docker.yml
.github/workflows/docs.yml
.github/workflows/publish-package.yml
.github/workflows/semantic-pr-check.yml
.readthedocs.yaml
docker/Dockerfile

* Backport PR #2149 and add Docker build and docs workflows
to run on PRs on patch release branches.
- PR https://github.com/scikit-hep/pyhf/pull/2047
- PR https://github.com/scikit-hep/pyhf/pull/2058
- PR https://github.com/scikit-hep/pyhf/pull/2102
- PR https://github.com/scikit-hep/pyhf/pull/2106
- PR https://github.com/scikit-hep/pyhf/pull/2140
- PR https://github.com/scikit-hep/pyhf/pull/2145
- PR https://github.com/scikit-hep/pyhf/pull/2146
```
* Backport PR #2149 and add Docker build and docs workflows
to run on PRs on patch release branches.
- PR https://github.com/scikit-hep/pyhf/pull/2047
- PR https://github.com/scikit-hep/pyhf/pull/2058
- PR https://github.com/scikit-hep/pyhf/pull/2102
- PR …
```

ci: Run CI and packaging workflows on release branch PRs  

---

docs/bib/use_citations.bib

* Add use citation from [LHC constraints on electroweakino dark matter revisited](https://inspirehep.net/literature/2133874) by Trygve Buanes, Iñaki Lara, Krzysztof Rolbiecki, and Kazuki Sakurai. (This wasn't missed earlier, the citation first appeared in [v4](https://arxiv.org/abs/2208.04342v4) of the arXiv preprint which came out in March 2023 :+1:).
```
* Add use citation from 'LHC constraints on electroweakino dark matter revisited'.
- c.f. https://inspirehep.net/literature/2133874
```

docs: Add use citation from constraints on electroweakino dark matter paper

---

.github/workflows/bump-version.yml
.github/workflows/docker.yml

* Update to use the new GitHub workflow GITHUB_OUTPUT environmental file to avoid problems when the setting 'set-output' via stdout is deprecated in 2023. c.f.:
- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files
- https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-of-setting-an-output-parameter
```
* Update to use the new GitHub workflow GITHUB_OUTPUT environmental file
to avoid problems when the setting 'set-output' via stdout is deprecated
in 2023. c.f.:
- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- …
```

fix: Set workflow output parameter with GITHUB_OUTPUT

---

.github/workflows/docker.yml

* Instead of trying to parse the `GITHUB_REF` environmental variable to get the tag or branch name use `GITHUB_REF_NAME` which provides this already.
* Split tag names over multiple lines in the YAML file for visual clarity.
```
* Instead of trying to parse the GITHUB_REF environmental variable to
get the tag or branch name use GITHUB_REF_NAME which provides this
already.
* Split tag names over multiple lines in the YAML file for visual clarity.
```

ci: Use GITHUB_REF_NAME environmental variable to set tag version

---

.github/workflows/bump-version.yml

Add option in bump version workflow for the target branch to checkout and push the resulting tag back to. Also include changes that have the string `(backport):` in the commit message, but include them last in the list of changes.
```
* Add option in bump version workflow for the target branch to checkout
and push the resulting tag back to.
* Add check that the target branch is either 'main' or a 'release/' branch.
Though don't run this check if the 'force override check' option is
enabled.
* Include changes that have the string '(backport):' in the commit
message, but include them last in the list of changes.
```

ci: Add workflow input for bump version branch

---

docs/bib/use_citations.bib

Add use citation from [Search for vector-like leptons at a Muon Collider](https://inspirehep.net/literature/2648832) by Qilong Guo, Leyun Gao, Yajun Mao, Qiang Li.
```
* Add use citation from 'Search for vector-like leptons at a Muon Collider'.
- c.f. https://inspirehep.net/literature/2648832
```

docs: Add use citation from vector-like leptons at a muon collider paper

---

tests/test_import.py
tests/test_optim.py
tests/test_patchset.py
tests/test_teststats.py
tests/test_utils.py
tests/test_workspace.py

Resolves #2161 
* This is a much simpler way and more maintainable way to check Error message content rather than manually checking captured output. In the cases where multiple strings need to be checked for still keep checking the values are in `str(exc_info.value)`.
* Fix checks in `tests/test_import.py` that were not properly checking the output.
Should go in before PR #2109 to allow that PR to use this as @alexander-held has already started to implement these changes there.
```
* This is a much simpler way and more maintainable way to check Error
message content rather than manually checking captured output. In the
cases where multiple strings need to be checked for still keep
checking the values are in str(exc_info.value).
* Fix checks in tests/test_import.py …
```

test: Use pytest.raises match argument to check Error messages

---

src/pyhf/readxml.py
tests/test_import.py
tests/test_import/xmlimport_noChannelDataPaths/config/HistFactorySchema.dtd
tests/test_import/xmlimport_noChannelDataPaths/config/example.xml
tests/test_import/xmlimport_noChannelDataPaths/config/example_channel.xml

Raise an error when attempting to convert an xml workspace that contains no data, i.e. looks like this:
```xml
<Data HistoName="" InputFile="" HistoPath=""/>
```
Previously this would raise an `IsADirectoryError` via `uproot`, which is confusing to users. See #566 for context.
I have not added any new test for this, as I haven't seen anything specifically targeting that API at the moment. I confirmed it raises as expected, an example is linked in https://github.com/scikit-hep/pyhf/issues/566#issuecomment-700573969.
```
* Raise NotImplementedError when attempting to convert an xml workspace that
contains no data. The previous behavior was uproot raising IsADirectoryError,
which is confusing.
* Add a test for raising NotImplementedError in tests/test_import.py and add …
```

fix: Raise error when converting xml workspaces without data

---

src/pyhf/readxml.py
tests/test_import.py
tests/test_import/xmlimport_noChannelDataPaths/config/HistFactorySchema.dtd
tests/test_import/xmlimport_noChannelDataPaths/config/example.xml
tests/test_import/xmlimport_noChannelDataPaths/config/example_channel.xml

Backport PR https://github.com/scikit-hep/pyhf/pull/2109
```
* Backport PR https://github.com/scikit-hep/pyhf/pull/2109
```

fix(backport): Raise error when converting xml workspaces without data

---

docs/release-notes.rst
docs/release-notes/v0.7.0.rst
docs/release-notes/v0.7.1.rst

* Add release notes for pyhf v0.7.1.
* Fix the PEP number of Python 3.10 in v0.7.0 release notes.
- c.f. https://peps.python.org/pep-0619/
```
* Add release notes for pyhf v0.7.1.
* Fix the PEP number of Python 3.10 in v0.7.0 release notes.
- c.f. https://peps.python.org/pep-0619/
```

docs: Add v0.7.1 release notes

---

docs/bib/HEPData_likelihoods.bib

* Add ATLAS search for gluinos in multi-b final states statistical model HEPDdata record
- c.f. https://www.hepdata.net/record/ins2182381
- Corresponding INSPIRE record: https://inspirehep.net/literature/2182381
```
* Add ATLAS search for gluinos in multi-b final states statistical model HEPDdata record
- c.f. https://www.hepdata.net/record/ins2182381
- Corresponding INSPIRE record: https://inspirehep.net/literature/2182381
```

docs: Add ATLAS search for gluinos in multi-b final states statistical model record

---

docs/bib/use_citations.bib

* Update use citations references to include their journal publication information.
- 'Signal region combination with full and simplified likelihoods in MadAnalysis 5' is published as SciPost Phys. 14 (2023) 1, 009. https://doi.org/10.21468/SciPostPhys.14.1.009
:clap: @jackaraz
```
* Update use citations references to include their journal
publication information.
- 'Signal region combination with full and simplified likelihoods in
MadAnalysis 5' is published as SciPost Phys. 14 (2023) 1, 009.
https://doi.org/10.21468/SciPostPhys.14.1.009
```

docs: Update use citations references to include journal publications

---

.github/workflows/release_tests.yml
codemeta.json

* Update codemeta.json to be similar style to the codemetapy v2.4.x output.
- Add numpy to codemeta.json.
* Update codemetapy to v2.4.1 in the release tests.
```
* Update codemeta.json to be similar style to the codemetapy v2.4.x output.
- Add numpy to codemeta.json.
* Update codemetapy to v2.4.1 in the release tests.
```

chore: Update codemeta

---

.github/workflows/publish-package.yml

In `pypa/gh-action-pypi-publish` `v1.7.0` inputs were changed to use kebab-case. Update to all inputs that were previously snake_case to use the new input format.
- c.f. https://github.com/pypa/gh-action-pypi-publish/releases/tag/v1.7.0
```
* In pypa/gh-action-pypi-publish v1.7.0 inputs were changed to use
kebab-case. Update to all inputs that were previously snake_case to
use the new input format.
- c.f. https://github.com/pypa/gh-action-pypi-publish/releases/tag/v1.7.0
```

ci: Use gh-action-pypi-publish v1.7.0+ APIs

---

.github/workflows/publish-package.yml

* Backport PR https://github.com/scikit-hep/pyhf/pull/2177
* In pypa/gh-action-pypi-publish v1.7.0 inputs were changed to use kebab-case. Update to all inputs that were previously snake_case to use the new input format.
- c.f. https://github.com/pypa/gh-action-pypi-publish/releases/tag/v1.7.0
```
* Backport PR https://github.com/scikit-hep/pyhf/pull/2177
* In pypa/gh-action-pypi-publish v1.7.0 inputs were changed to use
kebab-case. Update to all inputs that were previously snake_case to
use the new input format.
- c.f. https://github.com/pypa/gh-action-pypi-publish/releases/tag/v1.7.0
```

ci(backport): Use gh-action-pypi-publish v1.7.0+ APIs

---

README.rst

Add the NumFOCUS Affilated Project badge to the README and mention in the Acknowledgements section.
[![NumFOCUS Affiliated Project](https://img.shields.io/badge/NumFOCUS-Affiliated%20Project-orange.svg?style=flat&colorA=E1523D&colorB=007D8A)](https://numfocus.org/sponsored-projects/affiliated-projects)
I don't think(?) there is an official badge given this discussion https://github.com/glotzerlab/signac/pull/202#discussion_r299648150 between @bdice and @csadorf (:wave:), but I like what they made so I'm going to [copy `signac`](https://github.com/glotzerlab/signac/blob/1472dfa3037c0622b1869c9d3b0479ed8e0fa4f6/README.md?plain=1#L3). :+1: 
A note for posterity, `pyhf` became a NumFOCUS Affiliated Project on December 19th, 2022, but @matthewfeickert delayed a bit in getting a SVG version of …

docs: Add NumFOCUS Affiliated Project to README

---

README.rst

* Backport PR https://github.com/scikit-hep/pyhf/pull/2179
* pyhf became a NumFOCUS Affiliated Project on 2022-12-19.
- c.f. https://numfocus.org/sponsored-projects/affiliated-projects
* Add mention of being a NumFOCUS Affiliated Project to the Acknowledgements section.
```
* Backport PR https://github.com/scikit-hep/pyhf/pull/2179
* pyhf became a NumFOCUS Affiliated Project on 2022-12-19.
- c.f. https://numfocus.org/sponsored-projects/affiliated-projects
* Add mention of being a NumFOCUS Affiliated Project to the Acknowledgements
section.
```

docs(backport): Add NumFOCUS Affiliated Project to README

---

docs/bib/use_citations.bib

Add use citation from [First performance measurements with the Analysis Grand Challenge](https://inspirehep.net/literature/2650460) by @oshadura and @alexander-held. Submitted as proceedings for 21st International Workshop on Advanced Computing and Analysis Techniques in Physics Research (ACAT 2022) to Journal Of Physics: Conference Series.
```
* Add use citation from 'First performance measurements with the Analysis
Grand Challenge'.
- c.f. https://inspirehep.net/literature/2650460
- Submitted as proceedings for 21st International Workshop on Advanced
Computing and Analysis Techniques in Physics Research (ACAT 2022) to
Journal Of Physics: Conference Series
```

docs: Add use citation from IRIS-HEP AGC ACAT 2022 paper

---

docs/conf.py
pyproject.toml

Related to https://github.com/scikit-hep/scikit-hep.github.io/issues/278
* Use the Scientific Python org's Plausible instance to collect page visit statistics for the pyhf docs by adding it to the `html_js_files` in the Sphinx config.
After building the docs
```console
$ grep "plausible" docs/_build/html/index.html
<script data-domain="pyhf.readthedocs.io" defer="defer" src="https://views.scientific-python.org/js/plausible.js"></script>
```
c.f. https://views.scientific-python.org/pyhf.readthedocs.io/
```
* Use the Scientific Python org's Plausible instance to collect page visit
statistics for the pyhf docs by adding it to the html_js_files in the
Sphinx config.
- c.f. https://views.scientific-python.org/pyhf.readthedocs.io/
```

docs: Use Plausible for page visit statistics

---

docs/conf.py

Backport PR https://github.com/scikit-hep/pyhf/pull/2186
```
* Backport PR https://github.com/scikit-hep/pyhf/pull/2186
* Use the Scientific Python org's Plausible instance to collect page visit
statistics for the pyhf docs by adding it to the html_js_files in the
Sphinx config.
- c.f. https://views.scientific-python.org/pyhf.readthedocs.io/
```

docs(backport): Use Plausible for page visit statistics

---

.github/workflows/merged.yml

The GKE Binder Federation instance is being taken offline on 2023-04-28 and so requests made to gke.mybinder.org will fail. :disappointed: To keep the GHA workflow from failing remove the GKE build triggers.
- c.f. 2023-04-25 blog [Mybinder.org reducing capacity](https://blog.jupyter.org/mybinder-org-reducing-capacity-c93ccfc6413f)
```
* The GKE Binder Federation instance is being taken offline on
2023-04-28 and so requests made to gke.mybinder.org will fail.
To keep the GHA workflow from failing remove the GKE build triggers.
- c.f. https://blog.jupyter.org/mybinder-org-reducing-capacity-c93ccfc6413f
```

chore: Remove GKE mybinder build

---

docs/conf.py
pyproject.toml

Remove `sphinx-togglebutton` dependency from the 'docs' extra as `sphinx-togglebutton` was used only to make a instructional admonition into a toggleable dropdown. The admonition was removed in PR #2187 and so `sphinx-togglebutton` is no longer needed.
```
* Remove sphinx-togglebutton dependency from the 'docs' extra as
sphinx-togglebutton was used only to make a instructional admonition
into a toggleable dropdown. The admonition was removed in PR #2187 and so
sphinx-togglebutton is no longer needed.
* Remove use of sphinx_togglebutton extension from docs/conf.py.
* Amends PR https://github.com/scikit-hep/pyhf/pull/2187.
```

build: Remove sphinx-togglebutton from 'docs' extra

---

pyproject.toml

`sphinx-copybutton` `v0.5.1` has a bug that will place lines of output in the copy contents, so explicitly disallow `v0.5.1`. This bug is fixed in `sphinx-copybutton` `v0.5.2`.
---
In `sphinx-copybutton` `v0.5.1` the following reStructuredText block
https://github.com/scikit-hep/pyhf/blob/0cac4583ba33de33450daba6ab901ee712c74e73/README.rst?plain=1#L68-L82
when copied will contain the line
```
Observed: 0.05251497, Expected: 0.06445321
```
in the output which is not the desired effect.
`v0.5.0` copy contents:
```
import pyhf
pyhf.set_backend("numpy")
model = pyhf.simplemodels.uncorrelated_background(
signal=[12.0, 11.0], bkg=[50.0, 52.0], bkg_uncertainty=[3.0, 7.0]
)
data = [51, 48] + model.config.auxdata
test_mu = 1.0
CLs_obs, CLs_exp = pyhf.infer.hypotest(
test_mu, data, model, …
```

fix: Disallow sphinx-copybutton v0.5.1 to avoid output in copy

---

docs/release-notes/v0.7.1.rst

Fix 'tensorlfow' -> 'tensorflow' typ in the v0.7.1 release notes. :grimacing: 
https://github.com/scikit-hep/pyhf/blob/5161749fe8509dde6f5f9c1d6fcb7d7b8a796a9f/docs/release-notes/v0.7.1.rst?plain=1#L12
```
* Fix 'tensorlfow' -> 'tensorflow'
```

docs: Correct 'tensorflow' typo in v0.7.1 release notes

---

docs/bib/use_citations.bib

Add use citation from [Search for lepton-flavor-violating τ−→ℓ−ϕ decays in 2019-2021 Belle II data](https://inspirehep.net/literature/2657628) by the Belle II collaboration.
```
* Add use citation from 'Search for lepton-flavor-violating τ−→ℓ−ϕ
decays in 2019-2021 Belle II data'.
- c.f. https://inspirehep.net/literature/2657628
```

docs: Add use citation from Belle II lepton-flavor-violating decays paper

---

docs/bib/use_citations.bib

* '[Simplified likelihoods using linearized systematic uncertainties](https://inspirehep.net/literature/2623097)' is published as JHEP 04 (2023) 084. https://doi.org/10.1007/JHEP04(2023)084
* '[HighPT: A tool for high-pT Drell-Yan tails beyond the standard model](https://inspirehep.net/literature/2121076)' is published as Comput.Phys.Commun. 289 (2023) 108749. https://doi.org/10.1016/j.cpc.2023.108749
```
* Update use citations references to include their journal
publication information.
- 'Simplified likelihoods using linearized systematic uncertainties'
is published as JHEP 04 (2023) 084.
https://doi.org/10.1007/JHEP04(2023)084
- 'HighPT: A tool for high-pT Drell-Yan tails beyond the standard
model' is published as Comput.Phys.Commun. 289 (2023) 108749. …
```

docs: Update citations references to include journal pubs through 2023-04

---

pyproject.toml

* `tensorflow-probability` `v0.20.0` breaks all Python 3.7 and older as it lacks `requires-python` metadata, and so is explicitly disallowed.
- c.f. https://github.com/tensorflow/probability/issues/1723
```
* tensorflow-probability v0.20.0 breaks all Python 3.7 and older as it lacks
requires-python metadata, and so is explicitly disallowed.
```

fix: Disallow TensorFlow Probability v0.20.0

---

.github/workflows/merged.yml
.github/workflows/publish-package.yml
.pre-commit-config.yaml

- PR https://github.com/scikit-hep/pyhf/pull/2183
- PR https://github.com/scikit-hep/pyhf/pull/2189
- PR https://github.com/scikit-hep/pyhf/pull/2193
- PR https://github.com/scikit-hep/pyhf/pull/2195
```
- PR https://github.com/scikit-hep/pyhf/pull/2183
- PR https://github.com/scikit-hep/pyhf/pull/2189
- PR https://github.com/scikit-hep/pyhf/pull/2193
- PR https://github.com/scikit-hep/pyhf/pull/2195
```

ci(backport): Update CI workflows and use Trusted Publishers

---

src/pyhf/pdf.py
tests/test_pdf.py

Resolves #2200.
This addresses #2194. When a parameter with multiple components (`shapefactor` / `shapesys` / `staterror`) is used as POI, the model construction currently fails at an `assert` (assuming Python is not run with `-O`). This PR turns the failure into an exception with an error message to provide more context.
For simple MLEs, bypassing the `assert` actually  makes things work (so one could argue to not catch this early and force the exception). However, this would cause even more confusing issues down the line once the POI starts mattering. As an example, a `hypotest` could result in `RuntimeWarning: invalid value encountered in subtract` within `scipy`. I do not see any benefit in allowing to bypass the exception to allow running things that do not depend on the POI …

fix: Catch use of multi-component parameters as POI with error message

---

pyproject.toml
src/pyhf/tensor/numpy_backend.py

Resolves #2207 
The addition of `typing.TYPE_CHECKING` avoids situations in which the version of NumPy (whose lower bounds is enforced by SciPy) doesn't have `numpy.typing`, which was added in NumPy `v1.21.0`.
To avoid drops in code coverage at the patch level, exclude `if TYPE_CHECKING:` from the `coverage` report by using the `exclude_also` option.
```
* The addition of typing.TYPE_CHECKING avoids situations in which
the version of NumPy (whose lower bounds is enforced by SciPy)
doesn't have numpy.typing, which was added in NumPy v1.21.0.
* Exclude lines that match 'if TYPE_CHECKING:' from the coverage
report to avoid artificial drops in code coverage.
- c.f. https://coverage.readthedocs.io/en/stable/excluding.html#advanced-exclusion
Co-authored-by: Giordon Stark …
```

fix: Add TYPE_CHECKING guard for numpy.typing

---

.github/ISSUE_TEMPLATE/~release-checklist.md
docs/development.rst

Resolves #2032.
Update the maintainer release checklist to reflect the current release workflow.
Add selection of the branch for pushing the tag back to the developer docs.
```
* Update the maintainer release checklist to reflect the current release
workflow.
- Add 'After Release Tag Pushed To GitHub' section.
- Add checks for the container images being published to multiple
container image registries.
- Add additional example Software Process and Infrastructure JIRA
tickets.
* Add selection of the branch for pushing the tag back to the developer
docs.
```

docs: Update release checklist

---

docs/bib/talks.bib
docs/bib/tutorials.bib

Update pyhf talk and tutorial list through May 2023.
Fix DESY Indico URL for 'Traditional inference with machine learning tools' to avoid timeout error during linkcheck.
```
* Update pyhf talk and tutorial list through May 2023.
* Fix DESY Indico URL for 'Traditional inference with machine learning tools'
to avoid timeout error during linkcheck.
```

docs: Update talk list through May 2023

---

.github/ISSUE_TEMPLATE/~release-checklist.md
docs/bib/talks.bib
docs/bib/tutorials.bib
docs/development.rst

* Backport:
- PR https://github.com/scikit-hep/pyhf/pull/2209
- PR https://github.com/scikit-hep/pyhf/pull/2210
```
* Backport:
- PR https://github.com/scikit-hep/pyhf/pull/2209
- PR https://github.com/scikit-hep/pyhf/pull/2210
```

docs(backport): Update talk list and release checklist

---

src/pyhf/pdf.py
tests/test_pdf.py

Backport PR https://github.com/scikit-hep/pyhf/pull/2197
```
* Backport PR https://github.com/scikit-hep/pyhf/pull/2197
```

fix(backport): Catch use of multi-component parameters as POI

---

docs/release-notes.rst
docs/release-notes/v0.7.2.rst

* Forward port PR #2214 from `release/v0.7.x` to `main`.
* Add release notes for `pyhf` `v0.7.2`.
```
* Forward port PR #2214 from release/v0.7.x to main.
* Add release notes for pyhf v0.7.2.
```

docs: Add v0.7.2 release notes

---

pyproject.toml
tests/test_examples.py
tests/test_scripts.py

* Require `pytest-console-scripts` `v1.4.0+` in `test` extra. `pytest-console-scripts` `v1.4.0` introduces a `DeprecationWarning`:
> script_runner commands should be passed as a single sequence, not as multiple arguments.
> Replace `script_runner.run(a, b, c)` calls with `script_runner.run([a, b, c])`
* Remove unpacking of the command to be passed to `script_runner` with `shlex.split` to pass a list and not multiple arguments.
```
* Require pytest-console-scripts v1.4.0+ in 'test' extra. pytest-console-scripts v1.4.0
introduces a DeprecationWarning:
> script_runner commands should be passed as a single sequence, not as multiple arguments.
> Replace `script_runner.run(a, b, c)` calls with `script_runner.run([a, b, c])`
* Remove unpacking of the command to be passed to …
```

fix: Pass script_runner commands as a single sequence

---

docs/conf.py

* Resolves #2219
* Resolves #2191
`sphinx_rtd_theme` must be added to the sphinx extensions in `sphinx` `v6.0+` to properly load jQuery.
- c.f. https://sphinx-rtd-theme.readthedocs.io/en/1.2.0/changelog.html#known-issues
```
* sphinx_rtd_theme must be added to the sphinx extensions in sphinx v6.0+
to properly load jQuery.
- c.f. https://sphinx-rtd-theme.readthedocs.io/en/1.2.0/changelog.html#known-issues
```

fix: Add sphinx_rtd_theme to extensions

---

pyproject.toml
tests/test_examples.py
tests/test_scripts.py

Backport PR https://github.com/scikit-hep/pyhf/pull/2221
```
* Backport PR https://github.com/scikit-hep/pyhf/pull/2221
* Require pytest-console-scripts v1.4.0+ in 'test' extra. pytest-console-scripts v1.4.0
introduces a DeprecationWarning:
> script_runner commands should be passed as a single sequence, not as multiple arguments.
> Replace `script_runner.run(a, b, c)` calls with `script_runner.run([a, b, c])`
* Remove unpacking of the command to be passed to script_runner with shlex.split
to pass a list and not multiple arguments.
```

fix(backport): Pass script_runner commands as a single sequence

---

docs/conf.py

* Backport PR https://github.com/scikit-hep/pyhf/pull/2220
* sphinx_rtd_theme must be added to the sphinx extensions in sphinx v6.0+ to properly load jQuery.
- c.f. https://sphinx-rtd-theme.readthedocs.io/en/1.2.0/changelog.html#known-issues
```
* Backport PR https://github.com/scikit-hep/pyhf/pull/2220
* sphinx_rtd_theme must be added to the sphinx extensions in sphinx v6.0+
to properly load jQuery.
- c.f. https://sphinx-rtd-theme.readthedocs.io/en/1.2.0/changelog.html#known-issues
```

docs(backport): Add sphinx_rtd_theme to extensions

---

.github/workflows/dependencies-head.yml

Nightly wheels for the Scientific Python community have migrated from the Anaconda Cloud https://anaconda.org/scipy-wheels-nightly/ package index to https://anaconda.org/scientific-python-nightly-wheels/.
- c.f. https://scientific-python.org/specs/spec-0004/
- c.f. https://github.com/scientific-python/specs/pull/182
- c.f. https://github.com/matplotlib/matplotlib/pull/25950
For matplotlib use `--index-url` of `scientific-python-nightly-wheels` and use `--extra-index-url` of public PyPI (https://pypi.org) as some of `matplotlib`'s dependencies aren't on `scientific-python-nightly-wheels`.
```
* Nightly wheels for the Scientific Python community have migrated from
the Anaconda Cloud https://anaconda.org/scipy-wheels-nightly/ package
index to …
```

ci: Use scientific-python-nightly-wheels package index for dependency nightlies

---

pyproject.toml

Add an ignore to filterwarnings to avoid `ml_dtypes` `DeprecationWarning` from use of jaxlib
> DeprecationWarning: ml_dtypes.float8_e4m3b11 is deprecated. Use ml_dtypes.float8_e4m3b11fnuz
`ml_dtypes` deprecated this behavior in [`v0.2.0`](https://github.com/jax-ml/ml_dtypes/releases/tag/v0.2.0) and `jaxlib` will [avoid the deprecation in `jaxlib` `v0.4.12`](https://github.com/google/jax/blob/01ed663163faa7bff9890a7b9ac8096c7014022e/pyproject.toml#L69-L71). (c.f. https://github.com/google/jax/pull/16277)
```
* Add an ignore to filterwarnings to avoid ml_dtypes DeprecationWarning
from use of jaxlib
> DeprecationWarning: ml_dtypes.float8_e4m3b11 is deprecated. Use ml_dtypes.float8_e4m3b11fnuz
ml_dtypes deprecated this behavior in v0.2.0 …
```

fix: Add filterwarnings ignore for ml-dtypes DeprecationWarning

---

docs/conf.py

Ignore URLs for https://indico.desy.de/event/22731 from Sphinx linkcheck tests as the URL
https://indico.desy.de/event/22731/contributions/47953/ is frequently generating 403 Client Error.
```
* Ignore URLs for https://indico.desy.de/event/22731 from Sphinx
linkcheck tests as the URL
https://indico.desy.de/event/22731/contributions/47953/ is frequently
generating 403 Client Error.
```

test: Ignore DESY Indico presentation URL during Sphinx linkcheck

---

docs/bib/general_citations.bib

Add general citation from [Potential of the Julia programming language for high energy physics computing](https://inspirehep.net/literature/2666479).
(Also congrats to the authors for getting this up on arXiv! I know it was a long process.)
```
* Add general citation from 'Potential of the Julia programming
language for high energy physics computing'.
- c.f. https://inspirehep.net/literature/2666479
```

docs: Add general use citation from Julia in HEP paper

---

docs/examples/notebooks/pytorch_tests_onoff.ipynb
src/pyhf/tensor/numpy_backend.py

Address the upcoming deprecation of `numpy.product`, which results in warnings as of `numpy` 1.25, by switching over to `np.prod`.
See https://numpy.org/devdocs/release/1.25.0-notes.html#deprecations:
> np.product is deprecated. Use np.prod instead.
> ([gh-23314](https://github.com/numpy/numpy/pull/23314))
resolves #2241
```
* Use np.prod API over np.product as np.product is deprecated
as of NumPy v1.25.0.
- c.f. https://numpy.org/devdocs/release/1.25.0-notes.html#deprecations
```

fix: Replace deprecated np.product by np.prod

---

.dockerignore
docker/Dockerfile

For security reasons and to avoid the case where a user will bind mount the image and then find that they have `root` owned files on their machine, use a non-root default user "moby" for the Docker images that owns the Python virtual environment. "moby" has uid of `1000` as this should ensure that any files created in the container while bind mounted are owned by the user regardless of OS.
```console
$ docker run --rm -ti --entrypoint /bin/bash -v $PWD:/home/moby/work pyhf/pyhf:debug-local
moby@a470af96916a:~/work$ echo "hi" > here.txt
moby@a470af96916a:~/work$ exit
exit
$ ls -l here.txt 
-rw-r--r-- 1 feickert feickert 3 Jul  5 11:50 here.txt
```
```
* Add non-root default user 'moby' with uid 1000 that owns the Python virtual environment.
- Set default working …
```

feat: Use non-root default user for Docker image

---

pyproject.toml

Add an ignore to filterwarnings to avoid `jsonschema.RefResolver` `DeprecationWarning`
> DeprecationWarning: jsonschema.RefResolver is deprecated as of v4.18.0, in favor of the https://github.com/python-jsonschema/referencing library, which provides more compliant referencing behavior as well as more flexible APIs for customization. A future release will remove RefResolver. Please file a feature request (on referencing) if you are missing an API for the kind of customization you need.
This filterwarning should be removed once pyhf updates to referencing.
- c.f. https://github.com/scikit-hep/pyhf/issues/2139
```
* Add an ignore to filterwarnings to avoid jsonschema.RefResolver DeprecationWarning
> DeprecationWarning: jsonschema.RefResolver is deprecated as of v4.18.0, …
```

fix: Add filterwarnings ignore for jsonschema.RefResolver DeprecationWarning

---

.devcontainer/devcontainer.json

* Add devcontainer config using the pyhf Dockerfile.
- c.f. https://containers.dev/
- Motivated by @crazy4pi314's SciPy 2023 lightning talk.
@crazy4pi314, @guenp, and @ltalirz also gave the SciPy 2023 tutorial [Meet your coding best friend: VS Code💖 - A hands-on tutorial on how to get the most out of the world’s most popular Python editor](https://cfp.scipy.org/2023/talk/RKV3PZ/) which covers dev containers in it as well: https://github.com/crazy4pi314/scipy-vscode-tutorial
```
* Add devcontainer config using the pyhf Dockerfile.
- c.f. https://containers.dev/
- Motivated by Sarah Kaiser's SciPy 2023 lightning talk.
```

feat: Add devcontainer config

---

README.rst
binder/postBuild
docs/examples.rst
docs/examples/notebooks/binderexample/StatisticalAnalysis.ipynb

* Install ipywidgets and ipympl to have interactive IPython widgets in modern JupyterLab.
* Use from IPython.display import display to avoid using deprecated APIs.
* Use %matplotlib widget to get interactive matplotlib in JupyterLab.
* Use 'labpath' to open up files in JupyterLab.
```
* Install ipywidgets and ipympl to have interactive IPython widgets in
modern JupyterLab.
* Use from IPython.display import display to avoid using deprecated APIs.
* Use %matplotlib widget to get interactive matplotlib in JupyterLab.
* Use 'labpath' to open up files in JupyterLab.
```

docs: Update Binder to launch into JupyterLab environment

---

pyproject.toml

* Add `ipympl>=0.3.0` to the 'test' extra environment as it is used in the notebooks as of PR #2252. The lower bound of `v0.3.0` is chosen as this corresponds in time with the 'contrib' lower bound on matplotlib of `matplotlib>=3.0.0`.
* Amends PR #2252.
```
* Add ipympl>=0.3.0 to the 'test' extra environment as it is used in the
notebooks as of PR #2252. The lower bound of v0.3.0 is chosen as this
corresponds in time with the 'contrib' lower bound on matplotlib of
matplotlib>=3.0.0.
* Amends PR #2252.
```

fix: Add ipympl to 'test' extra

---

docs/bib/use_citations.bib

Add use citation from '[Spey: smooth inference for reinterpretation studies](https://inspirehep.net/literature/2677291)' by @jackaraz.
- Use comes from spey-pyhf optional backend https://github.com/SpeysideHEP/spey-pyhf
```
* Add use citation from 'Spey: smooth inference for reinterpretation
studies'.
- c.f. https://inspirehep.net/literature/2677291
- Use comes from spey-pyhf optional backend
https://github.com/SpeysideHEP/spey-pyhf
```

docs: Add use citation from Spey paper

---

docs/bib/use_citations.bib

Add use citation from '[Gauge SU(2)f flavour transfers](https://inspirehep.net/literature/2678488)' by Luc Darmé, Aldo Deandrea, Farvah Mahmoudi.
```
* Add use citation from 'Gauge SU(2)f flavour transfers'.
- c.f. https://inspirehep.net/literature/2678488
```

docs: Add use citation from Gauge SU(2)f flavour paper

---

pyproject.toml

* Update lower bound on sphinx-rtd-theme to v1.3.0rc1 to ensure compatibility with Sphinx v7+.
- c.f. https://github.com/readthedocs/sphinx_rtd_theme/issues/1463
- As soon as sphinx-rtd-theme v1.3.0 is released on PyPI the lower bound should be updated to reflect this stable release. The release candidate is being used to unbreak CI.
* Update lower bound of Sphinx to v7.0.0 for consistency.
```
* Update lower bound on sphinx-rtd-theme to v1.3.0rc1 to ensure
compatibility with Sphinx v7+.
- c.f. https://github.com/readthedocs/sphinx_rtd_theme/issues/1463
- As soon as sphinx-rtd-theme v1.3.0 is released on PyPI the lower
bound should be updated to reflect this stable release. The release
candidate is being used to unbreak CI.
* Update lower bound of Sphinx to v7.0.0 …
```

docs: Require sphinx-rtd-theme compatible with Sphinx 7

---

docs/conf.py

Ignore URLs for https://indico.belle2.org/event/8470 from Sphinx linkcheck tests as the URL https://indico.belle2.org/event/8470/contributions/55871/ is frequently generating 403 Client Error.
```
* Ignore URLs for https://indico.belle2.org/event/8470 from Sphinx
linkcheck tests as the URL
https://indico.belle2.org/event/8470/contributions/55871/ is frequently
generating 403 Client Error.
```

test: Ignore Belle2 Indico URL during Sphinx linkcheck

---

.readthedocs.yaml

* ReadTheDocs is removing the "use system packages" feature on 2023-08-29. The user should fully specify the docs environment, which for pyhf is already done, but pyhf was following the default template which included the uses of system_packages.
The following email was received:
> Hello,
>
> You are receving this email because your Read the Docs project is impacted by an upcoming deprecation.
>
> Read the Docs used to pre-install common scientific Python packages like scipy, numpy, pandas, matplotlib and others at system level to speed up the build process. However, with all the work done in the Python ecosystem and the introduction of "wheels", these packages are a lot easier to install via pip install and these pre-installed packages are not required anymore. If you have Apt package …

docs: Remove python.sytem_packages from ReadTheDocs config

---

docs/conf.py

Ignore URLs for CERN's Twiki instance https://twiki.cern.ch/ from Sphinx linkcheck tests as CERN seems to have problems regularly maintaining their SSL certs which can lead to SSL errors.
Example:
```
Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)'))
```
```
* Ignore URLs for CERN's Twiki instance https://twiki.cern.ch/ from
Sphinx linkcheck tests as CERN seems to have problems regularly
maintaining their SSL certs which can lead to SSL errors.
Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED]
certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)'))
```

test: Ignore CERN Twiki URLs during Sphinx linkcheck

---

docs/contributors.rst
src/pyhf/optimize/opt_minuit.py
tests/test_optim.py

The relevant line is supposed to set the strategy of minuit to one of the supported values `0`, `1`, ~~or `2`~~ (Note from @matthewfeickert: `pyhf` doesn't support option `2` at this time). Since the strategy `0` evaluates to `False`, this strategy couldn't be set when creating the optimizer if `do_grad` was `False`
https://github.com/scikit-hep/pyhf/blob/f8f3c96e8be560c3e5712fe080f97e95702d4942/src/pyhf/optimize/opt_minuit.py#L104-L106
. The default value in the case of no specified strategy is `None`
https://github.com/scikit-hep/pyhf/blob/f8f3c96e8be560c3e5712fe080f97e95702d4942/src/pyhf/optimize/opt_minuit.py#L39
meaning that the statement `is not None` solves the issue with
```python
self.strategy if self.strategy is not None else not do_grad
```
.
Amends PR …

fix: Correct handling of strategy 0 for Minuit optimizer

---

src/pyhf/optimize/opt_minuit.py
tests/test_optim.py

* Fixes #1785
* Amends PR https://github.com/scikit-hep/pyhf/pull/2277
Guard Minuit optimizer strategy from None by first attempting to get a not-None result from the options kwargs and then falling back to assigning the strategy through `int(not do_grad)`. In the process this simplifies the logic required and supersedes PR https://github.com/scikit-hep/pyhf/pull/2277.
Add tests to `test_minuit_strategy_global` for `strategy=None` and `strategy=2` (`2` is a valid `iminuit.Minuit.strategy` strategy but not used often, so done just for good measure).
Add a very brief explanation to docs of what using `strategy=None` means in terms of evaluation to 0 or 1 from `int(pyhf.tensorlib.default_do_grad)`.
This extended example from @alexander-held in Issue #1785 now runs with this PR:
```python …
```

fix: Guard Minuit optimizer against provided strategy of None

---

.readthedocs.yaml
README.rst
binder/postBuild
docs/conf.py
docs/examples.rst
docs/examples/notebooks/binderexample/StatisticalAnalysis.ipynb
pyproject.toml

- PR https://github.com/scikit-hep/pyhf/pull/2252
- PR https://github.com/scikit-hep/pyhf/pull/2255
- PR https://github.com/scikit-hep/pyhf/pull/2267
- PR https://github.com/scikit-hep/pyhf/pull/2271
- PR https://github.com/scikit-hep/pyhf/pull/2272
- PR https://github.com/scikit-hep/pyhf/pull/2276
```
- PR https://github.com/scikit-hep/pyhf/pull/2252
- PR https://github.com/scikit-hep/pyhf/pull/2255
- PR https://github.com/scikit-hep/pyhf/pull/2267
- PR https://github.com/scikit-hep/pyhf/pull/2271
- PR https://github.com/scikit-hep/pyhf/pull/2272
- PR https://github.com/scikit-hep/pyhf/pull/2276
```

docs(backport): Update docs build requirements

---

docs/examples/notebooks/pytorch_tests_onoff.ipynb
src/pyhf/tensor/numpy_backend.py

* Backport PR https://github.com/scikit-hep/pyhf/pull/2242
* Use np.prod API over np.product as np.product is deprecated as of NumPy v1.25.0.
- c.f. https://numpy.org/devdocs/release/1.25.0-notes.html#deprecations
```
* Backport PR https://github.com/scikit-hep/pyhf/pull/2242
* Use np.prod API over np.product as np.product is deprecated
as of NumPy v1.25.0.
- c.f. https://numpy.org/devdocs/release/1.25.0-notes.html#deprecations
```

fix(backport): Replace deprecated np.product by np.prod

---

.dockerignore
docker/Dockerfile

* Backport PR https://github.com/scikit-hep/pyhf/pull/2243
* Add non-root default user 'moby' with uid 1000 that owns the Python virtual environment.
- Set default working directory to /home/moby/work/.
* Add .dockerignore for local builds.
```
* Backport PR https://github.com/scikit-hep/pyhf/pull/2243
* Add non-root default user 'moby' with uid 1000 that owns the Python virtual environment.
- Set default working directory to /home/moby/work/.
* Add .dockerignore for local builds.
```

feat(backport): Use non-root default user for Docker image

---

docs/contributors.rst
src/pyhf/optimize/opt_minuit.py
tests/test_optim.py

* Backport:
- PR https://github.com/scikit-hep/pyhf/pull/2277
- PR https://github.com/scikit-hep/pyhf/pull/2278
```
* Backport:
- PR https://github.com/scikit-hep/pyhf/pull/2277
- PR https://github.com/scikit-hep/pyhf/pull/2278
```

fix(backport): Guard Minuit optimizer against provided strategy of None

---

docs/bib/HEPData_likelihoods.bib

* Add ATLAS observation of single-top-quark production in association with a photon statistical model HEPDdata record.
- c.f. https://www.hepdata.net/record/ins2628980
- Corresponding INSPIRE record: https://inspirehep.net/literature/2628980
```
* Add ATLAS observation of single-top-quark production in association with a photon
statistical model HEPDdata record.
- c.f. https://www.hepdata.net/record/ins2628980
- Corresponding INSPIRE record: https://inspirehep.net/literature/2628980
```

docs: Add ATLAS single-top-quark production observation statistical model record

---

docs/bib/general_citations.bib
docs/bib/use_citations.bib

Update use citations references to include their journal publication information.
- 'Unbinned profiled unfolding' is published as [Phys.Rev.D 108 (2023) 1, 016002](https://doi.org/10.1103/PhysRevD.108.016002).
- 'Search for long-lived, massive particles in events with displaced vertices and multiple jets in pp collisions at s√=13 TeV with the ATLAS detector' is published as [JHEP 2306 (2023) 200](https://doi.org/10.1007/JHEP06(2023)200).
- 'Search for an invisible Z′ in a final state with two muons and missing energy at Belle II' is published as [Phys.Rev.Lett. 130 (2023) 23, 231801](https://doi.org/10.1103/PhysRevLett.130.231801).
- 'Toward the end-to-end optimization of particle physics instruments with differentiable programming' is published as [Rev.Phys. 10 (2023) …

docs: Update citations references with journal pubs through 2023-07

---

docs/release-notes/v0.7.3.rst

As the bug that was fixed in PR #2278 was subtle add an example to the pyhf v0.7.3 release notes that people can use to see if they were affected by it.
Amends PR #2290 
```
* As the bug that was fixed in PR #2278 was subtle add an example to
the pyhf v0.7.3 release notes that people can use to see if they
were affected by it.
* Amends PR https://github.com/scikit-hep/pyhf/pull/2290
```

docs: Add v0.7.2 failing example to v0.7.3 release notes

---

docs/conf.py

Resolves #2299 
To avoid warning
```
WARNING: The config value `jupyterlite_dir' has type `str', defaults to `PosixPath'.
```
use a `pathlib.Path` for the `jupyterlite-sphinx` `v0.9.1` `jupyterlite_dir` config option.
```
* To avoid warning
WARNING: The config value `jupyterlite_dir' has type `str', defaults to `PosixPath'.
use a pathlib.Path for the jupyterlite-sphinx v0.9.1 jupyterlite_dir config
option.
```

fix: Use Path object for jupyterlite-sphinx jupyterlite_dir config

---

docs/release-notes.rst
docs/release-notes/v0.7.3.rst

* Forward port PR #2290 and #2294 from `release/v0.7.x` to `main`.
* Add release notes for pyhf v0.7.3.
```
* Forward port PR #2290 and #2294 from `release/v0.7.x` to `main`.
* Add release notes for pyhf v0.7.3.
```

docs: Add v0.7.3 release notes

---

.pre-commit-config.yaml

Committed via https://github.com/asottile/all-repos
```
* Update blackend-docs pre-commit hook repo to
https://github.com/adamchainz/blacken-docs.
```

chore: Update blackend-docs repo

---

docs/conf.py

* Ignore URLs for World Scientific journal article https://doi.org/10.1142/S0217732321020016 from Sphinx linkcheck tests.
Avoids:
```
403 Client Error: Forbidden for url: https://www.worldscientific.com/doi/abs/10.1142/S0217732321020016
```
```
* Ignore URLs for World Scientific journal article
https://doi.org/10.1142/S0217732321020016 from Sphinx linkcheck tests.
Avoids:
403 Client Error: Forbidden for url:
https://www.worldscientific.com/doi/abs/10.1142/S0217732321020016
```

test: Ignore World Scientific journal URLs during Sphinx linkcheck

---

pyproject.toml

* Now that sphinx-rtd-theme v1.3.0 is out set the lower required bound to v1.3.0 instead of the release candidate.
```
* Now that sphinx-rtd-theme v1.3.0 is out set the lower required bound
to v1.3.0 instead of the release candidate.
```

chore: Require sphinx-rtd-theme of v1.3.0+

---

docs/bib/use_citations.bib

Add use citation from '[Search for short- and long-lived axion-like particles in H → a a → 4 γ decays with the ATLAS experiment at the LHC](http://cds.cern.ch/record/2867933)'
- c.f. https://inspirehep.net/literature/2691210
- http://cds.cern.ch/record/2867933
- [ATLAS-CONF-2023-040](https://atlas.web.cern.ch/Atlas/GROUPS/PHYSICS/CONFNOTES/ATLAS-CONF-2023-040/)
```
* Add use citation from 'Search for short- and long-lived axion-like particles
in H → a a → 4 γ decays with the ATLAS experiment at the LHC'.
- https://inspirehep.net/literature/2691210
- http://cds.cern.ch/record/2867933
- ATLAS-CONF-2023-040
```

docs: Add use citation from H->aa ATLAS CONF note

---

.github/workflows/docs.yml

* Ubuntu 22.04 (current operating system for GitHub Actions runners for 'ubuntu-latest') will install pandoc v2.9.2.1 through apt-get which is too old for modern versions of nbsphinx. Installing directly from binaries provided on GitHub allows a workaround for getting newer versions of pandoc on runners until the GitHub Actions runner environment updates.
- Avoids
```
RuntimeWarning: You are using an unsupported version of pandoc (2.9.2.1).
Your version must be at least (2.14.2) but less than (4.0.0).
```
from nbsphinx.
```
* Ubuntu 22.04 (current operating system for GitHub Actions runners for
'ubuntu-latest') will install pandoc v2.9.2.1 through apt-get which is
too old for modern versions of nbsphinx. Installing directly from
binaries provided on GitHub allows a …
```

chore: Install pandoc manually from GitHub release binaries

---

docs/bib/use_citations.bib

Add use citation from [Extended Symmetry Preserving Attention Networks for LHC Analysis](https://inspirehep.net/literature/2693496) by Michael James Fenton, @Alexanders101, Hideki Okawa, Yuji Li, Ko-Yang Hsiao, @schsu, @danielwhiteson, Pierre Baldi.
```
* Add use citation from 'Extended Symmetry Preserving Attention Networks
for LHC Analysis'.
- c.f. https://inspirehep.net/literature/2693496
```

docs: Add use citation from extended SPANet paper

---

docs/contributors.rst
src/pyhf/events.py

Resolves #2311 
The bug fixed by this PR occured in my work in the repository https://gitlab.cern.ch/dawerner/statanabenchmark.
I am currently working on a summer student project at CERN benchmarking statistical analysis tools in python including pyhf.
When performing these benchmarks, pyhf is called multiple times in a row with different backends. In some cases an error occurs then as objects are called through weakrefs that are already dead and thus `NoneType` objects.
When events (such as 'tensorlib_changed') are called, a bug occured previously where objects (i.e. the `TensorViewer`) are already dead. In this case an error occured when member functions where using attributes such as `self._sorted_indices` in `src/pyhf/tensor/common.py:33`.
This bug is fixed by catching the cases, in …

fix: Skip callbacks with dead weakrefs while iterating over callbacks

---

.github/ISSUE_TEMPLATE/~release-checklist.md

* Update the maintainer release checklist to include opening MRs to https://gitlab.cern.ch/atlas/StatAnalysis to update the pyhf version.
- c.f. https://github.com/scikit-hep/pyhf/issues/2289#issuecomment-1683073278
* Use the pyhf v0.7.3 release as an example of a CERN Software Process and Infrastructure JIRA request ticket.
```
* Update the maintainer release checklist to include opening MRs to
https://gitlab.cern.ch/atlas/StatAnalysis to update the pyhf version.
* Use the pyhf v0.7.3 release as an example of a CERN Software Process
and Infrastructure JIRA request ticket.
```

docs: Add MRs to ATLAS StatAnalysis to release checklist

---

.github/ISSUE_TEMPLATE/~release-checklist.md
docs/bib/general_citations.bib
docs/bib/use_citations.bib
docs/conf.py
pyproject.toml

* Backport:
- PR https://github.com/scikit-hep/pyhf/pull/2291
- PR https://github.com/scikit-hep/pyhf/pull/2300
- PR https://github.com/scikit-hep/pyhf/pull/2306
- PR https://github.com/scikit-hep/pyhf/pull/2308
- PR https://github.com/scikit-hep/pyhf/pull/2309
- PR https://github.com/scikit-hep/pyhf/pull/2312
- PR https://github.com/scikit-hep/pyhf/pull/2315
- PR https://github.com/scikit-hep/pyhf/pull/2316
```
* Backport:
- PR https://github.com/scikit-hep/pyhf/pull/2291
- PR https://github.com/scikit-hep/pyhf/pull/2300
- PR https://github.com/scikit-hep/pyhf/pull/2306
- PR https://github.com/scikit-hep/pyhf/pull/2308
- PR https://github.com/scikit-hep/pyhf/pull/2309
- PR https://github.com/scikit-hep/pyhf/pull/2312
- PR https://github.com/scikit-hep/pyhf/pull/2315 …
```

docs(backport): Update docs requirements and use citations

---

docs/contributors.rst
src/pyhf/events.py

* Backport PR https://github.com/scikit-hep/pyhf/pull/2310
* Check refs while processing callbacks in case a callee is de-ref'd during the callback process.
* Additionally flush after processing callbacks in case any callback de-ref's a callee.
* Note that no additional tests are added for this case as the problem arises from and intermediate callback triggering a garbage-collect. It is unclear how to force this scenario deterministically in testing.
* Add Jonas Rembser to contributors list.
```
* Backport PR https://github.com/scikit-hep/pyhf/pull/2310
* Check refs while processing callbacks in case a callee is de-ref'd during
the callback process.
* Additionally flush after processing callbacks in case any callback de-ref's
a callee.
* Note that no additional tests …
```

fix(backport): Skip callbacks with dead weakrefs while iterating over callbacks

---

docs/release-notes.rst
docs/release-notes/v0.7.4.rst

Add release notes for pyhf v0.7.4.
```
* Add release notes for pyhf v0.7.4.
```

docs: Add v0.7.4 release notes

---

docs/bib/use_citations.bib

* Update use citations references to include their journal publication information.
- 'Search for heavy, long-lived, charged particles with large ionisation energy loss in pp collisions at s√=13 TeV using the ATLAS experiment and the full Run 2 dataset' is published as JHEP 2306 (2023) 158. https://doi.org/10.1007/JHEP06(2023)158
```
* Update use citations references to include their journal publication information.
- 'Search for heavy, long-lived, charged particles with large
ionisation energy loss in pp collisions at s√=13 TeV using the
ATLAS experiment and the full Run 2 dataset' is published as
JHEP 2306 (2023) 158.
https://doi.org/10.1007/JHEP06(2023)158
```

docs: Update citations references with journal pubs through 2023-08

---

docs/bib/HEPData_likelihoods.bib

* Add ATLAS measurement of the s-channel single top cross-section at 13 TeV statistical model HEPDdata record.
- c.f. https://www.hepdata.net/record/ins2153660
- Corresponding INSPIRE record: https://inspirehep.net/literature/2153660
```
* Add ATLAS measurement of the s-channel single top cross-section at 13 TeV
statistical model HEPDdata record.
- c.f. https://www.hepdata.net/record/ins2153660
- Corresponding INSPIRE record: https://inspirehep.net/literature/2153660
```

docs: Add ATLAS s-channel single top cross-section statistical model record

---

.zenodo.json
CITATION.cff
README.rst
codemeta.json
docs/lite/jupyterlite.py
src/pyhf/data/citation.bib
src/pyhf/utils.py
tbump.toml

Forward port the version bump information from release `v0.7.4` on the `release/v0.7.x` branch.
```
* Forward port the version bump information from release v0.7.4 on the
```

docs: Bump version: 0.7.3 → 0.7.4

---

src/pyhf/pdf.py
src/pyhf/simplemodels.py
tests/test_backend_consistency.py
tests/test_optim.py
tests/test_validation.py

Resolves #2327
To avoid making assumptions for users about model behavior set the default POI name to `None`.
To avoid making behavior changes for `pyhf.simplemodels` add the default `poi_name` to the returned model.
This then requires explicilty setting `poi_name="mu"` in the tests for all explicity `pyhf.pdf.Model` constrcution.
```
* Set the default model poi_name to None to avoid making assumptions
for users.
* To maintain the pyhf.simplemodels users experience add poi_name="mu"
as a default argument to be passed to the returned pyhf.pdf.Model
object.
* Add poi_name="mu" to all pyhf.Model construction in the tests.
```

feat: Don't specify a default POI name

---

.github/workflows/publish-package.yml

`python -m build` is currenlty giving
```pytb
* Creating venv isolated environment...
* Installing packages in isolated environment... (hatch-vcs>=0.3.0, hatchling>=1.13.0)
* Getting build dependencies for sdist...
* Building sdist...
/tmp/build-env-d8uvwaf0/lib/python3.11/site-packages/setuptools_scm/_get_version_impl.py:[15](https://github.com/scikit-hep/pyhf/actions/runs/6250968975/job/16971014904?pr=2336#step:5:16)3: DeprecationWarning: empty regex for tag regex is invalid, using default
warnings.warn(
Traceback (most recent call last):
File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
main()
File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in …
```

ci: Move PYTHONWARNINGS filter on build to weekly cron job

---

docs/examples/notebooks/ShapeFactor.ipynb
docs/examples/notebooks/StatError.ipynb
docs/examples/notebooks/histogrammar.ipynb
docs/examples/notebooks/histosys.ipynb
docs/examples/notebooks/multichannel-coupled-histo.ipynb
docs/examples/notebooks/multichannel-coupled-normsys.ipynb
docs/examples/notebooks/normsys.ipynb

* Ensure all pyhf.Model calls in the example notebooks that don't already have a poi_name definied have `poi_name="mu"` set.
* Amends PR https://github.com/scikit-hep/pyhf/pull/2328
```
* Ensure all pyhf.Model calls in the example notebooks that don't
already have a poi_name definied have `poi_name="mu"` set.
* Amends PR https://github.com/scikit-hep/pyhf/pull/2328
```

fix: Add poi_name to Model construction in notebooks

---

docs/api.rst
docs/examples/notebooks/binderexample/StatisticalAnalysis.ipynb
src/pyhf/pdf.py
tests/test_modifiers.py
tests/test_pdf.py

Resolves #1652.
Docs: https://pyhf--2339.org.readthedocs.build/en/2339/_generated/pyhf.pdf.Model.html#pyhf.pdf.Model
```
* Promote `pyhf.pdf._MainModel._modifications` to `pyhf.pdf._MainModel.modifications`.
* Promote `pyhf.pdf.Model._modifications` to `pyhf.pdf.Model.modifications`.
* Add `pyhf.pdf._MainModel` and `pyhf.pdf._ConstraintModel` to the docs.
* Add documentation for the `modifications()` functions.
```

feat: Promote modifications to public API

---

docs/bib/use_citations.bib

Add use citation from [Boosting dark matter searches at muon colliders with Machine Learning: the mono-Higgs channel as a case study](https://inspirehep.net/literature/2700441).
```
* Add use citation from 'Boosting dark matter searches at muon colliders
with Machine Learning: the mono-Higgs channel as a case study'.
- c.f. https://inspirehep.net/literature/2700441
```

docs: Add use citation from dark matter at muon colliders paper

---

pyproject.toml

`tensorflow` `v2.14.0` breaks `tensorflow-probability` at import time. Until this is fixed, `tensorflow` `v2.14.0` can't be used.
- c.f. https://github.com/tensorflow/probability/issues/1752
```
* tensorflow v2.14.0 breaks tensorflow-probability at import time.
Until this is fixed, tensorflow v2.14.0 can't be used.
- c.f. https://github.com/tensorflow/probability/issues/1752
```

build: Disallow TensorFlow v2.14.0

---

pyproject.toml

* With the release of tensorflow-probability v0.22.0, tensorflow v2.14.0 can be used and is required for tensorflow-probability v0.22.0+.
- c.f. https://github.com/tensorflow/probability/releases/tag/v0.22.0
* Reverts PR #2342
```
* With the release of tensorflow-probability v0.22.0, tensorflow v2.14.0
can be used and is required for tensorflow-probability v0.22.0+.
- c.f. https://github.com/tensorflow/probability/releases/tag/v0.22.0
* Reverts PR https://github.com/scikit-hep/pyhf/pull/2342
```

revert: Remove disallow of TensorFlow v2.14.0

---

docs/bib/general_citations.bib
docs/bib/use_citations.bib

* Add general citation from [Software Citation in HEP: Current State and Recommendations for the Future](https://inspirehep.net/literature/2703030) by Matthew Feickert, Daniel S. Katz, Mark S. Neubauer, Elizabeth Sexton-Kennedy, Graeme A. Stewart.
* Add use citation from [Bayesian Methodologies with pyhf](https://inspirehep.net/literature/2704887) by Matthew Feickert, Lukas Heinrich, Malin Horstmann.
```
* Add general citation from 'Software Citation in HEP: Current State and
Recommendations for the Future'.
- c.f. https://inspirehep.net/literature/2703030
* Add use citation from 'Bayesian Methodologies with pyhf'.
- c.f. https://inspirehep.net/literature/2704887
```

docs: Add use citations from CHEP 2023 proceedings preprints

---

tests/conftest.py

Resolves #1454. This adds `--disable-backend` that can be specified to skip those backends as part of the testing suite.
```
* Add pytest configuration `--disable-backend` that will skip tests that use
that backend choice.
```

feat: Allow for disabling backend when running tests via pytest

---

docs/bib/use_citations.bib

Add use citation from [Search for heavy neutral leptons in electron-positron and neutral-pion final states with the MicroBooNE detector](https://inspirehep.net/literature/2709095) by the MicroBooNE collaboration.
This is the first use citation from MicroBooNE.
```
* Add use citation from 'Search for heavy neutral leptons in
electron-positron and neutral-pion final states with the MicroBooNE
detector'.
- c.f. https://inspirehep.net/literature/2709095
* This is the first use citation of pyhf from a neutrino experiment.
```

docs: Add use citation from MicroBooNE heavy neutral leptons paper

---

docs/bib/general_citations.bib

Add general citation from [Differentiable Vertex Fitting for Jet Flavour Tagging](https://inspirehep.net/literature/2712691) by Rachel Smith, Inês Ochoa, Rúben Inácio, Jonathan Shoemaker, Michael Kagan.
```
* Add general citation from 'Differentiable Vertex Fitting for Jet
Flavour Tagging'.
- c.f. https://inspirehep.net/literature/2712691
```

docs: Add general use citation from differentiable vertex fitting paper

---

README.rst

Adding the award number for the second phase of IRIS-HEP to the readme. I only saw the award number from the first phase mentioned in one other place, the JOSS acknowledgements, but those were prior work so I don't think it makes sense to update there.
```
* Add badge and funding acknowledgement for NSF cooperative agreement
PHY-2323298 award for IRIS-HEP v2.
- c.f. https://www.nsf.gov/awardsearch/showAward?AWD_ID=2323298
```

docs: Add award number for second phase of IRIS-HEP

---

src/pyhf/schema/loader.py
src/pyhf/schema/validator.py

Resolves #2353. To allow `pyhf` to work a little bit better, at least on schemas on Windows, need to rely either on `pathlib` more fully or `os.sep` in order to build the paths correctly.
- fix schema loading by making it strictly os-independent
- ~~add an additional example that is os-independent~~
```
* Use pathlib to build the stem for the schema to use (version + type of schema).
- c.f. https://github.com/python/cpython/issues/65238
```

fix: Remove os-dependent pieces of schema validation

---

.github/workflows/docker.yml
.github/workflows/publish-package.yml
.pre-commit-config.yaml
docs/faq.rst
docs/governance/ROADMAP.rst
src/pyhf/contrib/viz/brazil.py
src/pyhf/tensor/jax_backend.py
src/pyhf/tensor/numpy_backend.py
src/pyhf/tensor/pytorch_backend.py
src/pyhf/tensor/tensorflow_backend.py

* Backport:
- PR https://github.com/scikit-hep/pyhf/pull/2332
- PR https://github.com/scikit-hep/pyhf/pull/2333
- PR https://github.com/scikit-hep/pyhf/pull/2334
- PR https://github.com/scikit-hep/pyhf/pull/2335
- PR https://github.com/scikit-hep/pyhf/pull/2337
- PR https://github.com/scikit-hep/pyhf/pull/2343
```
* Backport:
- PR https://github.com/scikit-hep/pyhf/pull/2332
- PR https://github.com/scikit-hep/pyhf/pull/2333
- PR https://github.com/scikit-hep/pyhf/pull/2334
- PR https://github.com/scikit-hep/pyhf/pull/2335
- PR https://github.com/scikit-hep/pyhf/pull/2337
- PR https://github.com/scikit-hep/pyhf/pull/2343
```

chore(backport): Update GitHub Actions and pre-commit hooks

---

src/pyhf/schema/validator.py

* Backport PR https://github.com/scikit-hep/pyhf/pull/2357
* Use pathlib to build the stem for the schema to use (version + type of schema).
- c.f. https://github.com/python/cpython/issues/65238
```
* Backport PR https://github.com/scikit-hep/pyhf/pull/2357
* Use pathlib to build the stem for the schema to use (version + type of schema).
- c.f. https://github.com/python/cpython/issues/65238
```

fix(backport): Remove os-dependent pieces of schema validation

---

docs/bib/general_citations.bib
docs/bib/use_citations.bib

* Update use citations references to include their journal publication information.
- [Vector-like lepton searches at a muon collider in the context of the 4321 model*](https://doi.org/10.1088/1674-1137/ace5a7)
- [Potential of the Julia Programming Language for High Energy Physics Computing](https://doi.org/10.1007/s41781-023-00104-x)
```
* Update use citations references to include their journal publication information.
- 'Vector-like lepton searches at a muon collider in the context of
the 4321 model*'.
https://doi.org/10.1088/1674-1137/ace5a7
- 'Potential of the Julia Programming Language for High Energy
Physics Computing'.
https://doi.org/10.1007/s41781-023-00104-x
```

docs: Update citations references with journal pubs through 2023-10

---

.github/workflows/ci-windows.yml
.github/workflows/ci.yml
.github/workflows/dependencies-head.yml
.github/workflows/lower-bound-requirements.yml
.github/workflows/notebooks.yml
noxfile.py
pyproject.toml

To be able to take advantage of PR #2340 in CI it requires the ability to select a subset of dependencies to install as well (c.f. Issue #2372). To do this, this PR decouples the installation of the test dependendies in the 'test' extra from the backends that are installed in the 'all' extra and now requires 'all' to be explicitly given.
```
* Remove the 'all' extra from the 'test' extra installs and add 'all' to 
the 'develop' extra.
* Add the 'all' extra to all install commands that also install the 'test' extra.
```

build: Remove installation of backends from 'test' extra

---

src/pyhf/tensor/jax_backend.py

As of [jax and jaxlib v0.4.20](https://github.com/google/jax/releases/tag/jax-v0.4.20) accessing `jax.config` from the `jax.config` submodule is deprecated and it should be accessed from the `jax` top level API instead.
```python
>>> from jax.config import config
<stdin>:1: DeprecationWarning: Accessing jax.config via the jax.config submodule is deprecated
```
This doesn't require any change to the lower bounds of `jax` and `jaxlib`
https://github.com/scikit-hep/pyhf/blob/aa22be90fe938d3dbf61845e1e9ee25da13c2004/pyproject.toml#L76-L79
~~~
* As of jax and jaxlib v0.4.20 accessing jax.config from the jax.config
submodule is deprecated and it should be accessed from the jax top
level API instead.
```
>>> from jax.config import config
<stdin>:1: DeprecationWarning: …
```

fix: Access jax.config from jax

---

pyproject.toml

Add an ignore to filterwarnings to avoid PyTorch virtualized device UserWarning on virtualized Apple hardware.
> UserWarning: Skipping device Apple Paravirtual device that does not support Metal 2.0.
- c.f. https://github.com/pytorch/pytorch/pull/111576
```
* Add an ignore to filterwarnings to avoid PyTorch virtualized device
UserWarning on virtualized Apple hardware.
> UserWarning: Skipping device Apple Paravirtual device that does not
> support Metal 2.0.
- c.f. https://github.com/pytorch/pytorch/pull/111576
```

fix: Add filterwarnings ignore for virtualized device UserWarning

---

pyproject.toml

Use the Ruff lint config option as [recommended in the Scientific Python Development Guide](https://learn.scientific-python.org/development/guides/style/#ruff).
- RF202: Use (new) lint config section.
Thanks for adding this to repo-review, @henryiii!
```console
$ pipx run 'sp-repo-review[cli]' . | tail -n 10
├── RF103 pyupgrade must be selected ✅
├── RF201 Avoid using deprecated config settings ✅
└── RF202 Use (new) lint config section ✅
Documentation:
├── RTD100 Uses ReadTheDocs (pyproject config) ✅
├── RTD101 You have to set the RTD version number to 2 ✅
├── RTD102 You have to set the RTD build image ✅
└── RTD103 You have to set the RTD python version ✅
```
```
* Use the Ruff lint config option as recommended in the Scientific
Python Development Guide.
- RF202: Use …
```

chore: Use Ruff lint config

---

.pre-commit-config.yaml
docs/index.rst

Impliment repo-review PC170: [Uses PyGrep hooks (only needed if RST present)](https://learn.scientific-python.org/development/guides/style/#PC170).
<tr style="color: green;">
<td><span role="img" aria-label="Passed">&#9989;</span></td>
<td>PC170</td>
<td><a href="https://learn.scientific-python.org/development/guides/style#PC170">Uses PyGrep hooks (only needed if RST present)</a></td>
</tr>
```
* Impliment repo-review PC170: Uses PyGrep hooks (only needed if RST present).
- c.f. https://learn.scientific-python.org/development/guides/style/#PC170
```

chore: Add pre-commit/pygrep-hooks to pre-commit hooks

---

.pre-commit-config.yaml
pyproject.toml

This is a quick update to pre-commit to use the native notebook support in Ruff rather than an adaptor.
I was looking at ruff-format, but can't use it due to the mix of single and double quotes. Ruff has options for both, but not a "let me mix and match" mode like black.
```
* Remove github.com/nbQA-dev/nbQA in favor of native Ruff Jupyter support.
* Add support for python, pyi, jupyter types to black-jupyter hook.
* Update github.com/astral-sh/ruff-pre-commit: v0.1.4 → v0.1.6.
```

chore: Use native Ruff Jupyter support

---

docs/bib/general_citations.bib
docs/bib/use_citations.bib

Add use citations from
* [Hadronic Mono-W′ Probes of Dark Matter at Colliders](https://inspirehep.net/literature/2725449) by Ryan Holder, John Reddick, Matteo Cremonesi, Doug Berry, Kun Cheng, Matthew Low, Tim M.P. Tait, Daniel Whiteson.
* [Light New Physics in B→K(∗)νν¯?](https://inspirehep.net/literature/2725980) by Wolfgang Altmannshofer, Andreas Crivellin, Huw Haigh, Gianluca Inguglia, Jorge Martin Camalich.
Add general citation from
* [Monojets reveal overlapping excesses for light compressed higgsinos](https://inspirehep.net/literature/2727900) by Diyar Agin, @BFuks, Mark D. Goodsell, Taylor Murphy.
```
* Add use citation from 'Hadronic Mono-W′ Probes of Dark Matter at Colliders'.
- c.f. https://inspirehep.net/literature/2725449
* Add use citation from 'Light …
```

docs: Add November 2023 use and general citations

---

docs/bib/use_citations.bib

Add use citation from [Evidence for B+→K+νν¯ Decays](https://inspirehep.net/literature/2725943).
Congratulations to the Belle II collaboration on this excellent result!
```
* Add use citation from 'Evidence for B+→K+νν¯ Decays'.
- c.f. https://inspirehep.net/literature/2725943
- Congratulations to the Belle II collaboration on this excellent result!
```

docs: Add use citation from Belle II evidence for B+→K+νν¯ decays paper

---

src/pyhf/infer/test_statistics.py

When running 
```python
model = pyhf.simplemodels.uncorrelated_background(signal=[5.0, 10.0], bkg=[50.0, 60.0], bkg_uncertainty=[5.0, 12.0])
pyhf.infer.hypotest(1.0, [53.0, 65.0] + model.config.auxdata, model, test_stat="qmu")
```
we get a warning
```
qmu test statistic used for fit configuration with POI bounded at zero.
Use the qmu_tilde test statistic (pyhf.infer.test_statistics.qmu_tilde) instead.
```
and vice versa for POIs not bounded at 0. 
But this should also tell you to set `test_stat="qtilde"` or (`test_stat="q"`).
```
* Add information to the user in the warning that provides them with the
higher level pyhf.infer APIs kwarg to set the correct test statistic.
```

feat: Improve warnings for qmu and qmu_tilde for the set POI bounds

---

docs/bib/use_citations.bib

Add use citation from [A novel search strategy for right-handed charged gauge bosons at the Large Hadron Collider](https://inspirehep.net/literature/2737265) by Mariana Frank, @BFuks, @ajueid, Stefano Moretti, @oozdal.
```
* Add use citation from 'A novel search strategy for right-handed
charged gauge bosons at the Large Hadron Collider'.
- c.f. https://inspirehep.net/literature/2737265
```

docs: Add use citation from right-handed charged gauge bosons paper

---

docs/bib/use_citations.bib

Add use citation from [Double Higgs production at the HL-LHC: probing a loop-enhanced model with kinematical distributions](https://inspirehep.net/literature/2739283) by Leandro Da Rold, Manuel Epele, Anibal D. Medina, Nicolás I. Mileo, Alejandro Szynkman.
```
* Add use citation from 'Double Higgs production at the HL-LHC: probing
a loop-enhanced model with kinematical distributions'.
- c.f. https://inspirehep.net/literature/2739283
```

docs: Add use citation from HH at HL-LHC paper

---

src/pyhf/contrib/viz/brazil.py

We discovered a little bug in the brazil band visualization where the two sigma band was assigned to the "one_sigma_band" attribute of our artist collection and vice versa.
Fixing this now.
cc @malin-horstmann
Amends PR https://github.com/scikit-hep/pyhf/pull/1377
```
* Assign the one and two sigma band artists to the correct objects.
- Amends PR https://github.com/scikit-hep/pyhf/pull/1377
```

fix: Correct variable assignment for limit band artists

---

pyproject.toml

sp-repo-review MY102: Mypy show_error_codes deprecated: Must not have `show_error_codes`. Use `hide_error_codes` instead (since Mypy v0.990).
```
* sp-repo-review MY102: Mypy show_error_codes deprecated
Must not have show_error_codes. Use hide_error_codes instead (since Mypy v0.990).
```

chore: Remove Mypy 'show_error_codes' as now default

---

docs/bib/use_citations.bib

Add use citation from [Global LHC constraints on electroweak-inos with SModelS v2.3](https://inspirehep.net/literature/2741235) by Mohammad Mahdi Altakach, @sabinekraml, Andre Lessa, Sahana Narasimha, Timothée Pascal, Théo Reymermier, @WolfgangWaltenberger.
```
* Add use citation from 'Global LHC constraints on electroweak-inos with
SModelS v2.3'.
- c.f. https://inspirehep.net/literature/2741235
```

docs: Add use citation from global LHC constraints SModelS paper

---

docs/bib/use_citations.bib

Add use citation from [Machine Learning for Columnar High Energy Physics Analysis](https://inspirehep.net/literature/2743013) by @ekauffma, @alexander-held, @oshadura.
```
* Add use citation from 'Machine Learning for Columnar High Energy
Physics Analysis'.
- c.f. https://inspirehep.net/literature/2743013
* First citation from 2024!
```

docs: Add use citation from ML for columnar HEP paper

---

README.rst

The previous URLs are starting to break and so the current web API URLs for the status badges is used.
```
* The previous URLs are starting to break and so the current web API
URLs for the status badges is used.
```

docs: Update GitHub Actions workflow status badge URLs

---

docs/bib/use_citations.bib

* Add use citation from [Search for a Heavy Neutrino in \ensuremath{\tau} Decays at Belle](https://inspirehep.net/literature/2616299).
* Add use citation from [Probing electroweak phase transition in the singlet
Standard Model via bbγγ and 4l channels](https://inspirehep.net/literature/2639009).
* Update use citations references to include their journal publication information.
- [SModelS v2.3: enabling global likelihood analyses](https://doi.org/10.21468/SciPostPhys.15.5.185).
- [Boosting dark matter searches at muon colliders with machine
learning: The mono-Higgs channel as a case study](https://doi.org/10.1093/ptep/ptad144)
```
* Add use citation from 'Search for a Heavy Neutrino in \ensuremath{\tau}
Decays at Belle'.
- c.f. …
```

docs: Update citations references with journal pubs through 2023-12

---

.github/workflows/ci.yml

As PyPI no longer supports any Python 3.7 versions of jax and jaxlib use the --find-links option and the Google archive of jax release wheels to install the dependencies.
```
* As Python 3.7 versions of jax and jaxlib are no longer hosted on PyPI, use
the --find-links option and the Google archive of jax release wheels to
install the dependencies.
```

ci: Use --find-links to install jax and jaxlib on Python 3.7

---

src/pyhf/tensor/jax_backend.py

Backport PR https://github.com/scikit-hep/pyhf/pull/2376
~~~
* Backport PR https://github.com/scikit-hep/pyhf/pull/2376
* As of jax and jaxlib v0.4.20 accessing jax.config from the jax.config
submodule is deprecated and it should be accessed from the jax top
level API instead.
```
>>> from jax.config import config
<stdin>:1: DeprecationWarning: Accessing jax.config via the jax.config submodule is deprecated
```
~~~

fix(backport): Access jax.config from jax

---

.pre-commit-config.yaml
docs/index.rst
pyproject.toml

* Backport:
- PR https://github.com/scikit-hep/pyhf/pull/2378
- PR https://github.com/scikit-hep/pyhf/pull/2380
- PR https://github.com/scikit-hep/pyhf/pull/2381
- PR https://github.com/scikit-hep/pyhf/pull/2382
- PR https://github.com/scikit-hep/pyhf/pull/2383
- PR https://github.com/scikit-hep/pyhf/pull/2386
- PR https://github.com/scikit-hep/pyhf/pull/2412
- PR https://github.com/scikit-hep/pyhf/pull/2414
```
* Backport:
- PR https://github.com/scikit-hep/pyhf/pull/2378
- PR https://github.com/scikit-hep/pyhf/pull/2380
- PR https://github.com/scikit-hep/pyhf/pull/2381
- PR https://github.com/scikit-hep/pyhf/pull/2382
- PR https://github.com/scikit-hep/pyhf/pull/2383
- PR https://github.com/scikit-hep/pyhf/pull/2386
- PR https://github.com/scikit-hep/pyhf/pull/2412 …
```

chore(backport): Update pre-commit hooks

---

docs/contributors.rst
src/pyhf/infer/test_statistics.py

* Backport PR https://github.com/scikit-hep/pyhf/pull/2390
* Add Lorenz Gaertner to contributors list.
Please describe the purpose of this pull request in some detail. Reference and link to any relevant issues or pull requests.
```
* Backport PR https://github.com/scikit-hep/pyhf/pull/2390
* Add Lorenz Gaertner to contributors list.
```

feat(backport): Improve warnings for qmu and qmu_tilde for the set POI bounds

---

src/pyhf/contrib/viz/brazil.py

* Backport PR https://github.com/scikit-hep/pyhf/pull/2411
* Assign the one and two sigma band artists to the correct objects.
```
* Backport PR https://github.com/scikit-hep/pyhf/pull/2411
* Assign the one and two sigma band artists to the correct objects.
```

fix(backport): Correct variable assignment for limit band artists

---

src/pyhf/infer/__init__.py
src/pyhf/infer/calculators.py
src/pyhf/infer/mle.py
src/pyhf/infer/test_statistics.py
src/pyhf/infer/utils.py

Resolves #2419.
`fixed_params` is an iterable that is of type tuple or list. Though operations on it may support tensor types, not all operations will necessarily be supported and so the docs should not list it as being a tensor.
```
* `fixed_params` is an iterable that is of type tuple or list. Though
operations on it may support tensor types, not all operations will
necessarily be supported and so the docs should not list it as being
a tensor.
```

docs: Correct fixed_params type to tuple or list

---

src/pyhf/infer/__init__.py
src/pyhf/infer/calculators.py
src/pyhf/infer/mle.py
src/pyhf/infer/test_statistics.py
src/pyhf/infer/utils.py

* Backport PR https://github.com/scikit-hep/pyhf/pull/2420
* `fixed_params` is an iterable that is of type tuple or list. Though operations on it may support tensor types, not all operations will necessarily be supported and so the docs should not list it as being a tensor.
```
* Backport PR https://github.com/scikit-hep/pyhf/pull/2420
* `fixed_params` is an iterable that is of type tuple or list. Though
operations on it may support tensor types, not all operations will
necessarily be supported and so the docs should not list it as being
a tensor.
```

docs(backport): Correct fixed_params type to tuple or list

---

docs/release-notes.rst
docs/release-notes/v0.7.6.rst

Add release notes for pyhf v0.7.6.
```
* Add release notes for pyhf v0.7.6.
```

docs: Add v0.7.6 release notes

---

docs/bib/use_citations.bib

Add use citation from [Probing Inert Triplet Model at a multi-TeV muon collider via vector boson fusion with forward muon tagging](https://inspirehep.net/literature/2743639
) by Priyotosh Bandyopadhyay, Snehashis Parashar, Chandrima Sen, Jeonghyeon Song.
```
* Add use citation from 'Probing Inert Triplet Model at a multi-TeV muon
collider via vector boson fusion with forward muon tagging'.
- c.f. https://inspirehep.net/literature/2743639
```

docs: Add use citation from inert triplet model paper

---

pyproject.toml

* [`tensorflow` `v2.16.1`](https://github.com/tensorflow/tensorflow/releases/tag/v2.16.1) breaks `tensorflow-probability` at import time with the Keras `v3.0` API breaking change. Until Keras `v3.0` is adopted in `tensorflow-probability`, `tensorflow` `v2.16.1+` can't be used.
- c.f. https://github.com/tensorflow/probability/issues/1795
* Note that Apple silicon machines should revert to installing 'tensorflow' instead of 'tensorflow-macos' for `tensorflow v2.16.1+`.
* Note that macos x86 builds of tensorflow will be deprecated and no longer released from `tensorflow v2.17.0+`.
```
* tensorflow v2.16.1 breaks tensorflow-probability at import time with
the Keras v3.0 API breaking change. Until Keras v3.0 is adopted in
tensorflow-probability, tensorflow v2.16.1+ can't …
```

build: Disallow TensorFlow v2.16.1

---

.github/workflows/ci.yml
tests/test_calculator.py

* Add Apple M1 runner to tests using 'macos-14' for the 'runs-on' key.
- c.f. https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
* Lower the tolerance for tests/test_calculator.py to reach agreement between amd64 and arm64.
* Skip doctest evaluation for arm64. While it is possible to go through and revise the precision in the docs examples to be lower so that the [`# doctest: +NUMBER` `doctest` option](https://docs.pytest.org/en/7.1.x/how-to/doctest.html#using-doctest-options) could be used, it isn't necesssarily worth it at the moment to add this.
```
* Add Apple M1 runner to tests using 'macos-14' for the 'runs-on' key.
- c.f. https://github.blog/changelog/2024-01-30-github-actions-introducing-the-ne …
```

ci: Add Apple silicon macOS to CI 

---

pyproject.toml

* Addresses https://github.com/tensorflow/probability/issues/1795
* Resolves https://github.com/scikit-hep/pyhf/issues/2449
---
* Split the requirements for the `'tensorflow'` extra into two different conditional groups by `python_version`.
- Starting with [`tensorflow` `v2.16.1`](https://github.com/tensorflow/tensorflow/releases/tag/v2.16.1), multiple changes were made that simplifies the installation of `tensorflow` across `platform_machine` and `Keras` `v3.0` was adopted.
- `tensorflow-probability` did _not_ adopt `Keras` `v3.0`, but instead requires `tf-keras`. Starting in [`tensorflow-probability` `v0.24.0`](https://github.com/tensorflow/probability/releases/tag/v0.24.0) the `'tensorflow-probability[tf]'` extra was added which includes all the required dependencies to be able to use …

build: Determine tensorflow-probability requirements from python version

---

src/pyhf/contrib/utils.py

Resolves #2454
In Python 3.12 extraction filters are added and will become default in Python 3.14. To start using them for when Python 3.12 support is added, and to guard against a Python 3.14 DeprecationWarning, use the data extraction filter for extracting tarfiles in `pyhf.contrib.utils.download`.
- c.f. https://docs.python.org/3.12/library/tarfile.html#extraction-filters
```
* In Python 3.12 extraction filters are added and will become default in
Python 3.14. To start using them for when Python 3.12 support is added, and
to guard against a Python 3.14 DeprecationWarning, use the data extraction
filter for extracting tarfiles in pyhf.contrib.utils.download.
- c.f. https://docs.python.org/3.12/library/tarfile.html#extraction-filters
```

feat: Use Python 3.12+ tarfile data extraction filter

---

src/pyhf/writexml.py
tests/test_export.py

Resolves #2453
In Python 3.14 testing the truth value of an [`xml.etree.ElementTree.Element`](https://docs.python.org/3.12/library/xml.etree.elementtree.html#element-objects) is deprecated and will raise an exception. As of Python 3.12 this behavior will raise a `DeprecationWarning`:
```
DeprecationWarning: Testing an element's truth value will raise an exception in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.
```
To avoid this, determine the truth element by using the `elem is not None` method.
~~~
* In Python 3.14 testing the truth value of an xml.etree.ElementTree.Element is
deprecated and will raise an exception. As of Python 3.12 this behavior will
raise a DeprecationWarning:
```
DeprecationWarning: Testing an element's truth …
```

fix: Test xml.etree.ElementTree.Element truth value by 'is not None'

---

.pre-commit-config.yaml
.readthedocs.yaml
binder/runtime.txt
codemeta.json
docker/Dockerfile
docs/development.rst
noxfile.py
pyproject.toml

* Update to using Python 3.12 in linting and validation tools.
* Update Binder runtime Python to Python 3.12.
* Update Dockerfile base image to python:3.12-slim-bullseye.
* Update the docs to advocate using Python 3.12 for development.
```
* Update to using Python 3.12 in linting and validation tools.
* Update Binder runtime Python to Python 3.12.
* Update Dockerfile base image to python:3.12-slim-bullseye.
* Update the docs to advocate using Python 3.12 for development.
```

chore: Update services and docs to Python 3.12 as default

---

docs/conf.py
pyproject.toml

* To avoid warning
```
WARNING: The config value `jupyterlite_dir` has type `PosixPath`, defaults to `str`.
```
use a `str` for the `jupyterlite-sphinx` `v0.13.0+` `jupyterlite_dir` config option.
* Update `jupyterlite-sphinx` lower bound to `v0.13.1` in `'docs'` extra.
* Amends PR https://github.com/scikit-hep/pyhf/pull/2300
```
* To avoid warning
WARNING: The config value `jupyterlite_dir` has type `PosixPath`, defaults to `str`.
use a str for the jupyterlite-sphinx v0.13.0+ jupyterlite_dir config
option.
* Update jupyterlite-sphinx lower bound to v0.13.1 in 'docs' extra.
* Amends PR https://github.com/scikit-hep/pyhf/pull/2300
```

fix: Use str object for jupyterlite-sphinx jupyterlite_dir config

---

.github/workflows/ci.yml
.github/workflows/dependencies-head.yml
.github/workflows/release_tests.yml

Committed via https://github.com/asottile/all-repos
```
* The 'macos-latest' `runs-on` option has been changed to
be the Apple silicon based 'macos-14' runners. To continue
to use the x86 based macOS runners use 'macos-13' instead.
```

ci: Use 'macos-13' runs-on to continue using x86 based macOS runners

---

pyproject.toml
tests/constraints.txt

* Update the lower bounds on `scipy` to `v1.5.2` to ensure that the minimum supported dependencies workflow passes as it has started to fail consistently for `scipy` `v1.5.1`.
* Update `scipy` to `v1.5.2` in `tests/constraints.txt` to enforce the lower bound for the minimum supported dependencies tests.
Amends PR [#2081](https://github.com/scikit-hep/pyhf/pull/2081)
```
* Update the lower bounds on scipy to v1.5.2 to ensure that the minimum
supported dependencies workflow passes as it has started to fail
consistently for scipy v1.5.1.
* Update scipy to v1.5.2 in tests/constraints.txt to enforce the lower
bound for the minimum supported dependencies tests.
```

build: Update scipy lower bound to v1.5.2

---

.github/workflows/ci.yml
.github/workflows/dependencies-head.yml
.github/workflows/release_tests.yml

* Use the 'macos-latest' runs-on option which now defaults to 'macos-14' which are Apple silicon runners.
- c.f. https://github.com/actions/runner-images/blob/e63a194563cb0bb3bc1493144fe0ef6804249b43/images/macos/macos-14-arm64-Readme.md
* Keep a 'macos-13' runners to continue to test Intel based macOS for the latest Python version.
- c.f. https://github.com/actions/runner-images/blob/e63a194563cb0bb3bc1493144fe0ef6804249b43/images/macos/macos-13-Readme.md
Updates PR #2468 
```
* Use the 'macos-latest' runs-on option which now defaults to 'macos-14' which are
Apple silicon runners.
- c.f. https://github.com/actions/runner-images/blob/e63a194563cb0bb3bc1493144fe0ef6804249b43/images/macos/macos-14-arm64-Readme.md
* Keep a 'macos-13' runners to continue to test Intel …
```

ci: Use Apple silicon for the default macOS runners

---

pyproject.toml

* Loosen the install requirements for papermill, scrapbook, and sphinxcontrib-bibtex to use lower bounds instead of compatible release constraints.
* Required for PR https://github.com/scikit-hep/pyhf/pull/2444
```
* Loosen the install requirements for papermill, scrapbook, and
sphinxcontrib-bibtex to use lower bounds instead of
compatible release constraints.
* Required for PR https://github.com/scikit-hep/pyhf/pull/2444
```

build: Use lower bounds for all dependencies

---

.github/workflows/bump-version.yml
.github/workflows/ci-windows.yml
.github/workflows/ci.yml
.github/workflows/dependencies-head.yml
.github/workflows/docs.yml
.github/workflows/lower-bound-requirements.yml
.github/workflows/notebooks.yml
.github/workflows/publish-package.yml
.github/workflows/release_tests.yml
.readthedocs.yaml
pyproject.toml

Use `uv` to try to speed up the installs of all the Python dependencies.
Fall back to using `pip` for Python 3.8 until https://github.com/astral-sh/uv/issues/2062 is resolved.
Apply subtle changes to install commands in .github/workflows/dependencies-head.yml.
* `uv pip install --upgrade` will try to upgrade all dependencies of the target package as well, which for the dependencies-head workflow isn't the goal. So remove the `--upgrade` from calls that also install from the scientific-python-nightly-wheels package index when testing only particular packages.
* `up pip` and `pip` have different behavior with regards to `--extra-index-url`, as `uv pip` gives `--extra-index-url` priority over `--index-url`, where `pip` does not give priority to either. Use this with `uv pip` to give priority …

ci: Use uv for all pip installs

---

.readthedocs.yaml

RTD doesn't support uv at the same level as pip, but there are ways to still use it along with most of the infrastructure. Adopt the strategy provided in ReadTheDocs's 'Build process customization' section https://docs.readthedocs.io/en/latest/build-customization.html#install-dependencies-with-uv, from https://github.com/readthedocs/readthedocs.org/pull/11152/, but continue to monitor alternative faster methods such as those described in https://github.com/readthedocs/readthedocs.org/issues/11289 .
```
* RTD doesn't support uv at the same level as pip, but there are ways
to still use it along with most of the infrastructure. Adopt the
strategy provided in ReadTheDocs's 'Build process customization' section
https://docs.readthedocs.io/en/latest/build-customization.html …
```

ci: Use uv for install on ReadTheDocs

---

docs/conf.py

* `pkg_resources` is deprecated as an API, so stop using it.
- c.f. https://setuptools.pypa.io/en/latest/pkg_resources.html
* `importlib.metadata.version` is the recommended way to get package version information.
- c.f. https://docs.python.org/3/library/importlib.metadata.html
```
* pkg_resources is deprecated as an API, so stop using it.
- c.f. https://setuptools.pypa.io/en/latest/pkg_resources.html
* importlib.metadata.version is the recommended way to get package
version information.
- c.f. https://docs.python.org/3/library/importlib.metadata.html
```

docs: Use importlib.metadata to get version info

---

.github/workflows/lower-bound-requirements.yml

* Place an upper bound on setuptools of <70.0.0 for the 'minimum supported dependencies' workflow as setuptools v70.0.0 reduces pkg_resources useage.
- Avoids a "cannot import name 'packaging' from 'pkg_resources'" ImportError caused by PyTorch.
- c.f. https://setuptools.pypa.io/en/latest/pkg_resources.html
```
* Place an upper bound on setuptools of <70.0.0 for the 'minimum supported
dependencies' workflow as setuptools v70.0.0 reduces pkg_resources
useage.
- Avoids a "cannot import name 'packaging' from 'pkg_resources'" ImportError
caused by PyTorch.
- c.f. https://setuptools.pypa.io/en/latest/pkg_resources.html
```

ci: Place upper bound on min supported setuptools

---

.github/workflows/bump-version.yml
.github/workflows/publish-package.yml
.pre-commit-config.yaml

* Add https://github.com/python-jsonschema/check-jsonschema pre-commit hook.
* Fix schema errors by converting 'choice' dispatch type, which is a string, to 'boolean'.
```
* Add https://github.com/python-jsonschema/check-jsonschema pre-commit hook.
* Fix schema errors by converting 'choice' dispatch type, which is a string, to
'boolean'.
```

ci: Add python-jsonschema/check-jsonschema pre-commit hook

---

.github/workflows/publish-package.yml

* Remove explicit content read permissions as not formally required.
- c.f. https://github.com/actions/attest-build-provenance/tree/v1.1.2?tab=readme-ov-file#usage
```
* Remove explicit content read permissions as not formally required.
- c.f. https://github.com/actions/attest-build-provenance/tree/v1.1.2?tab=readme-ov-file#usage
```

ci: Update permissions for GitHub attestations

---

.github/workflows/scorecard.yml

* Add the Open Source Security Foundation (OSSF) scorecard GitHub action to perform security tests
- c.f. https://github.com/ossf/scorecard-action
* Change from using branch protection rules to using repository rulesets to allow for use of action without personal access tokens.
- c.f. https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/about-rulesets
- c.f. https://github.com/ossf/scorecard-action?tab=readme-ov-file#authentication-with-fine-grained-pat-optional
* Recommended as part of SPEC-8: Supply-Chain Security.
- c.f. https://github.com/scientific-python/summit-2024/issues/9
```
* Add the Open Source Security Foundation (OSSF) scorecard GitHub action
to perform security tests.
- c.f. …
```

ci: Add OSSF Scorecard GitHub action

---

.github/workflows/docker.yml
.github/workflows/docs.yml
.github/workflows/lint.yml

* Restrict content permissions to read. At the moment there are no steps to the changed workflows that use tokens, and so this is preventative if this ever changes.
* Give packages write permissions to publish to ghcr.
- Amends PR https://github.com/scikit-hep/pyhf/pull/2483.
```
* Restrict content permissions to read. At the moment there are no
steps to the changed workflows that use tokens, and so this is
preventative if this ever changes.
* Give packages write permissions to publish to ghcr.
- Amends PR https://github.com/scikit-hep/pyhf/pull/2483.
```

ci: Restrict content permissions to harden GitHub Actions

---

docker/Dockerfile

* Speed up the Dockerfile build by using uv to install all Python dependencies.
* Have hadolint ignore SC1091 in Dockerfile.
- c.f. https://www.shellcheck.net/wiki/SC1091
```
* Speed up the Dockerfile build by using uv to install all Python
dependencies.
* Have hadolint ignore SC1091 in Dockerfile.
- c.f. https://www.shellcheck.net/wiki/SC1091
```

chore: Use uv during Dockerfile build

---

docker/Dockerfile

The first ever run of the CLI API incurs some overhead so do that during the build instead of making the user wait.
```
* The first ever run of the CLI API incurs some overhead so do that during the
build instead of making the user wait.
```

chore: Speed up pyhf CLI API execution for Docker users

---

.github/workflows/release_tests.yml

This follows up on a conversation with @alexander-held on better knowing if the latest releases are actually passing on new CPython versions. That being said, all the tests will fail currently given `v0.7.6` happened before PR https://github.com/scikit-hep/pyhf/pull/2452 and so TensorFlow is breaking everything.
* Override error on filterwarnings to avoid failing on warnings.
* Set the fail-fast to False in the CI strategy to allow for identifying if things are OS specific.
```
* Override error on filterwarnings to avoid failing on warnings.
* Set the fail-fast to False in the CI strategy to allow for identifying
if things are OS specific.
```

ci: Don't test warnings on release tests

---

pyproject.toml

Backport PR https://github.com/scikit-hep/pyhf/pull/2452
```
* Backport PR https://github.com/scikit-hep/pyhf/pull/2452
* Split the requirements for the 'tensorflow' extra into two different
conditional groups by python_version.
- Starting with tensorflow v2.16.1, multiple changes were made that simplifies
the installation of tensorflow across platform_machine and Keras v3.0 was adopted.
- tensorflow-probability did _not_ adopt Keras v3.0, but instead requires
tf-keras. Starting in tensorflow-probability v0.24.0 the
'tensorflow-probability[tf]' extra was added which includes all the required
dependencies to be able to use tensorflow-probability with tensorflow v2.15+.
- tensorflow v2.16.1 and tensorflow-probability v0.24.0 support Python 3.9+,
so for Python 3.8 …
```

build(backport): Determine tensorflow-probability requirements from python version

---

.github/workflows/bump-version.yml
.github/workflows/ci.yml
.github/workflows/dependencies-head.yml
.github/workflows/docs.yml
.github/workflows/notebooks.yml
.github/workflows/publish-package.yml
.github/workflows/release_tests.yml
pyproject.toml

* Backport:
- PR https://github.com/scikit-hep/pyhf/pull/2443
- PR https://github.com/scikit-hep/pyhf/pull/2446
- PR https://github.com/scikit-hep/pyhf/pull/2451
- PR https://github.com/scikit-hep/pyhf/pull/2458
- PR https://github.com/scikit-hep/pyhf/pull/2460
- PR https://github.com/scikit-hep/pyhf/pull/2465
- PR https://github.com/scikit-hep/pyhf/pull/2468
- PR https://github.com/scikit-hep/pyhf/pull/2471
- PR https://github.com/scikit-hep/pyhf/pull/2472
```
* Backport:
- PR https://github.com/scikit-hep/pyhf/pull/2443
- PR https://github.com/scikit-hep/pyhf/pull/2446
- PR https://github.com/scikit-hep/pyhf/pull/2451
- PR https://github.com/scikit-hep/pyhf/pull/2458
- PR https://github.com/scikit-hep/pyhf/pull/2460
- PR https://github.com/scikit-hep/pyhf/pull/2465 …
```

ci(backport): Update GitHub Actions

---

.github/workflows/bump-version.yml
.github/workflows/ci.yml
.github/workflows/dependencies-head.yml
.github/workflows/docs.yml
.github/workflows/lower-bound-requirements.yml
.github/workflows/notebooks.yml
.github/workflows/publish-package.yml
.github/workflows/release_tests.yml
.readthedocs.yaml

* Backport:
- PR https://github.com/scikit-hep/pyhf/pull/2444
- PR https://github.com/scikit-hep/pyhf/pull/2475
```
* Backport:
- PR https://github.com/scikit-hep/pyhf/pull/2444
- PR https://github.com/scikit-hep/pyhf/pull/2475
```

ci(backport): Use uv for all pip installs

---

.coveragerc
.github/workflows/ci.yml
pyproject.toml

* Backport parts of PR https://github.com/scikit-hep/pyhf/pull/2054
```
* Backport parts of PR https://github.com/scikit-hep/pyhf/pull/2054
```

test(backport): Use coverage over pytest-cov

---

tests/test_calculator.py

Backport PR https://github.com/scikit-hep/pyhf/pull/2447
```
* Backport PR https://github.com/scikit-hep/pyhf/pull/2447
```

test(backport): Lower tolerance for agreement between amd64 and arm64

---

binder/runtime.txt
codemeta.json
docs/development.rst
pyproject.toml

Backport parts of PR https://github.com/scikit-hep/pyhf/pull/2461
```
* Backport parts of PR https://github.com/scikit-hep/pyhf/pull/2461
```

chore(backport): Update services and docs to Python 3.12 as default

---

.github/workflows/bump-version.yml
.github/workflows/ci-windows.yml
.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/dependencies-head.yml
.github/workflows/docker.yml
.github/workflows/docs.yml
.github/workflows/lint.yml
.github/workflows/lower-bound-requirements.yml
.github/workflows/merged.yml
.github/workflows/notebooks.yml
.github/workflows/publish-package.yml
.github/workflows/release_tests.yml
.github/workflows/semantic-pr-check.yml

* Backport:
- PR https://github.com/scikit-hep/pyhf/pull/2363
- PR https://github.com/scikit-hep/pyhf/pull/2479
- PR https://github.com/scikit-hep/pyhf/pull/2481
- PR https://github.com/scikit-hep/pyhf/pull/2483
- PR https://github.com/scikit-hep/pyhf/pull/2489
```
* Backport:
- PR https://github.com/scikit-hep/pyhf/pull/2363
- PR https://github.com/scikit-hep/pyhf/pull/2479
- PR https://github.com/scikit-hep/pyhf/pull/2481
- PR https://github.com/scikit-hep/pyhf/pull/2483
- PR https://github.com/scikit-hep/pyhf/pull/2489
```

ci(backport): Update CI permissions changes

---

tests/test_optim.py

Lower the tolerance for the `tests/test_optim.py` `test_optim_uncerts` test to reach agreement for `iminuit` `v2.26.0+` on Apple silicon.
```
* Lower the tolerance for the tests/test_optim.py test_optim_uncerts test
to reach agreement for iminuit v2.26.0+ on Apple silicon.
```

test: Lower tolerance for iminuit v2.26.0+ on Apple silicon

---

docs/conf.py
docs/contributors.rst
docs/index.rst
pyproject.toml

This is a simple conversion of the documentation pages to the PyData Sphinx Theme using the default configurations for the theme.
From the documentation for the theme (https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/readthedocs.html#version-switcher) the version switcher from readthedocs should still work after this is done (but won't show up before the PR is merged). If you want to use the version switcher of the PyData Sphinx Theme instead, it would require having urls for all of the previous versions of the library and one json file mapping urls to versions. This would also enable using the Version warning banner from the PyData theme itself: https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/announcements.html#version-warning-banners
Closes #2512 
- [N/A] …

docs: Change docs theme to PyData Sphinx theme

---

tests/conftest.py

As `setuptools` is not the build backend there should be no reliance on `setuptools` or `distutils` for use. This exchanges `setuptools._distutils.dir_util.copy_tree` for `shutil.copytree` with `dirs_exist_ok=True` as pyhf supports Python 3.8+.
Follows up on an idea brought forward in PR https://github.com/scikit-hep/pyhf/pull/1711.
```
* As setuptools is not the build backend there should be no reliance on
setuptools or distutils for use. This exchanges
setuptools._distutils.dir_util.copy_tree for shutil.copytree with
dirs_exist_ok=True as pyhf supports Python 3.8+.
```

fix: Use shutil.copytree over setuptools._distutils

---

.github/workflows/bump-version.yml
.github/workflows/ci-windows.yml
.github/workflows/ci.yml
.github/workflows/dependencies-head.yml
.github/workflows/docs.yml
.github/workflows/notebooks.yml
.github/workflows/release_tests.yml
docker/Dockerfile
docker/gpu/Dockerfile

Remove `setuptools` installs and upgrades from CI workflows and the Dockerfile build as it should not be required by any component of `pyhf`.
```
* Remove setuptools installs and upgrades from CI workflows and the
Dockerfile build as it should not be required by any component of pyhf.
```

ci: Remove setuptools uprgrade as no longer backend

---

src/pyhf/tensor/jax_backend.py

* Change the argument name in `jax.numpy.percentile` from `'interpolation'` to `'method'`. No change to the lower bounds on `jax` and `jaxlib` is required as `'method'` already existed as an argument in `jax` `v0.4.1`. This just deprecates the use of `'interpolation'`.
- Avoids the following DeprecationWarning in `jax` `v0.4.29+`:
```
DeprecationWarning: The interpolation= argument to 'percentile' is deprecated. Use 'method=' instead.
```
- c.f. https://github.com/google/jax/pull/21267
The CI is failing given another `DeprecationWarning` fixed in PR https://github.com/scikit-hep/pyhf/pull/2523.
```
* Change the argument name in jax.numpy.percentile from 'interpolation' to 'method'.
No change to the lower bounds on jax and jaxlib is required as 'method' already …
```

feat: Use 'method' arg for jax.numpy.percentile

---

pyproject.toml

Add an ignore to filterwarnings to avoid a DeprecationWarning on jax.xla_computation in jax v0.4.30+.
```
DeprecationWarning: jax.xla_computation is deprecated. Please use the AOT APIs.
```
c.f. https://github.com/google/jax/pull/21923
```
* Add an ignore to filterwarnings to avoid a DeprecationWarning
on jax.xla_computation in jax v0.4.30+.
> DeprecationWarning: jax.xla_computation is deprecated.
> Please use the AOT APIs.
- c.f. https://github.com/google/jax/pull/21923
```

fix: Add filterwarnings for jax.xla_computation DeprecationWarning

---

.github/workflows/bump-version.yml
.github/workflows/ci-windows.yml
.github/workflows/ci.yml
.github/workflows/dependencies-head.yml
.github/workflows/docs.yml
.github/workflows/lower-bound-requirements.yml
.github/workflows/notebooks.yml
.github/workflows/release_tests.yml
docker/Dockerfile

* Remove upgrading of wheel from CI workflows.
- For dependencies that don't provide a wheel, and don't have `build-system` metadata in `pyproject.toml`, modern `setuptools` has integrated `wheel` and so installation is unnecessary.
- c.f. https://github.com/pypa/setuptools/pull/3859
* Remove `uv pip install --system --upgrade pip` as `uv pip` is a different program.
```
* Remove upgrading of wheel from CI workflows.
- For dependencies that don't provide a wheel, and don't have build-system
metadata in pyproject.toml, modern setuptools has integrated wheel and so
installation is unnecessary.
* Remove 'uv pip install --system --upgrade pip' as 'uv pip' is a different
program.
```

ci: Remove upgrade of wheel

---

docker/Dockerfile
docker/gpu/Dockerfile

* Apply revisions to Dockerfile from Docker build checks.
- https://docs.docker.com/reference/build-checks/from-as-casing/
- https://docs.docker.com/go/dockerfile/rule/undefined-var/
- https://docs.docker.com/go/dockerfile/rule/legacy-key-value-format/
```
* Apply revisions to Dockerfile from Docker build checks.
- https://docs.docker.com/reference/build-checks/from-as-casing/
- https://docs.docker.com/go/dockerfile/rule/undefined-var/
- https://docs.docker.com/go/dockerfile/rule/legacy-key-value-format/
```

chore: Apply Docker build check corrections

---

docs/conf.py
docs/contributors.rst
pyproject.toml

I think one of the difference is it will point toward uproot stable instead of latest (which is the dev version).
- No, but expected.
```
* Add intersphinx_registry to 'docs' extra.
* Use intersphinx_registry to provide automated inter Sphinx mapping.
- c.f. https://github.com/Quansight-labs/intersphinx_registry
* Add Matthias Bussonnier to contributors list.
```

docs: Use intersphinx_registry to keep intersphinx urls up to date
