scikit-hep/pyhf

pyhf/__init__.py, tests/test_validation.py
of the parameters (for now) is determined by hfpdf.__init__ and so
the bounds are a priori not easy to set from the outside
=> added suggested parameter settings (init, bounds) since the order

binder/requirements.txt
https://github.com/nteract/papermill
=> Add papermill to Binder requirements.txt

.travis.yml
Following the .travis.yml from PyTorch vision repo:
c.f. https://github.com/pytorch/vision/blob/master/.travis.yml
=> Add conda environment to test PyTorch

pyhf/__init__.py, pyhf/tensor/tensorflow_backend.py, setup.py, tests/test_tensor.py
this is WIP and code is completely courtesy of @pablodecm (manually pasted from https://github.com/pablodecm/pyhf/blob/tensorflow/pyhf/tensor/tensorflow_backend.py ) 
I changed the `tolist` method a bit to work. The backend can optionally receive a TF session object, which will then be called in `tolist()` to actually run the graph and return the result. This makes the initial tests in test_tensor.py pass
=> [WIP] tensorflow backend

pyhf/__init__.py, tests/test_tensor.py
=> shapesys eval test

examples/experiments/edwardpyhf.ipynb
This adds an example of how to use edward to sample the a minmal version of HF-like pdf's.. this could be useful as a reference for an actual toy-based implementation
=> example of sampling via edward

pyhf/__init__.py, tests/test_pdf.py
* these were relics from earlier times. this is all in tensorlib now
=> remove stat shims _gaussian_impl _poisson_impl

pyhf/__init__.py, pyhf/optimize/__init__.py, pyhf/tensor/__init__.py, tests/benchmarks/test_benchmark.py, tests/test_backend_consistency.py, tests/test_optim.py
* moves tensor and optimzer import into their respective __init__.py
=> simplify import structure

validation/spec.json
Needed to complete #119 (`spec_2bin_2channel_coupledshapefactor`)
=> Add shapefactor to accepted modifications

pyhf/readxml.py, tests/test_import.py
this adds StatError import (for now only via GetBinError route)
=> staterror for XML import

pyhf/__init__.py, pyhf/tensor/mxnet_backend.py, pyhf/tensor/numpy_backend.py, pyhf/tensor/pytorch_backend.py, pyhf/tensor/tensorflow_backend.py, tests/test_tensor.py
=> Add tensor clipping

pyhf/modifiers/histosys.py
The suggested "nominal" value for HistoSys is 0
=> fix histosys suggested init

binder/postBuild
Make binder postBuild install editable.
=> make installation editable

.travis.yml, docs/development.rst, docs/index.rst, setup.py
This PR adds a `development` docs with a short blurb about how to `pip` install for full-suite development
```
pip install -e .[develop,tensorflow,mxnet,torch]
```
and also updates `setup.py` to freeze down some of the necessary versions to ensure that things are installed correctly.
Closes #162.
=> fix up some of the package versioning. add docs on development installation

pyhf/commandline.py
Trivial fix to actually print the JSON result of the conversion to stdout
=> Print the JSON dump

pyhf/commandline.py, pyhf/readxml.py, tests/test_scripts.py
addresses #204 
both the pipe and the read from file work
=> add cls command to cli

pyhf/modifiers/__init__.py, pyhf/modifiers/histosys.py, pyhf/modifiers/normsys.py, pyhf/modifiers/shapesys.py, pyhf/modifiers/staterror.py, tests/test_modifiers.py
This PR attempts to optimize the internal calculations being made by grouping the modifiers into *meta-modifiers* instead to perform the calculations. This is discussed somewhat heavily in #150.
=> Feature: specify a modifier's pdf type

MANIFEST.in
=> Use correct path for MANIFEST.in

.travis.yml, pyhf/readxml.py, pyhf/tensor/mxnet_backend.py, pyhf/tensor/numpy_backend.py, pyhf/tensor/pytorch_backend.py, pyhf/tensor/tensorflow_backend.py, pytest.ini, setup.py, tests/test_interpolate.py, tests/test_tensor.py
Please first read [CONTRIBUTING.md](https://github.com/diana-hep/pyhf/tree/master/CONTRIBUTING.md).
This PR is to help get ready for #285 by making it more manageable. This will add the necessary functionality into the backends, fixes up coverage, and cleans up `test_tensor.py`.
Add necessary functionality into the backends, such as gather, shape, and reshape -- to get fully ready for the full refactor of tensorizing the code.
=> Updates the backend to get ready for full refactor

pyhf/optimize/opt_pytorch.py, pyhf/optimize/opt_tflow.py
This PR is to help get ready for #285 by making it more manageable. Update optimizers to allow for constrained fits with a configurable number of iterations and handle exceptions better/more appropriately.
This is a much smaller PR.
Update optimizers to allow for constrained fits with a configurable number of iterations.
=> Update optimizers to allow for custom iterations for constrained fits

.travis.yml, pyhf/tensor/tensorflow_backend.py, setup.py, tests/test_notebooks.py
[TensorFlow Probability](https://www.tensorflow.org/probability/) is going to be where all developments for probabilistic distributions and sampling in TensorFlow will be implemented, so it is important to switch to using it over the `contrib` modules.
There are additional issues with Travis and memory footprints that this PR exposes, and may need to be resolved in another PR as they go beyond this scope. Resolves #297.
=> Use TensorFlow Probability for distributions

pyhf/constraints.py, pyhf/modifiers/__init__.py, pyhf/modifiers/histosys.py, pyhf/modifiers/normsys.py, pyhf/modifiers/shapesys.py, pyhf/modifiers/staterror.py, pyhf/pdf.py, tests/test_constraints.py, tests/test_modifiers.py, tests/test_pdf.py
Another PR to split up #285. This factors out the constraint pdf computation from the modifiers
=> combined constraints

pyhf/commandline.py
Resolves #306 
The PR title should suffice
=> Add --version option to the CLI

pyhf/constraints.py, pyhf/modifiers/__init__.py, pyhf/modifiers/histosys.py, pyhf/modifiers/normfactor.py, pyhf/modifiers/normsys.py, pyhf/modifiers/shapefactor.py, pyhf/modifiers/shapesys.py, pyhf/modifiers/staterror.py, pyhf/paramsets.py, pyhf/pdf.py, tests/test_constraints.py, tests/test_modifiers.py
This PR will separate modifier and contraint codes since some modifiers can share the same constraint (e.g. the qualify_names issue)
=> begin separation of constraints and modifiers

pyhf/constraints.py, pyhf/modifiers/histosys.py, pyhf/modifiers/normsys.py, pyhf/modifiers/shapesys.py, pyhf/modifiers/staterror.py, tests/test_constraints.py
This continues to separate paramsets and modifiers 
=> continue separating mods / parsets

pyhf/modifiers/staterror.py, pyhf/paramsets.py, tests/test_constraints.py, tests/test_modifiers.py
removes the alphas(..) method on paramsets
=> remove unneeded methods

.ackrc, pyhf/pdf.py, tests/test_pdf.py
This is to aid #285. Add additional information on the PDF config to aid with refactoring.
=> Add additional pdf information to aid with refactoring

docs/bib/use_citations.bib, docs/citations.rst, docs/index.rst
Resolves #315 
The PR title should suffice
=> Add citations and use cases to website

setup.py
Resolves #331
Add `bumpversion` to dependencies for develop
> Add `bumpversion` to dependencies for develop
=> Add bumpversion to dependencies for develop

docs/conf.py, docs/faq.rst, docs/index.rst, setup.py
Add a FAQ section to the website that covers questions and troubleshooting.
=> Add a FAQ to the website

pyhf/optimize/opt_minuit.py
iminuit was spitting out a lot of warnings as we were relying on a bunch of defaults.. this now explicitly sets them.
```
* set iminuit defaults for stepsize, ncalls and errordef
```
=> reduce iminuit warnings

.travis.yml
#374 didn't do what it claimed to do. Hopefully this one is more honest.
```
Move the after_success back to the matrix, and skip after_success on all non-matrix jobs.
```
=> Get the coveralls working again (really, really)

docs/bib/talks.bib
This adds the gaussian process talk to the bibliography that lukas gave at the CERN ML Fora today.
(no summary needed)
=> add Gaussian Process talk by lukas

README.md, docs/examples.rst
Updates the badge design for the "launch Binder" badges in the `README` and on the examples webpage to the [new default badge](https://discourse.jupyter.org/t/help-us-choose-an-updated-launch-binder-badge/100).
```
Updates the badge design for the "launch Binder" badges in the `README` and on the examples webpage
c.f. https://discourse.jupyter.org/t/help-us-choose-an-updated-launch-binder-badge/100
```
=> Update launch Binder badge to new default design

tests/test_tensor.py
Resolves #288
```
* Correct test name typo where test_ones tested the zeroes method and vise versa
* Explicitly check that the behavior of 0 in tensors matches other numbers
```
=> Add tensor shape tests for behavior of 0

README.md
Resolves #421 
[CodeFactor](https://www.codefactor.io/) provides an overall code-grade. [![CodeFactor](https://www.codefactor.io/repository/github/diana-hep/pyhf/badge)](https://www.codefactor.io/repository/github/diana-hep/pyhf)
This addition was inspired after seeing its use on the [zfit repo](https://github.com/zfit/zfit)
```
* Add CodeFactor overall code-grade badge to README
- c.f. https://www.codefactor.io/
```
=> Add codefactor.io badge

.travis.yml
Resolves #425 
```
- Add test deployment to TestPyPI for every commit to master to test real PyPI deployment
c.f. https://test.pypi.org/project/pyhf/
```
=> Add test deploy to TestPyPI

README.md
For the [Optimizers table](https://github.com/diana-hep/pyhf/blob/ba9f24317381dffd116bd7669aab157b795389cf/README.md#what-does-it-support) choose left alignment so that the actual optimizer names are aligned
```
- Choose left alignment for the Optimizers table so that the actual optimizer names are aligned
```
=> Use consistent column alignment in Markdown tables

docs/bib/posters.bib, docs/bib/talks.bib, docs/talks.rst
Resolves #447 
Please describe the purpose of this pull request in some detail. Reference and link to any relevant issues or pull requests.
```
- Add posters section to the talks page in the docs and corresponding BibTeX file
- Add ACAT 2019 pyhf poster given by Lukas
- Add guards on BibTeX title listings to ensure intended case of letters
```
=> Add ACAT 2019 poster to talks page

docs/likelihood.rst
Correct names in documentation text to reflect those used in example code
```
* Correct names in documentation text to reflect those used in example code
```
=> Correct mismatch in names between example and text

src/pyhf/exceptions/__init__.py, src/pyhf/interpolators/code4.py, src/pyhf/modifiers/__init__.py, src/pyhf/modifiers/histosys.py, src/pyhf/modifiers/normsys.py, src/pyhf/paramsets.py, src/pyhf/pdf.py, src/pyhf/tensor/mxnet_backend.py, src/pyhf/tensor/pytorch_backend.py, src/pyhf/tensor/tensorflow_backend.py, src/pyhf/writexml.py, tests/test_import.py, tests/test_modifiers.py, tests/test_validation.py, validation/shared_nuispar_across_types/make_data.py
This is simply a cleaning PR that goes through and addresses most of the "issues" that CodeFactor finds (though it leaves all the cylic import issues because those [can't be dealt with as long as we still have Python 2](https://github.com/diana-hep/pyhf/issues/469#issuecomment-511637392)).
```
* Apply recommended changes from CodeFactor's pylint linter
- Removal of unnecessary pass
- Removal of unnecessary return (Python returns None if there is no return statement)
- Removal of len to check if list or dict is empty (empty arrays and empty dict evaluate to False in Python)
- Use 'is' for singleton comparison (c.f. https://www.python.org/dev/peps/pep-0008/#programming-recommendations)
```
=> Apply recommended changes for CodeFactor issues

src/pyhf/tensor/mxnet_backend.py, src/pyhf/tensor/numpy_backend.py, src/pyhf/tensor/pytorch_backend.py, src/pyhf/tensor/tensorflow_backend.py, tests/test_tensor.py
broken out of #519 to add tile method
```
* Add 'tile' method to the NumPy, TensorFlow, PyTorch, and MxNet tensor backends
* Add tests for 'tile' and 'normal_logpdf'
```
=> Add 'tile' method to tensorlib API

docs/examples/notebooks/binderexample/StatisticalAnalysis.ipynb, src/pyhf/paramsets.py, src/pyhf/pdf.py, src/pyhf/simplemodels.py, tests/test_pdf.py, tests/test_validation.py
this builds on PR #519 to enable full batch evaluation
```
* Add ability to do batched evaluation
* pdf.logpdf(pars, data), where pars.shape = (B,N) with B==pdf.batch_size and N==len(pdf.config.suggested_config())
* Add test to expose bug in constrained_by_poisson.expected_data
* Add fix for bug in constrained_by_poisson.expected_data
* Relax tolerance in validation (suspect it's due to order of moving python arrays to tensors)
* Add arg in hepdata_like to return batched model
* Rename 'thenom' to 'nominal_rates'
```
=> Enable full batch evaluation

CONTRIBUTING.md
adds https://github.com/probot/semantic-pull-requests configuration file. Ensures minimal level of good habits abour PR titles and/or commit msgs
```
feat: add semantic PR 
```
=> feat: add semantic PR

src/pyhf/interpolators/code2.py, src/pyhf/pdf.py, src/pyhf/tensor/tensorflow_backend.py, validation/manualonoff_roofit/onoff.py
The LGTM scans [reveal a few warnings](https://lgtm.com/projects/g/diana-hep/pyhf/alerts/?mode=list&severity=warning) that are easy to fix. This simply addresses them. 
```
* fix: Correct the warnings that are raised by the LGTM scans
```
=> fix: Correct warnings raised by LGTM scan

src/pyhf/tensor/numpy_backend.py, src/pyhf/tensor/pytorch_backend.py, src/pyhf/tensor/tensorflow_backend.py, tests/test_tensor.py
In support of PR #534 add `conditional` method ~~, `less`, and `greater` methods~~ to tensorlib API. Also add tests for them.
**TODO:**
```
* Add 'conditional' method to the NumPy, TensorFlow, and PyTorch tensor backends
* Add tests for 'conditional'
* Add tests for overloaded operators on tensor operations that would be the equivalent of 'add', 'subtract', 'less', and 'greater'
```
=> feat: Add 'conditional' method to tensorlib API

README.md, docs/api.rst, docs/examples/notebooks/binderexample/StatisticalAnalysis.ipynb, docs/talks.rst
See #676.
```
* Rename statistics to inference
* Correct capitalization in arXiv
```
=> docs: Rename statistics to inference in API key

docs/bib/use_citations.bib
Resolves #586
```
* Add ATLAS PUB note on likelihood serialization to pyhf use citations
- c.f. https://cds.cern.ch/record/2684863
```
=> docs: Add ATLAS likelihood PUB note to use citations

.bumpversion.cfg, setup.py, src/pyhf/version.py
Cut a new release to allow for the string aliases in PR #672 to be used.
```
* Cut a patch release to allow for setting the backend with a string alias
```
=> feat: Bump version: 0.3.0 → 0.3.1

.github/workflows/ci.yml, src/pyhf/interpolators/__init__.py, src/pyhf/interpolators/code0.py, src/pyhf/interpolators/code1.py, src/pyhf/interpolators/code2.py, src/pyhf/interpolators/code4.py, src/pyhf/interpolators/code4p.py
Adds Docstrings for Interpolators. `pydocstyle` passes.
```
* Add docstrings for interpolators module
* Add interpolators module to pydocstyle test
```
=> docs: Add docstrings for interpolators

.github/workflows/ci.yml, tests/conftest.py, tests/contrib/test_viz.py, tests/test_events.py, tests/test_export.py, tests/test_import.py, tests/test_infer.py, tests/test_interpolate.py, tests/test_modifiers.py, tests/test_pdf.py, tests/test_utils.py, tests/test_workspace.py
Resolves #670 
Cleanup test files to have them pass pyflakes. Also add the `tests/` directory to the pyflakes linting in the CI.
```
* Make the tests pass pyflakes
* Add testing of 'pyflakes tests/' to the CI
```
=> chore: Make tests pass pyflakes

src/pyhf/infer/utils.py
Another PR in the series to get to #709 . This slightly rearranges the Cls computation in order to make the upcoming calculator PR cleaner / more trackable where those changes came from.
```
* Reorder CLs computation in 'pvals_from_teststat' for greater clarity in upcoming calculator PR
```
=> refactor: rearrange asymptotics

README.md
As agreed upon in [discussion with the other members of Scikit-HEP](https://github.com/scikit-hep/scikit-hep.github.io/issues/36), Scikit-HEP projects should have a badge at the top of their README that links to the Scikit-HEP homepage. This should raise visibility of the project and help people associate different project libraries together.
[![Scikit-HEP][sk-badge]](https://scikit-hep.org/)
[sk-badge]: https://img.shields.io/badge/Scikit--HEP-Project-blue?logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABoAAAAcCAYAAAB/E6/TAAAACXBIWXMAAAEZAAABGQHyCY1sAAAAGXRFWHRTb2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAAA6dJREFUSImdlktonFUUx/930kQ0nYo2JX5NUqSghSq2oIgvcCFaC0EEH2AXUh9FEV1UUaGIC924qY8igo+FQi26sWp8gDS24qOgCOIiKCVomLlnZpxk7Dh2GjMz389F7tgv4zfNJGdzh/M/5/zuud/ch9MKDFgnaUjSnHOu2kuOmb0h6brMMoVHgce …
=> docs: Add Scikit-HEP Project badge to README

setup.py, src/pyhf/modifiers/__init__.py
Resolves #797.
```
* Six is a Python 2/3 compatibility library and not needed for Python3-only packages
```
=> build: Remove dependency on six package

.github/workflows/ci.yml, .github/workflows/publish-docker.yml
It is a better idea to exactly test the workflows that will be run during merges to `master` and publication to Docker Hub, so use the official Docker GitHub Action for all Docker builds. Additionally switch syntax in `if` statements from
```yaml
if: "! ${{ startsWith(github.ref, 'refs/tags/') }}"
```
to
```yaml
if: "!(startsWith(github.ref, 'refs/tags/'))"
```
as the former was causing issues and [`${{ }}` syntax is ignored in `if` statements](https://twitter.com/joshmgross/status/1241088248572776451).
```
* Use the same Docker build workflow in testing as is used in publication to Docker Hub
- Amends PR #808
* Use suggested () syntax as ${{ }} is ignored in 'if' statements
- https://twitter.com/joshmgross/status/1241088248572776451
```
=> ci: Use the same Docker workflow for testing as publication

.github/workflows/ci.yml, docker/Dockerfile
Add `curl` to the Docker image to improve its usefulness. Also add some simple test checks to the Docker image build stage.
PR #825 should go in before this.
```
* Add curl to Docker image
* Add test check to the Docker build CI
```
=> feat: Add curl to Docker image

setup.py
Update [`papermill`](https://github.com/nteract/papermill) to v2.X.Y releases. This is done only to track development improvements and not because there is a need to update due to bugs.
```
* Update papermill to use v2.X.Y releases
```
=> chore: Update papermill to use v2 releases

src/pyhf/cli/infer.py, src/pyhf/cli/rootio.py, src/pyhf/cli/spec.py, src/pyhf/mixins.py, src/pyhf/workspace.py
Fixes #865. @alexander-held
```
* Remove setting logging.basicConfig()
- Makes the user fully responsible for setting the log info level
```
=> fix: Allow users to set logging level

docs/bib/HEPData_likelihoods.bib
Add the 1Lbb HEPData record released: https://www.hepdata.net/record/ins1755298 .
```
* Add 1Lbb hepdata record with patchset likelihoods
- c.f. https://www.hepdata.net/record/ins1755298
```
=> docs: Add 1Lbb hepdata likelihood record

CONTRIBUTING.md
To help orient people towards creating high quality contributions add examples of good PRs to `CONTRIBUTING.md`. We can start by adding PR #902 which was _excellent_.
```
* Add examples of high quality PRs to CONTRIBUTING.md
- Start with PR #902 by @nikoladze
```
=> docs: Add examples of good contributions to CONTRIBUTING

src/pyhf/infer/mle.py
Resolves #957.
```
* clarify the objective function in infer.mle.fit and infer.mle.fixed_poi_fit
```
=> docs: Clarify objective function in infer.mle

README.rst
Add the Conda-forge release version badge to the README
[![Conda Version](https://img.shields.io/conda/vn/conda-forge/pyhf.svg)](https://anaconda.org/conda-forge/pyhf)
ReadTheDocs build: https://pyhf.readthedocs.io/en/docs-add-conda-forge-badge
```
* Add Conda-forge release version badge to README
- c.f. https://anaconda.org/conda-forge/pyhf
```
=> docs: Add Conda-forge release version badge

src/pyhf/cli/cli.py, src/pyhf/cli/spec.py, src/pyhf/workspace.py, tests/test_scripts.py, tests/test_workspace.py
Resolves #805. Incorporates and resolves #1033. 
```
* Add utility to sort a workspace
* Add CLI for sorting a workspace
* Add tests for sorting a workspace
```
=> feat: Add pyhf.Workspace.sorted to give ability to sort Workspace

src/pyhf/parameters/paramsets.py, src/pyhf/pdf.py, src/pyhf/workspace.py, tests/test_paramsets.py
This closes #1108.
```
* Rename paramset.fixed to paramset.suggested_fixed to harmonize the API more
```
=> refactor: Rename paramset.fixed to paramset.suggested_fixed

CONTRIBUTING.md
Update `CONTRIBUTING.md` to note the importance of Issues for communicating with the dev team.
```
* Note importance of Issues to communicating with the dev team
* Update terminology from WIP to Drafts
* Clarify pull request procedure
```
=> docs: Add importance of Issues to CONTRIBUTING.md

src/pyhf/workspace.py, tests/test_workspace.py
Fixes #1127 
```
* Perform a deep copy of the spec to make workspaces imutable
* Add test of workspace immutability
```
=> fix: Make workspaces immutable

src/pyhf/tensor/jax_backend.py, src/pyhf/tensor/numpy_backend.py, src/pyhf/tensor/pytorch_backend.py, src/pyhf/tensor/tensorflow_backend.py, tests/test_tensor.py
This will be needed for the `toycalc` PR #790. Essentially provide `ravel` following the `numpy` API to provide a flattened view of the tensor.
ReadTheDocs build:
- https://pyhf.readthedocs.io/en/feat-tensorlibravel/
- https://pyhf.readthedocs.io/en/feat-tensorlibravel/_generated/pyhf.tensor.numpy_backend.numpy_backend.html#pyhf.tensor.numpy_backend.numpy_backend.ravel
- https://pyhf.readthedocs.io/en/feat-tensorlibravel/_generated/pyhf.tensor.pytorch_backend.pytorch_backend.html#pyhf.tensor.pytorch_backend.pytorch_backend.ravel
- https://pyhf.readthedocs.io/en/feat-tensorlibravel/_generated/pyhf.tensor.tensorflow_backend.tensorflow_backend.html#pyhf.tensor.tensorflow_backend.tensorflow_backend.ravel
- https://pyhf.readthedocs.io/en/feat-tensorlibravel/_generated/pyhf.tensor.jax_backend.ja …
=> feat: Tensorlib ravel functionality

docs/bib/tutorials.bib
Add tutorial link for atlas SUSY+Exotics workshop given a month ago or so.
```
* Add tutorial for ATLAS SUSY+Exotics 2020 workshop
- c.f.: https://indico.cern.ch/event/898965/
```
=> docs: Add ATLAS SUSY+Exotics Tutorial

src/pyhf/cli/rootio.py, src/pyhf/contrib/cli.py, src/pyhf/contrib/utils.py, src/pyhf/optimize/mixins.py, src/pyhf/tensor/jax_backend.py, src/pyhf/tensor/numpy_backend.py, src/pyhf/tensor/pytorch_backend.py, src/pyhf/tensor/tensorflow_backend.py, src/pyhf/workspace.py
This will resolve #1195.
```
* Use exc_info in log.error to show error + message
* Use raise without arguments to re-raise last raised exception
```
=> chore: Use exc_info in log.error, re-raise last exceptions

setup.py, src/pyhf/optimize/opt_minuit.py, tests/test_optim.py
Resolves #1166 
Adopt the new `iminuit` `v2.0` API.
```
* Require iminuit release compatible with v2.1
* Migrate to iminuit v2.0 API
```
=> feat: Use iminuit v2.0 API

setup.py
Resolves #1260 
- Remove duplicated `jsonpatch`
- Remove `coverage`
```
* Remove jsonpatch in test extra as it is a core dependency and so in setup.cfg
* Remove coverage in test extra as no longer needed
- Required by Coveralls service, which is no longer used
```
=> chore: Remove duplicated and unused dependencies

src/pyhf/pdf.py, tests/test_pdf.py
Resolves #1098.
```
* Pass in the spec directly to _ModelConfig and store a deep-copy unchanged version on Model
* Resolve bug where the spec was being modified downstream via parameter.pop()
-  fix: change pop -> get
```
=> fix: Model.spec should be self-consistent and reproducible

CONTRIBUTING.md
Add a little syntax highlighting to make snippets prettier :)
```
* Add bash syntax highlighting to command line examples in CONTRIBUTING.md 
```
=> docs: Add syntax highlighting for bash snippets

codemeta.json
The `codemeta.json` needs to be updated to match all the requirements of the new release. This should get added to a developer release checklist. For now, update the `codemeta.json` with the latest updates.
```
* Update codemeta.json software requirements to match those of v0.6.0
```
=> chore: Update codemeta to include v0.6.0 software requirements

docs/bib/use_citations.bib
Add citation
```
* Add use citation from 'Hunting wino and higgsino dark matter at the muon collider with disappearing tracks'
- c.f. https://inspirehep.net/literature/1848034
```
=> docs: Add use citation for wino and higgsino dark matter at  muon collider

docs/release-notes.rst, docs/release-notes/v0.6.1.rst
Resolves #1356 
```
* Add release notes for pyhf v0.6.1
- c.f. https://github.com/scikit-hep/pyhf/releases/tag/v0.6.1
```
=> docs: Add v0.6.1 release notes

.github/workflows/codeql-analysis.yml
Resolves #1381 
```
* Apply automated suggestions from CodeQL and remove git checkout HEAD^2 as no longer necessary
```
=> ci: Simplify CodeQL scan setup

src/pyhf/infer/calculators.py, src/pyhf/infer/test_statistics.py
Resolves #1630
```
* Merge split docstring examples into contiguous blocks to ensure the
copy button on examples gets full working code
* Apply Black to docstring examples
```
=> docs: Ensure docstring examples are contiguous

README.rst
Add 1000 project commits (with PR #1710) to the list of project milestones in the README. :tada: 
```
* Add milestone to README for 1000 project commits.
- 1000th commit came from Alexander Held in PR #1710.
```
=> docs: Add milestone for 1000 project commits to README

docs/bib/use_citations.bib
Add use citation from [Revisiting mono-τ tails at the LHC](https://inspirehep.net/literature/1998227) by Florentin Jaffredo.
```
* Add use citation from Revisiting mono-τ tails at the LHC by Florentin Jaffredo.
- c.f. https://inspirehep.net/literature/1998227
```
=> docs: Add use citation from revisiting mono-tau tails at the LHC paper

docs/bib/general_citations.bib
Add general use citation from [HL-LHC Computing Review Stage 2, Common Software Projects: Data Science Tools for Analysis](https://inspirehep.net/literature/2027698) by Jim Pivarski, Eduardo Rodrigues, Kevin Pedro, Oksana Shadura, Benjamin Krikler, Graeme A. Stewart.
```
* Add general use citation from 'HL-LHC Computing Review Stage 2, Common
Software Projects: Data Science Tools for Analysis'.
- c.f. https://inspirehep.net/literature/2027698
```
=> docs: Add citation from 'HL-LHC Computing Review Stage 2' paper

.github/workflows/ci.yml, .github/workflows/dependencies-head.yml, .github/workflows/docs.yml, .github/workflows/lint.yml, .github/workflows/lower-bound-requirements.yml, .github/workflows/notebooks.yml, .github/workflows/publish-package.yml, .github/workflows/release_tests.yml, .github/workflows/tag.yml
Use [v3 of the setup-python GitHub Action](https://github.com/actions/setup-python/releases/tag/v3.0.0).
```
* Use actions/setup-python v3 for all workflows.
- c.f. https://github.com/actions/setup-python/releases/tag/v3.0.0
```
=> ci: Use actions/setup-python v3

docs/bib/general_citations.bib
Add general use citation from [Survey of Open Data Concepts Within Fundamental Physics: An Initiative of the PUNCH4NFDI Consortium](https://doi.org/10.1007/s41781-022-00081-7). @lukasheinrich is an author on the paper.
```
* Add general citation from 'Survey of Open Data Concepts Within Fundamental
Physics: An Initiative of the PUNCH4NFDI Consortium'.
- c.f. https://doi.org/10.1007/s41781-022-00081-7
```
=> docs: Add general use citation from Survey of Open Data Concepts paper

.github/workflows/semantic-pr-check.yml
As https://github.com/zeke/semantic-pull-requests is no longer maintained and is down (c.f. https://github.com/zeke/semantic-pull-requests/issues/183#issuecomment-1137844183), use the suggested alternative of https://github.com/amannn/action-semantic-pull-request to check that PR titles follow the Conventional Commits spec.
```
* As https://github.com/zeke/semantic-pull-requests is no longer maintained
and is down, use the suggested alternative of
https://github.com/amannn/action-semantic-pull-request to check that PR titles
follow the Conventional Commits spec.
```
=> ci: Add semantic PR check GHA workflow

.zenodo.json, CITATION.cff
@matthewfeickert is a postdoc at University of Wisconsin-Madison as of June 2022.
```
* Matthew Feickert is a postdoc at University of Wisconsin-Madison as of June 2022.
```
=> docs: Update Matthew's affiliation to University of Wisconsin-Madison

.github/workflows/bump-version.yml, .github/workflows/ci.yml, .github/workflows/dependencies-head.yml, .github/workflows/docs.yml, .github/workflows/lint.yml, .github/workflows/lower-bound-requirements.yml, .github/workflows/notebooks.yml, .github/workflows/publish-package.yml, .github/workflows/release_tests.yml
* Use actions/setup-python v4 for all workflows.
- c.f. https://github.com/actions/setup-python/releases/tag/v4.0.0
```
* Use actions/setup-python v4 for all workflows.
- c.f. https://github.com/actions/setup-python/releases/tag/v4.0.0
```
=> chore: Use actions/setup-python v4

docs/bib/use_citations.bib
* Add use citation from [Search for pair production of Higgs Bosons decaying to four bottom quarks with data collected by the ATLAS detector](https://inspirehep.net/literature/2085649).
- c.f. https://cds.cern.ch/record/2812193
- Ph.D. dissertation of @Lucas-Borgna
Belated congratulations Dr. Borgna! :tada: 
```
* Add use citation from 'Search for pair production of Higgs Bosons decaying
to four bottom quarks with data collected by the ATLAS detector'.
- c.f. https://inspirehep.net/literature/2085649
- c.f. https://cds.cern.ch/record/2812193
- Ph.D. dissertation of Lucas Santiago Borgna
```
=> docs: Add use citation from Lucas Santiago Borgna's Ph.D. thesis

src/pyhf/infer/calculators.py
Resolves #1335.
```
* Harmonize the docstring for test_stat between AsymptoticCalculator and ToyCalculator.
```
=> docs: Harmonize docstring for test_stat in ToyCalculator

codemeta.json
* Update scipy lower bound to v1.2.0 to match lower bound in setup.cfg.
- Amends PR #1274
```
* Update scipy lower bound to v1.2.0 to match lower bound in setup.cfg.
- Amends PR #1274
```
=> chore: Update codemeta.json for scipy lower bounds

src/pyhf/tensor/jax_backend.py, src/pyhf/tensor/numpy_backend.py, src/pyhf/tensor/pytorch_backend.py, src/pyhf/tensor/tensorflow_backend.py
Add `.. versionadded` to `transpose` and `percentile` methods.
Addresses part of Issue #1910.
```
* Add versionadded sphinx directive to transpose and percentile tensorlib methods.
```
=> docs: Add versionadded to new tensorlib methods

docs/bib/use_citations.bib
* Add use citation from 'A global approach to physics beyond the Standard Model'.
- c.f. https://inspirehep.net/literature/2157017
- Ph.D. dissertation of Guilherme Luis De Sousa Fihalo Guedes
```
* Add use citation from 'A global approach to physics beyond the Standard Model'.
- c.f. https://inspirehep.net/literature/2157017
- Ph.D. dissertation of Guilherme Luis De Sousa Fihalo Guedes
```
=> docs: Add use citation from Guilherme Luis De Sousa Fihalo Guedes Ph.D. thesis

docs/bib/general_citations.bib
* Add general citation from [Second Analysis Ecosystem Workshop Report](https://inspirehep.net/literature/2612625).
```
* Add general citation from 'Second Analysis Ecosystem Workshop Report'.
- c.f. https://inspirehep.net/literature/2612625
```
=> docs: Add general use citation from Second Analysis Ecosystem Workshop Report

docs/bib/use_citations.bib
Add use citation from [Phenomenology of the Higgs and Flavour Physics in the Standard Model and Beyond](https://inspirehep.net/literature/2615298), which is @alasfar-lina's Ph.D. dissertation. Congratulations Dr. Alasfar! :rocket: 
```
* Add use citation from 'Phenomenology of the Higgs and Flavour Physics in
the Standard Model and Beyond'.
- c.f. https://inspirehep.net/literature/2615298
- Ph.D. dissertation of Lina Alasfar
```
=> docs: Add use citation from Lina Alasfar's Ph.D. thesis

docs/bib/use_citations.bib
Add use citation from '[Simplified likelihoods using linearized systematic uncertainties](https://inspirehep.net/literature/2623097)' by @berger-nicolas. :+1: 
```
* Add use citation from 'Simplified likelihoods using linearized
systematic uncertainties'.
- c.f. https://inspirehep.net/literature/2623097
```
=> docs: Add use citation from Simplified Likelihoods with Linearized Systematics paper

docs/bib/general_citations.bib
Add general citation from [IRIS-HEP Strategic Plan for the Next Phase of Software Upgrades for HL-LHC Physics](https://inspirehep.net/literature/2628983
).
```
* Add general citation from 'IRIS-HEP Strategic Plan for the Next
Phase of Software Upgrades for HL-LHC Physics'.
- c.f. https://inspirehep.net/literature/2628983
```
=> docs: Add general use citation from IRIS-HEP Strategic Plan

docs/bib/use_citations.bib
Add use citation from [Unbinned Profiled Unfolding](https://inspirehep.net/literature/2631075) by @qwerasd903 and @bnachman.
```
* Add use citation from 'Unbinned Profiled Unfolding'.
- c.f. https://inspirehep.net/literature/2631075
```
=> docs: Add use citation from Unbinned Profiled Unfolding paper

.github/workflows/ci.yml, .github/workflows/publish-package.yml
If a PR is made to a patch release branch run the CI and the publish package GitHub Action workflows.
```
* If a PR is made to a patch release branch run the CI and
the publish package GitHub Action workflows.
```
=> ci: Run CI and packaging workflows on release branch PRs

src/pyhf/tensor/jax_backend.py
- PR https://github.com/scikit-hep/pyhf/pull/2079
- PR https://github.com/scikit-hep/pyhf/pull/2134
```
- PR https://github.com/scikit-hep/pyhf/pull/2079
- PR https://github.com/scikit-hep/pyhf/pull/2134
```
=> docs(backport): Update JAX backend docstring types to jax.Array

.github/workflows/bump-version.yml, .github/workflows/docker.yml
- PR https://github.com/scikit-hep/pyhf/pull/2154
- PR https://github.com/scikit-hep/pyhf/pull/2155
- PR https://github.com/scikit-hep/pyhf/pull/2156
```
- PR https://github.com/scikit-hep/pyhf/pull/2154
- PR https://github.com/scikit-hep/pyhf/pull/2155
- PR https://github.com/scikit-hep/pyhf/pull/2156
```
=> ci(backport): Add workflow input for bump version branch

.github/workflows/publish-package.yml, .pre-commit-config.yaml, src/pyhf/modifiers/lumi.py, src/pyhf/readxml.py, tests/test_scripts.py
- PR https://github.com/scikit-hep/pyhf/pull/2158
- PR https://github.com/scikit-hep/pyhf/pull/2159
```
- PR https://github.com/scikit-hep/pyhf/pull/2158
- PR https://github.com/scikit-hep/pyhf/pull/2159
```
=> chore(backport): Update pre-commit hooks and dependabot updates

docs/bib/general_citations.bib, docs/bib/use_citations.bib
* Backport:
- PR https://github.com/scikit-hep/pyhf/pull/2040
- PR https://github.com/scikit-hep/pyhf/pull/2063
- PR https://github.com/scikit-hep/pyhf/pull/2066
- PR https://github.com/scikit-hep/pyhf/pull/2082
- PR https://github.com/scikit-hep/pyhf/pull/2083
- PR https://github.com/scikit-hep/pyhf/pull/2089
- PR https://github.com/scikit-hep/pyhf/pull/2092
- PR https://github.com/scikit-hep/pyhf/pull/2094
- PR https://github.com/scikit-hep/pyhf/pull/2101
- PR https://github.com/scikit-hep/pyhf/pull/2107
- PR https://github.com/scikit-hep/pyhf/pull/2116
- PR https://github.com/scikit-hep/pyhf/pull/2120
- PR https://github.com/scikit-hep/pyhf/pull/2126
- PR https://github.com/scikit-hep/pyhf/pull/2127
- PR https://github.com/scikit-hep/pyhf/pull/2153
- PR …
=> docs(backport): Add use citations and general citations

tests/test_import.py, tests/test_optim.py, tests/test_patchset.py, tests/test_teststats.py, tests/test_utils.py, tests/test_workspace.py
Backport PR https://github.com/scikit-hep/pyhf/pull/2162
```
* Backport PR https://github.com/scikit-hep/pyhf/pull/2162
```
=> test(backport): Use pytest.raises match argument to check Error messages

docs/bib/HEPData_likelihoods.bib
Backport PR https://github.com/scikit-hep/pyhf/pull/2169
```
* Backport PR https://github.com/scikit-hep/pyhf/pull/2169
```
=> docs(backport): Add ATLAS search for gluinos in multi-b final states statistical model record

docs/bib/use_citations.bib
Backport PR https://github.com/scikit-hep/pyhf/pull/2171
```
* Backport PR https://github.com/scikit-hep/pyhf/pull/2171
```
=> docs(backport): Update use citations references to include journal publications

.zenodo.json, CITATION.cff, README.rst, codemeta.json, docs/generate_jupyterlite_iframe.py, docs/jupyterlite.rst, src/pyhf/data/citation.bib, src/pyhf/utils.py, tbump.toml
* Forward port the version bump information from release `v0.7.1` on the `release/v0.7.x` branch.
```
* Forward port the version bump information from release v0.7.1 on the
```
=> docs: Bump version: 0.7.0 → 0.7.1

docs/bib/use_citations.bib
* Backport:
- PR https://github.com/scikit-hep/pyhf/pull/2181
- PR https://github.com/scikit-hep/pyhf/pull/2199
- PR https://github.com/scikit-hep/pyhf/pull/2201
```
* Backport:
- PR https://github.com/scikit-hep/pyhf/pull/2181
- PR https://github.com/scikit-hep/pyhf/pull/2199
- PR https://github.com/scikit-hep/pyhf/pull/2201
```
=> docs(backport): Add use citations through April 2023

CONTRIBUTING.md, binder/postBuild, binder/runtime.txt, docs/development.rst, docs/examples/notebooks/learn/InterpolationCodes.ipynb, docs/installation.rst, docs/release-notes/v0.7.1.rst, src/pyhf/cli/complete.py, src/pyhf/cli/rootio.py, src/pyhf/contrib/cli.py, src/pyhf/contrib/utils.py, tests/test_scripts.py
Backport components of:
- PR https://github.com/scikit-hep/pyhf/pull/2046
- PR https://github.com/scikit-hep/pyhf/pull/2098
- PR https://github.com/scikit-hep/pyhf/pull/2113
- PR https://github.com/scikit-hep/pyhf/pull/2115
- PR https://github.com/scikit-hep/pyhf/pull/2145
- PR https://github.com/scikit-hep/pyhf/pull/2198
```
- PR https://github.com/scikit-hep/pyhf/pull/2046
- PR https://github.com/scikit-hep/pyhf/pull/2098
- PR https://github.com/scikit-hep/pyhf/pull/2113
- PR https://github.com/scikit-hep/pyhf/pull/2115
- PR https://github.com/scikit-hep/pyhf/pull/2145
- PR https://github.com/scikit-hep/pyhf/pull/2198
```
=> docs(backport): Add dev instructions and fix typos

.coveragerc, src/pyhf/tensor/numpy_backend.py
* Backport PR https://github.com/scikit-hep/pyhf/pull/2208
```
* Backport PR https://github.com/scikit-hep/pyhf/pull/2208
```
=> fix(backport): Add TYPE_CHECKING guard for numpy.typing

docs/release-notes.rst, docs/release-notes/v0.7.2.rst
Add v0.7.2 release notes
```
* Add release notes for pyhf v0.7.2.
```
=> docs: Add v0.7.2 release notes

.zenodo.json, CITATION.cff, README.rst, codemeta.json, docs/lite/jupyterlite.py, src/pyhf/data/citation.bib, src/pyhf/utils.py, tbump.toml
* Forward port the version bump information from release `v0.7.2` on the `release/v0.7.x` branch.
```
* Forward port the version bump information from release v0.7.2 on the
```
=> docs: Bump version: 0.7.1 → 0.7.2

docs/bib/use_citations.bib
Add use citation from [Investigation of Higgs Boson Decaying to Di-muon, Dark Matter Produced in Association with a Higgs Boson Decaying to b-quarks and Unbinned Profiled Unfolding](https://inspirehep.net/literature/2664141).
- Ph.D. dissertation of Jay Chan
```
* Add use citation from 'Investigation of Higgs Boson Decaying to Di-muon,
Dark Matter Produced in Association with a Higgs Boson Decaying to
b-quarks and Unbinned Profiled Unfolding'.
- c.f. https://inspirehep.net/literature/2664141
- Ph.D. dissertation of Jay Chan
```
=> docs: Add use citation from Jay Chan's Ph.D. thesis

docs/bib/use_citations.bib
Add use citation from [Reduce, Reuse, Reinterpret: an end-to-end pipeline for recycling particle physics results](https://inspirehep.net/literature/2669860) by @kratsg, Camila Aristimuno Ots, and @mhance. :tada: 
```
* Add use citation from 'Reduce, Reuse, Reinterpret: an end-to-end
pipeline for recycling particle physics results'.
- c.f. https://inspirehep.net/literature/2669860
```
=> docs: Add use citation from mapyde paper

docs/bib/use_citations.bib
Add use citation from [SModelS v2.3: enabling global likelihood analyses](https://inspirehep.net/literature/2673443) by Mohammad Mahdi Altakach, @sabinekraml, Andre Lessa, Sahana Narasimha, Timothée Pascal, @WolfgangWaltenberger. :rocket: 
```
* Add use citation from 'SModelS v2.3: enabling global likelihood
analyses'.
- c.f. https://inspirehep.net/literature/2673443
```
=> docs: Add use citation from SModelS v2.3 paper

.pre-commit-config.yaml
Update black pre-commit hook repo to faster https://github.com/psf/black-pre-commit-mirror.
Committed via https://github.com/asottile/all-repos
```
* Update black pre-commit hook repo to faster
https://github.com/psf/black-pre-commit-mirror.
```
=> chore: Use 2x faster black mirror

.github/workflows/docs.yml, .github/workflows/lint.yml, .github/workflows/lower-bound-requirements.yml, .github/workflows/publish-package.yml
- PR https://github.com/scikit-hep/pyhf/pull/2103
- PR https://github.com/scikit-hep/pyhf/pull/2237
- PR https://github.com/scikit-hep/pyhf/pull/2248
- PR https://github.com/scikit-hep/pyhf/pull/2254
- PR https://github.com/scikit-hep/pyhf/pull/2275
```
- PR https://github.com/scikit-hep/pyhf/pull/2103
- PR https://github.com/scikit-hep/pyhf/pull/2237
- PR https://github.com/scikit-hep/pyhf/pull/2248
- PR https://github.com/scikit-hep/pyhf/pull/2254
- PR https://github.com/scikit-hep/pyhf/pull/2275
```
=> ci(backport): Update GitHub Actions workflows

.flake8, .pre-commit-config.yaml, pyproject.toml, src/pyhf/cli/spec.py, src/pyhf/contrib/utils.py, src/pyhf/contrib/viz/brazil.py, src/pyhf/workspace.py, tests/test_workspace.py
- https://github.com/scikit-hep/pyhf/pull/2124
- https://github.com/scikit-hep/pyhf/pull/2238
- https://github.com/scikit-hep/pyhf/pull/2240
- https://github.com/scikit-hep/pyhf/pull/2273
```
- https://github.com/scikit-hep/pyhf/pull/2124
- https://github.com/scikit-hep/pyhf/pull/2238
- https://github.com/scikit-hep/pyhf/pull/2240
- https://github.com/scikit-hep/pyhf/pull/2273
```
=> chore(backport): Move to using Ruff for pre-commit

.pre-commit-config.yaml, pyproject.toml
- https://github.com/scikit-hep/pyhf/pull/2227
- https://github.com/scikit-hep/pyhf/pull/2239
- https://github.com/scikit-hep/pyhf/pull/2240
- https://github.com/scikit-hep/pyhf/pull/2264
- https://github.com/scikit-hep/pyhf/pull/2270
```
- https://github.com/scikit-hep/pyhf/pull/2227
- https://github.com/scikit-hep/pyhf/pull/2239
- https://github.com/scikit-hep/pyhf/pull/2240
- https://github.com/scikit-hep/pyhf/pull/2264
- https://github.com/scikit-hep/pyhf/pull/2270
```
=> chore(backport): Update pre-commit hooks

docs/bib/general_citations.bib, docs/bib/use_citations.bib
* Backport:
- PR https://github.com/scikit-hep/pyhf/pull/2226
- PR https://github.com/scikit-hep/pyhf/pull/2231
- PR https://github.com/scikit-hep/pyhf/pull/2236
- PR https://github.com/scikit-hep/pyhf/pull/2245
- PR https://github.com/scikit-hep/pyhf/pull/2258
- PR https://github.com/scikit-hep/pyhf/pull/2259
```
* Backport:
- PR https://github.com/scikit-hep/pyhf/pull/2226
- PR https://github.com/scikit-hep/pyhf/pull/2231
- PR https://github.com/scikit-hep/pyhf/pull/2236
- PR https://github.com/scikit-hep/pyhf/pull/2245
- PR https://github.com/scikit-hep/pyhf/pull/2258
- PR https://github.com/scikit-hep/pyhf/pull/2259
```
=> docs(backport): Update use citations

docs/release-notes.rst, docs/release-notes/v0.7.3.rst
* Add release notes for pyhf v0.7.3.
```
* Add release notes for pyhf v0.7.3.
```
=> docs: Add v0.7.3 release notes

docs/bib/HEPData_likelihoods.bib, docs/bib/general_citations.bib, docs/bib/use_citations.bib
* Backport:
- PR https://github.com/scikit-hep/pyhf/pull/2292
- PR https://github.com/scikit-hep/pyhf/pull/2293
```
* Backport:
- PR https://github.com/scikit-hep/pyhf/pull/2292
- PR https://github.com/scikit-hep/pyhf/pull/2293
```
=> docs(backport): Update models and journal publication citations

docs/bib/general_citations.bib
Add general citation from [Branches of a Tree: Taking Derivatives of Programs with Discrete and Branching Randomness in High Energy Physics](https://inspirehep.net/literature/2692444) by @makagan and @lukasheinrich.
```
* Add general citation from 'Branches of a Tree: Taking Derivatives of
Programs with Discrete and Branching Randomness in High Energy
Physics'.
- c.f. https://inspirehep.net/literature/2692444
```
=> docs: Add general use citation from 'Branches of a Tree' paper

.github/workflows/bump-version.yml, .github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/dependencies-head.yml, .github/workflows/docker.yml, .github/workflows/docs.yml, .github/workflows/lint.yml, .github/workflows/lower-bound-requirements.yml, .github/workflows/merged.yml, .github/workflows/notebooks.yml, .github/workflows/publish-package.yml, .github/workflows/release_tests.yml
* Backport:
- PR https://github.com/scikit-hep/pyhf/pull/2307
- PR https://github.com/scikit-hep/pyhf/pull/2313
```
* Backport:
- PR https://github.com/scikit-hep/pyhf/pull/2307
- PR https://github.com/scikit-hep/pyhf/pull/2313
```
=> ci(backport): Update GitHub Actions

docs/bib/HEPData_likelihoods.bib, docs/bib/use_citations.bib
* Backport:
- PR https://github.com/scikit-hep/pyhf/pull/2323
- PR https://github.com/scikit-hep/pyhf/pull/2324
```
* Backport:
- PR https://github.com/scikit-hep/pyhf/pull/2323
- PR https://github.com/scikit-hep/pyhf/pull/2324
```
=> docs(backport): Update citations references and model records

docs/bib/use_citations.bib
Add use citation from [Systematic Evaluation of Generative Machine Learning Capability to Simulate Distributions of Observables at the Large Hadron Collider](https://inspirehep.net/literature/2710627) by Jan Gavranovič, Borut Paul Kerševan.
```
* Add use citation from 'Systematic Evaluation of Generative Machine
Learning Capability to Simulate Distributions of Observables at the
Large Hadron Collider'.
- c.f. https://inspirehep.net/literature/2710627
```
=> docs: Add use citation from observable sim gen ML paper

README.rst, docs/bib/general_citations.bib, docs/bib/use_citations.bib
* Backport:
- PR https://github.com/scikit-hep/pyhf/pull/2341
- PR https://github.com/scikit-hep/pyhf/pull/2345
- PR https://github.com/scikit-hep/pyhf/pull/2349
- PR https://github.com/scikit-hep/pyhf/pull/2354
- PR https://github.com/scikit-hep/pyhf/pull/2355
- PR https://github.com/scikit-hep/pyhf/pull/2356
```
* Backport:
- PR https://github.com/scikit-hep/pyhf/pull/2341
- PR https://github.com/scikit-hep/pyhf/pull/2345
- PR https://github.com/scikit-hep/pyhf/pull/2349
- PR https://github.com/scikit-hep/pyhf/pull/2354
- PR https://github.com/scikit-hep/pyhf/pull/2355
- PR https://github.com/scikit-hep/pyhf/pull/2356
```
=> docs(backport): Update citations and docs

docs/release-notes.rst, docs/release-notes/v0.7.5.rst
Add release notes for pyhf v0.7.5.
```
* Add release notes for pyhf v0.7.5.
```
=> docs: Add v0.7.5 release notes

.zenodo.json, CITATION.cff, README.rst, codemeta.json, docs/lite/jupyterlite.py, src/pyhf/data/citation.bib, src/pyhf/utils.py, tbump.toml
* Forward port the version bump information from release v0.7.5 on the release/v0.7.x branch.
```
* Forward port the version bump information from release v0.7.5 on the
```
=> docs: Bump version: 0.7.4 → 0.7.5

docs/bib/use_citations.bib
Add use citation from [First search for dark-trident processes using the MicroBooNE detector](https://inspirehep.net/literature/2739832).
```
* Add use citation from 'First search for dark-trident processes using
the MicroBooNE detector'.
- c.f. https://inspirehep.net/literature/2739832
```
=> docs: Add use citation from dark-trident MicroBooNE paper

README.rst, docs/bib/general_citations.bib, docs/bib/use_citations.bib
Backport citations
* Backport:
- PR https://github.com/scikit-hep/pyhf/pull/2375
- PR https://github.com/scikit-hep/pyhf/pull/2392
- PR https://github.com/scikit-hep/pyhf/pull/2393
- PR https://github.com/scikit-hep/pyhf/pull/2394
- PR https://github.com/scikit-hep/pyhf/pull/2406
- PR https://github.com/scikit-hep/pyhf/pull/2407
- PR https://github.com/scikit-hep/pyhf/pull/2408
- PR https://github.com/scikit-hep/pyhf/pull/2415
- PR https://github.com/scikit-hep/pyhf/pull/2416
- PR https://github.com/scikit-hep/pyhf/pull/2417
- PR https://github.com/scikit-hep/pyhf/pull/2418
```
* Backport:
- PR https://github.com/scikit-hep/pyhf/pull/2375
- PR https://github.com/scikit-hep/pyhf/pull/2392
- PR https://github.com/scikit-hep/pyhf/pull/2393
- PR …
```
=> docs(backport): Update citations and README

.zenodo.json, CITATION.cff, README.rst, codemeta.json, docs/lite/jupyterlite.py, src/pyhf/data/citation.bib, src/pyhf/utils.py, tbump.toml
* Forward port the version bump information from release v0.7.6 on the release/v0.7.x branch.
```
* Forward port the version bump information from release v0.7.6 on the
```
=> docs: Bump version: 0.7.5 → 0.7.6

pyproject.toml
`jupyter` is a metapackage that is never updated, so defining the `notebook` dependency provides better control on the actual tools required.
```
* jupyter is a metapackage that is never updated, so defining the
notebook dependency provides better control on the actual tools
required.
```
=> build: Use notebook over jupyter

.github/workflows/publish-package.yml
Backport parts of PR https://github.com/scikit-hep/pyhf/pull/2530.
```
* Backport parts of PR https://github.com/scikit-hep/pyhf/pull/2530.
```
=> build(backport): bump actions/upload-artifact to 4.3.4
