pyhf/__init__.py
In preparation of adding many docstrings to the code, autopep8 is used to enforce the PEP 8 style standards.
Refinements can be made to taste as needed.
c.f.:
https://pypi.python.org/pypi/autopep8
https://www.python.org/dev/peps/pep-0008/
=> Beautify to PEP 8 standards

binder/requirements.txt
https://github.com/scikit-hep/uproot
`uproot` is explicitly needed in the `importxml` Jupyter notebook example
=> Add uproot to Binder requirements.txt

README.md
The link previously 404'd, and it now directs to the proper entry on
CDS --- that being CERN-OPEN-2012-016, _HistFactory: A tool for creating
statistical models for use with RooFit and RooStats_,
https://cds.cern.ch/record/1456844
=> Fix link to HistFactory paper on CDS

binder/environment.yml, binder/requirements.txt, examples/notebooks/example-mxnet.ipynb, pyhf/__init__.py, pyhf/tensor/mxnet_backend.py, setup.py, tests/test_tensor.py
Add in a backend for [MXNet](https://mxnet.incubator.apache.org) as described in Issue #80.
TODO:
This was made easier by the ["PyTorch to MXNet" README](https://github.com/zackchase/mxnet-the-straight-dope/blob/master/cheatsheets/pytorch_gluon.md) from the online book "[Deep Learning - The Straight Dope](https://github.com/zackchase/mxnet-the-straight-dope)"
=> Add MXNet backend

pyhf/__init__.py, tests/test_optim.py, tests/test_tensor.py
`pyhf.set_backend()` detects the backend that is being set and then globally sets
the backend and the corresponding optimizer. This is necessary to avoid
errors in data types and would normally have to be done manually.
This solves Issue #99 and will be fully implemented for all optimizers once Issue #86 is finished.
=> Change the optimizer with the backend

setup.py, tests/test_pdf.py, validation/spec.json
This PR adds a starter JSON schema that currently validates against all specs I could find in the pyhf code at the moment.
An interesting item was raised, during the writing of the spec, that the spec may need to be changed slightly in terms of modifications. Currently, modifications are defined like so:
```python
'mods': [
{'name': 'mu', 'type': 'normfactor', 'data': None}
]   
```
however, this introduces the case where two modifications of different types might have the same name! This could easily be solved (where a JSON schema cannot validate such conflicts) by restructuring like so
```python
'mods': {
'mu': {'type': 'normfactor', 'data': None}
}   
```
which has the added benefit of making the structure a little bit more intuitive. Instead of modifications being literally a list of …
=> Add starter json schema for spec

.travis.yml
Remove Python 3.5 testing and only support Python 2.7 and Python 3.6.
The CI should run tests, benchmarking, docs, deploy when merged into
master, but doesn't. This should fix that.
=> Remove Python 3.5 testing support and fix testing on master

.travis.yml
The 'push' builds were originally removed, but they are added back in
for the following reason (kindly provided by Lukas):
If you work on a feature you can very well have a self-consistent
branch that you are developing on. However, if the master has
been further developed the 'pr' type builds will fail until you rebase.
If you want to check if your feature branch is self-consistent then you
need only care about the 'push' build results, and then if the 'pr'
build tests fail you need only rebase once at the very end rather then
continually.
=> Run CI on Travis CI 'push' type builds

pyhf/__init__.py, tests/benchmarks/test_benchmark.py, tests/conftest.py, tests/test_backend_consistency.py, tests/test_optim.py, tests/test_tensor.py
Resolves #125.
- add a `default_backend` and `default_optimizer` to `pyhf/__init__.py` for resetting purposes
- update tests to add a global fixture to `conftest.py` that resets backend to default.
This is also related to #66.
=> global function-scope fixture to set backend back to default

pyhf/__init__.py, tests/test_pdf.py
the behaviour for non-existing modifiers is wrong `.get(name)` should be `[name]`
=> fix non existent modifier handling in pdf construction

pyhf/__init__.py, tests/benchmarks/test_benchmark.py, tests/test_optim.py, tests/test_validation.py
This resolves #66.
- `test_optim.py `
- `test_validation.py` (not so much as data isn't shared, but can make the validation part a function)
=> Use pytest fixtures in tests

pyhf/__init__.py
This just clarifies/fixes the variables names. Arguably we should just return CLs instead of 1/CLs, but I didn't want to change all the other pieces that might rely on the output of `runOnePoint`
addresses #140
=> clarify variable names

pyhf/modifiers/normsys.py, tests/test_pdf.py
Normsys was not working for PyTorch #144  because PyTorch does not have scalar types (as opposed to numpy) and we didn't catch this in our tests.
This PR:
* adds a test that would have caught this
* adds a fix for the test (make sure the at_minus, at_plus etc are added as shape = (1,) tensors and that in the pdf evaluation the widths is also a (1,) tensor
=> Fixnormsys

binder/environment.yml, binder/postBuild
I have observed that currently on binder, I get the following error in various locations.  For example, this code block in `ShapeFactor.ipynb` on binder: 
```
import json
source = {
"channels": {
"signal": {
"binning": [2,-0.5,1.5],
"bindata": {
"data":     [220.0, 230.0],
"bkg1":     [100.0, 70.0],
"sig":      [ 20.0, 20.0]
}
},
"control": {
"binning": [2,-0.5,1.5],
"bindata": {
"data":    [200.0, 300.0],
"bkg1":    [100.0, 100.0]
}
}
}
}
d,pdf = prep_data(source['channels'])
print (d)
init_pars = pdf.config.suggested_init()
print (pdf.expected_data(init_pars))
par_bounds = pdf.config.suggested_bounds()
```
returns:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last) …
```
=> Install pyhf from master to get notebooks to run on binder

docs/examples/notebooks/histogrammar.ipynb
Resolves #166 
If a notebook has multiple first level headings Sphinx will think that it should create a separate nav bar level entry for it, treating it like its own notebook. This enforces a single first level heading.
This is what the fix should look like:
=> Fix headings of histogrammar notebook

pyhf/__init__.py, pyhf/tensor/mxnet_backend.py, pyhf/tensor/numpy_backend.py, pyhf/tensor/pytorch_backend.py, pyhf/tensor/tensorflow_backend.py, tests/test_tensor.py
=> Fix simple_broadcast()

pyhf/__init__.py
This adds some sane defaults for init and par bounds since we have access to the pdf config in the function anyways.
One could also think about automatically extending the data with the aux measurements, since right now we have this pattern
```
obs_data = [...]
pyhf.runOnePoint(1.0, obs_data + pdf.config.auxdata, pdf ...)
```
which could be handled for the user as well to be
```
obs_data = [...]
pyhf.runOnePoint(1.0, obs_data, pdf, ...)
```
but either we make this automatic / "smart" or the default would change, which would be backward-compat. breaking (requiring a modification of notebooks etc)
=> better default options

docs/conf.py, docs/examples.rst
Resolves #173 
This is what the docs look like with the addition of the Binder example
It should be noted that the interactive plotting doesn't display (as expected as these are static pages) but I don't think that is a big enough detractor from the high quality of the notebook to keep it out of the docs.
=> Add Binder example notebook to docs examples

pyhf/tensor/pytorch_backend.py
This fixes failing doctests due to very small changes in the representation of the tensor from pytorch. There are less spaces than before. This does not change the code at all, just the documentation of the code. As such, there's not much to approve.
=> fix failing doctests

docs/bib/talks.bib, docs/conf.py, docs/index.rst, docs/talks.rst, setup.py
This PR will use a sphinxcontrib for bibtex so that talks can be added using a `docs/bib/talks.bib` file and inserted in the documentation. This closes #178.
=> add bib for adding talks to documentation

docs/_templates/modifierclass.rst, docs/api.rst
Fixes #169 and improves documentation a bit more. Duplicated methods were showing because of the `autoclass` and the `autosummary` conflicting with each other in the template we use. This is now cleaned up and also improved. Titles of generated API documentation pages are less verbose and exclude the package/module name as it is not needed at first glance.
=> bugfix: docs duplicated methods

pyhf/__init__.py, pyhf/data/spec.json, pyhf/exceptions/__init__.py, pyhf/utils.py, setup.py, tests/test_import.py, tests/test_pdf.py, tests/test_schema.py, tests/test_utils.py, tests/test_validation.py, validation/spec.json
This resolves #118. This adds specification validation to `hfpdf.__init__()` calls. This will simplify the tests used throughout, and all testing relevant to making sure the schema validation catches common pitfalls is being separated into `tests/test_schema.py` (for want of a better name).
This also sets up class-specific logging functionality to help filter out the logging a bit better as well in the future.
Also adds `staterror` to schema -- somehow missed this.
=> Feature: spec validation on init, update logging, add staterror to schema

tests/benchmarks/test_benchmark.py
The current master is breaking because of #193 moving `runOnePoint` to `utils.py` and forgetting to update the one line in the test for fixing it.
=> fix benchmark tests

pyhf/commandline.py, pyhf/readxml.py, setup.py, tests/test_scripts.py
This allows someone to use `pyhf` from command-line to parse the XML workspaces using the `readxml.parse` functionality. This uses `click` to set up options/arguments.
This also updates `readxml` with some slight reorganization to allow for a `tqdm` progress bar that can be enabled (default: disabled) for reading in the channels in various XML files.
```
pyhf_xml2json --entrypoint-xml validation/multibin_multibjets/config/NormalMeasurement.xml --workspace validation/multibin_multibjets/ --output_file test.json
```
NB: both `click` and `tqdm` are already installed via our dependencies, but I've explicitly listed them in `setup.py` now.
=> Feature: command line parse xml

pyhf/readxml.py, tests/test_import.py
This adds support for cases where `StatError` is activated, but the uncertainties are provided by an external `Histo`
Example:
https://github.com/diana-hep/pyhf/blob/master/validation/xmlimport_input/config/example_channel.xml#L29
=> support stat errors from external histogram (and fix those from internal ones if sumw2 structure is empty)

.travis.yml, README.md, docs/examples.rst, docs/examples/notebooks/hello-world.ipynb, tests/test_notebooks.py
=> Add hello world example and check to tests

pyhf/exceptions/__init__.py, pyhf/pdf.py, tests/test_pdf.py
Apparently ROOT allows modifiers to reuse names (without sharing) across modifiers. I would suggest that in  `pyhf` we qualify the modifier names as `type/name` which need to be unique
addresses #208
=> qualify modifier names by modifier type

pyhf/commandline.py, pyhf/readxml.py, pyhf/writexml.py, tests/test_scripts.py
Partially adresses #29  https://github.com/diana-hep/pyhf/issues/170
This is an incomplete stub to seed code for XML writing.
* `pyhf.writexml` module with XML generation code
* adds `pyhf json2xml command such that`
```
pyhf xml2json config/example.xml|pyhf json2xml > new.xml
pyhf xml2json new.xml
```
goes through without error by producing valid JSON and XML. (though it does not produce the right XML just yet)
=> stub for XML writing

MANIFEST.in
if installing in non-editable mode, the data we want to distribute via MANIFEST.in needs to be copied and the path was wrong
=> fixes manifest to correct path

pyhf/commandline.py
This just adds the ability to configure qualify names for `pyhf cls` command line, which allows MBJ to be validated more easily.
=> add qualify-names option for pyhf cls

pyhf/commandline.py, tests/test_scripts.py
This was raised as part of #233 . `pyhf cls foo.json --measurement MyMeasurement` now works.
=> Allow for configurable measurement to be specified from command line

pyhf/modifiers/__init__.py, tests/test_modifiers.py
Comes out of #231. Adds `op_code` to modifiers. For now, support addition and multiplication.
=> Feature: add op_code to modifiers

.travis.yml, CONTRIBUTING.md, docs/development.rst
If this is not done, then the default Travis installation of `numpy==1.13.3` will be used throughout instead of installing a later requested version unless it is explicitly asked for in `setup.py`'s `install_requires` (which is not done for details explained in PR #235). This allows for pyhf to be installed in Travis CI in the same way that a user or developer would, without having to force any version of NumPy.
This resolves the [confusion that I was having in PR #235](https://github.com/diana-hep/pyhf/pull/235#issuecomment-418910900) as well about the difference in NumPy releases being installed in my Docker containers and in Travis CI. In retrospect this difference should have been an obvious indicator that Travis CI already had a version of NumPy installed, so sorry about missing …
=> Install with --ignore-installed to ensure proper NumPy

pyhf/pdf.py
This is useful for #231 and similar where we can access a union of the names of all the various modifiers, samples, and channels involved in configuration of the model (pdf). This PR allows for the following to be possible:
```python
>>> spec = {  ... }
>>> model = pyhf.Model(spec)
>>> model.channels
['firstchannel']
>>> model.samples
['mu', 'bkg1', 'bkg2', 'bkg3']
>>> model.modifiers
['mu', 'stat_firstchannel']
```
=> Feature: maintain union of specification items as part of the model

pyhf/data/spec.json, pyhf/exceptions/__init__.py, pyhf/pdf.py, tests/test_schema.py
StatError and ShapeSys require at least one item in their `data` arrays. Samples require at least one item in their `data` arrays. Channels require at least one sample.
This revealed a bug with `poiname` where a sample with no modifiers (a valid spec) is still not being built by the `_ModelConfig` into a pdf.
This resolves #240 .
=> Feature: make schema stricter (require minItems for some arrays)

docs/Makefile
Got hit by this bug: travis-ci/travis-ci#9996 . Approve and merge asap. Changes the `ln -sfn` command to an `rsync -r` command. Images in `README.md` are not linked properly in the generated sphinx documentation because the symlinks were not transferred over as part of deployment.
=> Bug: docs deployment doesn't like symlinks

README.md
Resolves #244 
Given how the repo's Dockerfile is made it will build correctly on Docker Cloud, but fails on Docker Hub. If the build status badge is left in the `README` it will give the false impression that the Docker image is broken. c.f. Issue #239 for more details on this.
Additionally fix the broken rendering of the uproot link in the RST version of the `README` (the website index page)
=> Remove Docker Hub build status badge

pyhf/commandline.py, setup.py, tests/test_scripts.py
This adds a `--patch` flag to `pyhf cls`
```
cat newsignal.json|pyhf cls original.json --patch -
```
```
pyhf cls original.json --patch newsignal.json
```
```
pyhf cls original.json --patch newsignal.json
```
```
cat original.json pyhf cls - --patch newsignal.json
```
=> add patch CLI

pyhf/tensor/mxnet_backend.py, pyhf/tensor/numpy_backend.py, pyhf/tensor/pytorch_backend.py, pyhf/tensor/tensorflow_backend.py, tests/test_tensor.py
Add the following functionality to backends in preparation for tensorizing the interpolation code as in #251 
- einsum
- zeros
- abs
NB: mxnet does not support einsum. In lieu of this, I added a `raise NotImplementedError` when einsum is called.
=> Fix concatenate and add missing functionality to backends:

docs/examples/notebooks/learn/TensorizingInterpolations.ipynb, pyhf/interpolate.py, pyhf/modifiers/histosys.py, pyhf/modifiers/normsys.py, pyhf/utils.py, tests/test_interpolate.py, tests/test_tensor.py
The overarching theme for this PR is to get the interpolation codes to be tensorizable. This is one of the small pieces needed for #231 and we'll be doing this through a series of smaller PRs to break this up a bit more.
Related: #231, #246, #219.
A notebook is added describing the process of tensorizing these functions to aid with future understanding.
Additionally, I've added a (first draft of a) neat decorator in `utils.py` that tensorizes the inputs to the interpolator functions if they're not tensorized.
=> Feature: tensorize the interpolation codes (more general)

pyhf/readxml.py, tests/conftest.py, tests/test_init.py, tests/test_interpolate.py, tests/test_optim.py, tests/test_pdf.py, tests/test_tensor.py
This PR tries to make testing a lot easier for us moving forward as we start having complexity problems with testing combinations of backends+optimizers and so on and lots of duplicated code. In particular, the fixture is called `backend` so adding a `backend` parameter to any test function you have will automatically wrap that function in setting up the backend correctly, and breaking it down after the test runs. This can be useful with certain backends like tensorflow that need a new session or its internal graph cleared.
Additionally, some extra decorations (`pytest.mark`s) are specified to make this even easier to fine-tune which backends run. Right now, we add 5: `numpy`, `tensorflow`, `pytorch`, `mxnet`, `numpy_minuit`. The last one is numpy with the minuit optimizer.
One can …
=> Feature: (automatically) set backends through a fixture

pyhf/tensor/numpy_backend.py
This is a micro-optimization on the computation of the poisson in the numpy backend.
When the observed events are equal to zero the log is not computed in the expression
np.exp(n*np.log(lam)-lam-gammaln(n+1.))
using [`scipy.special.xlogy(n, lambda)`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.xlogy.html), which return `0` if `n==0` (also when `lambda==0`) without computing the log.
In principle further optimization is possible, returning just `np.exp(-lam)` when `n == 0` but probably this require some python control flow you want to avoid (and `np.where` is not lazy).
Quick performance test:
def f2(l, n):   # present one
return np.exp(n*np.log(l)-l-gammaln(n+1.))
def f3(l, n):   # new branch
return np.exp(xlogy(n, l)-l-gammaln(n+1.))
There is a 40% speed …
=> Use scipy.special.xlogy in poisson computation for numpy backend

.travis.yml, pyhf/tensor/numpy_backend.py, tests/benchmarks/test_benchmark.py, tests/test_pdf.py, tests/test_tensor.py
The benchmark tests were not running because of forgetting to `pip install minuit` dependency. This was introduced through #276 which imports the minuit optimizer in `tests/conftest.py` which raises the exception.
This also reverts the unfortunate regression introduced by #277 as we don't have equivalent methods to return `0` for the other backends, and whether the `poisson` for `lambda=0` should return 0 or `NaN` is probably not well-defined? (correct me if I'm wrong).
=> Fix: bug in benchmark tests

setup.py
[`uproot` `v3.0.0` introduced a change in the public API for accessing fSumw2](https://github.com/scikit-hep/uproot/issues/130). This is needed to make sure that the code in `pyhf/readxml.py` works with `uproot` that were added in PR #276.
=> Require uproot to be version 3.0.0 or newer

pyhf/modifiers/histosys.py, pyhf/modifiers/normfactor.py, pyhf/modifiers/normsys.py, pyhf/modifiers/shapefactor.py, pyhf/modifiers/shapesys.py, pyhf/modifiers/staterror.py, pyhf/pdf.py, tests/test_modifiers.py
This PR refactors the pdf to compute all modifications needed in one go. This should be possible independent of #231 #251 but help with the overall refactoring by collecting all necessary computations in a single function that can then be optimized
=> precomputes all modifications at once

.travis.yml, docs/development.rst, setup.py
~~Should not be merged in until PR #260 is in and this PR is rebased against it.~~ This can go in before as the Dask backend isn't ready yet.
Taking some inspiration [from Dask](https://github.com/dask/dask/blob/master/setup.py), add a `complete` option for installation that installs all environments defined in `extras_require`.
Additionally adds some extra information into the setup for PyPI such as website, license, keywords, classifiers, and supported Python versions.
As this is a large rewrite `autopep8` is also run over it to enforce PEP8 (as I haven't take care of Issue #185 yet).
=> Add complete install option

pyhf/tensor/mxnet_backend.py, pyhf/tensor/numpy_backend.py, pyhf/tensor/pytorch_backend.py, pyhf/tensor/tensorflow_backend.py, tests/test_tensor.py
I missed this in #287 because I couldn't find a solution for mxnet. This adds boolean_mask and tests to all the backends (except mxnet). This is for #285.
> Add boolean_mask back into all the backends (except mxnet) and adds tests.
=> Add boolean_mask back to backend

.travis.yml, binder/trigger_binder.py
Have Selenium properly wait for the Binder page to load to trigger the Binder build. Just using `time.sleep` is not necessarily sufficient.
Also trigger Binder builds for the entire repo as well as the example notebook.
Following the example at [How to get Selenium to wait for page load after a click](http://www.obeythetestinggoat.com/how-to-get-selenium-to-wait-for-page-load-after-a-click.html)
=> Have Selenium properly wait for page load

setup.py
This PR is a temporary patch in response to Issue #302.
Until a resolution to the issue of tensorflow-probability's change of the Poisson `log_prob` in release v0.4.0 to no longer support a continuous approximation to the Poisson p.m.f. can be reached with the help of the `tfp` dev team then `tfp` should be frozen at v0.3.0 to allow for continued
development. This API change in `tfp` is breaking and so it can't be easily fixed without fundamental changes in either `pyhf` or `tfp`.
Hopefully a resolution comes out of `tfp` Issue https://github.com/tensorflow/probability/issues/182
=> Pin tensorflow-probability to release v0.3.0

.bumpversion.cfg, .github/ISSUE_TEMPLATE/bug-report.md, pyhf/__init__.py, pyhf/version.py, setup.py
Add version information to the code in the form of `__version__` so that 
```
pyhf.__version__
```
returns information. So for example
**Edit below:** `0.0.16.dev` to `0.0.15`
```
>>> pyhf.__version__
'0.0.15'
```
~~(implicit here is that as `0.0.15` is the current PyPI release that what is currently in `master` is the next release's development version. There is probably a more industry standard or sane way to do this then what I just proposed here.)~~
~~The [`version.py` file added here is copied from TensorFlow Probability](https://github.com/tensorflow/probability/blob/f8bd785031340f2231ed0e0f01c378c03ac3ce52/tensorflow_probability/python/version.py).~~
[`bumpversion`](https://github.com/peritus/bumpversion) controls the actual version number in all of the code to …
=> Add version info through __version__

pyhf/events.py, tests/test_events.py
This is to help with #285 which needs an easy way to trigger recomputation in the case where the tensorlib changes. Since this needs to be somewhat globally-triggering with callbacks, it's easier to go for some sort of sub/pub model. I've implemented a bare-bones version that should handle all we need to do.
The idea is to do something like
```python
def normsys_combined(self):
def __init__(self):
pass
@pyhf.events.subscribe('tensorlib_change')
def _precompute(self):
```
and then `pyhf/__init__.py#set_backend` can simply call `pyhf.events.trigger('tensorlib_change')()` to trigger the change. There's zero checks on the arguments passed through to function calls, but it is flexible and can allow for passing through arguments from the trigger to the callbacks as long as the callbacks can …
=> Add a way to subscribe/trigger events globally

tests/test_validation.py
This fixes the validation Data. In #45 a better poisson approximation was used and in #47 the histosys sharing was fixed but the validation data was from runs before these. but we also forgot checking the absolute difference in the tests and thus missed failing tests since then
The source of the validation data is the commit of #47 i.e. 0eddbf9 with this diff applied https://gist.github.com/lukasheinrich/03323eb9adcac1ef709e4b23ba496ee1
=> fix validation data and tests

docs/examples.rst
Given the discussion in Issue #325 the notebooks that are shown on the website as examples should all be in [the CI](https://github.com/diana-hep/pyhf/blob/7486cac7e82dc1a5c6a47cbb472cc1920c220444/tests/test_notebooks.py). Until PR #285 is done and there is time to go through and clean up and rewrite all of the notebooks it is easier to just comment them out for the time being so that we don't confuse new users.
**Note:** This PR does _not_ fix Issue #325. It will have to be resolved after PR #285 is done.
> All the notebooks that are shown on the website as examples should all be in the CI. Until the megachannel overhaul is complete and there is time to to go through and clean up and rewrite all of the notebooks it is easier to just comment them out for the time …
=> Remove notebooks untested in the CI from website examples

docs/api.rst, docs/citations.rst, docs/installation.rst, docs/talks.rst
Given some new user feedback it wasn't immediately clear if the installation instructions were listing options or steps. The use of `...` (hopefully?) make this more clear that they are installation options.
Instructions on how to update an installation of `pyhf` are also added.
>- Use ellipses to convey that the installation subsections for different ways of installing pyhf are options and not successive steps that need to be executed.
>- Add instructions on how to update an installation of `pyhf`
=> Improve installation instruction clarity

pyhf/optimize/opt_tflow.py, tests/test_backend_consistency.py
`opt_tflow` doesn't insert the POI correctly. Assumed that it was the first one in the list of parameters, but might not always be the case. Need to respect the ordering.
Thanks to @dantrim for providing an example that found the bug.
=> Insert the POI parameter correctly using POI index in opt_tflow

pyhf/modifiers/shapesys.py, pyhf/modifiers/staterror.py
The main difficulty with shapesys/staterror as it affects multiple (non-consecutive) bins is the way we do masking. For situations where we need to figure out whether to enable the mask or not, it was filling in `-1` when the parameter index was `0` which is not good. Additionally, `tensorflow.gather()` is not happy with `-1`.
=> fix up indexing of summed_mask in shapesys, staterror

pyhf/modifiers/shapesys.py, pyhf/modifiers/staterror.py
See #333. This is fixing it according to @lukasheinrich 's comment.
=> Fix indexing for real this time (instead of 0, use len(...) -1)

setup.py
Python3's `open` supports encoding, but Python2's `open` does not so it must use `io.open`
```
- Python3's open supports encoding, but Python2's open does not so it must use io.open
- Fixes a bug present in PR #338 and PR #339 that were not caught in the craziness of the great GitHub outage of 2018-10-21/22 and resulted in erroneous early merges
```
=> Use version dependent open to get README

README.md
This resolves #250. The table now renders properly in the sphinx website by adding a period `.` instead of relying on spaces. I also tried to use non-breakable spaces `&nbsp;` but those are escaped and treated literally in converting from markdown to rST.
```
Add periods to empty table cells so that rST renders the table correctly.
```
=> Fix table in README to be rendered properly in docs

docs/development.rst, docs/installation.rst
By using the `pip` [VCS support `git+` feature](https://pip.pypa.io/en/stable/reference/pip_install/#git) make it easier for end users to install from GitHub. In addition, clarify that doing so gets the latest development version and not necessarily a stable release as PyPI does.
```
* Use the pip VCS support git+ feature (c.f. https://pip.pypa.io/en/stable/reference/pip_install/#git) to make it easier for end users to install from GitHub. In addition, clarify that doing so gets the latest development version and not necessarily a stable release as PyPI does.
* Specify code-block type for Sphinx in docs/development.rst
```
=> Make GitHub install instructions easier

docs/examples/notebooks/hello-world.ipynb
Resolves #351 
```
- Fix the rendering issue with Sphinx caused by having a mathmode environment inside of a bold text environment by ending and starting the bold outside of the mathmode
- Use \mathrm{CL} for proper formatting in mathmode
```
=> Use mathmode outside of bold environment

pyhf/modifiers/histosys.py, pyhf/modifiers/normfactor.py, pyhf/modifiers/normsys.py, pyhf/modifiers/shapefactor.py, pyhf/modifiers/shapesys.py, pyhf/modifiers/staterror.py, pyhf/paramsets.py, pyhf/pdf.py
this resolves the case in #272 of shared parsets over multiple modifiers
```
roohf not shared
{
"CLs_exp": [
0.15719136360999494,
0.28707182742358117,
0.49040108398224225,
0.7391079566241138,
0.9260249020571463
],
"CLs_obs": 0.6624276086776395
}
roohf shared
{
"CLs_exp": [
0.1824533173540692,
0.31861297860704774,
0.5224666964320326,
0.7615731173535661,
0.9344146382006049
],
"CLs_obs": 0.6768036954464488
}
pyhf shared
{
"CLs_exp": [
0.18257145128940405,
0.31875687511186174,
0.5226093840643298,
0.761670602736219,
0.9344501334751033
],
"CLs_obs": 0.6768690617184364
}
```
```
* expand config.modifiers to include mapping to parameter set (modname,type,paramset)
* use type/modname key to identify modifier data in mega_mods
* use paramset name in combined modifier appliers …
```
=> Enable shared nuisance parameters over modifier types

pyhf/commandline.py, pyhf/paramsets.py, pyhf/pdf.py, tests/test_pdf.py
Resolves #357 
```
- Remove obsolete --qualify-names CLI option
- Effectively revert PR #233
- Remove corresponding qualify_names arg from _ModelConfig and logic to remove the functionality of that keyword arg from Model. Additionally remove it from use in tests and from exception hints.
```
=> Remove --qualify-names option from the CLI

pyhf/data/spec.json, pyhf/modifiers/__init__.py, pyhf/modifiers/histosys.py, pyhf/modifiers/normfactor.py, pyhf/modifiers/normsys.py, pyhf/modifiers/shapefactor.py, pyhf/modifiers/shapesys.py, pyhf/modifiers/staterror.py, pyhf/paramsets.py, pyhf/pdf.py, tests/test_modifiers.py, tests/test_pdf.py, tests/test_schema.py
This expands the spec to allow for (optional) parameter configuration. This will not break existing specs, since if this isn't specified, we will defer to default configurations in all cases. The addition of a parameter configuration allows to override these defaults in the code.
This will get us closer to being able to do something like #355 and enables us to implement globally defined systematics such as luminosity uncertainty in #352 .
```
- Expand the spec to allow for optional parameter configuration
- Remove op_code from the paramset requirements
- Refactor to allow for op_code to be less hard-coded in pyhf/pdf::_modifications
```
=> Allow for parameter configuration from the spec

pyhf/commandline.py, pyhf/readxml.py, setup.py, tests/test_import.py
Hi,
The xml parser (re-)opens the histogram rootfiles for each histogram. This can slow down the process extremely when there are many histograms in one rootfile (as is the case if one creates the xml and histograms with HistFitter). This might be easily avoided by adding a dictionary somewhere that tracks which files have already been opened.
My current solution is probably not the cleanest way  to do this (no way clean up of the dictionary), but it shows that the approach is effective. I tried it for an example with ~100k Histograms in one rootfile which seemed to take forever without that fix (i aborted it after 2 hours). With the cache dictionary it took a few minutes to generate the json file.
Maybe somebody has a good idea on how to incorporate this.
(remark: HistFactory's …
=> adding cache dictionary to open root files only once in readxml

README.md, docs/examples/notebooks/binderexample/StatisticalAnalysis.ipynb, pyhf/commandline.py, pyhf/data/spec.json, pyhf/modifiers/__init__.py, pyhf/modifiers/lumi.py, pyhf/paramsets.py, pyhf/pdf.py, pyhf/readxml.py, tests/test_import.py, tests/test_pdf.py, tests/test_validation.py
This is the last piece needed for the MBJ validation. The luminosity is a modifier that affects some samples in some channels, but is a globally shared modifier (as such, the name is fixed to `lumi` in the spec). This is going to be similar to what normsys currently does, but globally shared.
- `readxml.py` is updated to check for this.
- `modifiers/lumi.py` is added with a gaussian constraint
- `tests/test_validation.py` is set-up to check for the calculation, but will need to run it in HistFactory to get the right calculation [e.g. use one of the validation XML files that already exist]
```
- the luminosity uncertainty is a global multiplicative scale factor, constrained by a gaussian whose mu is the single nuisance parameter constrained as follows (based on …
```
=> Add luminosity uncertainty calculations

README.md
This fixes #371. Documentation change only. Updates location of lumi uncertainty completion checkbox in readme.
=> Fix location of lumi uncertainty completion in readme

.travis.yml
Notice from time to time that the coverage of master goes awry. This is because every single success in our travis build matrix is sending its results to coveralls. Sometimes, like in doc-building, we don't cover everything (e.g. 50%) because it's just building documentation and not actually testing. And sometimes this gets sent to coveralls after the python tests run, and sometimes before. This is a race condition, but also explains why it shows up from time to time.
=> only run coveralls after python3.6 testing

pyhf/readxml.py, setup.py, tests/conftest.py
`tests/test_import.py` give an error of
```
E       ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
in `extract_error` due to a change in the return structure of `uproot-methods` `TH1.variances` return structure in [`uproot_methods` PR 21](https://github.com/scikit-hep/uproot-methods/pull/21) where the returned value [changed from a list to a `numpy.array`](https://github.com/scikit-hep/uproot-methods/commit/c2a78e4e05eb710c74d5c6ec5d017f70af28566b#diff-67fbe39413c91feb6ad80acd70f76d47).
This change was introduced in [`uproot-methods` release `v0.3.0`](https://github.com/scikit-hep/uproot-methods/releases/tag/0.3.0)
This necessitated a change in the query of `h.variances` on the pyhf side.
This PR is also affecting PR #377 and PR …
=> Make extract_error compliant with uproot-methods v0.3.0 API

.travis.yml
In the merge of PR #379 into `master` it was seen that the [benchmark CI stage failed with the memory error of](https://travis-ci.org/diana-hep/pyhf/jobs/474501916#L859-L861)
```
*** Error in `/home/travis/virtualenv/python3.6.3/bin/python': corrupted size vs. prev_size: 0x0000000000c2de00 ***
/home/travis/.travis/job_stages: line 104:  4633 Aborted                 (core dumped) pytest -r sx --benchmark-sort=mean tests/benchmarks/
The command "pytest -r sx --benchmark-sort=mean tests/benchmarks/" exited with 134.
```
This error had been [seen before in Issue #67](https://github.com/diana-hep/pyhf/issues/67#issuecomment-378529720) and @kratsg provided a [fix for a relevant similar memory issue in PR #296](https://github.com/diana-hep/pyhf/pull/296#issuecomment-427536326). Applying that …
=> Fix corrupted size vs. prev_size memory error in CI benchmark stage

.travis.yml
Related to Issue #385 (it _fixes_ it, but doesn't _resolve_ it)
Issues with calling `pytest` vs. `python -m pytest` are known as in the [pytest docs it is mentioned that](https://docs.pytest.org/en/latest/pythonpath.html#invoking-pytest-versus-python-m-pytest)
> Running `pytest` with `python -m pytest [...]` instead of `pytest [...]` yields nearly equivalent behaviour, except that the former call will add the current directory to `sys.path`. See also [Calling pytest through python -m pytest](https://docs.pytest.org/en/latest/usage.html#cmdline).
```
Use python -m pytest to call pytest. This is done as it has been empirically observed that a segfault only noticed in the Python 2.7 version of the notebook tests on Travis CI doesn't occur if python -m pytest is called …
```
=> Use python -m pytest to avoid segfault in Python 2.7 Travis notebook tests

setup.py, tests/conftest.py
- Together with PR #379 fixes the CI for 2018 going into 2019.
- This PR needs to be rebased against `master` after PR #379 is accepted.
- This PR is also affecting PR #377 and PR #378.
- One reoccurring problem seems to be(?) that the `v1.0` release of PyTorch is [causing issues with memory allocation in Travis](https://travis-ci.org/diana-hep/pyhf/jobs/473431783#L481-L483) resulting in errors or segfault 11.
In requiring the latest version of PyTorch (v1.0) the loading of it after other imports in `tests/conftest.py` causes there to be an [error during setup of the pytest fixtures](https://travis-ci.org/diana-hep/pyhf/jobs/473509231#L650-L655)
```
ImportError while loading conftest '/home/travis/build/diana-hep/pyhf/tests/conftest.py'.
tests/conftest.py:45: in <module> …
```
=> Require PyTorch v1.0 or newer and fix static TLS load error

.travis.yml
As a follow up to PR #383, use `curl` to access the Binder build API instead of `python -m webbrowser`. The only thing that needs to be done is for the build API endpoint to receive the request and so the simpler the tool used the better. Along these lines, there were some instances in which `python -m webbrowser` would suffer a timeout error resulting in a failed Binder stage. This is not an issue with `curl`.
This PR requires PR #387 to be merged in first.
```
* Use curl to trigger the Binder build API instead of python -m webbrowser to avoid any potential timeout errors
```
=> Use curl to trigger Binder build API

binder/postBuild
Resolves #389 
```
At minrk's suggestion the --ignore-installed flag is removed from the pip install in binder/postBuild
c.f. https://gitter.im/jupyterhub/binder?at=5c38af3e2e25e453d7662b05
```
=> Remove --ignore-installed pip install option flag in binder/postBuild

README.md
Add a badge to the `README` that shows the supported Python versions. 
[![Supported Python versionss](https://img.shields.io/pypi/pyversions/pyhf.svg)](https://pypi.org/project/pyhf/)
The badge information is taken from [pyhf's PyPI page](https://pypi.org/project/pyhf/) and is generated by [shields.io](https://shields.io/).
```
The badge information is taken from pyhf's PyPI page and is generated by shields.io
```
=> Add supported Python versions badge

README.md
The README has a contributing URL pointing to @lukasheinrich 's fork instead of diana-hep's.
```
- fix contributing URL in README
```
=> Fix URL in readme to point from lukasheinrich fork to main diana-hep repo

.travis.yml, binder/trigger_binder.sh
Safeguards Binder build section of the CI from taking too long and causing a timeout error by Travis CI. The trigger function sets a time limit on curl and accepts `--max-time` exit return code, `28`, as valid and then returns success.
```
* The trigger function sets a time limit on curl and accepts --max-time exit return code, 28, as valid and then returns success.
```
=> Add Bash script to guard max time return value for Binder build

pyhf/modifiers/histosys.py, pyhf/modifiers/lumi.py, pyhf/modifiers/normfactor.py, pyhf/modifiers/normsys.py, pyhf/modifiers/shapefactor.py, pyhf/modifiers/shapesys.py, pyhf/modifiers/staterror.py, pyhf/pdf.py
See #405 for more details. The short of it is that `param_set` name does not differ from the `modifier_def['name']` at all. If this is somehow a mistake, our tests should catch this (if there's a case where it differs). As the code is written, there's no difference. So this PR cleans up the code a bit given that assumption.
```
* remove redundant use of paramset_name everywhere as it does not differ from modifier_def['name'] anymore
* tuples of three elements passed around for each modifier is now a tuple of two elements
```
=> Remove redundant (repeated) param_set name

.travis.yml, setup.py
Now that [TensorFlow `v1.13.1` has been released](https://pypi.org/project/tensorflow/1.13.1/) which is compatible with Python 3.7, Python 3.7 should be added to the versions tested by the CI. To do this, the Travis CI Ubuntu Xenial images which have Python 3.7 are used.
Additionally, the Python 3.7 language tag is added to `setup.py` so that PyPI will know that future releases have been tested with Python 3.7.
The only downside to this addition is that Travis will only run 5 builds concurrently on a free version. As the notebook tests are split off into their own tests this results in 6 builds, and additional time being added to testing as the Python 3.7 notebook tests need to wait for one job to finish before it can start.
```
* Add Python 3.7 to Travis CI testing …
```
=> Add Python 3.7 to CI testing

pyhf/commandline.py, tests/test_scripts.py
This adds a commandline flag so that one can specify the test POI value during the CLs computation. Previously this was hardcoded to be 1.0
=> add commandline flag --testpoi

pyhf/tensor/mxnet_backend.py, pyhf/tensor/numpy_backend.py, pyhf/tensor/pytorch_backend.py, pyhf/tensor/tensorflow_backend.py, tests/test_tensor.py
In `mxnet >= v1.4.0` the shape of a `NDArray` when a scalar has been passed to it is empty. As a result, this should be caught and forced to have a consistent shape by wrapping the scalar in a list. However, at this point it is probably worth enforcing a default shape on tensors made from scalars, as the different tensor libraries handle them differently and we should have a consistent form.
```
* Ensure non-empty tensor shape for consistency
- Do this by asking for forgiveness and attempting to access shape information, and if it fails modifying the tensor object such that it has the proper shape
* Remove generic_len function from backends as a consistent tensor shape makes it unnecessary
* Add error logging and raise KeyError if an unsupported dtype is used for the …
```
=> Enforce consistent tensor shape for scalars

.travis.yml
Resolves #417 
As shown in Issue #417, if Xenial and Python 3.7 are used as the default OS and Python runtime in Travis CI there is a speed boost in running tests, resulting in test suites that are few minutes faster.
```
* Use Xenial Xerus as the default OS and use Python 3.7 as the default Python runtime in Travis CI for shorter tests
* Use Trusty Tahr as the Travis CI OS for testing with Python 2.7 and Python 3.6 runtimes
```
=> Use Xenial and Python 3.7 as defaults in Travis CI for speed

setup.py
Resolves #397
To ensure stable APIs for the computational backends while not pinning at specific versions &mdash; to keep pyhf acting like a proper library and not an application &mdash; use PEP 440/508's compatible version syntax for the backend releases to pin them at their current major release version while allowing for minor version updates. This is also done for pytest, uproot, and papermill.
This also has the nice feature of being able to intentionally choose when to update to a newer backend API even if the backend has had a new major release with API breaking changes for a long time.
Noting that if the release is specified down to the bug fix release (`X.Y.Z`) then it will be pinned down to the minor release (`X.Y`). c.f. [PEP …
=>  Use PEP 440/508 compatible version syntax in setup.py

pyhf/commandline.py, pyhf/readxml.py, pyhf/writexml.py, tests/test_export.py, tests/test_scripts.py, tests/test_validation.py
This pull request adds the functionality of exporting JSON specs into XML+ROOT for use with RooStats/HistFactory/HistFitter. This resolves #170.
```
- flesh out writexml.py to actually write out the XML+ROOT dump
- update tests to match the expected command line interface
- added unit tests to check exporting functionality per-element
- added integration tests to check full export
- added validation tests to check a round-trip xml->json->xml->json for the simplified XML import examples
```
=> Feature: json2xml (XML+ROOT exporting)

pyhf/pdf.py
This resolves #414.
```
- we use list(set(...)) to generate the metadata of a given spec but set() does not guarantee order
```
=> Use sorted() to maintain ordering of channel/samples/modifiers/parameters

MANIFEST.in, pyhf/data/HistFactorySchema.dtd, pyhf/writexml.py, tests/test_export.py
This resolves #433.
The XML exporting functionality `json2xml` was only validated in the context of passing it back through `xml2json` and checking that things worked. However, in the _scary_ *real* world where `hist2workspace` exists, it wasn't working. This was for a few reasons:
- HistFactorySchema.dtd was not included anywhere, so doctypes were added to the XML outputs as appropriate
- HistFactorySchema.dtd is now copied over into the output directory from `json2xml` and as such is added as `pyhf` data and will be shipped with future versions of the package
- ExportOnly is added to the measurement object since we don't want `hist2workspace` to actually run fits
```
- HistFactorySchema.dtd was not included anywhere, so doctypes were added to the XML outputs as …
```
=> Fix minor bugs with the xml exporting in the real world

.git_archival.txt, .gitattributes, .travis.yml, setup.cfg, setup.py
Completes PR #429 (which was merged early by accident) and resolves #425 and resolves #432.
Inspired by Issue #410 and @webknjaz's tweet which inspired Issue #425 to have more robust deployment to PyPI this PR implements PR level deployments to [TestPyPI](https://test.pypi.org/) that are versioned with version structure of `{next_version}.dev{distance}` through use of [`setuptools-scm`](https://github.com/pypa/setuptools_scm/) and [`setuptools-scm-git-archive`](https://github.com/Changaco/setuptools_scm_git_archive/) and heavy copying of [`ansible-lint`'s approach](https://github.com/ansible/ansible-lint/blob/d27451783dbc4f408cef04096a139f6be61f7611/setup.py).
The level of deployment is set to push commits on `master` as we commit frequently enough that there isn't a need to pollute the …
=> Finish adding deploy testing with TestPyPI

README.md
Resolves #410
For images in the README have their src target be the URL of their raw GitHub hosted versions and not a relative path inside the repo. The [reason for this is that](https://github.com/pypa/warehouse/issues/5246#issuecomment-451142432)
> PyPI does not support rendering from the package path itself, as it is not an image host.
and so without this the PyPI render will fail.
A working version of this can be seen on [TestPyPI release `0.0.17.dev22`](https://test.pypi.org/project/pyhf/0.0.17.dev22/) (note that this is `0.0.17.dev22` and not something expected like `0.0.18.dev1` as this PR branch was started before release `v0.0.17` of pyhf was cut and then rebased).
```
- Use GitHub hosted image URL as src targets for images in README to support PyPI render. …
```
=> Use GitHub hosted images as src target to support PyPI render

pyhf/commandline.py
This resolves #441. Uproot should not be required to use `pyhf`.
```
- writexml import is moved into the `json2xml` function.
```
=> Move writexml into the json2xml as uproot not required for pyhf usage

pyhf/utils.py
Applies Black formatting to a commit that snuck into PR #442 before CI was finished.
As to why this wasn't visually caught by me before I merged, I offer [the following suggested diff by Black](https://travis-ci.org/diana-hep/pyhf/jobs/522232858#L752-L756) :(
```
-    # space, where the p-values are Clsb = cdf(x-sqrt(lambda)) for  and CLb=cdf(x) 
+    # space, where the p-values are Clsb = cdf(x-sqrt(lambda)) for  and CLb=cdf(x)
#
-    
+
```
```
- Applies Black formatting to fix a formatting error in PR #442
```
=> Apply black

pyhf/commandline.py, pyhf/pdf.py, tests/test_scripts.py
An idea to inspect a given JSON and provide some summary information. Currently, output is as follows:
```
(pyhf) Lord Stark:~/pyhf (feature/inspect)$ pyhf inspect ~/Downloads/Excl-fit/Sig_MGPy8EG_A14N23LO_SM_Higgsino_130_100_2L2MET75_MadSpin_pruned.json 
Summary Statistics  
------------------  
channels  22
samples  7
parameters  88
modifiers  122
poi  mu_SIG
channels  nbins
----------  -----
CRtau_hghmet_met_Et    1  
SRee_eMLLf_hghmet_cuts    1  
SRee_eMLLd_lowmet_deltaM_low_cuts    1  
SRee_eMLLg_lowmet_deltaM_high_cuts    1  
CRVV_hghmet_met_Et    1  
SRee_eMLLf_lowmet_deltaM_low_cuts    1  
SRee_eMLLc_lowmet_deltaM_high_cuts    1  
SRee_eMLLc_lowmet_deltaM_low_cuts    1  
SRee_eMLLh_lowmet_deltaM_high_cuts    1  
CRtau_lowmet_met_Et    1  
SRee_eMLLg_hghmet_cuts    1 …
```
=> Add pyhf inspect

.travis.yml, docs/development.rst, pyproject.toml
The reasons for this are probably best given in [`pip` Issue 6434](https://github.com/pypa/pip/issues/6434) and [PR 6442](https://github.com/pypa/pip/pull/6442). In short, though, with `pip` `v19.1` enforces [PEP 517 which does not allow for editable mode installations](https://www.python.org/dev/peps/pep-0517/#get-requires-for-build-sdist)
> Editable installs
>
>This PEP originally specified another hook, install_editable, to do an editable install (as with pip install -e). It was removed due to the complexity of the topic, but may be specified in a later PEP.
As pyhf has a [`pyproject.toml` file for Black](https://github.com/diana-hep/pyhf/blob/f7d27c7c18c131c51b990dcc1b38ce0da577469d/pyproject.toml) this breaks the setup as there is no PEP yet to specify editable installations for …
=> Use --no-use-pep517 flag for editable mode with pyproject.toml

docs/examples/notebooks/multiBinPois.ipynb, setup.py, tests/test_notebooks.py
Resolves #419 
This PR updates to use papermill releases compatible with the [`v1.0.0`](https://pypi.org/project/papermill/1.0.0/) API. As part of that it also adds [nteract's scrapbook](https://github.com/nteract/scrapbook) as a dependency to replace papermill's [deprecated `pm.record` API](https://github.com/nteract/papermill/blob/d554193bc458797b63af1f94964883d5dcca2418/README.md#recording-values-to-the-notebook) with the [`scrapbook.glue` API](https://github.com/nteract/scrapbook/blob/96eab395e68069d5e775f01d587e16ef7ce39e01/README.md#glue-to-persist-scraps).
```
* Update papermill dependency to use releases compatible with v1.0
* Add scrapbook dependency to use the glue API to replace pm.record
- https://github.com/nteract/scrapbook
- …
```
=> Use papermill versions compatible with v1.0 and add scrapbook

docs/Makefile, docs/conf.py, docs/schemas
Amends PR #452
The docs were not publishing the schemas correctly because of how static files are actually treated. This fixes it with an explicit `rsync` into the folder we want. This is necessary to provide a public machine API for the time being.
```
- explicit rsync the pyhf/schemas folder into the build-directory to publish correctly. Amends PR #452.
```
=> Fix schema publishing to docs

pyhf/writexml.py, tests/test_export.py
In situations where, for example, sample-data is zero - this causes a runtime warning about divide (and returns a undefined instead of zero) when we need to convert from absolute uncertainties back to relative uncertainties. This is a slight drawback in the translation, but should not affect the end-results whether or not we choose to return undefined or zero if it's treated identically in both cases.
```
- only divide out sample data in cases where sample data is non-zero when exporting to XML
- this only affects modifiers that convert from absolute uncertainties back to relative uncertainties
```
=> fix divide to only divide non-zero pieces.

pyhf/pdf.py, tests/test_pdf.py
This adds a check and test to ensure we catch sample-channel size inconsistency.
```
- every sample in a given channel should have the same number of bins so we add a check for it
- additionally add a test to ensure that we're catching this appropriately
```
=> Add assertion and check for sample size consistency

pyhf/commandline.py, pyhf/exceptions/__init__.py, pyhf/optimize/__init__.py, pyhf/optimize/opt_scipy.py, pyhf/optimize/opt_tflow.py, pyhf/utils.py, setup.py, tests/test_optim.py, tests/test_scripts.py, tests/test_utils.py
This updates the other optimizers to accept `maxiter` as a keyword argument for configuration. We should just keep this pretty consistent. This makes it easier for us to configure from the command line now for CLs. This might not be the best option, since we might want to support something like a `dotenv` to load default backend/optimizer instead...? Unclear.
```
- raise an exception (InvalidOptimizer) if an optimizer is requested that does not exist
- allow for **kwargs for all optimizer initializations so we can extract out the additional options for configuration
- create click.ParamType (EqDelimStringParamType) to parse CLI options for configuring optimizer using equal-delimited key-value pairs, inspired by yadage
```
=> Add configurable optimizer (and options) through pyhf cls CLI

.travis.yml
For reasons unknown at this time, after PR #460 was successfully merged in PR #461 encountered a [memory error in Travis CI's Python 3.6 runtime environment in the Ubuntu Trusty dist](https://travis-ci.org/diana-hep/pyhf/jobs/527324500#L484-L486).
```
ERROR: python-coveralls 2.9.1 has requirement coverage==4.0.3, but you'll have coverage 4.5.3 which is incompatible.
ERROR: Error [Errno 12] Cannot allocate memory while executing command /home/travis/virtualenv/python3.6.3/bin/python -c 'import setuptools, tokenize;__file__='"'"'/home/travis/build/diana-hep/pyhf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
ERROR: Could not install packages due …
```
=> Don't cache pip installs for Python 3.6 in Travis to avoid memory EnvironmentError

pyhf/commandline.py
This fixes a bug introduced in #403, no `print` functions in the CLI. Only use `click.echo`.
```
This fixes a bug introduced in #403, no `print` functions in the CLI. Only use `click.echo`.
```
=> Remove print function in CLI

binder/postBuild
The `postBuild` file for Binder is breaking given the issues from pip v19.1 and PEP 517 that happened in PR #455. As Binder doesn't need to have an editable install of pyhf in it this can be resolved by not installing in editable mode, as there is no need for Binder.
```
- Follow up to PR #455
- Remove -e flag from pip install in postBuild to have Binder avoid issues with PEP 517 and pip
```
=> Remove editable flag for Binder to avoid PEP 517 issue with pip

.travis.yml
In Travis CI's [Trusty build environment](https://docs.travis-ci.com/user/reference/trusty/) there is an [apparent (not always reproducible) memory error](https://travis-ci.org/diana-hep/pyhf/jobs/529417919#L483-L486).
>    ERROR: Error [Errno 12] Cannot allocate memory while executing command /home/travis/virtualenv/python2.7.14/bin/python -c 'import setuptools, tokenize;__file__='"'"'/home/travis/build/diana-hep/pyhf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
ERROR: Could not install packages due to an EnvironmentError: [Errno 12] Cannot allocate memory
As this seems rather pathological the solution to ensure a CI that builds is to drop …
=> Add guard for Trusty build environments to prevent memory issues

docs/bib/talks.bib
Add the talk @lukasheinrich gave at the [May 2019 ATLAS Joint Machine Learning and Stats Fora Meeting](https://indico.cern.ch/event/817483/contributions/3412907/) that focused on likelihood preservation and statistical reproduction to the listed presentations in the docs.
```
- Add May 2019 ATLAS Joint Machine Learning and Stats Fora Meeting given by Lukas that focused on likelihood preservation and statistical reproduction. The talk is ATLAS internal.
c.f. https://indico.cern.ch/event/817483/contributions/3412907/
```
=> Add May 2019 Joint Machine Learning and Stats Fora Meeting talk

.travis.yml, docs/development.rst
With the [release of `pip` `v19.1.1`](https://github.com/pypa/pip/releases/tag/19.1.1) the decision was made to
> Restore ``pyproject.toml`` handling to how it was with pip 19.0.3 to prevent the need to add ``--no-use-pep517`` when installing in editable mode.
As such, the content of PR #455 is no longer needed and can be reverted to reduce complexity.
c.f.
- https://twitter.com/llanga/status/1125832882038235136
- https://github.com/pypa/pip/releases/tag/19.1.1
```
* Remove use of --no-use-pep517 flag from pip install with pip v19.1.1+
- https://twitter.com/llanga/status/1125832882038235136
- https://github.com/pypa/pip/releases/tag/19.1.1
* This PR essentially reverts PR #455 
```
=> Remove use of --no-use-pep517 flag from pip install with pip v19.1.1+

docs/bib/talks.bib
Add the talk @kratsg [gave at the SUSY 2019 conference](https://indico.cern.ch/event/746178/contributions/3396797/) that focused on publication and reinterpretation of likelihoods in the docs.
c.f. https://indico.cern.ch/event/746178/contributions/3396797/
```
- Add SUSY 2019 conference talkk by Giordon that focused on publication and reinterpretation of likelihoods
c.f. https://indico.cern.ch/event/746178/contributions/3396797/
```
=> Add SUSY 2019 conference talk

setup.py, tests/test_tensor.py
Resolves #482 
In TensorFlow `v1.14` [`tf.einsum`](https://www.tensorflow.org/api_docs/python/tf/einsum) is expecting Tensors. As such, ensure that in the `test_einsum` all inputs are in fact Tensors.
```
- Ensure that all inputs to the test_einsum test are Tensors
- Update minimum compatible version of TensorFlow to v1.14 to avoid future compatibility issues
```
=> Ensure inputs to tensor backend einsum test are tensors

pyhf/tensor/tensorflow_backend.py
Use `tf.math` names for [`tf.log`](https://www.tensorflow.org/api_docs/python/tf/math/log) and [`tf.is_finite`](https://www.tensorflow.org/api_docs/python/tf/math/is_finite) as these names are deprecated. Avoids the warning:
> The name `tf.X` is deprecated. Please use `tf.math.X` instead.
```
- Use tf.math names for tf.log and tf.is_finite as these names are deprecated. This avoids warnings.
```
=> Use updated TensorFlow names for math operations

.pre-commit-config.yaml, .travis.yml, MANIFEST.in, pyproject.toml, setup.py
This fixes a bug in the MANIFEST file where the schema paths were not updated.
I wonder why our tests did not catch this before, strangely.. but it doesn't error out.
```
* Update manifest to point to schemas/1.0.0 instead of just schemas/
* Add license to manifest
* Add check-manifest as dependency of develop option
* Add manifest check as test to Travis
```
=> Update MANIFEST.in with correct schema paths

.readthedocs.yml, docs/bib/docs.bib, docs/conf.py, docs/index.rst, docs/intro.rst, docs/likelihood.rst
This PR fleshes out our documentation so it is a little less bare-bones and gives people things to read and understand the history/background behind the project.
```
* Add background information on HistFactory
* Detail some of the mathematical formulation used in pyhf
* Add schema discussion in more detail
```
=> Flesh out base documentation with introduction/background/details

docs/examples/notebooks/binderexample/StatisticalAnalysis.ipynb, docs/likelihood.rst, pyhf/pdf.py, pyhf/readxml.py, pyhf/schemas/1.0.0/defs.json, pyhf/schemas/1.0.0/workspace.json, pyhf/writexml.py, tests/test_export.py, tests/test_import.py, tests/test_validation.py, tests/test_workspace.py
This is the last thing needed for the v1.0.0 of the JSON schema -- which is to switch out how we define the observed `data` of the workspace. I was initially lazy and defined it as a regular `object` which could've been anything... now we tighten up that definition ahead of release v1.0.0 of the schema.
This resolves #474.
```
- workspace 'data' renamed to 'observations'
- 'observation' specification is defined requiring a 'name' (channel) and 'data' (observations for that channel)
- code and tests are updated to reflect the change in the schema
- resolves #474
- additional test added to check that workspace data is retrieved correctly, and to handle situations in when the observed data requested for a channel does not exist
```
=> Update workspace specification to use 'observations' instead of 'data'

.travis.yml, pyhf/tensor/mxnet_backend.py, pyhf/tensor/numpy_backend.py, pyhf/tensor/pytorch_backend.py, pyhf/tensor/tensorflow_backend.py, pyhf/utils.py, setup.py
This PR contains changes to see how much of the current `setup.py` dependencies and `.travis.yml` definitions we can further simplify down. As we move from `trusty` entirely to `xenial`, this happens to mitigate #468 as well, by, well, uhh... running away from the problem. Additionally, this incorporates #439 with a nice regex since we're already going ahead and simplifying things further.
- Resolves #468
- Resolves #439
```
* Simplify .travis.yml by switching to using xenial for everything
* Don't run the full test suit on docs/ branches
- Only build and test the docs 
* Update existing backend signatures to use min_value/max_value instead of min/max for codefactor
* Simplify dependencies in setup.py as latest versions of various packages we pinned are behaving with …
```
=> Simplify Travis CI with use of Xenial distribution and update package dependencies

.travis.yml
Amends PR #491 and resolves #439 
As the `/^docs\//` branches are meant to focus on the docs only, build and test the docs on push commits to the docs branches. This will not build the docs on push builds of branches that don't match the desired pattern, as seen in the following screenshot
```
* Build and test the docs on push builds of /^docs\// branches
```
=> Always test the docs on docs branches

.travis.yml
Amends PR #487 
Given that [the Binder Federation](https://discourse.jupyter.org/t/the-binder-federation/1286) exists on both GKE and OVH there is no guarantee that the cluster that a build is triggered on is the same cluster that a user will be directed to when they launch the Binder. As a result, both clusters should be triggered when a PR is merged.
```
* Trigger Binder builds on both GKE and OVH clusters
```
=> Trigger Binder builds on both GKE and OVH clusters

docs/examples/notebooks/learn/InterpolationCodes.ipynb, docs/examples/notebooks/learn/TensorizingInterpolations.ipynb, docs/index.rst, docs/learn.rst, docs/likelihood.rst, tests/test_notebooks.py
This resolves #496. Learn notebooks are now added via `learn.rst` with the title `Fundamentals`.
Other titles considered:
- Foundations
- Learn the Fundamentals
- Learn Some Fundamentals
- Learn Some Concepts
- Underpinnings
- Tutorials
- Guides
- Learn the Code
- Learning Guides
- Learning Topics
- Learning
- Learnings
Related issues: #168, #325
```
- add learn notebooks to docs
- refactor notebook tests by making a fixture and splitting each notebook into an individual test
```
=> Add learn notebooks and split up notebook tests

docs/likelihood.rst
#497 snuck in a typo fix that wasn't perfect.
```
* Correct typo from ordering of old note
```
=> Fix the typo fix in the docs

docs/bib/posters.bib
Add BibTeX entry and link to SciPy 2019 proceedings:
http://conference.scipy.org/proceedings/scipy2019/slides.html
```
* Add BibTeX entry and link to the proceedings for poster shown by Matthew at SciPy 2019:
http://conference.scipy.org/proceedings/scipy2019/slides.html
* Poster LaTeX source found at: https://github.com/matthewfeickert/SciPy2019-Poster
```
=> Add SciPy 2019 poster BibTeX information

setup.py, src/pyhf/tensor/pytorch_backend.py
`torch.uint8` was deprecated in favor `torch.bool` for `torch.masked_select` in [PyTorch release `v1.2.0`](https://github.com/pytorch/pytorch/releases/tag/v1.2.0)
```
* Use torch.bool instead of torch.uint8 given deprecation for torch.masked_select in PyTorch release v1.2.0
- c.f. https://github.com/pytorch/pytorch/releases/tag/v1.2.0
* Require PyTorch version compatible with release v1.2.0
```
=> Use torch.bool over torch.uint8

CONTRIBUTING.md, docs/development.rst
Add the installation of the git pre-commit hook as part of the recommendations for contributing a PR. Additionally, update the [Black](https://github.com/psf/black) link endpoint to reflect that Black is now part of the Python Software Foundation :tada: &mdash; where it is now maintained for the whole community by awesome people like Carol Willing. :rocket: 
```
* Add installation of pre-commit for Git pre-commit hook to development recommendations in CONTRIBUTING
```
=> Add Git pre-commit hook install to CONTRIBUTING

src/pyhf/pdf.py
NB: This is progress towards Statisfactory.
This is a cute refactoring that, only through moving some code blocks around, basically puts the "main model" of histfactory on equal footing with the constraint pdfs.
i.e. a histfactory model can be viewed as a "joint pdf" of three subpdfs
`p(data,pars) =  p_main(maindata, pars) * p_gaus(gausdata,pars) * p_pois(poisdata,pars)`
```
self.main_model = MainModel(
self.config,
mega_mods=mega_mods,
nominal_rates=_nominal_rates,
batch_size=self.batch_size,
)
... snip ...
self.constraints_gaussian = gaussian_constraint_combined(
self.config, batch_size=self.batch_size
)
self.constraints_poisson = poisson_constraint_combined(
self.config, batch_size=self.batch_size
)
```
each of which provides the `logpdf` interface, also it decouples exactly how the …
=> Rewrite Model into PDF composition of MainModel and ConstrainedModel

README.md
Add the following GitHub Actions CI status badge to `README`
[![GitHub Actions Status](https://github.com/diana-hep/pyhf/workflows/CI/CD/badge.svg)](https://github.com/diana-hep/pyhf/actions)
This uses the workflow naming scheme (c.f. [Configuring a workflow: Adding a workflow status badge to your repository](https://help.github.com/en/articles/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository))
```
* Add a status badge to the README for the GitHub Actions CI
- c.f. https://help.github.com/en/articles/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository
```
=> Add GitHub Actions CI status badge to README

src/pyhf/exceptions/__init__.py, src/pyhf/pdf.py, tests/test_pdf.py, tests/test_validation.py
Resolves #554 
As `expected_result_1bin_lumi` is a 1 bin test it should not have 2 bins, which it erroneously had added in PR #352 .
This was caught by @lukasheinrich in PR #553, and is getting pulled out here.
```
* fix: Use 1 bin (instead of 2 bins) in the spec used in 'expected_result_1bin_lumi' to match the naming of the test
- This revises an error in PR #352
* feat: Verify parameter and data shapes during call to pdf.logpdf
* feat: Add exception classes for invalid pdf inputs
* test: Add tests for the input shape of the pdf parameters and data
```
=> fix: 1 bin lumi validation test

src/pyhf/constraints.py, src/pyhf/pdf.py, src/pyhf/probability.py, src/pyhf/tensor/common.py, src/pyhf/tensor/pytorch_backend.py
a demo PR against `add_probability_module` #551 showing how we will arrive at a pyfitcore like API
```
* extends pyhf.probability to have a joint pdf class pyhf.Simultaneous
* adapts pdf evaluation code to be thing layer around the pdf(pars).log_prob(data) pattern.
```
=> feat: Simultaneous pdf class

.github/workflows/ci.yml, .travis.yml, tests/conftest.py
A speed regression was introduced in PR #553 that caused the benchmark tests with the Minuit optimizer to take too long for 200 bins and cause the CI systems to timeout and fail. This is avoided here by using the [pytest keyword expression CLI flag of  `-k`](http://doc.pytest.org/en/latest/example/markers.html#using-k-expr-to-select-tests-based-on-their-name) to skip the 200 bin Minuit test.
From `man pytest`:
```
SPECIFYING TESTS / SELECTING TESTS
Several test run options:
...
py.test -k stringexpr # only run tests with names that match the
```
Skipping `numpy_minuit-200_bins` saves enough time that the CI systems finish. As tests of this see
- GitHub Actions: [run 227963902](https://github.com/diana-hep/pyhf/runs/227963902)
- Travis CI: [build …
=> fix: Avoid benchmark timeout in CI systems

tests/test_probability.py
Resolves #568 
`test_normal` in `tests/test_probability` is hidden from pytest by an accidental renaming of `test_normal` which is actually testing the `Independent` class. As such, rename the second test to run both.
```
* fix: Rename the test_probability test that tests the Independent pdf class to test_independent to unhide test_normal from pytest
```
=> fix: Unhide test_normal by renaming redundant name to test_independent

README.md
Given that [Semmle was acquired by GitHub](https://blog.semmle.com/secure-software-github-semmle/) and so LGTM is now going to become part of the GitHub toolchain in the coming months I've added LGTM to the code checks now. As it seems that Landscape's Code Health is no longer reliable then I think it makes sense to replace it with LGTM's Code Quality badge instead.
[![Language grade: Python](https://img.shields.io/lgtm/grade/python/g/diana-hep/pyhf.svg?logo=lgtm&logoWidth=18)](https://lgtm.com/projects/g/diana-hep/pyhf/latest/files/)
```
* docs: Drop landscape.io code health in favor of LGTM code quality summary badge
```
=> docs: Use LGTM code quality badge in README

.github/workflows/ci.yml, .travis.yml
Effectively revert PR #571 by removing the skip of NumPy+Minuit 200 bin benchmark.
This is contingent on PR #576 being merged into `master`.
```
* revert: Remove the skip of the NumPy+Minuit 200 bin benchmark test that was added in PR #571 to avoid CI failure due to a performance regression
```
=> revert: Remove skip of NumPy+Minuit 200 bin benchmark

.github/workflows/ci.yml
[Now that the MacOS environment seems to play nice with Python](https://github.com/actions/setup-python/issues/13) it can be incorporated into the testing suite. Additionally, avoid linting the same code multiple times by just giving this responsibility to Python 3.7 on Ubuntu.
```
* ci: Add MacOS testing environment to GitHub Actions CI
* ci: Lint only on Python 3.7 in the Ubuntu testing environment to avoid linting the same code multiple times
```
=> ci: Add MacOS testing environment to GitHub Actions CI

setup.py
Add an upper bound of [TensorFlow Probability `v0.7`](https://github.com/tensorflow/probability/releases/tag/v0.7). This is a temporary fix as the releases schedule of TensorFlow `v1.15` and [TensorFlow `v2.0`](https://github.com/tensorflow/tensorflow/releases/tag/v2.0.0) were not properly synced.
[TensorFlow `v2.0`](https://github.com/tensorflow/tensorflow/releases/tag/v2.0.0) was released first, but at its release time Tensorflow `v1.15` was still a release candidate ([`v1.15.0-rc2`](https://github.com/tensorflow/tensorflow/releases/tag/v1.15.0-rc2)). [TensorFlow Probability `v0.8`](https://github.com/tensorflow/probability/releases/tag/v0.8) was then released to support TensorFlow `v2.0`, but it only supports TensorFlow `v2.0` and TensorFlow `v1.15` which wasn't released at time of its …
=> fix: Add upper bound on TensorFlow Probability to avoid TensorFlow compatibility conflict

.github/workflows/ci.yml
Test the example notebooks separately from the source code so that the test will finish faster. This also isolated the source code testing from the example documentation testing.
```
* Test the example notebooks in a separate GitHub Action to isolate the source code tests from example documentation tests and speedup total testing
```
=> ci: Test example notebooks separately

.github/workflows/ci.yml
Avoid the following warning to prevent errors:
[##[warning]Input 'version' has been deprecated with message: The version property will not be supported after October 1, 2019. Use python-version instead](https://github.com/diana-hep/pyhf/runs/245116353#step:3:1)
```
* ci: Use 'python-version' keyword in GitHub Actions as 'version' is deprecated and can cause errors after 2019-10-01
```
=> ci: Use 'python-version' keyword in GitHub Actions

.travis.yml
Drop testing the notebooks in Python 2.7
```
* ci: Drop testing the notebooks in Python 2.7 to avoid errors given the near horizon of Python 2's sunsetting
```
=> ci: Drop Python 2.7 testing of notebooks

.coveragerc, .github/workflows/ci.yml, .gitignore, .travis.yml, README.md, pytest.ini, setup.py
Drop Coveralls in favor of [Codecov's GitHub Action](https://github.com/codecov/codecov-action) to report code coverage. [![Code Coverage](https://codecov.io/gh/diana-hep/pyhf/graph/badge.svg?branch=master)](https://codecov.io/gh/diana-hep/pyhf?branch=master)
Adds a generic [`.coveragerc`](https://gist.github.com/codecov-io/bf15bde2c7db1a011b6e)
```
* ci: Drop Coveralls in favor of Codecov
- Drop 'python-coveralls' library dependency
* ci: Use Codecov's GitHub Action to upload coverage and avoid 'codecov' library dependency
- Uses an XML report format
- Add a generic .coveragerc as recommended.
```
=> ci: Use Codecov GitHub Action to report coverage

.github/workflows/ci.yml, .github/workflows/deploy.yml, .github/workflows/merged.yml, .travis.yml
~~Do all testing in GitHub Actions and then have Travis CI be responsible for releases.~~ The setup action for Python 2.7 seems to be broken at the moment, so still use Travis for Python 2.7 testing. At the moment this still requires Travis CI to run one version of the test suite as Coveralls needs to be run.
~~Perhaps this is a good time to try to figure out how to get Coveralls to run in GitHub Actions as well.~~ Changed from Coveralls to Codecov in PR #598 
~~* ci: Have GitHub Actions be responsible for all testing and benchmarks~~
~~* ci: Migrate Coveralls to GitHub Actions~~
```
* ci: Have GitHub Actions be responsible for all Python 3 testing (Travis CI only tests Python 2.7)
- Travis CI is still responsible for releases
* ci: Add merged workflow to GitHub …
```
=> ci: Use Travis CI only for Python 2.7 testing and releases

src/pyhf/commandline.py, src/pyhf/interpolators/code4.py
Address the following LGTM alert:
> Result of division may be truncated as its left and right arguments may both be integers.
and the following LGTM error:
> Keyword argument 'exist_ok' is not a supported parameter name of function makedirs.
The false error above is due to LGTM thinking that the codebase is Python 2 as we have say that it is in our `setup.py`
```
* Fix LGTM alert: Result of division may be truncated as its left and right arguments may both be integers
* Ingore LGTM error: Keyword argument 'exist_ok' is not a supported parameter name of function makedirs
- This is a false error that will be irrelevant once Python 2 support is dropped
```
=> fix: Address LGTM division alert

src/pyhf/interpolators/code0.py, src/pyhf/interpolators/code1.py, src/pyhf/interpolators/code2.py, src/pyhf/interpolators/code4.py, src/pyhf/modifiers/histosys.py, src/pyhf/modifiers/lumi.py, src/pyhf/modifiers/normfactor.py, src/pyhf/modifiers/normsys.py, src/pyhf/modifiers/shapefactor.py, src/pyhf/modifiers/shapesys.py, src/pyhf/modifiers/staterror.py, src/pyhf/tensor/common.py, src/pyhf/tensor/mxnet_backend.py, src/pyhf/tensor/numpy_backend.py, src/pyhf/tensor/pytorch_backend.py, src/pyhf/tensor/tensorflow_backend.py, src/pyhf/utils.py, tests/conftest.py, tests/test_combined_modifiers.py, tests/test_probability.py, tests/test_tensor.py
Resolves #295
Remove or reduce the guarding `self.astensor()` calls in the methods of the tensor backends. This makes it more explicit that tensors are required, move the responsibility to the user to format their data correctly, and should add a speedup by dramatically reducing the number of `self.astensor()` calls.
```
* perf: Remove all non-essential 'self.astensor' calls from the tensor backend methods
* Replace custom instances of 'where' with tensor library versions for TensorFlow, PyTorch, and MXNet backends
- Uses: tf.compat.v2.where, torch.where, nd.where
* Make masks used in 'tensorlib.where' explicit bools
* docs: Update the docstring examples for the tensor backends
* test: Make all relevant arguments tensors in test_tensor.py
```
=> perf: Effectively remove the use of self.astensor() in tensor backend calls

.github/workflows/ci.yml, setup.py, src/pyhf/probability.py, src/pyhf/tensor/tensorflow_backend.py
Should be done _after_ PR #588 is merged.
Amend the docstrings added in PR #558.
- Some docstrings that were added in https://github.com/diana-hep/pyhf/commit/4e5acc3f8fc86da6f8e0cb0a795c24ab494c02de somehow got removed from the final PR
- For methods that are repeated across distributions use the same docstring for consistency
- Additionally fix some typos
```
* docs: Amend the docstrings for the probability module to include missing docstrings and fix typos and enforce consistency
* tests: Add probability module to pydocstyle testing
```
=> docs: Use consistent style in docstrings

LICENSE, setup.py
Add the pyhf authors to the Apache license. This should have been done at license creation, but was missed, as it isn't done automatically by GitHub for Apache as it is for BSD3 and MIT.
```
* Add pyhf author names to setup.py
* Add the pyhf developers to the Apache license as the copyright holders
```
=> docs: Add copyright holders to license

docs/governance/ROADMAP.md, tests/test_regression.py, tests/test_validation.py
Resolves #518 
Add a regression test that uses the observed and expected CLs values of the [ATLAS sbottom published likelihood](https://www.hepdata.net/record/ins1748602)
```
* Add regression test on ATLAS sbottom public likelihood
- c.f. https://www.hepdata.net/record/ins1748602
```
=> test: Add regression test on ATLAS sbottom public likelihood

docs/bib/talks.bib, docs/bib/tutorials.bib, docs/talks.rst
Add talks, seminars, and tutorials that have been given up through October 2019. Add a tutorial section to the talks webpage.
```
* Add Matthew PyHEP 2019 talk
* Add Lukas CERN seminar "HEP in the Cloud Computing and Open Science Era" that shows a pyhf example
* Add Giordon West Coast LHC Jamboree 2019 talk
* Add Lukas "Introduction to pyhf" tutorial given at the 2019 ATLAS Induction Day + Software Tutorial
* Add Lukas DESY stats school 2019 talk that demos pyhf
```
=> docs: Add talks, seminars, and tutorials up through October 2019

setup.py
Revert upper bound on TensorFlow Probability introduced in PR #592 and instead use a release of tfp that is compatible with TensorFlow v1.15, as it is the last TF v1.0 API release.
This should go in before release `v0.1.3` is cut.
```
* Use a release of tfp that is compatible with TensorFlow v1.15
- TensorFlow v1.15 is the last TF v1.0 API release
- Effectively reverts PR #592
* Use a NumPy release compatible with TensorFlow v1.15 requirements
```
=> revert: Use TensorFlow Probability release compatible with TensorFlow v1.15

.github/workflows/ci.yml, .travis.yml
Move deployment of the docs from Travis CI to GitHub Actions. This is motivated by the fact that [Travis CI is currently failing to build the docs due to changes on their end](https://travis-ci.org/diana-hep/pyhf/builds/607366695).
```
* Move deployment on the docs from Travis CI to GitHub Actions
```
=> ci: Migrate docs deployment to GitHub Actions

.github/workflows/ci.yml
In GitHub Actions the 'platform' matrix API was changed to 'os' when GitHub Actions was made stable at the end of the public beta. This API change should be adopted.
```
* Adopt the stable GitHub Actions 'os' matrix API instead of the legacy 'platform'
```
=> ci: Use GitHub Actions os API

.github/workflows/ci.yml
`check-manifest` is being run in the "Check MANIFEST" stage so there is no need to run it also in the "Lint with Pyflakes" stage. It seems [this was a typo on my part a long time ago](https://github.com/diana-hep/pyhf/pull/527/files#diff-e9f950f17198d3d5e3122a44230a09b9R33).
```
* Remove redundant check-manifest in the pyflakes lint stage
```
=> ci: Remove redundant check-manifest

tests/test_regression.py
The DOI (https://doi.org/10.17182/hepdata.89408.v1/r2) is shorter and more clear then the HEPData resource number (https://www.hepdata.net/record/resource/997020?view=true).
```
* The DOI (https://doi.org/10.17182/hepdata.89408.v1/r2) is shorter and more clear then the HEPData resource number (https://www.hepdata.net/record/resource/997020?view=true)
```
=> chore: Use DOI endpoint API for sbottom likelihood

.pre-commit-config.yaml
Don't hard code a minor release of Python as a language version. Instead just use a major release.
```
* Set language_version to Python 3 in .pre-commit-config.yaml
```
=> chore: Use python3 for precommit language version

.github/workflows/publish-package.yml, .travis.yml, README.md, docs/development.rst, docs/governance/ROADMAP.md, setup.py
Resolves #508
Migrate the publication of the distributions from Travis CI to GitHub Actions using the [PyPA's "PyPI publish GitHub Action"](https://github.com/pypa/gh-action-pypi-publish) using [PyPI's API token](https://pypi.org/help/#apitoken). This workflow publishes to TestPyPI on every commit to `master` and published to PyPI on every tag that is pushed to `master`. Thus, to publish, one simply just needs to run `bumpversion` on `master` and then do `git push origin master --tags`.
Many thanks go to the PyPA team for their tool and their [well written guide to it](https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/), and special thanks go to @webknjaz for his long patience and helpful advice. This workflow is based off of …
=> ci: Migrate publishing from Travis CI to GitHub Actions

.github/workflows/publish-package.yml, pyproject.toml
Fixes #638
This PR needs to add `[build-system]` in [pyproject.toml](https://github.com/diana-hep/pyhf/blob/52a02de19f848e12b74f5b87de0ac9c8e60da42b/pyproject.toml) which was missing in order to run the `pypa-publishing` recipe introduced in #638. Additionally, we didn't catch this because the test workflow wasn't being run to check if we could build... now we check and we're good to go.
```
* Fixes PR #638
* Add build-system in pyproject.toml which was missing in order to run the PyPA-publishing recipe introduced in #638
* Make sure workflow for publish builds packages, but does not publish to TestPyPI
```
=> fix: Add build-system to pyproject.toml

.github/workflows/publish-package.yml, setup.py
This adds in changes to #639. GHA triggers pushes on PRs as well... so you can't tell if a push event comes from a PR or not. Also need to fix logic of whether to use `scm` or not depending on if we're tagged or not.
```
* More fixes to workflow in #639, only push to testpypi on pushes on master
* Only use scm if the current commit is not tagged
* Protect forks from publishing
```
=> fix: Correct reference check in GitHub Actions publish to TestPyPI step

.github/PULL_REQUEST_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE/Bug-Fix.md, .github/PULL_REQUEST_TEMPLATE/Feature.md, .github/workflows/merged.yml, .github/workflows/publish-package.yml, CONTRIBUTING.md, README.md, docs/_templates/modifierclass.rst, docs/bib/docs.bib, docs/conf.py, docs/development.rst, docs/examples.rst, docs/examples/notebooks/binderexample/StatisticalAnalysis.ipynb, docs/faq.rst, docs/governance/ROADMAP.md, docs/index.rst, docs/installation.rst, docs/likelihood.rst, setup.py, src/pyhf/schemas/1.0.0/defs.json, src/pyhf/schemas/1.0.0/measurement.json, src/pyhf/schemas/1.0.0/model.json, src/pyhf/schemas/1.0.0/workspace.json, src/pyhf/utils.py
Migrate from the [DIANA/HEP](https://github.com/diana-hep) GitHub org to the [Scikit-HEP](https://github.com/scikit-hep) org
```
* Replace all instances of diana-hep with scikit-hep
```
=> chore: Migrate from diana-hep GitHub org to scikit-hep

.github/workflows/merged.yml
Promoting
```yaml
if: github.event.pull_request.merged
```
to the job level avoids errors like
https://github.com/scikit-hep/pyhf/pull/645/checks?check_run_id=312835964
or having to have the check for every step in the job
```
* Promote github.event.pull_request.merged check to the job level to avoid errors
```
=> fix: Promote check on PR merge to job level

.github/workflows/release_tests.yml, .gitignore, tests/conftest.py, tests/test_public_api.py
- Resolves #609 
- Resolves #605 
Add canary tests and GitHub Actions workflow to check if the current release of pyhf on PyPI is functional and able to work with the current API.
```
* Add GitHub Actions workflow to nightly check if the current release of pyhf on PyPI is valid for the public API
* Add canary tests of the public API
- Runs on both GitHub in CI and in against the releases from PyPI
* Use tf.compat.v1.Session to avoid warning
```
=> test: Add public API canary tests to CI and nightly tests for current PyPI release

.github/workflows/ci.yml, setup.py
Add further segmented `test`, `docs`, and `develop` environments in `setup.py` to avoid having to install unneeded dependencies.
This makes very little difference in terms of core developer operations, but the finer segmentation makes it easier to understand what all the dependencies a core developer would install are meant for.
```
* Redistribute the "develop" environment into separate "test", "docs", and "develop" environments
- "docs" contains all of the backend environments to successfully build all the API docs
- "develop" still combines "test", "docs", and the "develop" dependencies together
* Use more specific environments for testing in CI to make environment dependencies more clear
* In doing so, fix the API section of the docs by building the docs in an …
```
=> refactor: Add better segmented environments

src/pyhf/modifiers/histosys.py, src/pyhf/modifiers/lumi.py, src/pyhf/modifiers/normfactor.py, src/pyhf/modifiers/normsys.py, src/pyhf/modifiers/shapefactor.py, src/pyhf/modifiers/shapesys.py, src/pyhf/modifiers/staterror.py, src/pyhf/pdf.py, tests/test_combined_modifiers.py
This reorders mega mods to be first indexed by modifier name and then by sample. This should make it connect pyhf to (differentiable) upstream tools, as typically they will be able to process all samples for a given systematic setting (modifier) in one go
```
* change order of samples and modifier names in mega mods
* preparation for connecting to differentiable upstream
```
=> refactor: Reorder mega mods to be indexed first by modifier then by sample

.github/workflows/release_tests.yml
Install missing `pytest` (`v3`) and `pytest-cov` to ["Current release" tests](https://github.com/scikit-hep/pyhf/blob/0e56c6c2e4470b5dc2ad8fb02d1afeeb4184ec18/.github/workflows/release_tests.yml). This was forgotten in PR #611
Please describe the purpose of this pull request in some detail. Reference and link to any relevant issues or pull requests.
```
* Add pytest dependency to install
- pytest is regulated to be below v4.0 as pyhf isn't compliant with modern pytest
* Fixes bug introduced in PR #611
* Run "Current release" tests on PRs as well as on a daily schedule
```
=> fix: Add missing pytest dependencies to Current Release tests

src/pyhf/commandline.py, src/pyhf/mixins.py, src/pyhf/pdf.py, src/pyhf/workspace.py, tests/test_mixins.py, tests/test_workspace.py
This adds a channel summary mixin to be used by any object that needs a summary of the channel information in the spec they're using. This will apply to both `pyhf.Workspace` and `pyhf.pdf._ModelConfig`.
The end goal, if it's not obvious, is that unlike `pyhf.Model` which doesn't currently have a spec.. I want the `pyhf.Workspace` to be a "light" layer on top of the `workspace.json` spec we have. This means that we should do (directly)
```python
spec = pyhf.Workspace(json.load(open('spec.json')))
assert spec['version'] == 1.0.0
assert 'signal' in spec.samples
```
where it quacks like a python dictionary, but has some extra niceties such as being able to build a model from it, or listing summary information about itself. 
You might ask, well, why not just provide a …
=> feat: Add Channel summary mixin, JSON-serializable workspace object

docs/_templates/modifierclass.rst, docs/api.rst, docs/cli.rst, docs/conf.py, docs/index.rst, setup.py, src/pyhf/cli/cli.py, src/pyhf/cli/spec.py, src/pyhf/exceptions/__init__.py, src/pyhf/schemas/1.0.0/model.json, src/pyhf/schemas/1.0.0/workspace.json, src/pyhf/workspace.py, tests/test_schema.py, tests/test_scripts.py, tests/test_workspace.py
This requires:
- #657
- #656
Addresses (but does not resolve) an issue in #660 with `pyhf.Workspace` not showing up in our docs.
Resolves #663.
```
* Add specification operations to the workspace (prune, rename, combine)
* Add CLI entrypoints for prune, rename, combine
* Add API docs
* Update doc dependencies
* Fix docstrings for workspace.py
```
=> feat: pyhf spec CLI

.github/workflows/ci.yml, README.md, src/pyhf/pdf.py
* adds `pydocstyle` testing (on pdf.py only for now) to CI
* makes pdf.py pass pydocstyle
Adresses #97 
```
* Add pydocstyle to "develop" environment requirements
* Add pydocstyle testing (on pdf.py only for now) to CI
* Add docstrings to all public classes and methods in 'pdf.py'
```
=> ci: Use pydocstyle

.github/workflows/ci.yml, .github/workflows/merged.yml, .github/workflows/publish-package.yml, .github/workflows/release_tests.yml
With the release of the [beta of `v2` of the GitHub checkout action](https://github.com/actions/checkout/releases/tag/v2-beta) breaking the CI it is probably worth pinning all GitHub Actions to stable releases instead of `@master`.
```
* Pin checkout action to release v1.2.0
* Pin codecov action to release v1.0.4
```
=> ci: Pin GitHub Actions release versions to stable tags

src/pyhf/utils.py
Use the [`~`](https://www.sphinx-doc.org/en/1.5/markup/inline.html#cross-referencing-syntax) cross-referencing syntax instead of a hyperlink to dynamically link to functions in the codebase in the docs (results in _Model_ instead of `pyhf.pdf.Model`).
Thanks to @kratsg for pointing this out in PR #617.
```
* Use ~ instead of a hyperlink to dynamically link to functions in the codebase in the docs
- c.f. https://www.sphinx-doc.org/en/1.5/markup/inline.html#cross-referencing-syntax
```
=> docs: Use Sphinx cross-referencing '~' syntax to dynamically link the codebase

docs/faq.rst, src/pyhf/cli/stats.py, src/pyhf/utils.py, tests/test_scripts.py
Add ability to change the computational backend used by `pyhf` from the command line with a `--backend` flag.
**Example:**
```
$ curl -sL https://git.io/fjxXE | pyhf cls
{
"CLs_exp": [
0.07807427911686152,
0.17472571775474582,
0.35998495263681274,
0.6343568235898907,
0.8809947004472013
],
"CLs_obs": 0.3599845631401913
}
$ curl -sL https://git.io/fjxXE | pyhf cls --backend pytorch
{
"CLs_exp": [
0.07808291912078857,
0.1747395098209381,
0.36000293493270874,
0.6343730092048645,
0.8810024857521057
],
"CLs_obs": 0.3600029945373535
}
$ curl -sL https://git.io/fjxXE | pyhf cls --backend tensorflow
{
"CLs_exp": [
0.0780724585056305,
0.17472276091575623,
0.35998106002807617,
0.6343533396720886,
0.8809930086135864
],
"CLs_obs": 0.35998106002807617
}
```
```
* Add backend …
```
=> feat: Add backend option to pyhf CLI

src/pyhf/readxml.py, src/pyhf/writexml.py, tests/test_export.py, tests/test_import.py
This resolves #661. This allows for importing xml/exporting json of the NormFactor parameter configurations. 
A very strong assumption is made on import (checked via deduplication) that NormFactors (and the set of parameter configs grabbed from the channel specifications) do not conflict with one another. These parameter configurations are stored for all measurements.
A second assumption on import is that NormFactors defined `const` in ParamSetting override NormFactor settings.
A strong assumption is made on export that, for NormFactor, the first measurement should have all the same parameter configurations as the rest of the measurements (if there are more than one measurement). The Val/Low/High parameter configuration is only extracted from the first measurement and stored in the …
=> feat: normfactor import/export parameter configuration

.github/workflows/ci.yml
From the [ghaction-github-pages](https://github.com/crazy-max/ghaction-github-pages) section of the README on [Limitations of GitHub Actions](https://github.com/crazy-max/ghaction-github-pages#warning-limitation):
> Currently, `GITHUB_TOKEN` [does not suffice to trigger a page build](https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/m-p/26869) on a **public repository** (propagate content to the GitHub content-delivery network). You must therefore create a custom [Personal Access Token](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/) and use it through the `GITHUB_PAT` environment variable:
>
>```yaml
>- name: Deploy
>  if: success()
>  uses: crazy-max/ghaction-github-pages@v1
>  with:
>    target_branch: …
```
=> ci: use personal access token for gh-pages deployment

docker/Dockerfile
In PR #676 the `_is_test_pypi` was removed as it was discovered that it wasn't needed for CI to pass. However, removing it caused issues in the Docker image build on Docker Hub as a result of `setuptools-scm` looking for `.git`
>     LookupError: setuptools-scm was unable to detect version for '/code'.
>    
>    Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
Adding git to the image fixes these problems.
Also use `COPY` instead of `ADD` as `COPY` is considered best practice over using `ADD` unless `ADD`'s tar and remote URL capabilities are needed.
c.f.
- …
=> fix: Add git to Docker image during build to avoid setuptools-scm error

.github/workflows/ci.yml
Resolves #681 
Following up PR #680, add a test build of the Docker image ~~on `pull_request` events~~ to the CI to ensure that it should get properly built by Docker Cloud
```
* Add a test build of the Docker image to the CI 
```
=> ci: Add test build of the Docker image to the CI

.github/workflows/ci.yml, .readthedocs.yml, docs/conf.py, docs/installation.rst, setup.py
This allows RTD to only build and mock the necessary things (also makes it so docs can build without needing to install all the packages that pyhf depends on!)
```
* Create a 'backends' extra for installing all the supported backends
* Make the docs and test options for installing separate
* Mock the packages that are not needed to build the docs, but to make sure all pyhf modules are imported
```
=> refactor: Create 'backends' extra

docs/babel.rst, docs/index.rst
This adds documentation in `docs/babel.rst` that describe how to extract the HistFactory workspaces for use by `pyhf xml2json`.
```
* Add documentation for HistFitter users on extracting HistFactory workspaces
```
=> docs: add babel to describe HistFitter to pyhf workflow

codecov.yml, pyproject.toml
Allow a `0.2%` tolerance on the project coverage and still allow CI to pass.
This PR has been demoed/tested in PR #690 
```
* Add codecov.yml file to allows a 0.2% tolerance on the project coverage
* Add codecov.yml to the MANIFEST ignore
```
=> ci: Add Codecov threshold tolerance

docker/Dockerfile
Resolves #692 
To be able to drop Python 2 we will need to move away from the Python 2.7 Alpine Docker image that is used as the base image for the pyhf Docker image. This replaces it with a [Python 3 Docker image](https://github.com/matthewfeickert/python3-scipy-alpine).
This image uses the `py3-scipy` `apk` package, and so while not quite as small as the installed form PyPI scipy image (Python 2.7) it is just a few MB larger and could be brought down
```
$ docker images | grep scipy
matthewfeickert/python3-scipy-alpine                     latest              fba7df6a582c        2 hours ago         292MB
alectolytic/scipy                                        latest              00f11a79976b        15 months ago       276MB
```
which I think is pretty good.
```
* …
```
=> ci: Use Python 3 scipy Alpine image for base Docker image

docker/Dockerfile
Enables
```
jsonpatch lhood.json patch.json | docker run -i pyhf/pyhf cls
```
```
* Add ENTRYPOINT to the pyhf Dockerfile to run the pyhf CLI by default
```
=> feat: Add ENTRYPOINT to pyhf Docker image

src/pyhf/infer/__init__.py, src/pyhf/infer/utils.py
together with #690 src/pyhf/infer should pass pydocstyle
```
* Add pydocstyle compliant docstrings to the infer module
```
=> docs: add docstrings for src/pyhf/infer

binder/postBuild
PR #699 got merged before I could implement @cranmer's [comment](https://github.com/scikit-hep/pyhf/pull/699#issuecomment-567546289). This addresses it by adding Altair in the Binder `postBuild`.
```
* pip install Altair dependency in Binder postBuild (amends PR #699)
* Use python -m pip for best pip practices
```
=> fix: Add Altair dependency to Binder postBuild

.github/workflows/tag.yml
When a PR is labeled with one of the following:
- `bumpversion/major`
- `bumpversion/minor`
- `bumpversion/patch`
The workflow will trigger. This will run `bumpversion $part`, update the commit to refer to the issue number filed, and update the tag to summarize the commits since the previous tag to the new tag.
The changes will be commit messages that follow the semantic format `$semantic: $description`.
When the PR is merged in, then the commit and tag will be pushed to master as well (using a personal access token) which will trigger the publish release.
Successful action (PR from branch):
- [on labeling PR](https://github.com/kratsg/github-action-test/runs/315583006)
- [on merging labeled PR](https://github.com/kratsg/github-action-test/runs/315585704)
Failed action (PR from fork):
- …
=> ci: workflow that runs bumpversion and pushes when issue filed

.github/workflows/ci.yml
Move the reporting of coverage with Codecov to be after the main test suite is run to ensure the correct `coverage.xml` file is uploaded by Codecov. Fixes PR #694.
In PR #694 the testing of the `pyhf.contrib` module was added, but this runs `pytest` again and overwrites the `coverage.xml` file that previously existed. So the coverage that Codecov uploads is the coverage of `pyhf.contrib` and not the rest of the `src` directory.
The final result of this is that coverage reporting is fixed, and `pyhf.contrib` is tested without having coverage reporting &mdash; which is the desired behavior.
```
* Report coverage of src with Codecov before the coverage.xml is overwritten by testing pyhf.contrib
- Amends PR #694
* Update Codecov GitHub Actions app to v1.0.5
```
=> fix: Correct order of Codecov reporting in CI

.github/workflows/ci.yml, .github/workflows/release_tests.yml
The GitHub Actions [`matrix` context](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/contexts-and-expression-syntax-for-github-actions#contexts) has changed the API to use all lowercase parameters, so the [`matrix.os` parameter names](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idruns-on) should follow suit with `macos-latest` instead of using the deprecated `macOS-latest`. 
```
* Change the 'matrix.os' parameter names to be all lowercase, following a change in the API
```
=> ci: Use lowercase OS names to match API

README.md, docs/index.rst
Resolves #713 
To make it easier to get from the docs website to the GitHub project page, ~~convert the "Fork me on GitHub" ribbon on the docs page to a "Check us out on GitHub" ribbon. This makes forking the project 2 steps rather than 1, but I don't think that's in anyway a serious issue.~~ add a badge to the README that links to the GitHub project and uses the shields.io social style:
[![GitHub Project](https://img.shields.io/badge/GitHub--blue?style=social&logo=GitHub)](https://github.com/scikit-hep/pyhf)
```
* Add a badge to the README that links to the GitHub project
```
=> docs: Directly link to GitHub project page from docs website

docs/governance/ROADMAP.md, setup.py, src/pyhf/__init__.py, src/pyhf/cli/infer.py, src/pyhf/optimize/opt_tflow.py, src/pyhf/tensor/tensorflow_backend.py, tests/conftest.py, tests/test_backend_consistency.py, tests/test_tensor.py
Resolves #539 
Instead of adding conditional control flows through PR #535 and PR #537 in support of PR #534 , PR #534 will be delayed in favor of migrating to TensorFlow v2.0, where eager evaluation will avoid the issues that PR #535 and PR #537 addressed.
```
* Migrate the TensorFlow backend and optimizer to TensorFlow v2.0 / deprecate TensorFlow v1.0 behavior
- Changes evaluation from lazy (v1.0) to eager (v2.0 default)
* Require TensorFlow and TensorFlow Probability releases compatible with TensorFlow v2.0
* Simplify test configuration with deprecation of TensorFlow v1.0 Sessions
```
=> feat: Migrate to TensorFlow v2.0

src/pyhf/optimize/opt_minuit.py
It seems there's a typo in the minuit optimiser and it can never be set verbose. This MR should fix it.
Note that I have problems setting up all the test dependencies (notably tensorflow 1 seems to be hard to install these days now that v2 is default). Let's see what GitHub Actions have to say.
=> fix: Correct iminuit optimizer verbose setting typo

.github/workflows/release_tests.yml
The public release canary is failing when we added `jax` because `jax` wasn't added as an install there. Instead, switch to using the `backends` option for this purpose.
```
- switch to using the [backends] option for public release canary test
```
=> fix: Public release canary should be using [backends] option

.github/workflows/ci.yml, docs/faq.rst, docs/governance/ROADMAP.md, docs/installation.rst, pyproject.toml, setup.py, src/pyhf/cli/rootio.py, src/pyhf/infer/mle.py, src/pyhf/optimize/opt_minuit.py, src/pyhf/pdf.py, tests/test_notebooks.py, tests/test_scripts.py
Resolves #469
On ~~December 28th, 2019~~ January 13th, 2020 pyhf will drop support for Python 2.7. This PR implements that change.
This PR makes the codebase Python 3 _only_. I think that this is fine to do, given that pyhf is currently something a standalone tool that is run as in independent step in an analysis. So if a user only has access to Python 2 we can suggest that:
* If the user is on LXPLUS then they can setup Python 3 environment (there is a Red Hat Python 3.6 runtime with `source scl_source enable rh-python36`) and use that, as thanks to uproot any step that involves pyhf can be run in isolation from any ENV that requires ROOT
* If they are running on a local machine then we can try and point them to the best resources on how to get a Python 3 runtime with minimal pain
* …
=> feat: Drop Python 2.7 support

.github/workflows/ci.yml, docs/exts/xref.py
this runs pyflakes on the full source tree including docs.
@kratsg that variable seems to never have been used. What was this for originally?
```
* Run pyflakes over the full codebase, including docs
```
=> chore: Run pyflakes over the full codebase

src/pyhf/pdf.py
this simplifies the `_ModelConfig` `__init__` method and encapsulates the code that needs the JSON structure (somewhat related to #742 ) so that it could be replaced maybe by something non-JSON-y
This is a simple refactor.
```
* refactor spec usage into standalone parsing function
```
=> refactor: standalone spec parsing for parameters

src/pyhf/cli/spec.py, src/pyhf/workspace.py, tests/test_workspace.py
This PR will resolve a nagging issue with @kratsg about dealing with combining workspaces. The hardest thing is that there is not necessarily one right way to combine (or join) two workspaces. Considering this, `pyhf combine` will now support (as of this PR) four methods.
1. none
2. outer
3. left outer
4. right outer
Before, `pyhf combine` was doing a mixture of (1) and (2) above: `none` and `outer`. Now, the code is cleaned up to separate the two logic better.
A `none` will only check for duplicated data structures (by name) between the two workspaces and refuse to combine if any names are in common. This uses the summary data provided by `_ChannelSummaryMixin`.
An `outer` join will join both workspaces and any duplicated data structures will be merged together if they are fully …
=> feat: Combine is taught about formal data (outer) join methods

README.md, docs/faq.rst
Add a question section to direct users to the `pyhf` tag on Stack Overflow for user discussion. Additionally add this section to the FAQs.
A preview of this PR can be seen on RTD here: https://pyhf.readthedocs.io/en/docs-add-stack-overflow-tag/
**TODO:** 
- Source of guidance for tag description: [`uproot`'s Stack Overflow tag](https://stackoverflow.com/tags/uproot/info)
- [Fit convergence failure in pyhf for small signal model](https://stackoverflow.com/questions/60089405/fit-convergence-failure-in-pyhf-for-small-signal-model/)
```
* Add questions section for Stack Overflow [pyhf] tag to README and FAQs
```
=> docs: Add Stack Overflow question section

.github/workflows/tag.yml
Fix a minor typo in GitHub Actions `removeLabels` to `removeLabel`
```
* Fix a typo in the tagging workflow: removeLabels to removeLabel
```
=> fix: Minor typo in GitHub Actions removeLabels to removeLabel

.github/workflows/tag.yml
Following up PR #770, valid JavaScript doesn't allow a single string in a dictionary, assign a key to it fix it
```
* Valid JavaScript doesn't allow a single string in a dictionary, assign a key to it fix it
* Amends PR #770
```
=> fix: Add key to workflow dictionary to make it valid JavaScript

src/pyhf/cli/spec.py, src/pyhf/modifiers/__init__.py, src/pyhf/modifiers/histosys.py, src/pyhf/modifiers/lumi.py, src/pyhf/modifiers/normfactor.py, src/pyhf/modifiers/normsys.py, src/pyhf/modifiers/shapefactor.py, src/pyhf/modifiers/shapesys.py, src/pyhf/modifiers/staterror.py, src/pyhf/pdf.py, tests/test_modifiers.py
This is related to a few issues on shapesys, but overall, we need to be able to hav ethe fine-control/fine-tuning to mask individual bins of a given parameter.
Resolves #773.
- Poisson(0) is undefined
- Poisson(1/0) is poorly defined
- we don't like 1/0 or similarly asymptotic values
- sometimes an analysis with n-bins in a channel defines a shapesys with data value = 0 somewhere -- maybe all bins -- maybe one bin
- and sometimes an analysis has a sample with 0 expected events (poor stats)
- shapesys sucks in this cases, and ROOT prunes out these cases, but we don't
- so we should
- the PR is the first step by expanding the api to pass around more information so we can handle it.
```
* Modify required_parset API to allow sample data and modifier data to be passed …
```
=> feat: Update required_parset to pass in sample data and modifier data

docs/intro.rst
Fix of minor typo in documentation: Remove misplaced equal sign in equation for total background.
=> docs: remove misplaced equal sign

docs/likelihood.rst, src/pyhf/modifiers/shapesys.py, src/pyhf/pdf.py, tests/test_combined_modifiers.py, tests/test_pdf.py, tests/test_validation.py
from discussions with @kratsg this fixes shapesys by only allocating nuisance parameters for bins in shapesys where the yield and the uncrt is > 0
```
- improve handling of shapesys by only allocating nuisance parameters for valid, physically meaningful bins (yield and uncertainty are nonzero and positive)
- add documentation about this particular "feature" of shapesys
```
=> feat: Only allocate shapesys parameter if yield and uncrt are positive, nonzero

docs/bib/use_citations.bib
Add citation of pyhf in the [Les Houches 2019 Physics at TeV Colliders: New Physics Working Group Report](https://inspirehep.net/record/1782722). A blank "booktitle" entry is added to the citation entry from INSPIRE-HEP avoid an error during the Sphinx build. Additionally, reorder the BibTex file to be in _reverse_ chronological order for easier referencing (by humans) &mdash; this has no effect on the output.
```
* Add citation from Les Houches 2019 Physics at TeV Colliders: New Physics Working Group Report
* Use reverse chronological ordering in the use_citations BibTeX file
```
=> docs: Add Les Houches 2019 New Physics Working Group Report citation

.bumpversion.cfg, .zenodo.json
Thanks to the helpful information from @lnielsen, I've learned that we can control the metadata for Zenodo releases through a `.zenodo.json` file, which this PR adds. Under the "Metadata" tab on the Zenodo releases for pyhf it mentions that
> JSON Export
> Zenodo automatically extracts metadata about your repository from GitHub APIs. For example, the authors are determined from the repository's contributor statistics. The automatic extraction is **solely a best guess**. Add a `.zenodo.json` file the root of your repository to explicit define the metadata. The format of file is the same as for our REST API (use e.g. below JSON to get started).
By copying and revising the metadata for [pyhf release `v0.4.0`](https://doi.org/10.5281/zenodo.3678702) and then taking some inspiration from the …
=> docs: Add Zenodo metadata config file

docs/bib/media.bib, docs/index.rst, docs/outreach.rst, docs/talks.rst
Partially addresses Issue #736.
Adds a listing of media publications related to pyhf. This listing is added to the renamed (from "Talks") "Outreach" page.
```
* Rename "talks" page to "outreach"
* Add listing of media publications related to pyhf to outreach page
```
=> docs: Add list of media publications and make 'outreach' page

docs/bib/HEPData_likelihoods.bib, docs/citations.rst
- Resolves #736 
- Resolves #780 
Add a listing of HEPData published likelihoods to the Use and Citations page. This PR adds the first three full likelihoods to ever be published by an LHC experiment (ATLAS):
- [Search for bottom-squark pair production with the ATLAS detector in final states containing Higgs bosons, _b_-jets and missing transverse momentum](https://www.hepdata.net/record/ins1748602)
- [Search for direct stau production in events with two hadronic τ-leptons in s√=13 TeV pp collisions with the ATLAS detector](https://www.hepdata.net/record/ins1765529)
- [Search for chargino-neutralino production with mass splittings near the electroweak scale in three-lepton final states in s√ = 13 TeV pp collisions with the ATLAS detector](https://www.hepdata.net/record/ins1771533)
For the …
=> docs: Add published HEPData likelihoods to Use and Citations page

docs/faq.rst
As a _very_ minor PR, this PR adds a FAQ on how to properly typeset the name `pyhf` [inspired by](https://twitter.com/HEPfeickert/status/1233416311541260290) the inclusion of `pyhf` in the [Les Houches 2019 Physics at TeV Colliders: New Physics Working Group Report](https://inspirehep.net/record/1782722).
```
* Add FAQ on how to typeset the name "pyhf" in journals
```
=> docs: Add FAQ on how to typeset "pyhf"

tests/test_infer.py
this is a test that pyhf.infer.hypotest is really independent of pyhf. This is basically preparing a out-sourcing of the inference package
```
* Add test that pyhf.infer.hypotest is independent of pyhf to ensure that inference is decoupled
```
=> test: Add test of independence of pyhf.infer from pyhf details

docs/bib/use_citations.bib
Add citation by [MadMiner: Machine learning-based inference for particle physics](https://inspirehep.net/record/1746275) in 2019 to the citations docs page.
Thanks @johannbrehmer, @irinaespejo, @KlingFelix, and @cranmer! :)
```
* Add citation by MadMiner paper
```
=> docs: Add MadMiner citation

.dockerignore
Resolves #787 
As [noted here](https://github.com/docker/hub-feedback/issues/511#issuecomment-504777737), unlike GitHub Actions (and all of our local versions of Docker), the automated builds that Docker Hub runs **will not** read the `.dockerignore` the same if there are directory slashes after a `!`.
So though 
```
!/setup.py
```
is valid, Docker Hub requires
```
!setup.py
```
The docs simply note that
> [Lines starting with ! (exclamation mark) can be used to make exceptions to exclusions](https://docs.docker.com/engine/reference/builder/#dockerignore-file)
This PR amends the [`.dockerignore`](https://github.com/scikit-hep/pyhf/blob/a3082bdc9ff34c538f24eba54edf4226de6d674d/.dockerignore) added in PR #748 to be compliant with Docker Hub's rules.
```
* Remove …
```
=> fix: Remove unneeded directory slash in .dockerignore

.zenodo.json
Fixes the `.zenodo.json` file added in PR #779. This problem with the `.zenodo.json` file is there is an error in the autogenerated metadata that was copied and pasted form Zenodo in PR #779.
```
* Removes invalid content in .zenodo.json (schema-related)
- Amends PR #779
```
=> fix: Removes invalid property in .zenodo.json

src/pyhf/schemas/1.0.0/defs.json, src/pyhf/schemas/1.0.0/measurement.json, src/pyhf/schemas/1.0.0/model.json, src/pyhf/schemas/1.0.0/workspace.json, src/pyhf/workspace.py
This cleans up the schemas a little bit and fixes typos in the documentation.
```
* Clean up schemas by moving the bulk of the information into defs.json
* Fix up typos in documentation for the refs to the schema information
```
=> chore: Clean up schemas and fix typos in docs about schemas 

.github/workflows/ci.yml, docker/Dockerfile
For less than 100MB more in size using [`python:3.7-slim`](https://hub.docker.com/layers/python/library/python/3.7-slim/images/sha256-e65d472af32c1f51cca9350de6bd63cf4ce440f2e68fb9301bcf12cdba1b0acd?context=explore) as 
a base image for the pyhf Docker images gets a much more common environment for reproduction and testing. For example, it can reproduce the failing error of the [Minimal pyhf example failing with 'Inequality constraints incompatible'](https://stackoverflow.com/questions/60514470/minimal-pyhf-example-failing-with-inequality-constraints-incompatible) Stack Overflow issue instantly rather then running for minutes and then failing on an iteration limit exceeded error as the Alpine based image does. It also allows for direct installation of SciPy and NumPy.
For the PR …
=> chore: Use Debian based python:3.7-slim as base Docker image

src/pyhf/parameters/paramview.py, src/pyhf/pdf.py, src/pyhf/tensor/common.py, tests/conftest.py, tests/test_paramviewer.py, tests/test_regression.py, tests/test_tensorviewer.py
moves `ParamViewer` to use `_TensorViewer` so that we re-use that logic instead of repeating ourselves
```
* Remove unused constraint_model.expected_data method (used some details in ParamViewer that were removed
* Refactor ParamViewer to use TensorViewer remove .slices attribute
* Add ability in TensorViewer to attach names to subspaces and return only subset of tensors when splitting
* Add tensorviewer tests
* Modify paramviewer tests to test more interesting cases
* simpify _TensorViewer construction for full pdf using new helper methods
```
=> refactor: Use _TensorViewer in ParamViewer

docs/conf.py, setup.py
Add [`sphinx-copybutton`](https://sphinx-copybutton.readthedocs.io/en/latest/) to the `docs` extra to add copy buttons to all code snippet blocks.
Thanks [for tweeting](https://twitter.com/choldgraf/status/1213167082176577542?s=11) and for the great work, @choldgraf!
This makes all of our docstrings even nicer now as the copy button removes the Python REPL prompts:
[![cropped_view](https://user-images.githubusercontent.com/5142394/71749229-738fb480-2e3a-11ea-80dd-fc95e7520546.png)](https://scikit-hep.org/pyhf/_generated/pyhf.tensor.pytorch_backend.pytorch_backend.html#pyhf.tensor.pytorch_backend.pytorch_backend.clip)
so that when pasted you get
```python
import pyhf
pyhf.set_backend("pytorch")
a = pyhf.tensorlib.astensor([-2, -1, 0, 1, 2])
pyhf.tensorlib.clip(a, -1, 1)
```
For the PR …
=> docs: Add copy buttons to code snippets in docs with sphinx-copybutton

docs/exts/xref.py, src/pyhf/cli/spec.py, src/pyhf/workspace.py
Given a Tweet by @jakevdp [about mutable defaults](https://twitter.com/jakevdp/status/1235271748867612673) that got me thinking along with a message with @mickypaganini, this PR makes all function defaults that are empty lists be `None` instead and follow the
```python
x = [] if x is None else x
```
pattern. However, this doesn't actually really do anything, as the design of the code so far is well thought through and any mutable defaults can't propagate through to [produce any of the usual errors](http://effbot.org/zone/default-values.htm). This PR exists to essentially future proof any changes and to try to mindless adopt 'best patterns' (if you will).
As can be seen by `git grep "=\[\]"`, `git grep "={}"`, (thank you [Black](https://github.com/psf/black)!) and 
```
$ git grep ".update" …
```
=> chore: Avoid mutable defaults

docs/bib/use_citations.bib
Add use citation from [_Reinterpretation of LHC Results for New Physics: Status and Recommendations after Run 2_](https://inspirehep.net/record/1785921)
PR #808 should go in first.
```
* Add use citation from Reinterpretation of LHC Results for New Physics: Status and Recommendations after Run 2
- c.f. https://inspirehep.net/record/1785921
```
=> docs: Add citation from Run 2 Reinterpretation of LHC Results paper

.github/workflows/publish-docker.yml
Resolves #716
Use the [official Docker GitHub Action](https://github.com/docker/build-push-action) (released today) to publish to the Docker image to Docker Hub.
Using the `tag_with_ref` option, tag the image with the version release number and `latest-stable` when the push is a tag release.
c.f. [`pyhf/pyhf-validation` PR 11](https://github.com/pyhf/pyhf-validation/pull/11) for an example of this working.
```
* Use official Docker GitHub Action to publish to Docker Hub
- Tag image with version release and 'latest-stable' tags if the push is a tag release
```
=> ci: Use official Docker GitHub Action for publication to Docker Hub

docs/api.rst, docs/conf.py, src/pyhf/__init__.py, src/pyhf/tensor/jax_backend.py
Add JAX to the list of backends and optimizers in the Python API docs. We missed doing this in PR #377.
Build is at: https://pyhf.readthedocs.io/en/docs-add-jax-to-docs/
```
* Add JAX to list of backends and optimizers in the Python API docs
- Amends PR #377
* Use string alias to set JAX backend in examples
```
=> docs: Add JAX to Python API docs

.github/workflows/ci.yml, .github/workflows/merged.yml, .github/workflows/publish-docker.yml, .github/workflows/publish-package.yml, .github/workflows/release_tests.yml, .github/workflows/tag.yml
Update the [`checkout` GitHub Action](https://github.com/actions/checkout) to use stable release `v2`.
Requires PR #825 to go in first.
```
* Update checkout action to v2 (stable major release v2.0.0)
```
=> chore: Use GitHub Actions checkout action v2

.github/workflows/publish-package.yml
Resolves #832 
Have [`actions/checkout@v2`](https://github.com/actions/checkout/releases/tag/v2) unshallow the history and get all of the tags. This allows `pep517` to be able to use the repo information to assign the version number of the build properly.
Here are examples of the verification check:
- [Failing properly (as expected)](https://github.com/scikit-hep/pyhf/runs/606545321?check_suite_focus=true#step:7:13)
- [Succeeding](https://github.com/scikit-hep/pyhf/runs/606768192?check_suite_focus=true#step:8:13)
```
* Get all history and all tags for pep517 to determine version of the built distribution
- Amends PR #826
* Add versioning verification check
```
=> fix: Get full history and all tags for TestPyPI and PyPI publishing workflow

.github/workflows/publish-package.yml
The [`gh-action-pypi-publish` action](https://github.com/pypa/gh-action-pypi-publish) release currently being used is [`v1.0.0a0`](https://github.com/pypa/gh-action-pypi-publish/releases/tag/v1.0.0a0) which is an alpha release. This PR moves it to the first stable release: [`v1.1.0`](https://github.com/pypa/gh-action-pypi-publish/releases/tag/v1.1.0).
```
* Update gh-action-pypi-publish to a stable non-alpha release (v1.1.0)
```
=> chore: Update gh-action-pypi-publish to non-alpha release

.github/workflows/ci.yml, .github/workflows/release_tests.yml
The change on the VMs used for the Ubuntu builds that caused the disk space regression in PR #819 is getting rolled back (c.f. [`actions/virtual-environments` Issue 709](https://github.com/actions/virtual-environments/issues/709)). As a result, the temporary hack fix of running `apt-get clean` before installation on the `ubuntu-latest` jobs is no longer necessary and can be reverted.
```
* Revert apt-get clean hack fix for disk space regression (now resolved)
- c.f. https://github.com/actions/virtual-environments/issues/709
```
=> revert: Remove disk space regression hack fix

setup.py
Resolves #800 
Updates to [`jsonschema` `v3.2.0`](https://github.com/Julian/jsonschema/releases/tag/v3.2.0) which is a stable release that uses [JSON Schema draft-06](https://json-schema.org/draft-06/json-schema-release-notes.html).
```
* Update jsonschema to v3.2.0 to move off alpha release
- Moves to JSON Schema draft-06 (https://json-schema.org/draft-06/json-schema-release-notes.html)
```
=> feat: Update jsonschema to non-alpha release

.github/workflows/ci.yml
Similar to PR #833, the docs build requires information on the version of pyhf is is reporting on to be able to properly display the version on the page. This PR unshallows the clone of pyhf used for the docs build and gets the tags as well.
```
* Get all history and all tags for docs build to determine version of pyhf
- Amends PR #826
```
=> fix: Have release versioning work in docs build CI

src/pyhf/pdf.py, src/pyhf/workspace.py, tests/test_import.py, tests/test_pdf.py, tests/test_schema.py, tests/test_validation.py, tests/test_workspace.py
Resolves #836.
This PR will simplify `Workspace::get_measurement` by removing `_get_measurement` and rewriting into conditionals instead for clarity.
```
* Workspace::_get_measurement is removed and merged with Workspace::get_measurement
* measurement_name is not passed as a keyword argument into pyhf::Model
* poiname is renamed to poi_name for consistency everywhere
```
=> refactor: Simplify Workspace::get_measurement and harmonize poi_name

docs/faq.rst
Resolves #821 
Add two FAQs RE: validation of `pyhf` against `HistFactory` and `HistFitter`.
ReadTheDocs build: https://pyhf.readthedocs.io/en/docs-add-faqs-on-validation/
```
* Add two FAQs RE: validation of pyhf against HistFactory and HistFitter
```
=> docs: Add FAQs on validation

.github/workflows/tag.yml
In PR #826 all uses of `actions/checkout` were updated to `v2`. This was also done to the Tag Creator GitHub Action, which [resulted in a break](https://github.com/scikit-hep/pyhf/pull/796/checks?check_run_id=614484399#step:7:1). This change already caused trouble in PR #833 and PR #839, so the same patch that was applied to PR #833 is also applied here.
An example of the [patched workflow is done on this test branch here](https://github.com/scikit-hep/pyhf/runs/615811679?check_suite_focus=true#step:7:1).
```
* Get all history for checkout master to work in Tag Creator
- Amends PR #826
```
=> fix: Get full history for Tag Creator workflow

.github/workflows/ci.yml
Use the GitHub Action [`peaceiris/actions-gh-pages@v3`](https://github.com/peaceiris/actions-gh-pages) to deploy the docs to the `gh-pages` branch. The main advantage of [`peaceiris/actions-gh-pages`](https://github.com/peaceiris/actions-gh-pages) over [`crazy-max/ghaction-github-pages`](https://github.com/crazy-max/ghaction-github-pages) is that, in addition to being actively more developed, it allows for the use of an automatically created `GITHUB_TOKEN` instead of a user provided `GITHUB_PAT`.
For an example of this working see [PR 2 of `HEP-ML-LivingReview`](https://github.com/bnachman/HEP-ML-LivingReview/pull/2).
```
* Use peaceiris/actions-gh-pages@v3 to deploy docs to gh-pages branch
- Allows use of GITHUB_TOKEN instead of GITHUB_PAT
```
=> ci: Use actions-gh-pages GitHub Action for deploy of docs

AUTHORS, README.rst
As the dev team is listed as the authors in the citation it makes sense to also formally list them in the README. Additionally, an `AUTHORS` file is created with the dev team listed and an acknowledgements section is added and the [same NSF support statement that is used for `uproot`](https://github.com/scikit-hep/uproot#acknowledgements) is also attributed to @matthewfeickert.
ReadTheDocs build: https://pyhf.readthedocs.io/en/docs-add-authors/
```
* List dev team as authors in README and AUTHORS
* Add acknowledgements section for NSF support statement
```
=> docs: List the dev team as authors

src/pyhf/infer/__init__.py, src/pyhf/infer/mle.py, src/pyhf/infer/test_statistics.py
- Resolves #848
- Partially addresses #38 
Fix the docstrings for `infer.mle.fit` and `infer.mle.fixed_poi_fit`. Add examples to `infer.mle` fit methods,`infer.hypotest`, and `infer.test_statistics.qmu`.
To get `doctest` passing on the macOS builds there is a small cheat in that the MINUIT example for `pyhf.infer.mle.fit` has [its evaluations skipped](https://www.sphinx-doc.org/en/master/usage/extensions/doctest.html#directive-doctest). The SciPy optimizer evaluations before it pass though, so this small deviation should be fine.
ReadTheDocs build: https://pyhf.readthedocs.io/en/docs-add-infer-mle-doc-strings/_generated/pyhf.infer.hypotest.html
```
* Fix the docstrings for 'infer.mle.fit' and 'infer.mle.fixed_poi_fit' 
* Add examples to 'infer.mle' fit methods, …
```
=> docs: Add docstrings and examples to infer fitting methods

pyproject.toml
Add `AUTHORS` to `MANIFEST` ignore list in `pyproject.toml`. This was missed in PR #844 and is being caught now by a [logic change in `check-manifest` `v0.42`](https://github.com/mgedmin/check-manifest/blob/master/CHANGES.rst#042-2020-05-03).
```
* Add AUTHORS file to MANIFEST ignore list
- Amends PR #844
```
=> fix: Add AUTHORS to MANIFEST ignore

docs/development.rst
Extend and improve the instructions for validating and then publishing a release using GitHub Actions.
This follows up on [some discussion](https://github.com/scikit-hep/pyhf/pull/638#discussion_r346845955) on PR #638 with @webknjaz and advocates for locally merging on the command line so as to avoid a merge commit (as the branch would be just ahead of `master` and so can easily fastforward).
ReadTheDocs build: https://pyhf.readthedocs.io/en/docs-improve-publishing-docs/development.html
```
* Update the instructions for validating and then publishing a release using GitHub Actions
```
=> docs: Improve discussion of publication workflow

.github/workflows/merged.yml
Resolves #854 
The OVH Cloud [Binder Federation](https://discourse.jupyter.org/t/the-binder-federation/1286) cluster build API endpoint seems to be dead and is causing errors of
```
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to ovh.mybinder.org:443 
```
Given this remove the endpoint from the Merged PR CI. However, as the Binder Federation now includes [GESIS Notebooks](https://blog.jupyter.org/gesis-joins-the-binder-federation-8603d878ff77) and the [Turing Institute](https://www.turing.ac.uk/) these endpoints are added.
```
* Remove dead OVH Binder build endpoint from Merged PR workflow
* Add GESIS Notebooks and Turing Institute Binder build endpoints
```
=> fix: Remove dead OVH Binder build endpoint and add GESIS and Turing endpoints

docs/development.rst
Resolves #858
Add instructions on how to install test releases from [TestPyPI](https://test.pypi.org/project/pyhf/) using the [`--extra-index-url`](https://pip.pypa.io/en/stable/reference/pip_install/#cmdoption-extra-index-url) and [`--pre`](https://pip.pypa.io/en/stable/reference/pip_install/#cmdoption-pre) options for `pip`.
```
python -m pip install --extra-index-url https://test.pypi.org/simple/ --pre pyhf
```
ReadTheDocs build: https://pyhf.readthedocs.io/en/docs-add-testpypi-install-example/development.html#testpypi
```
* Add instructions on installing test releases from TestPyPI using --extra-index-url and --pre
```
=> docs: Add instructions for installing test releases from TestPyPI

.github/workflows/ci.yml, .github/workflows/release_tests.yml, setup.py
Resolves #633
Add Python 3.8 to the collection of Python runtimes tested, and reflect this in the PyPI classifiers list. Python 3.8 is tested both in the normal CI tests and in the PyPI release tests.
```
* Add Python 3.8 to runtimes tested in CI tests
* Add Python 3.8 to PyPI classifiers
```
=> ci: Add Python 3.8 to tests

.pre-commit-config.yaml, setup.py
Resolves #861 
Add JAX to the [list of keywords in `setup.py`](https://github.com/scikit-hep/pyhf/blob/917bd5127c1da023b279c076bb41614fbb859487/setup.py#L85). Additionally, update the [classifies](https://packaging.python.org/guides/distributing-packages-using-setuptools/#classifiers) to include a `Development Status`, `License`, `Intended Audience`, and `Topic`. Also sneak in a URL update for Black in `.pre-commit-config.yaml`
```
* Add JAX to keywords
* Update classifiers to include development status, license, intended audience, and topic
* Add project URLs
* Update Black URL in .pre-commit-config.yaml
```
=> docs: Update keywords, classifiers, and URLs in setup.py

.github/workflows/ci.yml, .github/workflows/publish-package.yml, .github/workflows/release_tests.yml, .github/workflows/tag.yml
[`v2` of the `setup-python` GitHub Action](https://github.com/actions/setup-python/releases/tag/v2) has been released. This PR updates all GitHub Action workflows to use the new stable release.
```
* Use v2 of the setup-python GitHub Action in all GitHub Action workflows
```
=> chore: Update setup-python action to v2

.bumpversion.cfg, setup.cfg, setup.py
Resolves #872 
Use `setup.cfg` as the main source of configuration and install information by migrating metadata and setup options from `setup.py` to `setup.cfg`. This is done mainly by following @henryiii's examples on the [Scikit-HEP packaging information page](https://scikit-hep.org/developer/packaging#setup-configuration-medium-priority) and by looking at the [gwcelery `setup.cfg` file](https://git.ligo.org/emfollow/gwcelery/-/blob/46374fad07099fcc38cc6e620c6c7fc7afc736b2/setup.cfg) and `setuptools` docs on [Configuring `setup()` using `setup.cfg` files](https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files).
The basic argument for doing this is `setup.py` is for logic as it is Python, and `setup.cfg` is for static configuration options. …
=> chore: Migrate metadata and setup options to setup.cfg

.github/workflows/tag.yml
Resolves #874 
Tag creator breaks due to
> feat: Add utility for computing object digests ("hashing")
as a result of the `"`s, so simply use `sed` to replace `"` with `'` in the sanitize stage.
```
sed -e 's/"/'"'"'/g'
```
This is not super elegant, but it works. Additionally, a `name` field is added to `github.issues.removeLabel` so that it actually removed the bumpversion label when the CI fails.
```
* Update to use github-script v1.1.0
* Replace double quotes with single quotes to avoid errors
* Add 'name' field to removeLabel to actually remove bumpversion label if tag creator fails
```
=> fix: Sanitize double quotes for Tag Creator

.github/workflows/ci.yml, .github/workflows/publish-package.yml, .github/workflows/tag.yml
Use the `fetch-depth: 0` option introduced in [`v2.2.0` of the `checkout` action](https://github.com/actions/checkout/releases/tag/v2.2.0) to fetch all history for all tags and branches in a much cleaner fashion.
```
* Use checkout fetch-depth API to unshallow all branches and tags
- Introduced in v2.2.0
- c.f. https://github.com/actions/checkout/releases/tag/v2.2.0
* Explicitly set checkout version to v2.2.0 to avoid floating v2 release
- c.f. https://github.com/actions/toolkit/blob/master/docs/action-versioning.md#recommendations
```
=> ci: Use checkout v2.2.0 fetch-depth option to unshallow all

setup.cfg
- Requires PR #795 to be resolved first
In [SciPy `v1.4.0`](https://github.com/scipy/scipy/blob/master/doc/release/1.4.0-notes.rst#scipy-optimize-improvements) the following fix is added in https://github.com/scipy/scipy/pull/10739
> SLSQP can run to singular BFGS updates, which it doesn't handle, and may exit with nan outputs and successful exit code. To avoid this, do the most trivial thing and just reset the matrix. This might not lead to convergence, but gets rid of false successful exits.
> ...
> The linalg changes are no-ops if there are no nans, and with nans generally give error exits. The BFGS update tweak is only triggered in cases where the code previously divided by zero. The SLSQP exit-on-too-many-resets check is also a corner case. So there should be no impact in …
=> build: Require minimum SciPy version of v1.4.0

src/pyhf/cli/infer.py, src/pyhf/cli/spec.py
Add some simple examples on how to use the `pyhf` CLI for `inspect`, `cls` and `digest`. This is not comprehensive, but just an in passing through PR.
ReadTheDocs build: https://pyhf.readthedocs.io/en/docs-add-inspect-example/cli.html
```
* Add simple example for pyhf inspect, pyhf cls, and pyhf digest CLI
```
=> docs: Add simple examples for inspect, cls, and digest CLI

docs/conf.py
Avoid warning in building the docs of
```
/home/runner/work/pyhf/pyhf/docs/conf.py:29: RemovedInSphinx40Warning: The app.add_stylesheet() is deprecated. Please use app.add_css_file() instead.
'https://cdnjs.cloudflare.com/ajax/libs/github-fork-ribbon-css/0.2.2/gh-fork-ribbon.min.css'
```
ReadTheDocs build: https://pyhf.readthedocs.io/en/docs-fix-inline-interpreted-parsing-error
```
* Use app.add_css_file over deprecated app.add_stylesheet
- Deprecated since Sphinx v1.8.0
- https://github.com/sphinx-doc/sphinx/blob/800dcf0f0a8040ae84c4aaa7053f62201170c47d/CHANGES#L1510
```
=> fix: Avoid warning of 'app.add_stylesheet() is deprecated'

.github/workflows/tag.yml
Fix the Tag Creator workflow that [failed](https://github.com/scikit-hep/pyhf/runs/718450042?check_suite_focus=true) in PR #796 on the "Push changes" step with
```
Run ad-m/github-push-action@v0.5.0
with:
github_token: ***
branch: master
directory: .
env:
IS_MAJOR: false
IS_MINOR: false
IS_PATCH: true
PR_NUMBER: 796
PR_TITLE: build: Require minimum SciPy version of v1.4.0
GITHUB_HEAD_REF: build/require-scipy-min-v-1.4.0
BV_PART: patch
pythonLocation: /opt/hostedtoolcache/Python/3.7.7/x64
OLD_TAG: v0.4.1
NEW_TAG: v0.4.2
CHANGES: <there were a lot but they don't matter here>
NUM_CHANGES: 48
/usr/bin/docker run --name be76db00e9f497df7b42a2802c9c7aa61823ab_e1ed51 --label be76db --workdir /github/workspace --rm -e IS_MAJOR -e IS_MINOR -e IS_PATCH -e PR_NUMBER -e PR_TITLE -e GITHUB_HEAD_REF -e …
```
=> fix: Set checkout GHA persist-credentials to false for push to succeed

.github/workflows/publish-package.yml
Resolves #887 
We can get the name of the latest tag that has been created (the tag that was just pushed) with
```
latest_tag=$(git describe --tags)
```
and then with that get the latest commit on the tag's `rev-list`
```
latest_tag_revlist_SHA=$(git rev-list -n 1 ${latest_tag})
```
As `git rev-list ${latest_tag}` will give the list of commits accessible _from_ the `${latest tag}`, then `${latest_tag_revlist_SHA}` will point to the most recent commit accessible &mdash; the last commit on `origin/master` which is the one `bumpversion` created when making `${latest tag}`. Note that we have to do it this way, as the actual SHA (from `git rev-parse --verfiy`) for the `${latest tag}` and `origin/master` will be _different_. Then we can simply get the SHA from `origin/master`
``` …
```
=> fix: Check if HEAD of origin/master is accessible from latest tag

.github/workflows/publish-package.yml
Update the publishing CI to use release [`v1.2.2`](https://github.com/pypa/gh-action-pypi-publish/releases/tag/v1.2.2) of the [PyPA's `gh-action-pypi-publish` action](https://github.com/pypa/gh-action-pypi-publish). As of [`v1.2.1`](https://github.com/pypa/gh-action-pypi-publish/releases/tag/v1.2.1) the action uses Python 3.8 inside of the Docker environment. Additionally, use Python 3.8 for 
Thank you again for such an awesome GitHub action, @webknjaz! :rocket: 
```
* Use Python 3.8 for building wheel and source distributions
* Update gh-action-pypi-publish GitHub action to v1.2.2
- Use Python 3.8 in the action's Docker environment as of v1.2.1
```
=> ci: Use Python 3.8 in all steps of publishing distributions

setup.py
This PR is in response to Issue #897, but does not fix it. [Sphinx Issue 7844](https://github.com/sphinx-doc/sphinx/issues/7844) is needed for it to actually resolved.
Temporarily keep Sphinx below `v3.1.0` as `v3.1.0` and `v3.1.1` have regressions that break the docs. 
ReadTheDocs build: https://pyhf.readthedocs.io/en/docs-fix-autosummary-bug
```
* Confine Sphinx to be in the v3.0.X series of releases
- Avoid regressions introduced in v3.1.0 and v3.1.1
```
=> fix: Keep Sphinx at v3.0.X releases

src/pyhf/infer/mle.py
With [SciPy `v1.5.0`](https://github.com/scipy/scipy/releases/tag/v1.5.0) the return type for [`scipy.optimize.minimize`'s `res.fun`](https://docs.scipy.org/doc/scipy-1.5.0/reference/generated/scipy.optimize.minimize.html#scipy.optimize.minimize) is a NumPy array instead of a scalar. This PR updates the return type shown in examples of `pyhf.infer.mle` to pass the doctests in CI.
```
* Show a NumPy array return type for the returned objective function (2*NLL) in the docs examples
```
=> fix: Update infer.mle docstrings to match SciPy v1.5.0

.github/workflows/ci.yml, .github/workflows/lint.yml, .github/workflows/publish-package.yml, setup.py
Create a separate `lint` extra that can be used to lint the codebase in a separate GitHub Actions workflow then the testing of the codebase. This should allow for faster testing overall, and it also allows for linting to not block development flow until a PR is finished.
```
* Add 'lint' extra to setup.py
* Move linting into a separate GitHub Actions workflow
- Only run lint workflow on pull_request events
* Move MANIFEST check to publish-package workflow
- Move check-manifest to 'develop' extra
```
=> ci: Separate linting from testing

src/pyhf/tensor/pytorch_backend.py
This fixes a small typo in the constructor of `pytorch_backend`. The kwargs key for the int type was wrongly queried as "float".
```
* typo in pytorch backend where one was unable to specify integer dtype
```
=> fix: make pytorch_backend use configured dtypes

.github/workflows/publish-package.yml
Resolves #908 
Use [`pep517.check`](https://github.com/pypa/pep517/tree/82a303d0cdb5de1e48f30b90ee299a8e0cbfad3b) to verify that the build backend is compliant with [PEP 517](https://www.python.org/dev/peps/pep-0517/) before attempting to build the distributions in the publishing workflow. Additionally, based off of the discussion with @henryiii in Issue #908, use more honest/clear wording RE: the wheels produced in the publishing workflow.
```
* Test the build backend is compliant with PEP 517 with pep517.check
* Use more clear language with regards to wheels
```
=> ci: Verify build backend is compliant with PEP 517 in publishing workflow

src/pyhf/tensor/jax_backend.py, src/pyhf/tensor/numpy_backend.py, src/pyhf/tensor/pytorch_backend.py, src/pyhf/tensor/tensorflow_backend.py, tests/test_tensor.py
This provides an API for `tb.xxxx_precision` to report the precision of the `float`/`int`. (I don't think we should mix and match precision for ints/floats so we should revisit how we set them).
This resolves #907.
```
* Provide API for tensorlib precision of ints and floats
```
=> feat: Add precision information to tensorlib backends

setup.py
Resolves #913 
This is a temporary fix to Issue #913, as the actual fix in [TensorFlow Probability PR 993](https://github.com/tensorflow/probability/pull/993) won't be available in a PyPI release until TensorFlow Probability `v0.11.0`. By explicitly disallowing `cloudpickle` `v1.5.0` this patch unblocks development.
```
* Explicitly disallow cloudpickle v1.5.0 to avoid breaking TensorFlow Probability 
- This is a temporary solution to unblock development, but should be removed once TensorFlow Probability v0.11 has been released
- https://github.com/tensorflow/probability/issues/991
- https://github.com/cloudpipe/cloudpickle/issues/390
```
=> fix: Disallow cloudpickle v1.5.0 in 'tensorflow' extra

.github/workflows/ci.yml
In the release of `v0.4.4` through the merge of PR #915 we saw that the deployment CI worked perfectly :tada: but that the [CI still failed on the **push of the tag**](https://github.com/scikit-hep/pyhf/runs/831652135) because the Docker image build test currently doesn't run the _build_ on tag events but we don't have a check for the following parts if it is tagged or not.
https://github.com/scikit-hep/pyhf/blob/6ac0f6280c56111c32f46ec9aaad0286d05d36e7/.github/workflows/ci.yml#L134-L147
These parts aren't skipped automatically, and so the CI fails.
Instead of trying to check every step, this PR just lets this CI step run even on tag events and avoid this problem alltogether.
```
* Run the Docker build check on all events, even if it is from a push of a tag
```
=> ci: Run Docker test on tag pushes to avoid breaking CI

src/pyhf/cli/infer.py, src/pyhf/tensor/jax_backend.py, src/pyhf/tensor/numpy_backend.py, src/pyhf/tensor/pytorch_backend.py, src/pyhf/tensor/tensorflow_backend.py, tests/conftest.py, tests/test_tensor.py
- Resolves #911
- Resolves #912 
This will unify our backends further by allowing for precision configuration of ints and floats simultaneously, rather than configuring each one separately. Allowing a mix of precisions doesn't quite make sense and we should not encourage this behavior.
```
* Unify setting precision for all tensorlib backends
* Provide 32/64 settings for all backends while keeping same defaults
```
=> feat: Single precision setting for backends

src/pyhf/__init__.py, src/pyhf/tensor/jax_backend.py, src/pyhf/tensor/numpy_backend.py, src/pyhf/tensor/pytorch_backend.py, src/pyhf/tensor/tensorflow_backend.py, tests/test_public_api.py, tests/test_tensor.py
This resolves #921 by providing an internal `_setup()` method to all tensorlib backends allowing us to call it when we `set_backend()` in `pyhf`. This allows us to update the global settings when needed.
Additionally, there's a regression introduced via #910 in which we don't trigger `tensorlib_changed` if the precision of the tensorlib changes &mdash; this is fixed as well.
```
* set_backend() will trigger global state changes for tensorlib
* Tensorlib precision changes will now trigger tensorlib_changed events
```
=> fix: Set backend global states correctly

setup.py
Given the release of [TensorFlow Probability `v0.10.1`](https://github.com/tensorflow/probability/releases/tag/v0.10.1) which [decided to constraint `cloudpickle` to `v1.3.0`](https://github.com/tensorflow/probability/issues/991#issuecomment-654502970) remove the explicit constraints
https://github.com/scikit-hep/pyhf/blob/64dbce070156945f6bb524f79ee6e23d26b52f01/setup.py#L7
in `setup.py`. Additionally, bump `TensorFlow Probability` to be in at least the `v0.10.X` range of releases.
This PR effectively reverts PR #915
```
* Remove constraints on cloudpickle version
- cloudpickle version is constrained in TensorFlow Probability
- Reverts PR #915
* Require TensorFlow Probability to at least in the v0.10 range
```
=> revert: Rollback constraints on cloudpickle given TFP v0.10.1 release

src/pyhf/infer/calculators.py, src/pyhf/tensor/pytorch_backend.py, tests/test_infer.py, tests/test_validation.py
Resolves #901 
By looking at the [implementation of `scipy.stats.norm.sf`](https://github.com/scipy/scipy/blob/0a7bc723d105288f4b728305733ed8cb3c8feeb5/scipy/stats/_continuous_distns.py#L262)  I noticed we can fix #901 by changing from `1-cdf(x)` to `cdf(-x)` which gives a more numerically stable result for most backends except pytorch. The pytorch function uses `erf`, but i changed that to using `erfc` (see https://en.wikipedia.org/wiki/Q-function#Definition_and_basic_properties) and after that it also seems to produce better results. I wrote it analogous to the [implementation of `torch.Normal.cdf`](
https://github.com/pytorch/pytorch/blob/3bbedb34b9b316729a27e793d94488b574e1577a/torch/distributions/normal.py#L78-L81)
Now, as a side effect it seems one of the validation tests does not …
=> fix: Change p-value calculation from 1-cdf(x) to cdf(-x)

setup.py
As @jpivarski mentioned that `uproot4` is going to have some API changes from the `uproot` `v3` releases, require that the version of `uproot` that is included in the releases until `uproot4` is released for broad use is using the `uproot` `v3` API.
Once `uproot4` is released and stable this can get changed to using
```python
'xmlio': ['uproot~=4.0']
```
to ensure that all future releases of `pyhf` get the `uproot4` API.
```
* Ensure that the next release series of pyhf isn't broken in the future by API changes in uproot4
```
=> chore: Future proof release against uproot4 API changes

setup.py
Resolves #897
Avoid the regressions caused by Sphinx `v3.1.0` and `v3.1.1` by requiring [Sphinx `v3.1.2`](https://github.com/sphinx-doc/sphinx/releases/tag/v3.1.2) or later.
Huge thanks goes out to @tk0miya :bow: who did some amazing work to make sure that Sphinx would still support libraries that are using `pyhf`'s style of syntax (c.f. [Sphinx Issue 7844](https://github.com/sphinx-doc/sphinx/issues/7844)).
ReadTheDocs build: https://pyhf.readthedocs.io/en/docs-unrestrict-sphinx
```
* Require Sphinx release v3.1.2 or later
- Avoid regressions in Sphinx v3.1.0 and v3.1.1
```
=> docs: Unrestrict Sphinx from v3.0.X releases

docs/babel.rst
This adds information about translating to pyhf from TRExFitter. See https://pyhf.readthedocs.io/en/docs-trexfitter-babel/babel.html#trexfitter for preview.
```
* Add documentation on translation from TRExFitter to pyhf
```
=> docs: Add TRExFitter babel translation

src/pyhf/cli/infer.py
Resolves #940.
Read the Docs build: https://pyhf.readthedocs.io/en/docs-shorterurlforcls/cli.html#pyhf-cls
```
* Use shorter git.io url for pyhf cls --help docstring
* Fix wrapping of pyhf cls --help docstring using \b
```
=> docs: Fix CLs wrapping and add shorter URL

docs/api.rst, src/pyhf/simplemodels.py
Resolves #928 
Add `pyhf.simplemodels.hepdata_like` to the docs as it is in the public API and used in many of the `pyhf` examples.
ReadTheDocs build: https://pyhf.readthedocs.io/en/docs-add-simplemodel-docs/_generated/pyhf.simplemodels.hepdata_like.html
```
* Add docstring with examples to simplemodels.hepdata_like
* Add simplemodels.hepdata_like API to docs
```
=> docs: Add hepdata_like model API to docs

src/pyhf/infer/mle.py
Following PR #960, add additional clarifying information to the note that in addition to being the objective function, `twice_nll` is given to the optimizer and is returned evaluated at the best fit model parameters when the optional kwarg `return_fitted_val=True`. Additionally, try to make this more clear by extending the docstring examples a bit.
Read the Docs build:
- https://pyhf.readthedocs.io/en/docs-clarify-objectiv-funciton-return/_generated/pyhf.infer.mle.fit.html
- https://pyhf.readthedocs.io/en/docs-clarify-objectiv-funciton-return/_generated/pyhf.infer.mle.fixed_poi_fit.html
```
* Clarify in note objective function returned evaluated at best fit model parameters for return_fitted_val
- Amend PR #960
* Update docstring examples for mle.fit and …
```
=> docs: Clarify role of return_fitted_val kwarg for fit and fixed_poi_fit

src/pyhf/infer/__init__.py, src/pyhf/infer/calculators.py
This changes hypotest to make better use of the teststat distribution API (which we overlooked before - making the hypotest code more principled.
```
* Use AsymptoticTestStatDistribution.expected_value for a more principled and clear calculation of the CLs
* Apply the displacement of the test statistic distribution shift to the AsymptoticTestStatDistribution.expected_value
```
=> refactor: Use AsymptoticTestStatDistribution.expected_value API in hypotest for better integration

src/pyhf/tensor/__init__.py, tests/test_init.py
Refactoring out #951. Add missing jax import protection.
```
* Protect against missing JAX imports
* Add JAX to backends in test_init
```
=> fix: Protect against missing JAX imports

docs/bib/tutorials.bib
This PR adds the tutorials that @lukasheinrich and @matthewfeickert gave on 2020-07-16 on `pyhf` `v0.4.4` at the [2020 ATLAS (internal) Induction Day + Software Tutorial](https://indico.cern.ch/event/892952/contributions/3853306/) and [PyHEP 2020](https://indico.cern.ch/event/882824/contributions/3931292/) respectively.
Read the Docs build: https://pyhf.readthedocs.io/en/docs-add-2020-tutorials/outreach.html#tutorials
```
* Add Lukas's tutorial at the 2020 ATLAS Induction Day + Software Tutorial
* Add Matthew's tutorial at PyHEP 2020
* Add pyhf version numbers used to all tutorials
```
=> docs: Add 2020 ATLAS Induction Day and PyHEP 2020 tutorials

setup.py
Set a minimum version of `iminuit` to [`v1.4.3`](https://github.com/scikit-hep/iminuit/releases/tag/v1.4.3) as PR #951 uses the `name` keyword in creating the instance of MINUIT. Additionally, use the compatible release syntax to ensure that `imuniuit` stays in the `v1.X` release series so that when it hits `v2.X` a conscious decision will be made to switch over for the next release of `pyhf`.
```
* Corresponds to use of 'name' keyword in Minuit class in the MINUIT optimizer
- c.f. https://github.com/scikit-hep/iminuit/releases/tag/v1.4.3
```
=> chore: Set minimum version for iminuit to v1.4.3

src/pyhf/tensor/jax_backend.py, tests/test_tensor.py
Not sure why we have axis!=0, but it works just fine. Needed for #951.
```
* Enable jax.np.stack for axis != 0
- Amends PR #377
* Add test for stack along axis !=0
```
=> fix: Enable jax.np.stack for axis !=0

docs/conf.py, docs/governance/ROADMAP.rst, src/pyhf/__init__.py, src/pyhf/cli/infer.py, src/pyhf/exceptions/__init__.py, src/pyhf/optimize/common.py, src/pyhf/optimize/mixins.py, src/pyhf/optimize/opt_jax.py, src/pyhf/optimize/opt_minuit.py, src/pyhf/optimize/opt_numpy.py, src/pyhf/optimize/opt_pytorch.py, src/pyhf/optimize/opt_scipy.py, src/pyhf/optimize/opt_tflow.py, src/pyhf/tensor/jax_backend.py, src/pyhf/tensor/numpy_backend.py, src/pyhf/tensor/pytorch_backend.py, src/pyhf/tensor/tensorflow_backend.py, tests/test_jit.py, tests/test_optim.py, tests/test_public_api.py, tests/test_scripts.py, tests/test_validation.py
Closes #754. Resolves #977.
As an example of behavior change:
```python
>>> pyhf.get_backend()
(<pyhf.tensor.numpy_backend.numpy_backend object at 0x7f33e6692dc0>, <pyhf.optimize.scipy_optimizer object at 0x7f33e668d460>)
>>> pyhf.set_backend("numpy", "minuit")
>>> pyhf.get_backend()
(<pyhf.tensor.numpy_backend.numpy_backend object at 0x7f339d705c80>, <pyhf.optimize.minuit_optimizer object at 0x7f339d706410>)
>>> # NumPy doesn't support autodiff
>>> pyhf.tensorlib.default_do_grad
False
>>> model = pyhf.simplemodels.hepdata_like([50.0], [100.0], [10])
>>> data = [125.0] + model.config.auxdata
>>> pyhf.infer.mle.fit(data, model, do_grad=False)
array([0.50004936, 1.00000438])
>>> # This will fail given that pyhf.tensorlib.default_do_grad == False for NumPy
>>> …
```
=> refactor: Optimizer API harmonization, minuit autodifferentiation support

src/pyhf/__init__.py, src/pyhf/cli/infer.py, src/pyhf/tensor/tensorflow_backend.py, tests/test_jit.py, tests/test_public_api.py
Resolves #982
Add the ability to set the backend precision through a `str` argument in `pyhf.set_backend`. This allows the following
```python
>>> pyhf.set_backend("pytorch", precision="64b")  # string API
>>> pyhf.tensorlib.precision
'64b'
>>> pyhf.set_backend(pyhf.tensor.pytorch_backend(precision="32b"))  # object API 
>>> pyhf.tensorlib.precision
'32b'
>>> pyhf.set_backend("pytorch")  # no default, so defer to backend for precision
>>> pyhf.tensorlib.precision
'32b'
>>> pyhf.set_backend(pyhf.tensor.pytorch_backend(precision="32b"), precision="64b")  # set_backend string API wins if conflict
>>> pyhf.tensorlib.precision
'64b'
```
~~Additionally, set the default backend precision for _all_ backends to `64b`.~~
ReadTheDocs build: …
=> feat: Add precision setting string API to set_backend

src/pyhf/infer/mle.py, src/pyhf/infer/test_statistics.py, src/pyhf/optimize/opt_numpy.py, src/pyhf/optimize/opt_pytorch.py, src/pyhf/optimize/opt_tflow.py, src/pyhf/tensor/jax_backend.py, src/pyhf/tensor/numpy_backend.py, src/pyhf/tensor/pytorch_backend.py, src/pyhf/tensor/tensorflow_backend.py, tests/test_backend_consistency.py, tests/test_constraints.py, tests/test_infer.py, tests/test_optim.py, tests/test_tensor.py
Resolves #954
This PR allows for tensors to take any shape, even empty `()` shapes. This effectively reverts PR #413. It also enforces that the optimizers return the objective function as a scalar (shape `()`), resulting in the test statistic being a scalar.
```
* Allow for arbitrary shape tensors, including 0-dimensional ("empty") shape tensors (floats)
- Reverts PR #413
* Enforce optimizers return objective function as a scalar to harmonize return type
* Revert tests that enforce minimum shape
* Add tests for return structure shape of pyhf.infer.mle.fit
* Add docstring examples for astensor
```
=> revert: Allow 0-dimensional shape tensors

src/pyhf/optimize/common.py, tests/test_optim.py
Unfortunately, #951 wasn't perfect. This fixes one minor bug 
https://github.com/scikit-hep/pyhf/blob/27f35e98739adc7a91d67c8a99581aa1020d407d/src/pyhf/optimize/common.py#L99-L101
where anything specified in `stitch_with` is unused, as `fixed_values` is just used directly. To also make sure this doesn't bite us in the future, I refactored the function slightly, and added tests for the expected behavior/functionality.
```
* Fix bug in stitch_pars to use stitch_with argument
* Refactor stitch_pars to inside _make_stitch_pars function 
* Add test for stitch_pars
```
=> fix: stitch_pars bug in stitching values other than fixed values

setup.py
Resolves #998 
As Issue #997 makes it clear that minor releases might as well be major releases for TensorFlow, then it is probably worth keeping tighter version constraints on TensorFlow and TensorFlow Probability release ranges and just watching the releases of both libraries TensorFlow and TensorFlow Probability to see when we can relax these. 
Note that Issue #997 won't be resolved until TensorFlow Probability `v0.11.0` can be released, and as a result of this the current release workflows will *also* be broken until `v0.11.0` is released. This is a good illustration of the point that with TensorFlow we need to be more restirctive.
```
* Restrict the release ranges of TensorFlow to v2.2.X and TensorFlow Probability to v0.10.X
- Minor releases of TensorFlow can …
```
=> build: Restrict TensorFlow to v2.2.X and TensorFlow Probability to v0.10.X

README.rst
This is our #1000's GitHub item!
ReadTheDocs build: https://pyhf.readthedocs.io/en/milestones-1k_github_items/#milestones
```
* 1000 down! :D
```
=> docs: 1000!

.github/workflows/lint.yml, .hadolint.yaml, docker/Dockerfile, docker/gpu/Dockerfile
Even if you install something with `apt-get` the underlying `lists` directory will be under `/var/lib/apt/lists/` and not `/var/lib/apt-get/lists/`. This is wrong in every Dockerfile I've created in the last 2 years. Thanks to @QuLogic for finding this in https://github.com/matplotlib/mpl-docker/pull/11#discussion_r461160828
This is also a Hadolint error: [DL3009: Delete the apt-get lists after installing something.](https://github.com/hadolint/hadolint/wiki/DL3009)
```
* Clean /var/lib/apt/lists/ as /var/lib/apt-get/lists/ does not exist
- c.f. https://github.com/hadolint/hadolint/wiki/DL3009
* Add linting of Dockerfile with Hadolint action to lint workflow
* Add Hadolint config file
```
=> fix: Clean apt path after apt-get install

setup.py, src/pyhf/infer/calculators.py, tests/test_calculator.py
This adds a cdf method to the asymptotic distribution. This will be useful for two-sided tests. c.f. discussion in PR #966.
ReadTheDocs build: https://pyhf.readthedocs.io/en/asymptotic_cdf
```
* Add cumulative distribution function method to AsymptoticTestStatDistribution
* Add tests for test stat distribution calculators
```
=> feat: Add cdf method to AsymptoticTestStatDistribution

src/pyhf/infer/calculators.py
Amends PR #1010. The return type is rendered on the left hand side of the colon, so the style is different from the function arguments.
```
* Correct return type format
- Amends PR #1010
```
=> docs: Match docstring style format

docs/bib/use_citations.bib
Add the citation of `pyhf` in [_Higgs boson potential at colliders: status and perspectives_](https://inspirehep.net/literature/1757043). The citation is currently incorrect, but it should still be listed.
Thanks to @mswiatlo and @msneubauer for bringing this to our attention through some emails chains. :)
ReadTheDocs build: https://pyhf.readthedocs.io/en/docs-add-higgs-boson-potential-paper/citations.html#use-in-publications
```
* Add citation in "Higgs boson potential at colliders: status and perspectives" paper
- c.f. https://inspirehep.net/literature/1757043
```
=> docs: Add citation in Higgs boson potential at colliders paper

README.rst
To help the [Throughput project](http://throughputdb.com/) track NSF funded software projects add a badge with the IRIS-HEP NSF award number to the `README`
[![NSF-1836650](https://img.shields.io/badge/NSF-1836650-blue.svg)](https://nsf.gov/awardsearch/showAward?AWD_ID=1836650)
as requested by @SimonGoring [on Twitter](https://twitter.com/sjGoring/status/1291452923612762112?s=20).
ReadTheDocs build: https://pyhf.readthedocs.io/en/docs-add-nsf-badge
```
* Add IRIS-HEP NSF award number badge to README
- Helps Throughput project with tracking (http://throughputdb.com/)
```
=> docs: Add NSF award badge for Throughput project tracking

src/pyhf/tensor/tensorflow_backend.py, tests/test_tensor.py
Resolves #1025 
Implements a workaround solution for tensorflow/tensorflow#42332. Essentially, tensorflow's `tile` should technically work when the repeats has more dimensions than the input tensor (works in numpy, torch, jax). Make this possible by using `tf.reshape` to add in extra dimensions to the front.
Needed by #731.
```
* Add support to tensorlib.tile for tensorflow for repeats with more dimensions than the input tensor
* Add test for new behaviour
```
=> fix: Tensorflow tile tensor backend feature parity

README.rst, docs/examples/notebooks/hello-world.ipynb, src/pyhf/cli/infer.py, src/pyhf/infer/__init__.py, tests/test_infer.py, tests/test_regression.py, tests/test_validation.py
Resolves #714
Results in the following behavior for the CLs values
```python
>>> model = pyhf.simplemodels.hepdata_like(signal_data=[12.0, 11.0], bkg_data=[50.0, 52.0], bkg_uncerts=[3.0, 7.0])
>>> data = [51, 48] + model.config.auxdata
>>> test_mu = 1.0
>>> CLs_obs, CLs_exp = pyhf.infer.hypotest(test_mu, data, model, qtilde=True, return_expected=True)
>>> CLs_obs
array(0.05251554)
>>> CLs_exp
array(0.06445521)
```
previous behavior was
```python
>>> model = pyhf.simplemodels.hepdata_like(signal_data=[12.0, 11.0], bkg_data=[50.0, 52.0], bkg_uncerts=[3.0, 7.0])
>>> data = [51, 48] + model.config.auxdata
>>> test_mu = 1.0
>>> CLs_obs, CLs_exp = pyhf.infer.hypotest(test_mu, data, model, qtilde=True, return_expected=True)
>>> CLs_obs
array([0.05251554])
>>> …
```
=> refactor: Make hypotest return CLs as 0-d tensor

docs/api.rst, src/pyhf/infer/__init__.py, src/pyhf/infer/calculators.py, src/pyhf/infer/mle.py, src/pyhf/infer/test_statistics.py
Resolves #601 
Add mathematical examples/foundations of the use of the infer API in [arXiv:1007.1727](https://arxiv.org/abs/1007.1727) as well as provide additional API examples. This is mainly a port of work started on [`docs/add-docstrings-to-utils`](https://github.com/scikit-hep/pyhf/compare/docs/add-docstrings-to-utils), which was incomplete and had errors.
ReadTheDocs build: https://pyhf.readthedocs.io/en/docs-update-maths-in-infer-docstrings/api.html#inference
```
* Add maths examples to the infer API docstrings
- Based on relation to equations in https://arxiv.org/abs/1007.1727
* Correct hypotest docstring to use the profile likelihood ratio test statistic
* Add API example to twice_nll docstring
```
=> docs: Extend infer docstrings with mathematical examples

src/pyhf/events.py, tests/test_events.py, tests/test_interpolate.py, tests/test_tensor.py
(See this nice answer for other libs: https://stackoverflow.com/a/16192256/1532974)
Fix a source of memory leaks observed by SModelS developers reported in #934, #620. This leak occurs because even though certain objects go out of scope - garbage-collect in python isn't invoked because we kept rather strong references to the bound methods of these objects. Instead, use [`weakref.WeakMethod`](https://docs.python.org/3/library/weakref.html#weakref.WeakMethod) to keep weaker references that are auto-removed from events if the objects owning those methods go out of scope (allowing python's garbage collect to actually.. collect garbage).
This was not so easy to track down, so I thank @lukasheinrich for narrowing it down a lot more with a simple MWE and his latest theory.
```python
a = …
```
=> fix: Weakly reference callables for pub-sub model

src/pyhf/pdf.py, tests/test_pdf.py
This resolves #1027.
Both `pyhf.pdf.Model.expected_actualdata` and `pyhf.pdf.Model.expected_auxdata` only take tensors as arguments, while `pyhf.pdf.Model.expected_data` converts its arguments to the appropriate tensor format. This PR adds the conversion also to `expected_actualdata` and `expected_auxdata`.
This enables running the following:
```python
import pyhf
model = pyhf.simplemodels.hepdata_like(
signal_data=[12.0, 11.0], bkg_data=[50.0, 52.0], bkg_uncerts=[3.0, 7.0]
)
model.expected_data(model.config.suggested_init())
model.expected_actualdata(model.config.suggested_init())
model.expected_auxdata(model.config.suggested_init())
```
Also adding a test for the behavior that would fail on the current master branch.
```
* Make args of Model.expected_actualdata and …
```
=> fix: Tensor conversion for expected aux and actual data

src/pyhf/workspace.py, tests/test_workspace.py
Resolves #1023 
```
* Workspace.combine returns cls() instead of Workspace() allowing for others to inherit pyhf.Workspace
```
=> fix: Make pyhf.Workspace.combine return CLs instead of Workspace

.pre-commit-config.yaml, docs/development.rst, src/pyhf/cli/patchset.py, src/pyhf/cli/spec.py, src/pyhf/constraints.py, src/pyhf/modifiers/histosys.py, src/pyhf/modifiers/lumi.py, src/pyhf/modifiers/normfactor.py, src/pyhf/modifiers/normsys.py, src/pyhf/modifiers/shapefactor.py, src/pyhf/modifiers/shapesys.py, src/pyhf/optimize/mixins.py, src/pyhf/parameters/paramview.py, src/pyhf/pdf.py, src/pyhf/tensor/common.py, src/pyhf/tensor/tensorflow_backend.py, src/pyhf/writexml.py, tests/conftest.py, tests/test_backend_consistency.py, tests/test_combined_modifiers.py, tests/test_infer.py, tests/test_optim.py, tests/test_patchset.py, tests/test_pdf.py, tests/test_schema.py, tests/test_scripts.py, tests/test_tensor.py, tests/test_tensorviewer.py
The final beta releases of Black bring about some changes in formatting, as we see in Black [`v20.8b1`](https://github.com/psf/black/releases/tag/20.8b1). This PR applies those style changes, and appropriatley changes the pre-commit style change so that commits don't fail with Black conflicts.
This PR also introduces the use of pinning the `rev` used in `pre-commit` as this is advocated for by `pre-commit` core dev @asottile in https://github.com/psf/black/issues/420 &mdash; thanks to @alexander-held and @henryiii for pointing this out and explaining more to us. (It seems from https://github.com/omry/omegaconf/pull/340 that others are in a similar boat as we are right now). The dev docs are also updated to reflect this.
```
* Apply Black v20.8b1 formatting
- Should …
```
=> style: Update to Black v20.8 formatting

src/pyhf/workspace.py, tests/test_workspace.py
Resolves #751. Resolves #811.
Prune/Rename now raise a `pyhf.exceptions.InvalidWorkspaceOperation` if a supplied name for channel, sample, measurement, modifier, modifier type is not in the workspace. This allows us to be a bit more strict and help the user catch typos they might not have otherwise noticed.
```
* prune/rename raise exceptions if a supplied name for channel, sample, measurement, modifier, or modifier type is not in the workspace
* Add tests for raised exceptions
```
=> feat: Prune/Rename raise errors if item name not in workspace

src/pyhf/optimize/opt_minuit.py, tests/test_optim.py
This resolves a comment made in #1051 where step sizes were not being zero'd out correctly.
> Suggestion: For the minuit optimizer, the initial step size is set in minuit_optimizer._get_minimizer. For a fixed Gaussian-constrained nuisance parameter with default bounds [-5, 5], this is 0.01 with the default 1000 steps. This will be the parameter uncertainty reported by minuit after the fit. Given that it does not make sense to have an uncertainty for a fixed parameter, it might be nice to set the entries of step_sizes corresponding to fixed parameters to 0 instead.
_Originally posted by @alexander-held in https://github.com/scikit-hep/pyhf/pull/1051#issuecomment-687117202_
```
* Step sizes are set to 0.0 for fixed parameters in a fit for minuit
- The step size acts as …
```
=> fix: Step sizes for fixed parameters in minuit should be 0.0

docs/bib/use_citations.bib
Add [_A SModelS interface for pyhf likelihoods_](https://inspirehep.net/literature/1814793) by @Ga0l, @sabinekraml, and @WolfgangWaltenberger to list of papers that cite `pyhf`. :clap: to the SModelS team on both the [release of `v1.2.4`](https://github.com/SModelS/smodels/releases/tag/v1.2.4) as well as the nice paper. :rocket:
ReadTheDocs build: https://pyhf.readthedocs.io/en/docs-add-citation-from-smodels/citations.html#use-in-publications
```
* Add SModelS paper on SModelS v1.2.4 pyhf interface and use of public likelihoods
- c.f. https://inspirehep.net/literature/1814793
```
=> docs: Add SModelS paper to citations list

docs/governance/ROADMAP.rst, pyproject.toml, pytest.ini, setup.py, tests/conftest.py, tests/test_teststats.py, tests/test_validation.py
Requires pytest > 6.0
Resolves #370 
```
* Require pytest 6.0+ in the 'test' extra
* Migrate from pytest.ini to pyproject.toml
* Fix fixtures in test_validation.py
* Fix Node.get_marker calls
- c.f. https://docs.pytest.org/en/stable/historical-notes.html#marker-revamp
* Mark pytest issue on ROADMAP complete
```
=> feat: Bump to modern pytest (6.0+)

src/pyhf/tensor/jax_backend.py, src/pyhf/tensor/numpy_backend.py, src/pyhf/tensor/pytorch_backend.py, src/pyhf/tensor/tensorflow_backend.py, tests/test_tensor.py
Resolves #963 
Add the functions `erf` and `erfinv` to the tensorlib backends.
ReadTheDocs build: https://pyhf.readthedocs.io/en/feat-add-erf-and-inverf/_generated/pyhf.tensor.numpy_backend.numpy_backend.html#pyhf.tensor.numpy_backend.numpy_backend.erf
```
* Add erf and erfinv methods to the tensorlib backends
* Add tests for erf and erfinv
```
=> feat: Add erf and erfinv to tensorlib

src/pyhf/cli/cli.py, src/pyhf/cli/infer.py, tests/test_scripts.py
* Resolves #784 
* Resolves #828
Adds the following functionality to the CLI API:
```
$ pyhf fit --help
Usage: pyhf fit [OPTIONS] [WORKSPACE]
Perform a maximum likelihood fit for a given pyhf workspace.
Example:
.. code-block:: shell
$ curl -sL https://git.io/JJYDE | pyhf fit --value
{
"mle_parameters": {
"mu": [
0.00017298628839781602
],
"uncorr_bkguncrt": [
1.0000015671710816,
0.9999665895859197
]
},
"twice_nll": 23.19636590468879
}
Options:
--output-file TEXT              The location of the output json file. If not
specified, prints to screen.
--measurement TEXT
-p, --patch TEXT
--value                         Flag for returning the fitted value of the
objective function.
--backend [numpy|pytorch|tensorflow|jax|np|torch|tf]
The tensor backend used for the calculation.
--optimizer …
```
=> feat: Add fit to infer CLI API

setup.py
To temporarily avoid the problems of Issue #1069, restrict `iminuit` to be below `v1.5.0` as it seems that there might need to be a new release of `iminuit` before #1069 can be resolved.
```
* Restrict iminuit to releases in the v1.4.X range for X >= 3
- iminuit v1.5.0 breaks pyhf for 32b TensorFlow and PyTorch
- c.f. Issue #1069
```
=> fix: Restrict iminuit to v1.4.X releases

.github/workflows/dependencies-head.yml
In light of Issue #1069, this PR adds nightly tests that run at the `HEAD` of dependencies that are the most reasonable for us to check and interact with. If we detect breaking changes in these dependencies at their `HEAD` then we should have time to either proactively address this in `pyhf` or work with the dependency dev team to mitigate them. They can also be run on demand with workflow dispatch.
Note that these tests only run on CRON jobs and on demand, but never on pushes of PRs.
Example workflow: https://github.com/scikit-hep/pyhf/actions/runs/265261547
```
* Add nightly tests to run test suite at HEAD of dependencies
- Use as early alert for breaking changes in dependencies
- Run for SciPy, iminuit, and uproot
```
=> ci: Add nightly tests using HEAD of dependencies

.github/workflows/ci.yml, .github/workflows/publish-package.yml, .github/workflows/release_tests.yml, .github/workflows/tag.yml
Update the releases of the GitHub Actions uses in the CI workflows and update to using Python 3.8 as the default for testing actions.
```
* Update releases of GitHub Actions used in workflow
- codecov-action @v1, gh-action-pypi-publish@v1.3.1
* Use Python 3.8 as the runtime for all reporting in CI
```
=> chore: Update GitHub Action releases and Python runtimes in CI

.github/workflows/ci.yml, .github/workflows/dependencies-head.yml, .github/workflows/lint.yml, .github/workflows/merged.yml, .github/workflows/publish-docker.yml, .github/workflows/publish-package.yml, .github/workflows/release_tests.yml
Add support for workflow dispatch.
```
* Add workflow dispatch support to GitHub Actions workflows
- c.f. https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
```
=> ci: Add workflow dispatch support

.github/workflows/ci.yml, .github/workflows/notebooks.yml
Resolves #1077 
To speed up the PR process, as the notebooks are the slowest tests by far, have the notebooks no longer be tested every PR but in a workflow that runs nightly on a CRON job and through workflow dispatch. This will ensure that any breaking changes that get through are caught within 24 hours, while speeding up CI. Workflow dispatch will also allow for the notebook tests to be run on any branch.
```
* Migrate notebook tests from main CI to notebook testing workflow to speed up PRs
- Run on as a nightly CRON job as well as through workflow dispatch
- Don't run on pushes or PRs
```
=> ci: Add workflow for nightly tests of notebooks

README.rst, docs/conf.py, docs/faq.rst
Resolves #1062 
Add information to the docs on how to subscribe to the `pyhf-announcements` mailing list (run through Google Groups for the time being).
ReadTheDocs build:
- https://pyhf.readthedocs.io/en/docs-add-mailing-list-to-contact/#questions
- https://pyhf.readthedocs.io/en/docs-add-mailing-list-to-contact/faq.html#how-can-i-get-updates-on-pyhf
```
* Add information on subscribing to the pyhf-announcements mailing list to the README and FAQ
- https://groups.google.com/group/pyhf-announcements/subscribe
```
=> docs: Add information on announcement mailing list

docs/bib/use_citations.bib
Add citations from the following papers that @lukasheinrich discovered had cited us with a `site:arxiv.org pyhf` search on Google. :)
- [Sensitivity of Future Hadron Colliders to Leptoquark Pair Production in the Di-Muon Di-Jets Channel](https://inspirehep.net/literature/1764068)
- [Lepton Flavor Violation and Dilepton Tails at the LHC](https://inspirehep.net/literature/1780095)
- [SModelS database update v1.2.3](https://inspirehep.net/literature/1794162)
- [GPU coprocessors as a service for deep learning inference in high energy physics](https://inspirehep.net/literature/1808088)
ReadTheDocs build: https://pyhf.readthedocs.io/en/docs-add-new-citations/citations.html#use-in-publications
```
* Add citations from papers in 2019 and 2020
- …
```
=> docs: Add citations from 2019 and 2020 papers

.github/workflows/tag.yml, docs/development.rst, setup.py
Resolves #1082 
Migrate to using `bump2version` `v1.X` release series in the `tag` workflow.
```
* Migrate from using bumpversion to bump2version in the develop extra
- bumpversion is no longer maintained and bump2version is the recommended fork
* Use bump2version v1.X series in the tag workflow
```
=> chore: Migrate from bumpversion to bump2version

tests/test_tensor.py
Resolves #971 
Add a test to ensure the tensor backends implement a continuous approximation of the Poisson distribution.
```
* Add test to ensure tensor backends implement a continuous approximation of the Poisson distribution
```
=> test: Ensure continuous approximation of Poisson implemented

docs/babel.rst
Clean up docs a bit. This is supported as of #846 / #1051.
/cc @alexander-held 
```
* Remove fixed parameters caveat for TRexFitter in babel as it is now supported
```
=> docs: Remove fixed parameters caveat for TRexFitter in babel

CONTRIBUTING.md, docs/contributors.rst, docs/index.rst
Resolves #1094 
List all the contributors to `pyhf` on the website and update the `CONTRIBUTING.md` to tell people to do so.
ReadTheDocs build: https://pyhf.readthedocs.io/en/docs-add-contributers-to-docs/contributors.html
```
* Add list of all contributors as page to the website
* Update CONTRIBUTING.md to instruct people to add their names
```
=> docs: Add contributors to website

docs/contributors.rst, src/pyhf/infer/calculators.py
Fix deprecation warnings due to invalid escape sequences by using raw strings
```
* Fix deprecation warnings due to invalid escape sequences by using raw strings
```
=> fix: Avoid deprecation warnings due to invalid escape sequences

src/pyhf/cli/contrib.py
Resolves #1103 
Remove defaults for `pyhf contrib download` that were wrongly set.
```
* Remove contrib download defaults for arguments ARCHIVE_URL OUTPUT_DIRECTORY
* Amends PR #1046
```
=> fix: Remove improper defaults for contrib download

src/pyhf/cli/contrib.py
using the new DOI thanks to @GraemeWatt
```
* Use DOI in docstring example for pyhf contrib download
- c.f. https://doi.org/10.17182/hepdata.90607.v3/r3
```
=> docs: Use 1Lbb DOI in contrib download docstring

src/pyhf/infer/__init__.py, src/pyhf/infer/intervals.py, tests/test_infer.py
Make `infer.intervals` available upon import of `pyhf`. This comes from a request from @alexander-held.
```
* Make infer.intervals available at import of infer
* Remove unneeded imports
```
=> fix: Import all infer submodules

.github/workflows/ci.yml, .github/workflows/docs.yml, README.rst
As there are certain times when the docs fail or needs to be rerun it is more convenient if they can be run by themselves rather than the full CI workflow. This PR migrates the doc testing and deployment into a separate GitHub Actions workflow.
ReadTheDocs build: https://pyhf.readthedocs.io/en/ci-migrate-docs-to-seperate-workflow/
```
* Migrate the testing and deploying of the docs into a separate GitHub Actions workflow
- Allows for running independently using workflow dispatch
* Add Docs build status on master badge to README
```
=> ci: Make docs separate workflow

src/pyhf/cli/spec.py, src/pyhf/workspace.py, tests/test_scripts.py, tests/test_workspace.py
This adds functionality to get channel merging as part of a "combination". Can only be done with `outer`, `left outer`, or `right outer`:
```
pyhf combine --join "left outer" \
--merge-channels \
<(pyhf prune --sample C1N2_Wh_hbb_800_250 pyhf_likelihood.json)\
test.json
```
Additionally, clean up the logic in `pyhf.workspace._join_items` to fix up coverage.
```
* Extend combine to allow for merging channels from two workspaces when performing an outer join
- This is generally useful when you want to combine a bkg-only workspace with a signal-only workspace with the same set of channels, but need to merge the channels together (extend bkg-only samples with signal-only samples for each channel)
* Improve the coverage of pyhf/workspace.py by cleaning up the …
```
=> feat: Merge channel functionality in pyhf combine

src/pyhf/__init__.py, src/pyhf/constraints.py, src/pyhf/contrib/utils.py, src/pyhf/infer/__init__.py, src/pyhf/infer/calculators.py, src/pyhf/infer/intervals.py, src/pyhf/infer/mle.py, src/pyhf/infer/test_statistics.py, src/pyhf/modifiers/__init__.py, src/pyhf/optimize/common.py, src/pyhf/optimize/mixins.py, src/pyhf/optimize/opt_jax.py, src/pyhf/optimize/opt_minuit.py, src/pyhf/optimize/opt_numpy.py, src/pyhf/optimize/opt_pytorch.py, src/pyhf/optimize/opt_tflow.py, src/pyhf/patchset.py, src/pyhf/pdf.py, src/pyhf/probability.py, src/pyhf/simplemodels.py, src/pyhf/tensor/jax_backend.py, src/pyhf/tensor/numpy_backend.py, src/pyhf/tensor/pytorch_backend.py, src/pyhf/tensor/tensorflow_backend.py, src/pyhf/utils.py, src/pyhf/workspace.py
Resolves #1116 . Use `:obj:` notation consistently everywhere in our docs.
Docs: https://pyhf.readthedocs.io/en/docs-fixdocstringnotation/
```
* Harmonize use of sphinx :obj: notation in docs
```
=> docs: Use sphinx obj scope in docs by default

src/pyhf/events.py
Resolves #984 
Use [`functools.wraps`](https://docs.python.org/3.8/library/functools.html#functools.wraps) to wrap the [`events.register` decorator](https://github.com/scikit-hep/pyhf/blob/f248db092dcfbe6e3354bc1d0731a7713258dc2a/src/pyhf/events.py#L47) to properly get docstrings for `pyhf.set_backend`.
https://github.com/scikit-hep/pyhf/blob/f248db092dcfbe6e3354bc1d0731a7713258dc2a/src/pyhf/__init__.py#L37-L58
ReadTheDocs build: https://pyhf.readthedocs.io/en/fix-use-functools-wraps-for-docs/_generated/pyhf.set_backend.html#pyhf.set_backend
HT to @kratsg for identifying the fix. :+1: 
```
* Use functools.wraps to wrap events.register decorator to properly get docstrings for pyhf.set_backend
```
=> fix: Use functools.wraps with events.register to render docstrings

src/pyhf/infer/__init__.py, src/pyhf/infer/mle.py, tests/test_infer.py
Resolves #1123 
Addresses Issue #1123 reported by @alexander-held. This raises `ValueError` if any initial parameter (fixed or not) used
in a fit lies outside of the parameter bounds.
```
* Add check to validate initialization parameters for pyhf.infer.fit
* Add test of raised error using hypotest POI out of bounds
```
=> fix: Validate fit initialization parameters

src/pyhf/workspace.py, tests/test_workspace.py
This technically had the right tests in place, but simply forgot to add `outer` join as a join method to check the logic of the merge channels for. This PR will add it in, but then also fix the logic bug (reverse the conditionals).
See #1088 .
```
* Fix logic bug for merge channels of combine for outer join functionality
* Amends PR #1088
```
=> fix: Logic bug for outer joins of merge channels

docs/conf.py, src/pyhf/readxml.py, src/pyhf/utils.py, src/pyhf/writexml.py, tests/test_export.py, tests/test_import.py, tests/test_scripts.py, tests/test_utils.py
Resolves #1107. ROOT, in all its glory, decides to prefix parameter names in the measurement specification. We need to update `readxml.py` to strip this prefix, but additionally update `writexml.py` to prepend this prefix.
```
* Fix parameter naming for compatibility with ROOT import/export
- prefixes alpha_ and gamma_ are stripped when importing from ROOT workspaces
- prefixes alpha_ and gamma_ are added when exporting to ROOT workspaces
```
=> fix: Fixed parameter naming for compatibility with ROOT import/export

.gitattributes
Help `git diff` give more information in the diff by giving it information on file type via file extensions. HT [this Tweet from Raymond Hettinger](https://twitter.com/raymondh/status/1318260360789454848) on this article "[Better Git diff output for Ruby, Python, Elixir, Go and more](https://tekin.co.uk/2020/10/better-git-diff-output-for-ruby-python-elixir-and-more)" by [Tekin Süleyman](https://tekin.co.uk/) (@tekin) &mdash; thanks Tekin!
This is labeled as "chore" given that this only helps the devs and has no other impact on the project.
```
* Add file information for Python and Markdown to .gitattributes for git diff to use
- c.f. https://tekin.co.uk/2020/10/better-git-diff-output-for-ruby-python-elixir-and-more
- …
```
=> chore: Add file types for diff to .gitattributes

setup.py, src/pyhf/tensor/jax_backend.py, tests/test_probability.py
With release [`v0.2.4` of JAX](https://github.com/google/jax/releases/tag/jax-v0.2.4) the underlying stats API has changed as there is no longer a `jax.scipy.stats.norm.osp_stats` or `jax.scipy.stats.poisson.osp_stats` API, but instead [JAX now just uses the SciPy API directly with](https://github.com/google/jax/blob/4b8334ab0b8d9d3f1c676866d177f3e3e6b4c250/jax/_src/scipy/stats/poisson.py#L16)
```
import scipy.stats as osp_stats
```
As such, this requires a minimum version bump of `jax` and `jaxlib` and then also requires changing the imports to use SciPy directly. Given that the continuous approximation to the Poisson is used there is actually no need to import `jax.scipy.stats.poisson` anymore either.
```
* Use JAX v0.2.4 API with regards to using scipy.stats …
```
=> fix: Use JAX v0.2.4+ API

src/pyhf/tensor/jax_backend.py
As a follow up to PR #1134, I noticed in [JAX PR 3760](https://github.com/google/jax/pull/3760) that JAX has changed style from
```python
import numpy as onp
import jax.numpy as np
```
to now using
```python
import numpy as np
import jax.numpy as jnp
```
To try to make the code as clear as possible for comparison purposes we should also adopt this style change.
```
* Adopt JAX v0.2 API style change of numpy and jax.numpy imports:
- import numpy as np
- import jax.numpy as jnp
* c.f. https://github.com/google/jax/pull/3760
```
=> style: Adopt new JAX style of np and jnp

src/pyhf/readxml.py, src/pyhf/writexml.py, tests/test_export.py, tests/test_import.py
Resolves #1080. This adds in the shapefactor import. ./cc @alexander-held 
```
* Add ShapeFactor support to pyhf.readxml
* Add ShapeFactor support to pyhf.writexml
* Add ShapeFactor test
```
=> feat: Support ShapeFactor for import/export

.github/workflows/tag.yml
Resolves #1096. 
```
* Migrate workflow from deprecated 'set-env' and 'add-path' to 'exportVariable' and 'addPath'
- c.f. https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files
```
=> chore: Migrate to new way to set environment variables in GHA

src/pyhf/cli/infer.py, src/pyhf/infer/__init__.py, src/pyhf/infer/calculators.py, src/pyhf/infer/test_statistics.py, src/pyhf/pdf.py, tests/test_validation.py
changes to saner defaults in python (same defaults used in CLI).
since this is an API change this should probably go in for `v0.6.0`.
ReadTheDocs build:
- https://pyhf.readthedocs.io/en/change_defaults/
- [`pyhf.infer.hypotest`](https://pyhf.readthedocs.io/en/change_defaults/_generated/pyhf.infer.hypotest.html)
- [`pyhf.infer.test_statistics.qmu_tilde`](https://pyhf.readthedocs.io/en/change_defaults/_generated/pyhf.infer.test_statistics.qmu_tilde.html)
- [`pyhf.infer.calculators.AsymptoticCalculator`](https://pyhf.readthedocs.io/en/change_defaults/_generated/pyhf.infer.calculators.AsymptoticCalculator.html)
```
* Use the same defaults across the Python and CLI API
- Use interpolation code4 and code4p in default modifier settings for models
- Use qtilde as the default …
```
=> feat: Update model and inference defaults

.pre-commit-config.yaml, docs/contributors.rst
Hi,
Thanks for trying out nbqa - our default hooks use the latest available version of each tool, but for best reproducibility it's best to pin them. Admittedly, that's something we'd neglected to document :flushed:  but [it's there now](https://github.com/nbQA-dev/nbQA#pre-commit)
```
* Set dependency versions of black and pyupgrade for nbQA to use
* Remove language_version from Black pre-commit hook as already specified
```
=> fix: Pin additional dependencies in pre-commit hooks

src/pyhf/optimize/opt_minuit.py, tests/test_optim.py
Teach pyhf to set the minuit strategy correctly depending on whether user provides gradient or not. Additionally allow for this to be configurable via `strategy` kwarg.
Resolves #1172.
ReadTheDocs build: https://pyhf.readthedocs.io/en/feat-userprovidedgradientstominuit/_generated/pyhf.optimize.opt_minuit.minuit_optimizer.html
```
* Set MINUIT strategy to 0/1 automatically if using gradients/no-gradient
* Allow for MINUIT strategy to be configurable
* Add test for strategy selection
```
=> feat: Set minuit strategy automatically for gradient/non-gradient mode

docs/bib/use_citations.bib
Add use citation from [the published CHEP 2019 conference proceedings](https://doi.org/10.1051/epjconf/202024506017) for @matthewfeickert's talk "Likelihood preservation and statistical reproduction of searches for new physics" that was given on behalf of ATLAS.
Resolves the last part of Issue #658.
ReadTheDocs build: https://pyhf.readthedocs.io/en/docs-add-chep-2019-proceedings/citations.html#use-in-publications
```
* Add use citation for the published CHEP 2019 conference proceedings
- c.f. https://doi.org/10.1051/epjconf/202024506017
```
=> docs: Add CHEP 2019 proceedings use citation

src/pyhf/optimize/opt_minuit.py, src/pyhf/optimize/opt_scipy.py, tests/test_optim.py
This PR fully resolves #929.
/cc @alexander-held
```
* Add configurable optimizer tolerance for minimization termination
- NB: SciPy defaults to None, iminuit defaults to 0.1
* Add tests to ensure the API for SciPy/iminuit
```
=> feat: Configurable optimizer tolerance for termination

src/pyhf/contrib/cli.py, tests/test_scripts.py
Resolves #1182
Move the import of `pyhf.contrib.utils` inside of the `pyhf.contrib.cli` methods, as `pyhf contrib` still needs to be accessible from the CLI along with the other modules by default so that users can learn about it but the methods of the module should be able to warn if there are missing libraries. This allows for the other CLI modules to not trigger the warnings and for the warnings to still come up if the errors are directly triggered through use.
As an example, this allows for the following:
```
$ python -m pip install pyhf[xmlio]
$ pyhf json2xml --help
Usage: pyhf json2xml [OPTIONS] [WORKSPACE]
Convert pyhf JSON back to XML + ROOT files.
Options:
--output-dir PATH
--specroot TEXT
--dataroot TEXT
--resultprefix TEXT
-p, --patch TEXT
-h, --help           Show this message …
```
=> fix: Isolate pyhf contrib commands from rest of CLI

src/pyhf/modifiers/histosys.py, src/pyhf/modifiers/lumi.py, src/pyhf/modifiers/normfactor.py, src/pyhf/modifiers/normsys.py, src/pyhf/modifiers/shapefactor.py, src/pyhf/modifiers/shapesys.py, src/pyhf/modifiers/staterror.py
@lukasheinrich identified this. It seems that #323 and #285 are the culprit here. Primarily, as it was a large PR, the refactoring wasn't so perfect and we left some cruft in at the end. This just cleans it up.
```
* Drop the modifier from required_parset()
- Parameter set requirements do not need to know modifier
```
=> refactor: Drop 'modifier' from parameter set requirements

setup.py, src/pyhf/cli/rootio.py, src/pyhf/readxml.py, src/pyhf/writexml.py, tests/test_import.py
Avoid errors seen in CI with by switching over to using the new [`uproot3`](https://pypi.org/project/uproot3/) namespace. It is seen that some of the tests like
https://github.com/scikit-hep/pyhf/blob/a33baddf6620df371338c6d1b98fdbab1b9da5c4/tests/test_scripts.py#L169
find an 
```
ModuleNotFoundError: No module named 'uproot3'
```
without the namespace switch. cc-ing @jpivarski just in case this is of interest.
I think this is because in `uproot_methods` instances of 'uproot' were renamed to 'uproot3': https://github.com/scikit-hep/uproot-methods/commit/02f9911b4437ae895a742a173eb88094e27eb65c
We could require a max on `uproot_methods` of `v0.9` so that we never get `v0.9.1` in which this takes place, but it seems easier to just update to `uproot3` and we'll probably be able to switch …
=> fix: Use uproot3 namespace

.flake8, .github/workflows/lint.yml, .pre-commit-config.yaml, setup.cfg, setup.py, src/pyhf/contrib/cli.py, src/pyhf/infer/__init__.py, src/pyhf/infer/utils.py, src/pyhf/optimize/opt_minuit.py, src/pyhf/pdf.py, src/pyhf/readxml.py, tests/test_init.py, tests/test_modifiers.py, tests/test_optim.py, validation/manualonoff_roofit/onoff.py
Resolves #863
Switch from `pyflakes` to the more configurable and modern `flake8` for linting.
In `setup.cfg` ignore
- [E203: whitespace before ':'](https://www.flake8rules.com/rules/E203.html) (avoid things like `text[len(prefix) :]`)
- [E402: module level import not at top of file](https://www.flake8rules.com/rules/E402.html) (sometimes needed)
- [E501: line too long](https://www.flake8rules.com/rules/E501.html) (not worth changing)
and fix:
- `src/pyhf/readxml.py:43:8:` [E713 test for membership should be 'not in'](https://www.flake8rules.com/rules/E713.html)
- `src/pyhf/infer/utils.py`: [E231 missing whitespace after ','](https://www.flake8rules.com/rules/E23.html)
and inline ignore `# noqa` (special cases):
- [F401: Module imported but …
=> chore: Use flake8 for linting

tests/test_optim.py
Resolves #1193.
This adds a check for the NLL value returned by minimization with various backends, which is compared against a reference.
It also adds a check for the parameter uncertainties returned by Minuit, which was motivated by #1183 (the addition of the HESSE call would have resulted in a slight change in the uncertainties returned here). A test for the parameter values could also be added here, but since that behavior is tested in `test_minimize` already I did not add it again here.
I noticed that three functions set parameters constant without using the keyword argument `fixed_vals`, which I expect is not on purpose. I added another commit in here that changes that.
```
* Add a test for the NLL value returned by minimization
* Explicitly specify the …
```
=> test: Verify NLL values and Minuit parameter uncertainties

src/pyhf/writexml.py
With the release of [`uproot3` `v3.14.1`](https://github.com/scikit-hep/uproot3/releases/tag/3.14.1) and the [yanking of release of `v3.14.0`](https://pypi.org/project/uproot3/3.14.0/#history), `uproot3` requires `uproot3-methods`. To quote the release notes:
> Rename `uproot-methods` → `uproot3-methods`, since the fact that "`uproot-methods`" as a package with different versions was breaking dependencies for people with old versions of this package.
```
* Use uproot3-methods namespace
- Required by uproot3 since the release of v3.14.1 and the yank of v3.14.0
```
=> fix: Use uproot3-methods with uproot3

src/pyhf/pdf.py, tests/test_init.py
As a follow up to PR #1191, this PR specify some exception for all exception cases, allowing for the `#noqa`s for [E722: Do not use bare except, specify exception instead](https://www.flake8rules.com/rules/E722.html) to be removed.
```
* Specify exception for all exception cases
* Remove all inline noqa: E722
- E722: Do not use bare except, specify exception instead
```
=> chore: Specify exceptions to remove inline ignores of E722

src/pyhf/tensor/jax_backend.py, src/pyhf/tensor/numpy_backend.py, src/pyhf/tensor/pytorch_backend.py, src/pyhf/tensor/tensorflow_backend.py, tests/test_tensor.py
Fixes the typo `continous` -> `continuous` in a few docstrings and a comment.
```
* Fix typo of the word "continous" in a few docstrings and a comment
```
=> docs: Correct spelling of continuous

setup.py, src/pyhf/optimize/opt_minuit.py, tests/test_optim.py
Update to `iminuit` `v1.5.3+` API to take advantage of https://github.com/scikit-hep/iminuit/pull/464. This allows for the mocking of `iminuit.Minuit().from_array_func` that was added in PR #951 to be removed.
```
* Require iminuit compatible with v1.5.3 in 'minuit' extra
* Adopt iminuit v1.5.3+ API
- ncalls -> ncalls_total
- ngrads -> ngrads_total
* Remove mocking of iminuit.Minuit().from_array_func from tests
- c.f. https://github.com/scikit-hep/iminuit/pull/464
```
=> feat: Use iminuit v1.5.X API

.github/workflows/ci.yml, .github/workflows/release_tests.yml
The MacOS VMs are quite slow and the level of redundency in testing all the Python runtimes across all the OS seems to give a minimal advantage while incuring a lot of lag in CI speed. This PR excludes Python 3.6 and Python 3.7 on MacOS from the testing matrix. Python 3.6, 3.7, and 3.8 are still tested on Linux.
```
* Exclude Python 3.6 and Python 3.7 from the testing matrix for macos-latest
- Speed up CI significantly while still testing the latest Python runtime on macos-latest
* Add testing of Python 3.6 to current release tests
* c.f. https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#example-excluding-configurations-from-a-matrix
```
=> ci: Test only latest Python runtime on MacOS

src/pyhf/tensor/jax_backend.py
The nightly CI is failing doctest as there was a change from the `type` of a JAX `DeviceArray` from `jax.interpreters.xla.DeviceArray` -> `jax.interpreters.xla._DeviceArray`.
```
* Update JAX DeviceArray type in docstrings to jax.interpreters.xla._DeviceArray
- Needed to pass doctest
```
=> fix: Update JAX DeviceArray type in docstrings for doctest

README.rst, docs/index.rst
- Resolves #1214 
- Resolves #1215 
Make the [![Conda-forge version](https://img.shields.io/conda/vn/conda-forge/pyhf.svg)](https://github.com/conda-forge/pyhf-feedstock) badge link to the conda-forge `pyhf-feedstock` page and make the docs banner redirect to the repo page instead of directly to the fork page.
ReadTheDocs build: https://pyhf.readthedocs.io/en/docs-improve-links/
```
- Link conda-forge badge to pyhf-feedstock repo
- c.f. https://github.com/conda-forge/pyhf-feedstock
- Make docs banner link to repo page and not fork page
- Change banner text from 'Fork me' to 'View me'
```
=> docs: Link to conda-forge feedstock and link banner to repo

.github/workflows/dependencies-head.yml, setup.py, tests/test_optim.py
Resolves #1219
~~In response to Issue #1219, this PR avoids the issues that `pytest` `v6.2.0` brings by restricting `pytest` to the `v6.1.X` series.~~ 
This PR ensures that there `floats` are compared instead of `floats` to `tensors`. To try to catch these sorts of issues sooner and maybe bring them up with the `pytest` devs add `pytest` to the HEAD of dependencies workflow as well.
```
* Compare floats to floats and not tensors in pytest.approx
* Add pytest and uproot3 to HEAD of dependencies workflow
* Restrict sphinxcontrib-bibtex to v1.X
- c.f. PR #1221
```
=> fix: Ensure pytest.approx only compares floats

.github/workflows/dependencies-head.yml
After doing some testing on PR #1208 I've found that if `iminuit` (installed from PyPI) is not uninstalled before it is installed from HEAD from GitHub that it is not guaranteed to properly pick up changes.
This was found when Hans reported the PyTorch fix that allowed tests to pass for `pyhf` locally for `iminuit` `v2.0` was merged into the `develop` branch (which is `iminuit`'s default branch) and yet the HEAD of dependencies workflow as failing still. After I added in a 
```yaml
python -m pip uninstall --yes iminuit
```
to the workflow things were passing. This behavior should then be applied to all HEAD of dependencies tests to make sure that the source code on GitHub is being properly tested.
```
* pip uninstall the dependency that is being tested before …
```
=> ci: Uninstall dependencies before installed HEAD versions

setup.cfg
To give releases longer stability and lifetimes upper bounds are required on core dependencies to ensure that breaking API changes to not break old releases. This is a builtin functionality of [PEP 440's compatible release syntax](https://www.python.org/dev/peps/pep-0440/#compatible-release). This PR applies compatible release syntax (`~=`) to all of the dependencies in `install_requires`, establishing lower bounds from when they were added and similarly upper bounds.
---
[Quick summary of compatible release syntax](https://github.com/mwouts/jupytext/pull/596):
In [PEP 440's "Compatible release" section](https://www.python.org/dev/peps/pep-0440/#compatible-release)
> For a given release identifier V.N, the compatible release clause is approximately equivalent to the pair of comparison …
=> build: Use compatible release syntax to give ranges for install_requires

src/pyhf/infer/__init__.py, src/pyhf/infer/calculators.py
More work towards making #520 easy to support/add in. This PR will clean up docstrings first and get qtilde removed from hypotest signature. One would argue it's a change to the API, but in actuality, we never do anything with `qtilde` inside hypotest, as it's forwarded straight to the calculators.
docs: https://pyhf.readthedocs.io/en/refactor-calculators/
```
* Remove duplicated qtilde description in AsymptoticCalculator description
* Remove qtilde from hypotest docs and function signature to demote it to kwargs
```
=> refactor: Clean up docstrings and remove qtilde from hypotest

docs/conf.py, src/pyhf/tensor/jax_backend.py, src/pyhf/tensor/numpy_backend.py, src/pyhf/tensor/pytorch_backend.py, src/pyhf/tensor/tensorflow_backend.py, tests/test_tensor.py
Resolves #1225 
Add `.to_numpy()` API that returns the tensor converted to a [NumPy `ndarray`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html#numpy.ndarray).
Example:
```python
>>> pyhf.set_backend("jax")
>>> tensor = pyhf.tensorlib.astensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
>>> tensor
DeviceArray([[1., 2., 3.],
[4., 5., 6.]], dtype=float64)
>>> numpy_ndarray = pyhf.tensorlib.to_numpy(tensor)
>>> numpy_ndarray
array([[1., 2., 3.],
[4., 5., 6.]])
>>> type(numpy_ndarray)
<class 'numpy.ndarray'>
```
`.to_numpy()` is used rather than `.numpy()` as this is being called from tensorlib (rather than by a tensor object) and the grammar seems to make more sense this way. c.f. [Awkward's API.](https://awkward-array.readthedocs.io/en/latest/_auto/ak.to_numpy.html …
=> feat: Add to_numpy API to tensorlib

.github/workflows/dependencies-head.yml, docs/conf.py, setup.py, src/pyhf/cli/rootio.py, src/pyhf/readxml.py, src/pyhf/writexml.py, tests/test_export.py, tests/test_import.py
Following PR #930 and the release of `v0.5.0`, this PR now moves to adopting `uproot4` and its API.
As of [`uproot4` `v4.0.0`](https://github.com/scikit-hep/uproot4/releases/tag/4.0.0) `uproot4` does not support the ability to write to ROOT files, so `uproot3` must still be retained to write to ROOT. This is the only remaining requirement for `uproot3` and so the move to the `uproot4` API can begin now.
As `uproot4` is also added to the HEAD of dependnecies workflow, the pattern of
```
import uproot
```
is used instead of
```
import uproot4 as uproot
```
as installing `uproot4` from GitHub installs under the `uproot` namespace. So to test the HEAD of `uproot4`, the `uproot` namespace must be used now instead of waiting to drop `uproot3`.
```
* Require uproot4 in the …
```
=> build: Begin move to uproot4

.readthedocs.yml, docs/_templates/autosummary/module.rst, docs/api.rst, setup.py
This needs #1002. Add `readxml` and `writexml` to our documented API. Resolves #1131.
Related issue: #943.
ReadTheDocs build: https://pyhf.readthedocs.io/en/docs-importexport/api.html#top-level
```
* Add readxml and writexml to docs API
* Add template for autosummary module to render classes/functions properly
* Update [docs] option for installation to depend on [xmlio]
* Teach RTD to fail on warnings (be more strict)
```
=> docs: Add readxml and writexml

src/pyhf/contrib/viz/brazil.py
Following PR #1242, I noticed that in PR #1176 I used incorrect math mode syntax that is now being displayed thanks to PR #1242 showing it. Offending syntax (I must have been tired)
```
$ git grep ":math:\\$"
src/pyhf/contrib/viz/brazil.py:        tests (:obj:`list` or :obj:`array`): The :math:$\\mathrm{CL}_{s}$ values
src/pyhf/contrib/viz/brazil.py:        test_size (:obj:`float`): The size, :math:$\alpha$, of the test.
```
This PR fixes that by using proper syntax.
ReadTheDocs build: https://pyhf.readthedocs.io/en/docs-fix-math-mode-for-contrib/_generated/pyhf.contrib.viz.brazil.plot_results.html#pyhf.contrib.viz.brazil.plot_results
```
* Use correct Sphinx math mode syntax for contrib.viz.brazil.plot_results docstring
```
=> docs: Fix math mode syntax in contrib.viz.brazil.plot_results docstring

tests/test_probability.py
* Resolves #1251
* Required for PR #1232
* Addresses https://github.com/google/jax/issues/5386
To avoid the issues with floating point comparison out to 15 decimal places that started surfacing with the release of [`jaxlib` `v0.1.58`](https://pypi.org/project/jaxlib/0.1.58/) don't use exact `assert`s for floating point comparison in `test_probability.py`. `atol=1e-12` was chosen as that is well beyond the floating point precision that should matter for comparion here, but not up to the `1e-15` or so that caused the difference.
Also remove redundant test added by mistake in PR #582 
```
* Use np.allclose with an absolute tolerance of 1e-12 instead of exact assert to compare floating point values in test_probability.py
- Applies to tests test_joint and test_independent …
```
=> fix: Don't use exact assert for test_probability.py

.gitignore, docs/bib/talks.bib, docs/bib/use_citations.bib
* Resolves #1253
* Resolves #920
Add use citations
- [Search for new phenomena in events with two opposite-charge leptons, jets and missing transverse momentum in p p collisions at √s = 13 TeV with the ATLAS detector](https://inspirehep.net/literature/1811757) (ATLAS-CONF-2020-046)
- [New developments in SModelS](https://inspirehep.net/literature/1836682)
and talks
- [TOOLS 2020 workshop talk](https://indico.cern.ch/event/955391/contributions/4075505/)
- [SciPy 2020 talk](https://github.com/matthewfeickert/talk-SciPy-2020)
ReadTheDocs build: 
- https://pyhf.readthedocs.io/en/docs-add-end-2020-citations/citations.html
- https://pyhf.readthedocs.io/en/docs-add-end-2020-citations/outreach.html#presentations
```
* Add use citations from 2020
- ATLAS-CONF-2020-046 …
```
=> docs: Add talks and use citations from 2020

.github/workflows/docs.yml, .readthedocs.yml, docs/conf.py, setup.py
~~Require `sphinxcontrib-bibtex` releases compatible with `v2.0`, which requires the definition of the `bibtex_bibfiles` in the Sphinx `conf.py`. With `v2.0` [Sphinx must be run twice to generate the bibliography](https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#running-sphinx):~~
> ~~It is good to be aware that the extension stores all citation information in a `bibtex.json` file in the source folder. If it does not exist, the file will be created on your first sphinx build, and you will have to rerun the build to make use of it. The file is automatically kept up to date, with a warning whenever you need to rerun the build (i.e. whenever your citations change). The file can be stored in version control if you do not want your users to have to run sphinx twice when they …
=> docs: Use sphinxcontrib-bibtex v2.1 and bibtex_bibfiles setting

.github/workflows/docs.yml, setup.cfg
Resolves #1256
Use Sphinx's Makefile to build the docs using `sphinx-build` via `make html`. 
https://github.com/scikit-hep/pyhf/blob/fd8fdf3c280604c173f6229837baab3616abe8c3/docs/Makefile#L54-L58
This deprecates the previously used method of using [Sphinx's `setuptools` integration](https://www.sphinx-doc.org/en/master/usage/advanced/setuptools.html).
This also more closely resembles the [ReadTheDocs procedure](https://docs.readthedocs.io/en/stable/builds.html)
> When we build your Sphinx documentation, we run `sphinx-build -b <format> . _build/<format>`. We also create pdf’s and ePub’s automatically based on your project.
```
* Build the docs using the html Make target from Sphinx's Makefile
- Sphinx Make targets all invoke sphinx-build
- Deprecate pattern `python …
```
=> docs: Build docs with sphinx-build via Sphinx Makefile

docs/Makefile, docs/examples/notebooks/learn/UsingCalculators.ipynb, tests/test_notebooks.py
This is the last thing from #709 that we don't have in `pyhf` by now.
Render: https://pyhf.readthedocs.io/en/docs-usingcalculators/examples/notebooks/learn/UsingCalculators.html
```
* Add learn notebook on using calculators (asymptotics, toy-based)
- Add notebook to notebook tests
* Update Sphinx Makefile to correctly raise warnings as errors
- c.f. https://www.sphinx-doc.org/en/master/man/sphinx-build.html
- Amends PR #1257
Co-authored-by: Lukas Heinrich <lukas.heinrich@gmail.com>
```
=> docs: Add learn notebook on using calculators

docs/bib/media.bib
Resolves #1262 
Adds ["ATLAS releases ‘full orchestra’ of analysis instruments" Symmetry Magazine article](https://www.symmetrymagazine.org/article/atlas-releases-full-orchestra-of-analysis-instruments) to "In the Media" section in the docs.
ReadTheDocs build: https://pyhf.readthedocs.io/en/docs-add-symmetry-magazine-article/outreach.html#in-the-media
```
* Add Symmetry Magazine article on likelihood publication using pyhf to docs
- c.f. https://www.symmetrymagazine.org/article/atlas-releases-full-orchestra-of-analysis-instruments
```
=> docs: Add Symmetry Magazine article on likelihood publication

docs/contributors.rst, src/pyhf/infer/mle.py
Resolves #1234 
As mentioned in the issue, there was a readability problem with the following lines:
https://github.com/scikit-hep/pyhf/blob/fd7930cce36cbc3a2d0ee1828f060d7382129579/src/pyhf/infer/mle.py#L134-L135
I have added the comma around the constrained maximal likelihood as mentioned in the issue.
ReadTheDocs build: https://pyhf.readthedocs.io/en/docs-build-docs-docfix-1nformed/_generated/pyhf.infer.mle.fixed_poi_fit.html
```
* Add commas around constrained maximal likelihood for reading clarity
* Add Pradyumna to list of contributors
```
=> docs: Add commas to infer.mle.fixed_poi_fit docstring for clarity

docs/JOSS/paper.md
Following review, it has been requested that [the release number of `pyhf` available at the time of writing be stated in the text of the JOSS paper itself](https://github.com/openjournals/joss-reviews/issues/2823#issuecomment-769311767). This PR adds in the following text:
> At the time of writing this paper the most recent release of `pyhf` is [`v0.5.4`](https://doi.org/10.5281/zenodo.4318533).
```
* Explicitly state the release of pyhf at time of writing JOSS paper is v0.5.4
- Link to pyhf v0.5.4 Zenodo archive
* Amend PR #1089
```
=> docs: Explicitly give version number in JOSS paper

CONTRIBUTING.md, README.rst, docs/conf.py, docs/contributors.rst, docs/faq.rst
Fixes  #1269, by replacing links to the `pyhf` stackoverflow tag with links to the Github Discussions page of the project.
ReadTheDocs build: https://pyhf.readthedocs.io/en/trigger-docs-github-discussion/
- https://pyhf.readthedocs.io/en/trigger-docs-github-discussion/#questions
- https://pyhf.readthedocs.io/en/trigger-docs-github-discussion/faq.html#where-can-i-ask-questions-about-pyhf-use
```
* Deprecate Stack Overflow in favor of GitHub Discussions for community use questions
* Add Eric Schanet to list of contributors
```
=> docs: Redirect questions to GitHub Discussions

docs/development.rst
The instructions on how to install a dev release from TestPyPI are not actually correct (@matthewfeickert got it a little bit wrong in PR #859 :grimacing:). This PR corrects those instructions and tries to clarifying things more.
ReadTheDocs build: https://pyhf.readthedocs.io/en/docs-correct-testpypi-install-instructions/development.html#testpypi
```
* Note to first install library from PyPI and then upgrade to TestPyPI
- If library dependencies have releases on TestPyPI ensures installed from PyPI
* Clarify the package index hierarchy checked during install
```
=> docs: Correct TestPyPI install instructions

docs/JOSS/paper.md
As requested by the JOSS Editor in Chief for the review https://github.com/openjournals/joss-reviews/issues/2823, add a section for "Statement of Need". Additionally, move the information on the archival of the `pyhf` source code on Zenodo and the version used in the review out of "Statement of Need" and (back into) the end of "Summary" as this information doesn't belong with motivational text.
For posterity, related PRs to the JOSS paper revision are:
- PR #1089 
- PR #1280 
```
* Add 'Statement of Need' section heading to JOSS paper
- c.f. https://github.com/openjournals/joss-reviews/issues/2823
* Move information on version and Zenodo archive back to 'Summary' section
```
=> docs: Make 'Statement of Need' explicit section in JOSS paper

.github/workflows/merged.yml
GESIS notebooks are failing, so drop the endpoint.
```
* Remove GESIS Notebooks endpoint from Binder triggers to keep workflow from failing
```
=> ci: Drop GESIS from Binder trigger

README.rst, docs/citations.rst, src/pyhf/data/citation.bib, src/pyhf/utils.py, tests/test_scripts.py
JOSS is out! https://twitter.com/JOSS_TheOJ/status/1357410376124669952
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02823/status.svg)](https://doi.org/10.21105/joss.02823)
ReadTheDocs build: https://pyhf.readthedocs.io/en/docs-addjossbadge/
```
* Add JOSS paper BibTeX entry to preferred citation
* Add JOSS DOI badge to README
- c.f. https://doi.org/10.21105/joss.02823
* Add test for JOSS paper in pyhf --cite output
```
=> docs: Add JOSS paper to preferred citation and DOI Badge

docs/_static/css/custom.css
Docs are currently 800px max-width. Changing this to 1200px is a bit better for readability on most PC monitors.
https://pyhf.readthedocs.io/en/docs-widercontent/
```
* Change doc content width from 800px to 1200px
```
=> docs: Widen the content box of docs

docs/contributors.rst, setup.cfg
The universal setting means that it gets a py2.py3 tag, which is not true. This should already get the correct, `py3` only tag without any extra settings. (the Requires-Python metadata setting is set correctly, so no harm, just not needed)
```
* Remove universal wheel setting as pyhf is Python 3 only
- Fixes py2.py3 tag naming scheme for wheels
* Add Henry Schreiner to list of contributors   
```
=> fix: Make wheel naming indicate wheels are not Python 2 compatible

docs/bib/use_citations.bib
Resolves #1296 
Add use citation from the [Proceedings of the second MadAnalysis 5 workshop on LHC recasting in Korea](https://inspirehep.net/literature/1839663).
ReadTheDocs build: https://pyhf.readthedocs.io/en/docs-add-madanalysis5-citation/citations.html#use-in-publications
```
* Add use citation from Proceedings of the second MadAnalysis 5 workshop on LHC recasting in Korea
- c.f. https://inspirehep.net/literature/1839663
```
=> docs: Add use citation from MadAnalysis 5 workshop

.github/workflows/publish-package.yml
Following the release of [`pypa/gh-action-pypi-publish` `v1.4.2`](https://github.com/pypa/gh-action-pypi-publish/releases/tag/v1.4.2) update for reasons listed in the release notes.
```
* Update pypa/gh-action-pypi-publish to v1.4.2 for newer pip and stability
- c.f. https://github.com/pypa/gh-action-pypi-publish/releases/tag/v1.4.2
```
=> ci: Update PyPI publish GitHub Action to v1.4.2

setup.cfg
As https://github.com/tqdm/tqdm/issues/624 which @kratsg opened up has been resolved, take advantage of its resolution by picking up the release in which is it fixed, [`v4.56.1`](https://github.com/tqdm/tqdm/releases/tag/v4.56.1), by requiring a minimum compatible version of `tqdm` of `v4.56` in `setup.cfg`.
Example of it working now:
```python
>>> import tqdm
>>> import sys
>>> print(tqdm.__version__, sys.version, sys.platform)
4.56.1 3.8.6 (default, Jan  5 2021, 00:14:15) 
[GCC 9.3.0] linux
>>> a = tqdm.tqdm([], disable=True)
>>> print(a)
0it [00:00, ?it/s]
>>> str(a)
'0it [00:00, ?it/s]'
>>> dir(a)
['__bool__', '__class__', '__del__', '__delattr__', '__dict__', '__dir__', '__doc__', '__enter__', '__eq__', '__exit__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', …
```
=> build: Update minimum required tqdm release to avoid repr crash

.github/workflows/ci.yml, .github/workflows/release_tests.yml, .pre-commit-config.yaml, codemeta.json, pyproject.toml, setup.cfg, tests/test_optim.py, tests/test_scripts.py
Resolves #1075 
Drop support for Python 3.6. Require Python 3.7+ for `pyhf` installation and remove all Python 3.6 specific code.
```
* Require Python 3.7+ for installation
* Remove Python 3.6 from testing in CI
* Remove Python 3.6 specific code from the codebase and metadata
```
=> build: Drop support for Python 3.6

setup.py
Temporary resolution to Issue #1305 
In the interest of getting `v0.6.0` released in a timely manner, bound `iminuit` releases to be below `v2.4.0` until the behavior in PR #1306 can be better understood. Aim to have this understood and acted on  for [`pyhf` `v0.6.1`](https://github.com/scikit-hep/pyhf/projects/14).
```
* Restrict iminuit to compatible releases below v2.4.0
- c.f. https://github.com/scikit-hep/pyhf/issues/1305
```
=> fix: Restrict iminuit to compatible releases below 2.4.0

docs/index.rst, docs/release-notes.rst, docs/release-notes/index.rst, docs/release-notes/v0.5.3.rst, docs/release-notes/v0.5.4.rst
As the docs are going to start being versioned in releases with `v0.6.0` then we should also make sure release notes are available on the website as well.
A follow up PR can add `v0.6.0` release notes being drafted in Issue #1303 for the time being.
ReadTheDocs build: https://pyhf.readthedocs.io/en/docs-add-release-notes/release-notes.html
```
* Add release notes page to docs website
- Add v0.5.3 and v0.5.4 release notes from GitHub
```
=> docs: Add release notes to website

src/pyhf/infer/__init__.py, src/pyhf/infer/calculators.py, tests/test_infer.py
Resolves #1159
In the standard brazil band plot ROOT HypotestInverter produces, there is a bit of an imprecision as the expected limits are calculated in $mu^/sigma$ space but for significant upward fluctuations it returns p-values that are not actually realizable with any data since if $expected µ^ > µ$ the test stat can at most be the one returned for $µ=µ^$, namely $q_µ = 0$, that in turn means that the p-value is capped at $CLs_obs$.
For compatibility and recognizability the default behavior is unchanged but it's now possible to get the correct asymptotic bahaviorr with `calc_kwargs = {'base_dir': 'clipped_normal'}`
ReadTheDocs build: https://pyhf.readthedocs.io/en/clipped_expected/api.html#inference
- [`pyhf.infer.calculators.AsymptoticTestStatDistribution`](https://pyhf.readthedocs.i …
=> feat: Add kwarg for AsymptoticCalculator base distribution

src/pyhf/infer/calculators.py, src/pyhf/infer/utils.py
Resolves #1268
Ensure all p-value-like values and test statistics are given as 0-d tensors and harmonize returns types across calculator types.
ReadTheDocs build: https://pyhf.readthedocs.io/en/fix-ensure-p-value-like-return-type/
- [`pyhf.infer.calculators.AsymptoticCalculator`](https://pyhf.readthedocs.io/en/fix-ensure-p-value-like-return-type/_generated/pyhf.infer.calculators.AsymptoticCalculator.html)
- [`pyhf.infer.calculators.ToyCalculator`](https://pyhf.readthedocs.io/en/fix-ensure-p-value-like-return-type/_generated/pyhf.infer.calculators.ToyCalculator.html)
```
* Ensure p-value-like values and test statistics are all 0-d tensors for consistent return type
- Update docstrings
* Harmonize return types from asymptotic and toy calculators
```
=> fix: Make p-value-like values 0-d tensors

docs/governance/ROADMAP.rst, docs/release-notes.rst, docs/release-notes/v0.5.3.rst, docs/release-notes/v0.6.0.rst
- Resolves #1270 
- Resolves #1303
Add release notes for release v0.6.0
ReadTheDocs build: https://pyhf.readthedocs.io/en/docs-add-v0.6.0-release-notes/
- [ROADMAP](https://pyhf.readthedocs.io/en/docs-add-v0.6.0-release-notes/governance/ROADMAP.html)
- [release notes](https://pyhf.readthedocs.io/en/docs-add-v0.6.0-release-notes/release-notes.html)
```
* Add release notes for v0.6.0
* Update ROADMAP to note discovery test statistic support added
```
=> docs: Add v0.6.0 release notes

docs/release-notes/v0.6.0.rst
Corrects typos in PR #1314. @matthewfeickert needs to get a spell checker for VS Code that works in .rst files.
```
* Correct spelling errors and typos in the v0.6.0 release notes
- Amends PR #1314 
```
=> docs: Correct typos in v0.6.0 release notes

docs/release-notes/v0.6.0.rst
Amend PR #1314 to mention that Python 3.6 support is dropped in v0.6.0.
ReadTheDocs build: https://pyhf.readthedocs.io/en/docs-add-drop-3.6-to-release-notes/release-notes.html
```
* Include dropping of support for Python 3.6 in the v0.6.0 release notes
- Include motivation from NEP 29 and PEP 494
- Amends PR #1314
```
=> docs: Add dropping of Python 3.6 support to v0.6.0 release notes

src/pyhf/data/citation.bib, src/pyhf/utils.py
Resolves #1321
Use author field of
```bibtex
@software{pyhf,
author = {Lukas Heinrich and Matthew Feickert and Giordon Stark},
title = "{pyhf: v0.6.0}",
version = {0.6.0},
doi = {10.5281/zenodo.1169739},
url = {https://github.com/scikit-hep/pyhf},
}
```
allowing BibTeX to render author names more natively for different BibTeX styles
```
* Use more flexible syntax in the BibTeX author field for the Zenodo citation
- Allows BibTeX to change formatting of names to fit the BibTeX style
```
=> docs: Use more flexible BibTeX syntax for Zenodo DOI

README.rst, docs/release-notes/v0.6.0.rst
@matthewfeickert was too quick on the trigger for PR #1322 and forgot to get the docs too. Doh! :(
```
* Update the BibTeX author field for the Zenodo archive citation in the docs
- Amends PR #1322
```
=> docs: Update Zenodo BibTeX author field in citation in docs

setup.cfg
Add PyPI metadata for Python 3 only and CPython implementation. 
Influence came from [`pyupgrade`'s `setup.cfg`](https://github.com/asottile/pyupgrade/blob/49b8cba72e2222451be96402428d771f0b6fe1ea/setup.cfg#L12-L21).
```
* Add metadata for Python3 only and CPython implementation to setup.cfg
```
=> docs: Add CPython implementation and Python 3 only metadata

docs/bib/use_citations.bib
Resolves #1328
Add citations  to the [Use and Citations page](https://scikit-hep.org/pyhf/citations.html) for:
- [How to discover QCD Instantons at the LHC](https://inspirehep.net/literature/1836890) (arXiv: 2012.09120)
- [Charged Lepton Flavor Violation at the EIC](https://inspirehep.net/literature/1846026) (arXiv: 2102.06176)
```
* Add use citation from 'How to discover QCD Instantons at the LHC'
- c.f. https://inspirehep.net/literature/1836890
* Add use citation from 'Charged Lepton Flavor Violation at the EIC'
- c.f. https://inspirehep.net/literature/1846026
```
=> docs: Add use citations for QCD instantons and charged lepton flavor violation

setup.cfg, src/pyhf/modifiers/__init__.py, src/pyhf/pdf.py, src/pyhf/readxml.py
I ran [DeepSource](https://deepsource.io/) analysis on my fork of the repo, and found some interesting [code quality issues](https://deepsource.io/gh/akshgpt7/pyhf/) that can improve the general code quality here.
This PR fixes a few of the issues detected.
- Refactor unnecessary use of `elif/else` after `return`.
- Simplify `if` statements to use `bool()`.
- Refactor iterating over dictionary instead of using `dict.keys()`.
- Refactor unnecessary `dict()` call.
```
* Apply minor code changes
- Use raise error as default behavior to avoid if-else evaluation
- Use evaluation of bool() over trivial if statements
- Drop use of keys on dict iteration
```
=> chore: Apply minor code quality revisions

docs/bib/use_citations.bib
Citation initially referred to CONF note that's now superseded by the paper. Likely better to cite the paper on arXiv.
```
* Update 3G tt 2L CONF note that is superseded by paper
- c.f. https://inspirehep.net/literature/1844425
```
=> docs: Update ATLAS 3G tt 2L citation

CONTRIBUTING.md
Add clarifying language to `CONTRIBUTING.md` to emphasize the importance of communication with the dev team when opening up a PR. This helps to establish a policy of avoiding "drive by PRs".
```
* Clarify in CONTRIBUTING.md that contribution PRs should involve communication with the dev team
- Goal is to improve PR experience and avoid noise
```
=> docs: Update CONTRIBUTING.md to disincentivize 'drive by PRs'

src/pyhf/optimize/opt_scipy.py, tests/test_optim.py
This adds in the functionality to pass through solver options to the chosen method for the scipy minimizer. See https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.show_options.html for more details.
It should be useful to help with debugging minimization by being able to tweak some of the handles available for the given method chosen for minimization (e.g. SLSQP). This should help understand issues like #876.
```
* Add solver_options kwarg to opt_scipy for extra configurability
* Add tests for solver_options
```
=> feat: Solver options for scipy

docs/bib/HEPData_likelihoods.bib
Add records of HEPData published likelihoods for
- [Search for displaced leptons in $\sqrt{s} = 13$ TeV $pp$ collisions with the ATLAS detector](https://doi.org/10.17182/hepdata.98796)
- [Search for trilepton resonances from chargino and neutralino pair production in $\sqrt{s}$ = 13 TeV $pp$ collisions with the ATLAS detector](https://doi.org/10.17182/hepdata.99806)
```
* Add ATLAS displaced leptons HEPData record
- c.f. https://doi.org/10.17182/hepdata.98796
* Add ATLAS trilepton resonances from chargino and neutralino HEPData record
- c.f. https://doi.org/10.17182/hepdata.99806
```
=> docs: Add record for published ATLAS likelihoods from November 2020

src/pyhf/infer/__init__.py, src/pyhf/infer/calculators.py, src/pyhf/infer/mle.py, src/pyhf/infer/test_statistics.py, src/pyhf/optimize/common.py, src/pyhf/optimize/mixins.py
This clarifies a lot of the docstrings and makes them slightly more verbose and appropriate for the corresponding function. This was initially raised due to confusino about the `fixed_params` docstrings which wasn't explicit about what that list or tensor should/could be.
```
* Clarify docstrings for fit parameters: init_pars, par_bounds, fixed_params, and fixed_vals
```
=> docs: Clarify and harmonize docstrings for fit parameters

.pre-commit-config.yaml, README.rst, docs/babel.rst, docs/development.rst, docs/likelihood.rst
Apply Anthony Sottile's [`blacken-docs`](https://github.com/asottile/blacken-docs) as a pre-commit hook to all docs files in the codebase. HT to @kratsg for making me aware! :)
```
* Add blacken-docs as a pre-commit hook
- c.f. https://github.com/asottile/blacken-docs
* Apply blackend-docs to RST and Markdown files in the codebase
- Use 'pycon' formatting in codeblocks with REPL markers (>>>)
```
=> docs: Add and apply blacken-docs as a pre-commit hook

setup.py, src/pyhf/tensor/pytorch_backend.py, tests/test_tensor.py
Resolves #1348 
To retain the continuous approximation of the Poisson, set `validate_args=False` in instantiations of the `torch.distributions.Poisson` class.
```
* Add validate_args=False to instantiations of the torch.distributions.Poisson class in PyTorch backend to allow for the continuous approximation of the Poisson distribution in torch v1.8+
* Ensure tensor value arguments for torch.distributions.Normal
* Check that ValueErrors are raised by PyTorch v1.8+ when the validations of validate_args are violated
```
=> fix: Retain continuous approximation of Poisson in torch v1.8.0

docs/bib/use_citations.bib
Resolves #1346 
Add use citation from [Artificial Proto-Modelling: Building Precursors of a Next Standard Model from Simplified Model Results](https://inspirehep.net/literature/1837822) by @WolfgangWaltenberger, @andlessa, and @sabinekraml :rocket: 
```
* Add use citation from 'Artificial Proto-Modelling: Building Precursors of a Next Standard Model from Simplified Model Results'
- c.f. https://inspirehep.net/literature/1837822
```
=> docs: Add use citation for Artificial Proto-Modelling paper

.github/workflows/docs.yml
When people are testing on their own branches we can often run into the situation where RTD hits the concurrency limit and delays each subsequent build of the docs by 5 minutes. This PR won't ~~fully~~ fix that, but we don't need to build the docs on every push, so only have the docs get build by the CI on `push` events if pushing to `master`.
```
* Only build the docs on 'push' events if push is to master
- In the case of the pyhf dev workflow these push events happen during merges of PRs
```
=> ci: Run docs CI on push events only from PR merges

setup.py, src/pyhf/tensor/pytorch_backend.py
Resolves #1349 
Adopt the `torch` API for `ravel`, `tile`, and `outer` for easier comparisons across backends as the [PyTorch `v1.8.0` release notes](https://github.com/pytorch/pytorch/releases/tag/v1.8.0) comment
> New functions (most of them to improve numpy compatibility)
Note that in the case of `outer` the `v1.8.0` docs note that for [`torch.ger`](https://pytorch.org/docs/1.8.0/generated/torch.ger.html) (the current function)
> This function is deprecated and will be removed in a future PyTorch release. Use `torch.outer()` instead.
As a result also bump the minimum compatible release number of PyTorch to `1.8` so that these APIs exist.
```
* Use torch.ravel, torch.tile, torch.outer for PyTorch backend tensorlib methods
- …
```
=> refactor: Use torch APIs for ravel, tile, and outer tensorlib methods

.github/workflows/lower-bound-requirements.yml, .pre-commit-config.yaml, MANIFEST.in, lower-bound-requirements.txt, setup.py
Resolves #1350
To ensure that the lower bound of all dependencies are still sufficient for the API used, add a test that installs from a `lower-bound-requirements.txt`.
```
* Test lowest version of dependencies specified in setup.cfg and setup.py
- Add lower-bound-requirements.txt with lowest versions pinned
- Add lower-bound-requirements.yml GHA nightly workflow to test lower-bound-requirements.txt versions on test suite
* Update lower bounds of extra dependencies in setup.py to reflect their actual lowest bounds
```
=> test: Test lower bounds of dependencies

src/pyhf/tensor/jax_backend.py, src/pyhf/tensor/numpy_backend.py, src/pyhf/tensor/pytorch_backend.py, src/pyhf/tensor/tensorflow_backend.py, tests/test_optim.py, tests/test_tensor.py
- Resolves #1368 
- Resolves #1145
As this is fixing and so changing the `dtype` that is being set from `64b` to `32b` then this is also going to mean corrections of tests.
```
* Add dtype arg to tensorlib .ones and .zeros to set precision
- Ensures that precision set at tensorlib set time is propagated
- Default to the value of the tensor backend dtypemap
* Add test_tensor tests to cover invalid dtype to .ones and .zeros
* Update test_optim to use 32b values
```
=> fix: Set precision for ones and zeros through dtype arg

src/pyhf/tensor/jax_backend.py
Update JAX tensor type to `jaxlib.xla_extension.DeviceArray` that was introduced in `jax` `v0.2.11`.
```
* Update JAX tensor type to jaxlib.xla_extension.DeviceArray in docs
- Changed in JAX v0.2.11
```
=> fix: Correct JAX tensor type in docstring

.github/workflows/ci.yml
First noted in PR #1377, this allows for running the main tests, uploading the coverage to Codecov with a "unittests" flag, then running the tests for the contrib module, and uploading the new coverage report with these tests **added** to the main tests with a "contrib" flag.
```
* Upload coverage reports to Codecov in staged runs with different flags to allow for iterative reporting
- Allows for testing contrib module separately buy adding the coverage to the final report
- c.f. https://docs.codecov.io/docs/flags
```
=> ci: Upload coverage to Codecov in flagged stages for complete coverage report

src/pyhf/utils.py
In light of a discussion, motivated by PR #1378, with @alexander-held, @henryiii, and @jpivarski about the security risk of PyYAML, use `yaml.safe_load` over `yaml.full_load` in `pyhf.utils.options_from_eqdelimstring`.
```
* Use yaml.safe_load over yaml.full_load in pyhf.utils.options_from_eqdelimstring
* Further safeguards against things like CVE-2020-14343
- c.f. PR #1378
```
=> feat: Use PyYAML's safe_load for better security

lower-bound-requirements.txt, setup.py, tests/test_optim.py
Resolves #1305 
Update the minimum required release of `iminuit` in the `minuit` extra to `v2.4.0`. This changes some of the minimization values which requires loosening of `iminuit`'s tolerances to reach convergence.
As [Hans notes](https://github.com/scikit-hep/pyhf/issues/1305#issuecomment-777223845):
> Remember that Minuit's tolerance and convergence criterion stops the iteration earlier than other minimisers, once the change in the parameter values becomes negligible compared to the parameter errors. This makes sense for statistical fits. Small means 1e-2 to 1e-3 of the error.
~~While this PR does introduce some large changes in the tests it also seems that `iminuit` `v2.4.0` gives more consistent results across OS and across CI vs. local.~~
```
* Set minimum …
```
=> fix: Loosen iminuit tolerances for optimization tests

src/pyhf/schemas/1.0.0/defs.json, tests/test_schema.py
Resolves #1387. Histosys and Normsys should be stricter about not allowing additional properties in the `data` object in the schema.
```
* Teach the schema to not allow additional properties for histosys and normsys
* Be more explicit about the patchset/jsonpatch metadata information (that we do allow additionalProperties)
* Add tests to check that additionalProperties for for histosys and normsys result in an invalid spec
```
=> fix: Stricter schema definitions for histosys and normsys

src/pyhf/tensor/tensorflow_backend.py
While investigating Issue #1398, it was noticed that for `64b` precision for the TensorFlow backed the precision was not properly being used throughout. `tf.float32` was used as a default instead of the result of `self.dtypemap["float"]` and if TensorFlow Probability is given floats as parameters it will default to using `32b` precision, and so _requires_ that a tensor of the desired precision be given.
```
* Ensure that the precision requested in the set_backend API is used throughout the TensorFlow backend calculations
- Determine dtype from dtypemap
- Ensure TensorFlow Probability operations are given a tensor of the correct precision
```
=> fix: Ensure tensorlib precision used throughout TensorFlow backend

src/pyhf/__init__.py, src/pyhf/tensor/pytorch_backend.py, src/pyhf/tensor/tensorflow_backend.py
Requires PR #1399 to go in first, as this PR relies on those changes.
Resolves #1398 
Set the default precision for all backends to `64b`.
```
* Set the default precision for all tensorlib backends to 64b in pyhf.set_backend
* Update the TensorFlow and PyTorch docstrings
```
=> refactor: Set default precision to 64b

.pre-commit-config.yaml, src/pyhf/patchset.py
Update Black to use release [`21.4b0`](https://github.com/psf/black/releases/tag/21.4b0).
```
* Update docstrings to use Black release v21.4b0 style
- c.f. https://github.com/psf/black/releases/tag/21.4b0
* Update pre-commit hooks releases
- github.com/psf/black: 20.8b1 → 21.4b0
- github.com/asottile/pyupgrade: 2.12.0 → 2.13.0
```
=> chore: Update Black to release v21.4b0

.pre-commit-config.yaml
Update Black to use release [`21.4b1`](https://github.com/psf/black/releases/tag/21.4b1).
```
* c.f. https://github.com/psf/black/releases/tag/21.4b1
* Update pre-commit hooks releases
- github.com/psf/black: 21.4b0 → 21.4b1
```
=> chore: Update Black to release v21.4b1

docs/bib/use_citations.bib
Add use citation from [Search for B⁺→ K⁺νν̅ decays using an inclusive tagging method at Belle II](https://inspirehep.net/literature/1860766) by the Belle II Collaboration! :rocket: 
This is the second paper by an experiment to cite `pyhf` (ATLAS was first with https://doi.org/10.1007/JHEP04(2021)165)!
```
* Add use citation from 'Search for B⁺→ K⁺νν̅ decays using an inclusive tagging method at Belle II'
- c.f. https://inspirehep.net/literature/1860766
- First use citation of pyhf in a paper by a non-LHC experiment
```
=> docs: Add use citation from Belle II B⁺→ K⁺νν̅ decays search paper

docs/api.rst, src/pyhf/utils.py
Resolves #1315
```
* Add pyhf.utils.citation to the Python API docs
* Add oneline arg to docstring example to make output format more clear
```
=> docs: Add utils.citation to Python API docs

README.rst, docs/release-notes/v0.6.0.rst, src/pyhf/data/citation.bib, src/pyhf/utils.py
Resolves #1423 
```
* Update the 'url' field in the requested software citation to be the Zenodo DOI URL
* Add a 'note' field that has the GitHub release URL
```
=> docs: Update software citation URL to Zenodo DOI

src/pyhf/pdf.py
To satisfy `pydocstyle` in PR #1403 docstrings need to be added to `pyhf.pdf._ModelConfig`, so these are added here.
```
* Add docstrings and examples to pyhf.pdf._ModelConfig and its methods
```
=> docs: Add docstrings to _ModelConfig methods

src/pyhf/__init__.py, src/pyhf/cli/__init__.py, src/pyhf/constraints.py, src/pyhf/contrib/cli.py, src/pyhf/contrib/utils.py, src/pyhf/contrib/viz/brazil.py, src/pyhf/events.py, src/pyhf/exceptions/__init__.py, src/pyhf/infer/__init__.py, src/pyhf/infer/calculators.py, src/pyhf/infer/intervals.py, src/pyhf/infer/mle.py, src/pyhf/infer/test_statistics.py, src/pyhf/infer/utils.py, src/pyhf/interpolators/__init__.py, src/pyhf/modifiers/__init__.py, src/pyhf/parameters/__init__.py, src/pyhf/parameters/paramsets.py, src/pyhf/parameters/paramview.py, src/pyhf/parameters/utils.py, src/pyhf/patchset.py, src/pyhf/pdf.py, src/pyhf/probability.py, src/pyhf/readxml.py, src/pyhf/simplemodels.py, src/pyhf/utils.py, src/pyhf/workspace.py, src/pyhf/writexml.py, tests/test_public_api_repr.py
Resolves #1402 
```
* Use module level __dir__ in combination with __all__ to restrict the public API import views to useful imports
* c.f. https://snarky.ca/lazy-importing-in-python-3-7/
```
=> chore: Use module level __dir__ to restrict public API views
